### ISSUE TITLE
Andrews Curves

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#100]
Implement `AndrewsCurves` , which are a [`FeatureVisualizer`](https://github.com/DistrictDataLabs/yellowbrick/blob/master/yellowbrick/features/base.py) similar to [`ParallelCoordinates`](https://github.com/DistrictDataLabs/yellowbrick/blob/master/yellowbrick/features/pcoords.py).

**Comment by rebeccabilbro** [comment]
See also: http://pandas.pydata.org/pandas-docs/version/0.18.1/visualization.html#visualization-andrews-curves

**Comment by rebeccabilbro** [comment]
See also #59 for notes and guidelines.

**Comment by bbengfort** [comment]
Pandas implementation here:

https://github.com/pandas-dev/pandas/blob/master/pandas/plotting/_misc.py#L235

Shouldn't be too hard; we can also add scaling etc. to the visualization.

**Comment by bbengfort** [comment]
Note that fast vs. slow issues discussed in #448 and related topics may also impact the implementation of Andrews Curves.

**Comment by rebeccabilbro** [comment]
Going to go ahead and close this one out since it's gone a bit stale; to anyone with interest/bandwidth &mdash; feel free to reopen!
