### ISSUE TITLE
Quick API for visualization instead of passing sklearn model

### ISSUE THREAD

**Issue by chrimerss** [DistrictDataLabs/yellowbrick#1005]
call visualization plots directly by providing training data/testing data and bypass sklearn model.
For instance, construct a fast way object: FastVisualizer
functions:
FastVisualizer.regressor.ResidualPlot(*args, **kwargs) -> FastVisualizer.regressor.ResidualPlot(Xtrain, ytrain, Xtest, ytest);
FastVisualizer.classification.ClassificationReport(*args, **kwargs)

**Comment by bbengfort** [comment]
Hi @chrimerss - thank you for your suggestion. We do actually have quick methods that can produce a visualization in one line of code as you suggest, for example, the suggestions you gave can be implemented as follows:

```python
from yellowbrick.regressor import residuals_plot
from yellowbrick.classifier import classification_report

viz1 = residuals_plot(model, X, y, **kwargs)
viz2 = classification_report(model, X, y, **kwargs)
```

We've been working on improving these methods and documenting them - so many of them will be documented in our upcoming v1.1 release. 

As for bypassing the sklearn model; I'm not sure what you mean by that - both of these plots require a model to produce visualizations. For example, the residuals plot visualizes the error between the predicted value of the model and the expected value -- you need a model to show this data. 

Hope this helps! Let us know if you have any other questions.

**Comment by fdeheeger** [comment]
I think the question was: could we use `residuals_plot` without a sklearn object and pass directly `(y_true, y_predicted, y_test_true, y_test_predicted)` to benefit from the plot and associated scores or to use if with a model that would not be a sklearn model.
(at least that's what I am looking for when I found that question !)

**Comment by bbengfort** [comment]
@fdeheeger In some cases we've created DummyEstimators to do what you've suggested, however, it would be very complex to do this for the residuals plot in particular.
