### ISSUE TITLE
Joint Plots - Add tests

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#101]
Implement `JointPlot`, which is a  [`FeatureVisualizer`](https://github.com/DistrictDataLabs/yellowbrick/blob/master/yellowbrick/features/base.py) that is a plot of two variables with bivariate and univariate graphs.

**Comment by rebeccabilbro** [comment]
http://seaborn.pydata.org/generated/seaborn.jointplot.html

**Comment by rebeccabilbro** [comment]
See issue #185

**Comment by rebeccabilbro** [comment]
@pdamodaran leaving this one open so that we remember to add tests.

**Comment by bbengfort** [comment]
@pdamodaran @rebeccabilbro also add it to the documentation!

**Comment by rebeccabilbro** [comment]
@pdamodaran should we close this?

**Comment by pdamodaran** [comment]
sure - do you want me to close it?

**Comment by rebeccabilbro** [comment]
yes :)

**Comment by pdamodaran** [comment]
Done!
