### ISSUE TITLE
Using your own models with yellow brick

### ISSUE THREAD

**Issue by achapkowski** [DistrictDataLabs/yellowbrick#1014]
**Describe the issue**
If you create your own clustering algorithm that follows the sklearn pattern, is there anything I need to know to allow users to use the additional clustering methods to extend this package to my own sklearn like models?

**Comment by lwgray** [comment]
hi @achapkowski Thanks for using yellowbrick.
If your models follow the sklearn estimator paradigm then it should work without any further changes.  Are you running into any particular errors?  @bbengfort might want to chime in on this.

**Comment by bbengfort** [comment]
@achapkowski if your method implements `fit()` and to a lesser extent for clustering algorithms, `predict()` then you'll probably be 80% of the way there. The only thing to pay attention to is the learned attributes of the model, e.g. the attributes that have an underscore suffix (like `labels_`) and are only added to the object after `fit()` has been called. 

I'm happy to dive into specifics for our clustering visualizers, was there one in particular that you were hoping to use?

**Comment by bbengfort** [comment]
@achapkowski closing this as stale; let me know if you have any further comments or questions!
