### ISSUE TITLE
Alphas Plot

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#103]
Create some new type of visualizer that enables the user to plot the error for different alphas. Line graph - use the line to show which alpha was selected.

**Comment by bbengfort** [comment]
I've started investigating this issue this morning; it seems like a fairly straight forward implementation. For reference, here is the implementation from the Machine Learning slides. However, I believe the best way to implement this visualizer is to wrap one of the RegressorCV models, e.g. `RidgeCV` or `LassoCV`, etc.

**Comment by bbengfort** [comment]
More investigation reveals that `RidgeCV`, `LassoCV`, `ElasticNetCV`, and `LassoLarsCV` all have different attributes to fetch for their models:

RidgeCV:

```python
from sklearn.linear_model import RidgeCV 

# Must pass store_cv_values=True in order to store the MSE of the alphas. 
ridge = RidgeCV(alphas=alphas, store_cv_values=True)
ridge.fit(X, y)

# Plot against ridge.alphas and ridge.cv_values_
g = plt.plot(ridge.alphas, ridge.cv_values_.mean(0), label="ridge")
```

![ridge](https://cloud.githubusercontent.com/assets/745966/23262956/9720c500-f9aa-11e6-8fc0-0085eee8415d.png)

LassoCV:

```python
from sklearn.linear_model import LassoCV 

lasso = LassoCV(alphas=alphas)
lasso.fit(X, y)

# plot against lasso.alphas_ and lasso.mse_path_
g = plt.plot(lasso.alphas_, lasso.mse_path_.mean(1), label="lasso")
```

![lasso](https://cloud.githubusercontent.com/assets/745966/23262980/b1f1391e-f9aa-11e6-9e98-5a9a2ab7b197.png)

**Comment by bbengfort** [comment]
ElasticNetCV:

```python
from sklearn.linear_model import ElasticNetCV 

enet = ElasticNetCV(alphas=alphas)
enet.fit(X, y)

g = plt.plot(enet.alphas_, enet.mse_path_.mean(1), label="elasticnet")
```

![enet](https://cloud.githubusercontent.com/assets/745966/23263017/d9ca5ed4-f9aa-11e6-8fc3-37e4e3aaffe1.png)

LassoLarsCV:

```python
from sklearn.linear_model import LassoLarsCV 

larslasso = LassoLarsCV()
larslasso.fit(X, y)

# plot against lars.cv_alphas_ and lars.cv_mse_path_
g = plt.plot(larslasso.cv_alphas_, larslasso.cv_mse_path_.mean(1), label="lasso lars")
```

![lassolars](https://cloud.githubusercontent.com/assets/745966/23263024/e02ba95e-f9aa-11e6-862a-7d305c9994e7.png)

All of them on the same graph:

![all](https://cloud.githubusercontent.com/assets/745966/23263030/e4f3723c-f9aa-11e6-863b-d9b9f705bebb.png)

**Comment by bbengfort** [comment]
Note: we should also put the selected alpha and final cross validation score into the plot as well!

**Comment by bbengfort** [comment]
`AlphaSelection` visualizer implemented, as well as a refactoring of the `regressor` package! 

Here are some screenshots:

```python
from yellowbrick.regressor import AlphaSelection 
from sklearn.linear_model import RidgeCV, LassoCV, LassoLarsCV, ElasticNetCV

alphas = np.logspace(-12, -1, 400)

model = AlphaSelection(RidgeCV(alphas=alphas, scoring="neg_mean_squared_error"))
model.fit(X, y)
model.poof()
```

![ridge](https://cloud.githubusercontent.com/assets/745966/23665720/3d5aca58-0327-11e7-82d0-e27cf45c63e3.png)

```python
model = AlphaSelection(LassoCV(alphas=alphas))
model.fit(X, y)
model.poof()
```

![lasso](https://cloud.githubusercontent.com/assets/745966/23665747/56aefbfa-0327-11e7-92bc-d08017b89fc2.png)

```python
model = AlphaSelection(LassoLarsCV())
model.fit(X, y)
model.poof()
```

![lassolars](https://cloud.githubusercontent.com/assets/745966/23665759/5f02bdb4-0327-11e7-8a1d-70604a53029b.png)


```python
model = AlphaSelection(ElasticNetCV(alphas=alphas))
model.fit(X, y)
model.poof()
```

![elasticnet](https://cloud.githubusercontent.com/assets/745966/23665774/67001192-0327-11e7-9d1a-d4b1be0f5eb4.png)

**Comment by bbengfort** [comment]
Done but not in examples; closing this issue and filing bug report for the examples thing.

**Comment by BradKML** [comment]
Thanks for the note, but I am also encountering the `LassoLarsCV` issue as they don't require someone to define `alphas`.
Also as a side note how can [`LassoLarsIC`](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LassoLarsIC.html) use this?
