### ISSUE TITLE
API reference conflict for residuals.py in documentation

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#1031]
We have a minor documentation conflict where the `:class:~yellowbrick.regressor.residuals.PredictionError` directive in our documentation is not able to resolve the link to the API documentation. The issue is that we have the `yellowbrick.regressor.residuals` `automodule` in both `peplot.rst` and in `residuals.rst` so the documentation doesn't know which one to link to. The solutions that I can see to fix this are:

1. Move PredictionError to its own module `yellowbrick.regressor.peplot` (and associated tests)
2. Combine the residuals documentation into one page (probably not the best)
3. Research a way to get Sphinx to recognize two separate `automodule` directives (no idea if this is possible)

This issue was discovered in #1022

**Comment by rebeccabilbro** [comment]
Thank you @bbengfort for opening this so that we don't forget it in the midst of the quick method extravaganza! My vote is for option # 1!
