### ISSUE TITLE
ROCAUC treats binary classification as multiclass for estimators with predict_proba available

### ISSUE THREAD

**Issue by VladSkripniuk** [DistrictDataLabs/yellowbrick#1040]
**Describe the bug**
``ROCAUC`` plots 4 different curves for a binary classification problem when using an estimator with ``predict_proba``, which returns predictions of shape ``nx2``. Only one curve is plotted when estimator only has ``decision_function``, which returns predictions of shape ``nx1``. I think only one ROC curve should be drawn for a binary classification problem, as in the binary case the two ROC curves before averaging are just a reflection of each other.

For comparison, ``PrecisionRecallCurve`` plots 1 curve for binary classification irrespective, whether provided estimator uses ``predict_proba`` or ``decision_function``.

**To Reproduce**

To see this behavior it is enough to look at 
``yellowbrick/tests/baseline_images/test_classifier/test_rocauc/test_binary_decision.png`` and ``yellowbrick/tests/baseline_images/test_classifier/test_rocauc/test_binary_probability.png``

**Expected behavior**

I expected to see just one ROC for binary classification instead of separate curves for class 0 and 1 and their micro and macro averaging.

**Comment by VladSkripniuk** [comment]
To draw just 1 ROC curve minor changes are needed in ``ROCAUC``, I can work on this.

**Comment by bbengfort** [comment]
@VladSkripniuk thank you so much for opening this issue and for the two PRs - I've been away on travel and we've been working to get the v1.1 release out; but I'll get to your PRs soon!

**Comment by lwgray** [comment]
@VladSkripniuk which sklearn estimators do you believe should produce single curves?

**Comment by VladSkripniuk** [comment]
@lwgray basically all estimators which solve binary classification problem, i.e. estimators which have `predict_proba` or `decision_function` which returns array of shape (n_samples,2) or (n_samples,)

**Comment by bbengfort** [comment]
Relates to #1041

**Comment by VladSkripniuk** [comment]
@lwgray @bbengfort could you please take a look at  PR #1056. This PR uses `sklearn.utils.multiclass.type_of_target` to infer whether the classification task is binary or multi class. I left as many tests as possible not changed.
