### ISSUE TITLE
Definition of “Precision” seems incorrect...

### ISSUE THREAD

**Issue by Scoodood** [DistrictDataLabs/yellowbrick#1049]
On this page at [ClassificationReport](https://www.scikit-yb.org/en/latest/api/classifier/classification_report.html) 

![CE6AA3AE-37ED-4CA2-8D19-6AF2395DAC79](https://user-images.githubusercontent.com/15989924/76366402-1eaf6500-62e7-11ea-9c32-1ea7c17964c3.jpeg)

For binary classifier, the part **“not to label an instance positive that is actually negative”** sounded like “to correctly classified a negative”, which is the definition of **True Negative** right? I think the first sentence should be removed to avoid confusion.

**Comment by bbengfort** [comment]
@Scoodood I agree that we could make it more clear; however I don't think we can necessarily simply remove the first sentence; do you have an edit to suggest?

**Comment by Scoodood** [comment]
Hi @bbengfort, 

If we simplified the first sentence it will read
"**Precision** is the ability of a classifier to correctly label an instance negative as negative."

That definition belongs to the **True Negative Rate**, not **Precision**. According to the [wikipedia](https://en.wikipedia.org/wiki/Precision_and_recall), 
Precision = TP / (TP + FP) = [Positive Predictive Value (PPV)](https://en.wikipedia.org/wiki/Positive_and_negative_predictive_values)

The denominator term TP + FP also means total predicted output. So the whole equation means **for all cases that were predicted as positive by the classifier, what percent was actually correct**. But your second sentence already said this. 

The formula of TPR and PPV is very similar, and yet their interpretation is different.
TPR = The ability of classifier to recognize positive instance
PPV = The ability of classifier to give relevant positive output

So if you insist to keep the first sentence, then I would like to suggest something like this
**Precision measures the ability of a classifier to give relevant positive output.**

But I think your second sentence is clear enough even if we skip the first sentence.
