### ISSUE TITLE
Unable to upgrade yellowbrick with pip

### ISSUE THREAD

**Issue by karthikreddykuna** [DistrictDataLabs/yellowbrick#1063]
Hi,

I am trying to upgrade the package from 0.9.1 to 1.1 using "pip install  yellowbrick". Ideally it should uninstall the existing version and install the new version. But, it's not working.

It's working only when i'm using pip install -U yellowbrick.

**Comment by rebeccabilbro** [comment]
Hi @karthikreddykuna and welcome to Yellowbrick! 

In Python, when you upgrade any package using `pip`, you will always need to `pip install -U` or `pip install --upgrade` the package. The `pip` program checks what's already in your computer's `site-packages` and if you already have the target package, as well as all of it's dependencies, it determines that the package requirements are already satisfied and does not automatically upgrade. This is not particular to Yellowbrick. 

If you're curious, you can read up on the history of the Python Package Index's decision [here](https://github.com/pypa/pip/issues/3786). 

Thanks again for checking out Yellowbrick!
