### ISSUE TITLE
issue in installation in ubuntu

### ISSUE THREAD

**Issue by parulmishra19** [DistrictDataLabs/yellowbrick#1065]
**try:
import deepmatcher
except:
!pip install -qqq deepmatcher

While running the above code in python 3.6 i am getting the error mention below

File "/home/vikrant/anaconda2/lib/python2.7/site-packages/deepmatcher/data/field.py", line 163
    def build_vocab(self, *args, **vectors=None**, cache=None, **kwargs):
                                                           ^
SyntaxError: invalid syntax

Showing error at vectors
**

@DistrictDataLabs/team-oz-maintainers

**Comment by rebeccabilbro** [comment]
Hi @parulmishra19, and welcome to Yellowbrick &mdash; however based on the above error message, your issue appears to be with the `deepmatcher` library rather than Yellowbrick.
