### ISSUE TITLE
Image missing for JointPlotVisualizer example in Quickstart

### ISSUE THREAD

**Issue by tktran** [DistrictDataLabs/yellowbrick#1077]
The Quickstart tutorial at [https://www.scikit-yb.org/en/latest/quickstart.html](https://www.scikit-yb.org/en/latest/quickstart.html) has a section that illustrates the use of JointPlotVisualizer, but the associated plot directive fails to output anything (that is, a .PNG of the intended visualization, in addition to links to the .PNG and a .PDF).

After some investigation I found out that this plot directive works when pandas is installed and fails when it is not, due to a line in jointplot.py that calls "data[:, idx]", where idx is a list of column names. When pandas is missing, the dataset loader sets data to a numpy array instead of a pandas df (ref: [https://www.scikit-yb.org/en/latest/api/datasets/](https://www.scikit-yb.org/en/latest/api/datasets/), section "API Reference"). But the indexes used in this example are ('temp', 'feelslike'), and the numpy array throws an exception when these strings (anything non-numerical) are used as indices.

**Comment by bbengfort** [comment]
@tktran thank you so much for this note and good catch in the documentation! Based on your analysis of the issue, I think the fix would be to add pandas as a dependency to `docs/requirements.txt` -- this will install pandas on ReadTheDocs when the documentation is built and ensure that the JointPlot visualizer is correctly constructed. It would be great if you could open a PR for this simple fix - it would get your name on the contributors list and hopefully, inspire you to contribute more in the future!

**Comment by tktran** [comment]
@bbengfort Hello, I've made an PR for this fix. Please excuse (delete?) the two PRs I made and closed before making the final one, as they had errors (where I referenced the wrong Issue #s). I certainly am interested in contributing more going forward; thank you for the welcome.
