### ISSUE TITLE
Show ROC for train and test + hide macro/micro in binary classification.

### ISSUE THREAD

**Issue by pablo14** [DistrictDataLabs/yellowbrick#1087]
Hi! Thanks (again) for this incredible package 👍 

I hope not to be missing heavily with this feature, I read all of the documentation + google + stackoverflow. Please if I'm wrong to point me in the right direction (=> URL)

Normally we check train data vs test data. I see that ROC feature only shows the data for test. It would be nice to see the whole picture and check if the model is overfitting.

But it is not easy in multiclass.

In addition, I'd like to know how micro/macro statistics are calculated in binary class. Never see it before (and I guess it is only useful in multiclass). Thus, my recommendation is to turn them False by default.

It can be done smoothly in sklearn:
![image](https://user-images.githubusercontent.com/9369685/87863788-97799a00-c935-11ea-8dfa-e75d4942edb4.png)

In yellowbrick, for the same data I see:
![image](https://user-images.githubusercontent.com/9369685/87863816-1242b500-c936-11ea-9b80-130b66c83ced.png)

As you can see, in the last plot the information regarding micro/macro does not add value, but the fact that the model heavily overfitting cannot be missed.

This is my hack, to pass the train data as test data as shown in the image:
![image](https://user-images.githubusercontent.com/9369685/87863843-6057b880-c936-11ea-9270-8c87ed97cfa0.png)

Given the mentioned behavior, why do we have to pass the train in order to plot since the current plot only shows the data for testing? Wouldn't be enough the model + the test data?

Finally, another suggestion is in binary classification, to hide less representative class. It shouldn't add too much value to show both classes.

Thanks a lot in advance! Keep rocking 🤘

**Comment by bbengfort** [comment]
Hi @pablo14 - thanks for using Yellowbrick and for the great suggestions! Yellowbrick implements the scikit-learn estimator API - so the training data is used to fit the underlying estimator; the goal for this was to be able to construct visual pipelines that assisted in the experimental process, though that's still experimental. However, I believe the current `roc_auc` functionality does do what you'd like it to do as follows:

```python
# Fit the estimator ahead of time, you could use the wrapped estimator in Yellowbrick, but
# this makes things a bit more apparent about what is going on.
rf = RandomForestClassifier().fit(X_train, y_train)

# Create a fig, ax to plot on, you could also use the ax created by the first Yellowbrick visualizer,
# but again, this is just to be even more clear about what is going on.
_, ax = plt.subplots(figsize=(9,6))

# Plot the training data using the quick method, specify that the classifier has already been fitted
# and that this is a binary classification, which turns off the micro, macro, and per_class flags. Note
# that you could also manually turn off each of these flags if you wanted, but this is a simple way
# to specify all three flags. 
roc_auc(rf, X_train, y_train, ax=ax, binary=True, is_fitted=True)

# Now plot the test data using the same classifier and same axes
roc_auc(rf, X_test, y_test, ax=ax, binary=True, is_fitted=True)
```

This results in the same figure as in your sklearn example, with the same number of lines of code.

**Edit**

I just realized that the `binary` flag is still in the `develop` branch: see [docs here](https://www.scikit-yb.org/en/develop/api/classifier/rocauc.html#yellowbrick.classifier.rocauc.roc_auc) and is related to #1041 -- this feature will be out very soon, but you could `pip install git+https://github.com/DistrictDataLabs/yellowbrick.git@develop` to install the development branch now. The update will be included in the v1.2 release.

**Comment by bbengfort** [comment]
For the sake of, completeness, here is the 2 line version of the above:

```python
# Fit a classification model on training data, and draw ROC curves for test data
viz = roc_auc(RandomForestClassifier(), X_train, y_train, X_test, y_test, binary=True)

# Draw ROC curves for training data on same Axes with wrapped estimator
roc_auc(viz.estimator, X_train, y_train, ax=viz.ax, binary=True, is_fitted=True)
```

**Comment by pablo14** [comment]
Thanks for such a complete & quick answer @bbengfort ! 

I'm in yb 1.1 version. If I do:

```
_, ax = plt.subplots(figsize=(9,6))

# Fit a classification model on training data, and draw ROC curves for test data
viz = roc_auc(pipe_rf, x_train, y_train, x_test, y_test, binary=True, macro=False, micro=False, is_fitted=True)

# Draw ROC curves for training data on same Axes with wrapped estimator
roc_auc(viz.estimator, x_train, y_train, ax=viz.ax, binary=True, is_fitted=True)

```
I get:
![image](https://user-images.githubusercontent.com/9369685/87989660-d421ce80-cab8-11ea-9a95-8fdfa897a11b.png)

I don't see the tr/ts curves. Is it going to be in yb 1.2?


In addition the following warnings appears:

```/usr/local/lib/python3.7/site-packages/sklearn/base.py:213: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  FutureWarning)
```

And, at the same time, the pipeline schema I used (maybe is this related to sklearn?):

![image](https://user-images.githubusercontent.com/9369685/87989813-1b0fc400-cab9-11ea-9b36-1496133b23cb.png)

If you need to raise another issue for this, LMK. 

Thanks, again, in advance.

**Comment by bbengfort** [comment]
@pablo14 yes - sorry the message got buried, this functionality will be in version 1.2. 

As for the warning - I'm not sure where that's coming from. If you can localize it to a place in yellowbrick code, please feel free to open another issue.
