### ISSUE TITLE
Parallel Plot with independent vline

### ISSUE THREAD

**Issue by franperezlopez** [DistrictDataLabs/yellowbrick#1089]
**Describe the solution you'd like**
`ParallelCoordinates` plots each vline using a shared y scale. Instead of normalizing the values (using the parameter normalize), I'd like to keep original values, and allow each vline to have its own scale (scaling / moving the axis in order to fit current figsize)

**Examples**
I believe I've seen this behavior in other packages (i.e. plotly)

![image](https://user-images.githubusercontent.com/1222398/88701023-c4823580-d109-11ea-9323-4b6ba3b6e705.png)

**Comment by bbengfort** [comment]
Hello, @franperezlopez thank you for using Yellowbrick and thank you for your suggestion. I've done some extensive research on your suggestion and while I agree it would be a useful feature, unfortunately, I don't think it's possible with matplotlib. The way that the web frameworks like plotly work is to create an independent object for each axes - then independent lines are drawn across the axes using relative positioning. This is a result of how drawing is conducted using canvas or svg elements. 

With matplotlib, the `Axes` objects are not independent with respect to the data. So while you can [create multiple axes](https://matplotlib.org/3.1.1/gallery/ticks_and_spines/multiple_yaxis_with_spines.html), you have to draw each data on each axes separately:

![Multi-axes drawing](https://matplotlib.org/3.1.1/_images/sphx_glr_multiple_yaxis_with_spines_001.png)

This would allow you to have independent scaling you requested, but how would you deal with the x-axis? After several attempts, I'm afraid I do not a see a path forward or a solution at this time. Note that right now, what we do is use a single y-axis (hence all sharing the same scale), then take out the spines, and plot lines for each "axes" object, they aren't in fact true axes. That's also why the scale is on the left side where it normally is. 

Sorry I couldn't find a way to make it work out - but if you can find a way to implement this in matplotlib, please let us know - we'd be more than happy to see a prototype and figure out if we could implement it in Yellowbrick.
