### ISSUE TITLE
Make YB stickers

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#110]
I know this is lame but I don't want to forget.

**Comment by rebeccabilbro** [comment]
thoughts from Ben

- likes stylized text
- doesn't like images that don't stand alone
- avoid logo plus text combination (not two separate components

interlocking yb?

**Comment by rebeccabilbro** [comment]
tony suggested http://www.logonerds.com/ and  https://www.stickermule.com/

**Comment by bbengfort** [comment]
I've also used https://99designs.com/ for work before; including the stickers that are on the back of my laptop. It's a bit more expensive, but potentially get more ideas because there are more designers.

**Comment by rebeccabilbro** [comment]
Here's a [possible place for inspiration](http://www.logobook.com/letter/b/), if we're thinking of going with the YB initials. @bbengfort let me know if anything catches your eye.

**Comment by bbengfort** [comment]
Oh nice, yes this is definitely cool. I like the fluid, curvy melding of the letters, like: [bonairia-casu](http://www.logobook.com/logo/bonairia-casu/), [tobu](http://www.logobook.com/logo/tobu/) or [a-bertelli](http://www.logobook.com/logo/a-bertelli/); it seems to invoke curves through space, which is good. I also like the braiding effect of [tolimpex](http://www.logobook.com/logo/tolimpex/) or [yamamura senkaku[(http://www.logobook.com/logo/yamamura-senkaku/) which seems to also invoke dimensionality. There may be something to a more topological view like [yamachan planning](http://www.logobook.com/logo/yamachan-planning/) or [york center](http://www.logobook.com/logo/york-centre/), but that was certainly way to busy with the "B" letter. 

Although [amici di brera](http://www.logobook.com/logo/amici-di-brera/) is a bit too thin, I think I prefer the vertical layout to the horizontal for the YB. But something more clear than [broderna larsson](http://www.logobook.com/logo/broderna-larsson/) or [banco itau america](http://www.logobook.com/logo/banco-itau-america/). 

The negative space associated with curves is also interesting like [bertuzzi](http://www.logobook.com/logo/bertuzzi/) or [york construction](http://www.logobook.com/logo/york-construction/). 

It has nothing to do with us, but I appreciate [cobbler's bench](http://www.logobook.com/logo/cobblers-bench/); I think that'd be a great logo for a cobbler! I'm also still trying to decide how I feel about [yoshihiro tatsuki](http://www.logobook.com/logo/yoshihiro-tatsuki/).

**Comment by rebeccabilbro** [comment]
pulling into this sprint, with the goal of having an early draft by next sprint review on 4/5

**Comment by rebeccabilbro** [comment]
Ok, drafted some initial ideas and sent to logonerds to start the process. Will follow up when I get their professional mockup

![yb_logo_ideas](https://cloud.githubusercontent.com/assets/8760385/24565151/f2238b2a-1621-11e7-88ef-38d4fc86956a.JPG)

**Comment by rebeccabilbro** [comment]
Ok, here's the first draft of the yb logo from logonerds. I prefer concept 4. Anyone else have thoughts?

![yb order 78875-01](https://cloud.githubusercontent.com/assets/8760385/24928256/d2391d6e-1ecf-11e7-957d-a7bcf371cdd4.jpg)

**Comment by morganmendis** [comment]
@rebeccabilbro  for whats its worth, I like 3,1, and 5 in that order of preference :)

**Comment by NealHumphrey** [comment]
I'd lean towards 3 but honestly I think there could be a better pick out there somewhere, they all fall a little flat in my opinion. 

Also don't forget to consider the impact of resizing. Worst case scenario is a 16x16 favicon, at which point any internal texture is indiscernable, but even at a moderately small icon size some of the textures in these designs will start to get muddy. This could be handled by altering the design at a certain size threshold (i.e. making the bricks bigger w/ respect to the letters), or just a different design. We went through that with the first logo we picked for [Flashband](http://www.flashband.org) which had some elements that wouldn't scale down appropriately.

**Comment by NealHumphrey** [comment]
Note I'm not dismissing the yb filled with bricks concept, but I think coloring / font / brick design in the logonerds mockups could be done better.

**Comment by ojedatony1616** [comment]
Out of the options posted, I like the font in concepts 3 and 6 best. I also like the bricked letters idea, but think they would look better if the bricks themselves were yellow, the outlining was dark gray, and the b-hole (for lack of a better term) was present and not covered. Perhaps they can add some additional texture or shadowing in order to make the designs have a little more depth as well. I think it would also be good to see a couple of designs with the full 'yellowbrick' name, if only just to see what it would look like.

**Comment by rebeccabilbro** [comment]
@morganmendis @NealHumphrey @ojedatony1616 - thanks for the feedback. I've never used logonerds before, but they do web and print ready design, which suggests they're prepared for images that require scaling. They also offer free revisions, so we can continue to iterate until we're happy with the look (though obviously I'd prefer to close this ticket relatively soon to move on to more interest yb tasks). I'll consolidate your feedback and send it to them tomorrow - anyone else want to weigh in before I do? @bbengfort?

**Comment by NealHumphrey** [comment]
@rebeccabilbro I'm sure they can handle it, but based on the mockups you gave you might need to explicitly tell them. I'm not sure all the use cases so I'm not sure what to recommend - but for example our user photos on this page are 44x44. Here's what option 3 looks like resized to that size - the bricks get lost though the yb is clear:
![yb-44](https://cloud.githubusercontent.com/assets/5642566/24972624/0b09513a-1f8a-11e7-8ca2-e1b29a441d82.jpg)


No need to hold up the process of sticker-creation too - You can also make a modified version later if needed. For example, sklearn's favicon is different but related to their standard logo. 

I agree w/ Tony on the bricks being yellow and b maybe having a hole.

**Comment by rebeccabilbro** [comment]
OK, edits submitted; will keep you posted.

**Comment by rebeccabilbro** [comment]
*cough* @jfhiggins *cough*

**Comment by tuulihill** [comment]
@rebeccabilbro my designer friend first declined, but then i showed him the sorry state of affairs and he said he take a stab at it tonight! will send it along if he does!

**Comment by rebeccabilbro** [comment]
@tuulihill Awesome!! (And thank goodness ;D)

**Comment by tuulihill** [comment]
OK, my friend Steve sent along these sketches and also the .ai files if any of these would be useful to adapt/resize in any way!  
[yellowbrick-sketches.pdf](https://github.com/DistrictDataLabs/yellowbrick/files/948710/yellowbrick-sketches.pdf)

**Comment by rebeccabilbro** [comment]
@tuulihill you're a lifesaver! We'll send in a print order on Monday -- please convey our sincere gratitude to Steve; these look fantastic!

**Comment by jkeung** [comment]
@tuulihill @rebeccabilbro I also am working with my friend to brainstorm a few ideas he said he would have something drafted by this weekend also

**Comment by rebeccabilbro** [comment]
@jkeung fantastic, can't wait to see -- thank you all so much for your help with this!

**Comment by tuulihill** [comment]
@rebeccabilbro i'll email you the zipped folder with the individual images in it! also won't be offended if something better comes along :)

**Comment by bbengfort** [comment]
Sticker Proofs: 

![1012504](https://cloud.githubusercontent.com/assets/745966/25355191/cc898758-2903-11e7-8e20-9b642265494b.png)
![1012505](https://cloud.githubusercontent.com/assets/745966/25355190/cc87ae24-2903-11e7-88cd-cb6b9356d80c.png)
![1012506](https://cloud.githubusercontent.com/assets/745966/25355192/cc8baa56-2903-11e7-92a0-16cb22472d3f.png)

**Comment by jkeung** [comment]
they came out good! Why does the last logo have that stray line on the right side?

**Comment by bbengfort** [comment]
@jkeung -- don't know; it wasn't in the EPS file?

**Comment by jkeung** [comment]
@bbengfort ah it did, I should've taken a look when my friend sent it over. I can get that fixed if its not too late

**Comment by bbengfort** [comment]
@jkeung sorry ... the order has been proofed and submitted; but I don't think it's a big deal. I actually thought it was a lego thing on first glance. 

I think the order will arrive before our meeting next Wednesday, so everyone should have stickers by then!

**Comment by jkeung** [comment]
cool!
