### ISSUE TITLE
yellowbrick dataset load functions are not able to download data

### ISSUE THREAD

**Issue by ypauchard** [DistrictDataLabs/yellowbrick#1101]
**Describe the bug**
Calling one of the yellowbrick.datasets.load_() functions for a dataset that is not locally cached fails.

**To Reproduce**

```python
from yellowbrick.datasets import load_energy

X, y = load_energy()
```

**Expected behavior**
The energy dataset is not cached locally and should be downloaded first, then loaded. It fails, instructing to contact yellowbrick maintainers.

**Traceback**

```
---------------------------------------------------------------------------
DatasetsError                             Traceback (most recent call last)
<ipython-input-19-af4150160b82> in <module>
      2 from yellowbrick.datasets import load_credit
      3 
----> 4 X, y = load_credit()
      5 
      6 # X, y = load_energy()

~/miniconda3/envs/ensf-ml/lib/python3.8/site-packages/yellowbrick/datasets/loaders.py in load_credit(data_home, return_dataset)
    191         data in a variety of formats as well as associated metadata and content.
    192     """
--> 193     return _load_dataset("credit", data_home, return_dataset)
    194 
    195 

~/miniconda3/envs/ensf-ml/lib/python3.8/site-packages/yellowbrick/datasets/loaders.py in _load_dataset(name, data_home, return_dataset)
     60     if return_dataset:
     61         return data
---> 62     return data.to_data()
     63 
     64 

~/miniconda3/envs/ensf-ml/lib/python3.8/site-packages/yellowbrick/datasets/base.py in to_data(self)
    175         """
    176         if pd is not None:
--> 177             return self.to_pandas()
    178         return self.to_numpy()
    179 

~/miniconda3/envs/ensf-ml/lib/python3.8/site-packages/yellowbrick/datasets/base.py in to_pandas(self)
    218         # Ensure the metadata is valid before continuing
    219         if self.meta is None:
--> 220             raise DatasetsError(
    221                 (
    222                     "the downloaded dataset was improperly packaged without meta.json "

DatasetsError: the downloaded dataset was improperly packaged without meta.json - please report this bug to the Yellowbrick maintainers!
```

**Desktop (please complete the following information):**
 - OS: macOs and Windows
 - Python Version Anaconda Python 3.8
 - Yellowbrick Version 1.1

**Many thanks!**

**Comment by mgarod** [comment]
I am experiencing similar issues. I created a brand new environment and tried to run `python -m yellowbrick.download` and end up with `urllib.error.HTTPError: HTTP Error 403: Forbidden`.

I dug into https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/datasets/manifest.json and found that these links end with `Access Denied`. I think someone forgot to pay the AWS bill? ;)

**Comment by bbengfort** [comment]
@ypauchard @mgarod AWS has been changing its access policies and blocked public reads. I've updated the ACLs - would you mind trying again and seeing if it has been fixed?

**Comment by ypauchard** [comment]
> @ypauchard @mgarod AWS has been changing its access policies and blocked public reads. I've updated the ACLs - would you mind trying again and seeing if it has been fixed?
> 
> _Update_
> 
> I just tested on a clean computer and was able to download the datasets. Please feel free to open the issue again if you're having any problems.

@bbengfort Thank you for looking into this so quickly. It does not work for me yet, I still get the same error. Maybe there is a delay for ACLs to update?

**Comment by bbengfort** [comment]
@ypauchard It could be there is a delay, but also perhaps your data download folder got stuck in a weird state? Would you mind running the following commands to try to refresh your datasets?

```
$ python -m yellowbrick.download -c -f
```

Make sure that you run this command in the virtual environment or python distribution you installed yellowbrick in.

**Comment by ypauchard** [comment]
@bbengfort Ha, it works! The failed download left an empty folder in the datasets directory with the dataset name. Removing the empty folder was enough for download to succeed.

Many thanks!

**Comment by bbengfort** [comment]
Glad that got it sorted out!
