### ISSUE TITLE
importing yellowbrick messes with default matplotlib settings

### ISSUE THREAD

**Issue by delorytheape** [DistrictDataLabs/yellowbrick#1109]
When the yellowbrick module is imported, it messes with the default matplotlib linestyle. 

Eg. Compare outputs of the following MWE with the yellowbrick import line present/absent.
* markeredgewidth (mew) is set to 0.0 (compared to default of 1.0 when yellowbrick is not imported)
* markersize (mw) is set to 7.0 (compared to default of 6.0  when yellowbrick is not imported) 
* solid_capstyle is set to 'round' (compared to default of 'projecting'  when yellowbrick is not imported)
* the gridlines of the plot are turned on  (compared to off  when when yellowbrick is not imported)

python version = 3.8.5
matplotlib version = 3.3.1
yellowbrick version = 1.1

```
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np

#import yellowbrick as yb   # Comment or uncomment this line and compare differences in output

if __name__ == "__main__":

    x = np.random.rand(10)
    y = np.random.rand(10)

    fig = plt.figure('Test',dpi=72)
    ax_1 = fig.add_subplot(111)
    p=ax_1.plot(x,y,marker='x',ls='')
    print(plt.getp(p))
    plt.show()

```

**Comment by bbengfort** [comment]
Hello @delorytheape thank you for using Yellowbrick and your interest in using matplotlib defaults. We are currently discussing how to manage Yellowbrick-specific styles in #734; if you'd like, please feel free to use that issue and comment over there. However, I believe it may be simplest to address your concern directly using the `reset_orig` or `reset_defaults` functions in Yellowbrick as follows:

```python
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np

import yellowbrick as yb
yb.reset_orig()

if __name__ == "__main__":

    x = np.random.rand(10)
    y = np.random.rand(10)

    fig = plt.figure('Test',dpi=72)
    ax_1 = fig.add_subplot(111)
    p=ax_1.plot(x,y,marker='x',ls='')
    print(plt.getp(p))
    plt.show()
```

This produces the following image, which I believe matches the original exactly:

![Test2](https://user-images.githubusercontent.com/745966/95249964-7a8f8d00-07e7-11eb-8cf6-9e698e1203e1.png)

Note that `reset_orig` resets the matplotlib styles to whatever they were before Yellowbrick was imported and `reset_defaults` directly modifies the rcParams to the matplotlib defaults. 

Thanks again for using Yellowbrick!

Closing in favor of #734
