### ISSUE TITLE
Update reference on Zenodo (v1.2)

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#1114]
Version 1.2 has been released, time to update our reference on Zenodo!

**Comment by lwgray** [comment]
@rebeccabilbro @bbengfort can we close this issue?  Zenodo is showing v1.3post1

**Comment by bbengfort** [comment]
@lwgray good catch; yes we can close this - both 1.2 and 1.2.1 are on Zenodo!
