### ISSUE TITLE
Yellowbrick v1.2 Conda Package

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#1115]
Version 1.2 has been released, once it's been verified we need to [upload it to conda](http://www.scikit-yb.org/en/develop/contributing/advanced_development_topics.html#deploying-to-anaconda-cloud)!

**Comment by jamesmyatt** [comment]
What's the status of the conda-forge version? https://anaconda.org/conda-forge/yellowbrick

**Comment by lwgray** [comment]
@jamesmyatt thanks for the comment.
@rebeccabilbro  Can this issue be closed?  The current conda-forge version is the current yellowbrick release v1.2

**Comment by jamesmyatt** [comment]
@lwgray , is conda-forge the official channel now, rather than districtdatalabs?

**Comment by lwgray** [comment]
@jamesmyatt let me check with the others
@bbengfort is there an official conda install channel? conda-forge versus districtdatalabs

**Comment by bbengfort** [comment]
@lwgray I wasn't aware of the conda forge version; the districtdatalabs version is the "official" one; at least the one that we upload to. It's nice that someone is making sure that Yellowbrick is on conda cloud. @jamesmyatt you're right we've dropped the ball getting v1.2 deployed via conda; I'll work on getting it up right now.

**Comment by bbengfort** [comment]
@jamesmyatt @lwgray @rebeccabilbro ok, we've uploaded v1.2 to Anaconda Cloud at the districtdatalabs channel. Sorry it took so long, it's not difficult, just time consuming! 

https://anaconda.org/DistrictDataLabs/yellowbrick

**Comment by rebeccabilbro** [comment]
@bbengfort thank you so much for getting the Anaconda package updated; I know it's a handful and I'm sorry we let this fall through the cracks!

@jamesmyatt &mdash; would you mind verifying that you can update to v1.2 as expected via `conda`? We don't currently have many YB maintainers who use Anaconda, so just want to make sure!

**Comment by jamesmyatt** [comment]
I've just done a `conda env update` and got 1.2 using "districtdatalabs::yellowbrick >=1"

**Comment by rebeccabilbro** [comment]
Fantastic, thanks @jamesmyatt!
