### ISSUE TITLE
yellowbrick.exceptions.DatasetsError: the downloaded dataset was improperly packaged without meta.json - please report this bug to the Yellowbrick maintainers!

### ISSUE THREAD

**Issue by lihuiknight** [DistrictDataLabs/yellowbrick#1116]
**Describe the bug**
yellowbrick.exceptions.DatasetsError: the downloaded dataset was improperly packaged without meta.json - please report this bug to the Yellowbrick maintainers!

**To Reproduce**

```
import pandas as pd
from yellowbrick.datasets import load_bikeshare

X, y = load_bikeshare()

from yellowbrick.regressor import ResidualsPlot
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

# Create training and test sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.1
)

visualizer = ResidualsPlot(LinearRegression())
visualizer.fit(X_train, y_train)
visualizer.score(X_test, y_test)
visualizer.show()

```

**Comment by bbengfort** [comment]
@lihuiknight thank you for using Yellowbrick and thanks for reporting the issue! We had a minor blip with our S3 service last week (see #1101) and that may have caused some issues. Please run the following command to refresh your dataset:

```
$ python -m yellowbrick.download -c -f 
```

This will download all of the datasets to your local machine. Please ensure that you run this command in the virtual environment or python distribution you installed Yellowbrick in!
