### ISSUE TITLE
Show regression negative validation CV scores  as possitive in plots.

### ISSUE THREAD

**Issue by vchaparro** [DistrictDataLabs/yellowbrick#1119]
Hi!

This is just a question, not an issue. In validation plots such as CV scores or learning curves, is there a way to change the sign of the RMSE to show possitive in plots (that is negative because sklearn API maximizes the score, so to minimize it as regression requires, the negative value is needed).

I can't find a way to get the scores and change it through the visualizer before plotting the values.

Thanks in advance!

**Comment by bbengfort** [comment]
Hi @vchaparro thanks for using Yellowbrick, and thank you for your question! The best way that I can think to do this is to pass a custom `scoring` function to any visualizer that supports this parameter, which both `CVScores` and `LearningCurves` do! The function must have a signature `scorer(estimator, X, y)` (see [sklearn.model_selection.learning_curve](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.learning_curve.html) or [sklearn.model_selection.cross_val_score](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_score.html) for more information). I haven't tested it, but I believe the following would work:

```python
import numpy as np

from sklearn.metrics import mean_squared_error 
from yellowbrick.model_selection import learning_curve

def positive_rmse(estimator, X, y):
    y_pred = estimator.predict(X)
    rmse = mean_squared_error(y, y_pred, squared=False)
    return np.abs(rmse)

viz = learning_curve(estimator, X, y, scoring=positive_rmse)
```

Hope that helps - let me know if it works!

**Comment by vchaparro** [comment]
Thanks  @bbengfort , it works perfectly.
