### ISSUE TITLE
Update kneed

### ISSUE THREAD

**Issue by arvkevi** [DistrictDataLabs/yellowbrick#1120]
The [kneed](https://github.com/arvkevi/kneed) library has been updated a couple of times (with bugfixes!) since it was incorporated into the yellowbrick code. I would like to update the knee finding algorithm to be consistent with the [0.7.0 release](https://github.com/arvkevi/kneed/releases/tag/v0.7.0) of kneed.

Would you welcome a PR to update the code? Thanks!

**Comment by bbengfort** [comment]
Hi @arvkevi - yes, we would welcome a PR to update the code, and thank you so much for asking! As a fellow maintainer, I'm guessing that you have also had the experience where PRs out of the blue can inspire a certain … dread. But we've really enjoyed having kneed as part of our codebase and we're always looking for new opportunities to use it to detect inflection points in other visualizers!

**Comment by arvkevi** [comment]
Thanks, @bbengfort, see #1121. I'm so glad to hear that it could be used in other visualizers. These changes should reduce the number of surprises where: "I thought the elbow point should be at x=<subjective value>", and kneed was previously unable to find them.

**Comment by arvkevi** [comment]
Hi @bbengfort, #1121 should be ready for review now. Thank you!

**Comment by bbengfort** [comment]
@arvkevi perfect thank you - will review shortly!
