### ISSUE TITLE
MissingValuesBar does not work on categorical columns

### ISSUE THREAD

**Issue by ngupta23** [DistrictDataLabs/yellowbrick#1131]
## Describe the solution you'd like
Currently, I am unable to get MissingValuesBar to work on data that has categorical columns. It is internally trying to convert these columns to a floating point value and producing an error at this step. I am hoping this can be handles internally in the class itself since it is just checking for missing values so it should not care about the type of column.

## Is your feature request related to a problem? Please describe.

Described above, but this is the error that I get on categorical data. One of the columns has continent values and it looks like it is producing an error at that point.

```python
# Instantiate the visualizer
plt.figure(figsize=(15,10))
visualizer = MissingValuesBar(features=features)

visualizer.fit(X=data[features], y=data[target].values) # Supply the targets via y
_ = visualizer.show() # Finalize and render the figure
```

**Traceback**
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-2b58032dfe22> in <module>
      3 visualizer = MissingValuesBar(features=features)
      4 
----> 5 visualizer.fit(X=data[features], y=data[target].values) # Supply the targets via y
      6 _ = visualizer.show() # Finalize and render the figure

~\.conda\envs\ds7337_cs3\lib\site-packages\yellowbrick\contrib\missing\base.py in fit(self, X, y, **kwargs)
     70         self.y = y
     71 
---> 72         self.draw(X, y, **kwargs)
     73         return self
     74 

~\.conda\envs\ds7337_cs3\lib\site-packages\yellowbrick\contrib\missing\bar.py in draw(self, X, y, **kwargs)
    137         target values.
    138         """
--> 139         nan_col_counts = self.get_nan_col_counts()
    140 
    141         # the x locations for the groups

~\.conda\envs\ds7337_cs3\lib\site-packages\yellowbrick\contrib\missing\bar.py in get_nan_col_counts(self, **kwargs)
    110 
    111         else:
--> 112             nan_matrix = self.X.astype(np.float)
    113 
    114         if self.y is None:

ValueError: could not convert string to float: 'euorpe'
```

**If I just take the numeric features, it works well**

```python
# Instantiate the visualizer
plt.figure(figsize=(15,10))
visualizer = MissingValuesBar(features=features_numerical)

visualizer.fit(X=data[features_numerical], y=data[target].values) # Supply the targets via y
_ = visualizer.show() # Finalize and render the figure
```

**See output below**

![image](https://user-images.githubusercontent.com/33585645/100137410-0cb02b00-2e52-11eb-8a0f-04a94c07dfdd.png)

**Comment by bbengfort** [comment]
Hi @ngupta23 thank you so much for using Yellowbrick! Sorry it's taken us so long to reply to your issue, it just got buried in the stream of GitHub messages. I apologize for that. Thank you for mentioning the MissingValuesBar visualizer - right now this visualizer is in our `contrib` package since I don't think we fully fleshed it out for prime time use in the package. I believe @ndanielsen  was working on it - @ndanielsen do you have any comments?

If this visualizer is useful to you, we'd love to have you contribute to our project and help make the visualizer ready for categorical variables and moved out of contrib! Let us know if you're interested and how we can advise you to get started!

**Comment by ndanielsen** [comment]
@ngupta23 thanks for the detailed bug report. I'll take a look at this. My suggestion for the time being is that you encode categorical columns into numeric.

For example utilizing the [LabelEncoder in scikit-learn](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html) would resolve this:

```
from sklearn import preprocessing

le = preprocessing.LabelEncoder()
df['label'] = le.fit_transform(df['label'])

```
