### ISSUE TITLE
pytest-runner is deprecated

### ISSUE THREAD

**Issue by jamesmyatt** [DistrictDataLabs/yellowbrick#1132]
pytest-runner is deprecated: https://github.com/pytest-dev/pytest-runner/#deprecation-notice

If I find time, then I can make a PR, but I thought I'd let you know in the meantime.

**Comment by bbengfort** [comment]
@jamesmyatt thanks for the note! If you can get a PR together, that would be great!

**Comment by ndanielsen** [comment]
@bbengfort happy to pick this one up when CI is fixed.

**Comment by ndanielsen** [comment]
Scratch picking it up after CI is fixed, after looking into it -- it seemed fairly straightforward according to the pytest-runner docs
