### ISSUE TITLE
ValueError: too many values to unpack (expected 2) in Residual Plots Documentation.

### ISSUE THREAD

**Issue by Siddharth1698** [DistrictDataLabs/yellowbrick#1140]
**Describe the bug**
In Documentation of residual plots : https://www.scikit-yb.org/en/latest/api/regressor/residuals.html

Error in Code of load_concrete() . The following is shown as error:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-206-5d707f074e08> in <module>()
      6 
      7 # Load a regression dataset
----> 8 X, y = load_concrete()
      9 
     10 # Create the train and test data

ValueError: too many values to unpack (expected 2)

**Comment by bbengfort** [comment]
@Siddharth1698 thank you for using Yellowbrick - I'm sorry to hear that you're having trouble with it. Unfortunately, I am not able to reproduce your issue on OS X with Yellowbrick v1.2, scikit-learn v0.23.2 and matplotlib 3.3.1 -- the `load_dataset` methods are indeed supposed to return two values, `X` - the feature array and `y` - the target vector. 

The complete code that I used is exactly from the documentation you mentioned:

```python
from sklearn.linear_model import Ridge
from sklearn.model_selection import train_test_split

from yellowbrick.datasets import load_concrete
from yellowbrick.regressor import ResidualsPlot

# Load a regression dataset
X, y = load_concrete()

# Create the train and test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Instantiate the linear model and visualizer
model = Ridge()
visualizer = ResidualsPlot(model)

visualizer.fit(X_train, y_train)  # Fit the training data to the visualizer
visualizer.score(X_test, y_test)  # Evaluate the model on the test data
visualizer.show()                 # Finalize and render the figure
```

As far as I can tell it works exactly as advertised. I think that this means that there is something going on locally for you or in the context of the code that we can't see. 

Please feel free to reopen the issue with a bit more context including:

- Operating system 
- Yellowbrick, scikit-learn, and matplotlib versions
- The complete code and exception
