### ISSUE TITLE
While import the library and use load_mushroom get nan values

### ISSUE THREAD

**Issue by sparkingdark** [DistrictDataLabs/yellowbrick#1142]
```python
from yellowbrick.datasets import load_mushroom

df = load_mushroom()
print(df[1:5]) # inspect the first five rows
```

This library is giving nan values.

```
[(nan, nan, nan, nan) (nan, nan, nan, nan) (nan, nan, nan, nan)
 (nan, nan, nan, nan)]

```

this value.

**Comment by rebeccabilbro** [comment]
Hello @sparkingdark and thanks for using Yellowbrick!

Sorry to hear that you're having trouble. Unfortunately, I am not able to reproduce your issue on either Windows (Yellowbrick v1.2, scikit-learn v0.23.0, pandas 1.1.1) or OS X (Yellowbrick v1.2, scikit-learn v0.23.0, pandas 1.2.0)

As far as I can tell it works exactly as advertised. I think that this means that there is something going on locally for you or in the context of the code that we can't see. 

Please feel free to reopen the issue with a bit more context including:

- Operating system 
- Yellowbrick, scikit-learn, and pandas versions
- The complete code and exception
