### ISSUE TITLE
Discrimination Threshold - Running time

### ISSUE THREAD

**Issue by shaksham95** [DistrictDataLabs/yellowbrick#1145]
Hey,

First of all, yellow bricks have been a HUGE help to develop some of the most visually appealing plots that I could showcase in my work. Thank you for this package :)

The issue that I have been facing is concerning the use of the discrimination function. I have trained a random forest model using word embeddings (word2vec) on a movie review dataset: 25000 reviews ([Standford AI](https://ai.stanford.edu/~amaas/data/sentiment/)). 

Using the one-line function shown in the docs `discrimination_threshold(clf_rf_w2v, X_train_enc, train['sentiment']),` I tried generating the discrimination plot, and the plot generated successfully. **However, it took around 2 hr 18 mins for the plot to develop.** 

**What I want to understand is there a way by which time taken is reduced?**

**(OPTIONAL)**
It would also be nice to have a progress bar showcasing the number of folds left, estimated time, and so forth while generating the plots.

My machine configuration is:

- Processor: Intel(R) Core(TM) i5-8300H CPU@2.30 GhZ
- RAM: 8.00 GB
- OS: Windows 10 (x64)
- GPU: NVIDIA GTX 1050 4GB

**Comment by bbengfort** [comment]
Hi @shaksham95 thank you for using Yellowbrick, we're glad you're enjoying using it! 

The easiest way to reduce the time that's taken is to modify the `n_trials` and `cv` parameters, the number of iterations that the discrimination threshold takes is equal to the number of trials times the number of CV splits. By default, the function uses 50 trials and 10 splits, which could mean up to 500 iterations (depending on the CV splitter used)! 

See if the following speeds up the plot:

```python
discrimination_threshold(clf_rf_w2v, X_train_enc, train['sentiment'], n_trials=10, cv=0.25)
``` 

There [is a TODO](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/classifier/threshold.py#L259) to use `joblib` to parallelize iterations, but it hasn't been implemented yet. We'd welcome a PR to add this if you're interested in that functionality.
