### ISSUE TITLE
Investigate Palettable

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#115]
[Palettable](https://penandpants.com/2017/02/20/palettable-3-0-released/) is a Python library that packages a variety of color palettes for use with matplotlib or really anywhere.

The 3.0 release includes a number of new palettes:

 - cmocean from Kristen Thyng’s cmocean library
- New matplotlib palettes as added to matplotlib 1.5
- Sequential palettes from MyCarta
- Additional Wes Anderson palettes from the Wes Anderson Palettes blog

The new cmocean, matplotlib, and MyCarta palettes are created from data that contains 256 color points per palette. By default palettes are created with lengths 3-20 colors, but you can request longer ones via the get_map function.

**Comment by anshima1** [comment]
Hey! I want to work on this issue.

**Comment by rebeccabilbro** [comment]
Hi @anshima1 - that would be great! You can check out a bit of information about our current colors and styles [here](http://www.scikit-yb.org/en/latest/api/palettes.html) -- essentially we've got the basics but we're interested in some new options that would visually distinguish YB and add polish. Let me know if I can answer any questions and look forward to seeing what you come up with!

**Comment by anshima1** [comment]
https://github.com/DistrictDataLabs/yellowbrick/pull/622

Please Review my PR once and let me know what is missing and what more can be added. 
I will eventually keep modifying the code and keep looking at newer options available! 
Thanks for your prompt reply @rebeccabilbro !

**Comment by anshima1** [comment]
This was the first time I was using the palettable package, hence the PR is at a novice stage. (Also, I have just started with open source contributions, this was my third PR, so do give valuable inputs!)

**Comment by rebeccabilbro** [comment]
I think we can safely archive this one for now &mdash; thanks @thisHermit for the heads up!
