### ISSUE TITLE
A dangling print statement in the new 1.3 release while plotting LearningCurve & ValidationCurve.

### ISSUE THREAD

**Issue by Viveckh** [DistrictDataLabs/yellowbrick#1153]
**Describe the bug**
A dangling print statement in the new 1.3 release while plotting LearningCurve & ValidationCurve.

**To Reproduce**
Any snippet like the following
```python
viz = validation_curve(
    DecisionTreeClassifier(), X, y, param_name="max_depth",
    param_range=np.arange(2, 50, 2), cv=10, scoring="f1_macro"
)
```

**Dataset**
any

**Expected behavior**
Should not print these logs

**Traceback**

```
If applicable, add the traceback from the exception.
```

**Desktop (please complete the following information):**
 - macOS
 - python 3.7
 - Yellowbrick Version 1.3

**Additional context**
![image](https://user-images.githubusercontent.com/9113166/107856838-fda99b00-6df8-11eb-9cf6-5c4d26bec768.png)

**Comment by rebeccabilbro** [comment]
Thank you @Viveckh for the heads up! Working on a fix now & will include you in the release notes! Thank you for using Yellowbrick!
