### ISSUE TITLE
Feature importance plot has some image dimensions issues (large column name are cropped)

### ISSUE THREAD

**Issue by actcod01** [DistrictDataLabs/yellowbrick#1157]
Hi Guys,

The feature Importance plot didnt look well when column names are long.
![image](https://user-images.githubusercontent.com/67143298/108391039-4ae19e80-7237-11eb-8a6d-5b0d1c6bb1ca.png)

How to fix this issue ?
Thanks

**Comment by bbengfort** [comment]
Hi @actcod01 thanks for using Yellowbrick and sorry it's taken us so long to get back to you; it's been a crazy year! 

The way I normally make the column names fit is to use [`tight_layout`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.tight_layout.html), e.g. on the visualizer you could use:

```python
oz = FeatureImportances(model)
oz.fit(X, y)
oz.fig.tight_layout()
``` 

However, this line of code is called automatically from `finalize` or from `show`. E.g. in the following code snippet:

```python
from yellowbrick.model_selection import FeatureImportances
from yellowbrick.datasets import load_occupancy
from sklearn.ensemble import GradientBoostingClassifier

X, y = load_occupancy()
X.columns = ["this is a super long column really really really long", "a", "B", "c", "D"]
oz = FeatureImportances(GradientBoostingClassifier())
oz.fit(X, y)
oz.show()
```

The result is the following image with the correct layout:

![Figure_1](https://user-images.githubusercontent.com/745966/113359357-9c407b80-9315-11eb-9103-e4c00c0db921.png)

You would call `finalize` on the visualizer if you didn't want to `plt.show` or `plt.savefig` at the moment; calling `show()` on the visualizer also renders the image. 

I hope this solves your problem; if not - please feel free to reopen the issue with a code snippet, the yellowbrick, matplotlib, and scikit-learn versions and your operating system and python environment so we can better diagnose what's happening!
