### ISSUE TITLE
Change elbow plot fit time to use color palette instead of hardcoded "g"

### ISSUE THREAD

**Issue by jaymegordo** [DistrictDataLabs/yellowbrick#1159]
https://github.com/DistrictDataLabs/yellowbrick/blob/2d4e23648b33ad42e2e95b559e35ca6de2db5bb6/yellowbrick/cluster/elbow.py#L406

Would be nice if the fit time line, as well as the elblow line - (black/dark-grey? not sure where/if this is hardcoded) could be changed to use the global color palette instead of hardcoded values.

I'd like to be able to use the matplotlib palette 'dark_background', which makes it impossible to see the black elbow line:

<img width="656" alt="yellowbrick_elbow_black" src="https://user-images.githubusercontent.com/29611875/108923485-c2278180-75ed-11eb-9c6f-90b052c69f43.png">

Thanks!

**Comment by bbengfort** [comment]
Hi @jaymegordo thank you for using yellowbrick and the feature request. We've implemented a fix, please see the PR at #1172 for details; this fix will be available in Yellowbrick v1.3
