### ISSUE TITLE
Learning Curves

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#116]
Implement a `LearningCurveVisualizer` (subclass of  `ModelVisualizer`?) that enables the user to plot learning curves to see how error increases/decreases as more samples are added. There can be an option to show error increase/decrease on a per class basis.

References:
 - http://scikit-learn.org/0.15/auto_examples/plot_learning_curve.html
 - http://www.ultravioletanalytics.com/2014/12/12/kaggle-titanic-competition-part-ix-bias-variance-and-learning-curves/
 - http://alexanderfabisch.github.io/learning-curves-in-scikit-learn.html
 - http://stats.stackexchange.com/questions/220827/how-to-know-if-a-learning-curve-from-svm-model-suffers-from-bias-or-variance

**Comment by bbengfort** [comment]
@balavenkatesan just wanted to make you aware of this issue so you could reference it as you're working on it.

**Comment by jkeung** [comment]
going to follow this implementation
http://scikit-learn.org/stable/auto_examples/model_selection/plot_learning_curve.html

**Comment by bbengfort** [comment]
I'm wrapping this up by generalizing it for both classification and regression and adding to documentation and a new model selection package. See #377
