### ISSUE TITLE
Fix / Replace Travis CI

### ISSUE THREAD

**Issue by ndanielsen** [DistrictDataLabs/yellowbrick#1161]
**Describe the issue**

Looks like Travis CI is no longer functional on this project (and most open source projects). Creating an issue to track the fix.

I put up a work-in-progress issue to replace Travis CI with github actions. I'm happy to complete that if there is any interest in migrating to github actions.

https://github.com/DistrictDataLabs/yellowbrick/pull/1158

@DistrictDataLabs/team-oz-maintainers

**Comment by ndanielsen** [comment]
Main body of work merged in: https://github.com/DistrictDataLabs/yellowbrick/pull/1158

Remained TODOs:

- enabling github actions on this repo
- setting up the slack token access
- setting up codecov
- statuses badges for github actions and codecov
- documentation scan to update any references to coveralls / travis

**Comment by ndanielsen** [comment]
@pdamodaran did you want to pick up the remaining items or should I?

**Comment by pdamodaran** [comment]
@ndanielsen - thanks for offering to take on additional work in relation to Github Actions!  I am new to this so I appreciate the help.  Please see my responses below your TODO list.

> Main body of work merged in: #1158
>     
> A few remaining TODOs come to mind:
> 
> * enabling github actions on this repo
             - I had thought the merge would trigger Github Actions but it didn't so if you can take care of this, it will be helpful.
> * setting up the slack token access
              - this is done
> * setting up codecov
              - this is done
> * statuses badges for github actions and codecov
               - I am curious what this is - and yes would appreciate it if you can take this on as well
> * documentation scan to update any references to coveralls / travis
               - would love the help on this also

**Comment by ndanielsen** [comment]
Just had a moment to look at this now. Seems like you took on the badge item in a PR this morning. 

As for the slack token, I can't see the slack token that was set but it needs to be the entire slack_webhook url - not just the token as it was before. I'll let you fix this as I've been avoiding slack in-general for awhile now. 

If anything else needs to be done, please loop me in via github. 

I'll addresses the minor issue on my pending PR soon.

**Comment by bbengfort** [comment]
@pdamodaran @ndanielsen it looks like we're all in on GitHub actions now; can we close this issue?

**Comment by pdamodaran** [comment]
@bbengfort - yes I will go ahead and close this issue - thanks for merging the PR.
