### ISSUE TITLE
ax param ignored in feature_correlation quick method

### ISSUE THREAD

**Issue by giancds** [DistrictDataLabs/yellowbrick#1163]
**Describe the bug**
When using matplotlib subplots create 2 plots of feature correlations side by side, the ax parameter seems to be ignored  and two images are created.

![image1](https://user-images.githubusercontent.com/3305726/109315893-cc35c400-7829-11eb-8453-de098ae7f375.png)
![image2](https://user-images.githubusercontent.com/3305726/109315930-d3f56880-7829-11eb-9f3f-75b4977dcac4.png)

**To Reproduce**

```python
import numpy as np
from sklearn import datasets
import matplotlib.pyplot as plt
from yellowbrick.target.feature_correlation import feature_correlation

#Load the diabetes dataset
data = datasets.load_iris()
X, y = data['data'], data['target']

features = np.array(data['feature_names'])

_, axes = plt.subplots(ncols=2, figsize=(18, 6))

feature_correlation(X, y, labels=features, method='pearson', ax=axes[0])
feature_correlation(X, y, labels=features, method='mutual_info-classification', ax=axes[1])

plt.tight_layout()
```

**Expected behavior**
The expected behaviour would be the plots side by side in a single image.

**Desktop (please complete the following information):**
 - OS: macOS
 - Python Version: Python 3.7.10 (Google Colab)
 - Yellowbrick Version: 1.3.post1

**Additional context**
I can confirm it happens also locally with `Yellowbrick 1.3.post1` running using command line and using jupyter notebooks

**Comment by bbengfort** [comment]
Hello @giancds thank you for using Yellowbrick and for reporting this bug! @lwgray has come up with a solution and a fix that we should be able to roll out soon; see #1171 for details!

**Comment by lwgray** [comment]
@giancds you will also have to set show parameter in the featurecorrelation quickmethod to False

import numpy as np
from sklearn import datasets
import matplotlib.pyplot as plt
from yellowbrick.target.feature_correlation import feature_correlation

#Load the diabetes dataset
data = datasets.load_iris()
X, y = data['data'], data['target']

features = np.array(data['feature_names'])

_, axes = plt.subplots(ncols=2, figsize=(18, 6))

feature_correlation(X, y, labels=features, method='pearson', ax=axes[0], show=False)
feature_correlation(X, y, labels=features, method='mutual_info-classification', ax=axes[1], show=False)


plt.tight_layout()
