### ISSUE TITLE
AttributeError: 'LogisticRegression' object has no attribute 'classes'

### ISSUE THREAD

**Issue by Albembo** [DistrictDataLabs/yellowbrick#1165]
Hi everyone, that's my first help request, so I'm sorry if I do something wrong; so:

**Description**
I used for evaluate the classification models the classification_report class and it worked until I setted up `imblearn`(I don't think that it change something but, it happen when I set up that), now when i run the program I had the error 

`AttributeError: 'LogisticRegression' object has no attribute 'classes'`

That's the "core" of the code called into question:

```
X_train, X_test, y_train, y_test = train_test_split(features, labels,test_size=0.25,shuffle=True, random_state = 0)
from sklearn.linear_model import LogisticRegression
logisticRegr = LogisticRegression(random_state=0)

from yellowbrick.classifier import ClassificationReport
visualizer = ClassificationReport(logisticRegr)
visualizer.fit(X_train, y_train)  # Fit the visualizer and the model
visualizer.score(X_test, y_test)  # Evaluate the model on the test data
visualizer.show()             # Draw/show the data
```
someone can help me to fix that?
Thank you

**Versions**
scikit-learn 0.24.1
yellowbrick 1.2
python 3.7
Environment Anaconda 1.9.12

@DistrictDataLabs/team-oz-maintainers

**Comment by bbengfort** [comment]
Hi @Albembo thank you for using Yellowbrick and for opening the issue - you did your first help request perfectly! Sorry, it's taken us so long to respond, we've been backed up for the past few weeks. 

I used the following code on Yellowbrick v1.3 and it worked:

```python
from sklearn.model_selection import train_test_split
from yellowbrick.datasets import load_occupancy

features, labels= load_occupancy()

X_train, X_test, y_train, y_test = train_test_split(features, labels,test_size=0.25,shuffle=True, random_state = 0)
from sklearn.linear_model import LogisticRegression
logisticRegr = LogisticRegression(random_state=0)

from yellowbrick.classifier import ClassificationReport
visualizer = ClassificationReport(logisticRegr)
visualizer.fit(X_train, y_train)  # Fit the visualizer and the model
visualizer.score(X_test, y_test)  # Evaluate the model on the test data
visualizer.show(outpath="t.png")             # Draw/show the data
```

![t](https://user-images.githubusercontent.com/745966/113366311-d403ef00-9326-11eb-99ad-10124b6ab72f.png)

Perhaps the fix is as simple as:

```
$ pip install -U yellowbrick
```

If that doesn't solve the problem, let me know and we can dig in deeper!

**Comment by Albembo** [comment]
It works, thank you sooooo much @bbengfort
