### ISSUE TITLE
Argument to remove colorbar in classification plots

### ISSUE THREAD

**Issue by nateGeorge** [DistrictDataLabs/yellowbrick#1166]
**Describe the solution you'd like**
Can we add an argument to remove the colorbar for the classification plots, like sklearn has plot_confusion_matrix() with the colorbar argument? This would be for at least the confusion matrix and classification reports, maybe more.

**Is your feature request related to a problem? Please describe.**
I consider the colorbar chartjunk since we already have the raw counts on the plot.

**Comment by nateGeorge** [comment]
Currently this can be done with a slightly hacky method:

```python
from yellowbrick.classifier import ClassificationReport

f, ax = plt.subplots(1, 1)
viz = ClassificationReport(lr_model,
                           support=True,
                           classes=['no default', 'default'],
                           cmap='Blues')
viz.score(x_test, y_test)
f.delaxes(f.axes[0])
viz.show()
```

**Comment by bbengfort** [comment]
Hi @nateGeorge thank you for using Yellowbrick; we'll certainly take your request under consideration and are more than open to PRs or other contributions. I would have suggested the `delaxes` mechanism in the meantime - thank you for adding it here in case anyone else has a similar question!
