### ISSUE TITLE
Residuals Plot visualization error on Regression dataset

### ISSUE THREAD

**Issue by ukamath** [DistrictDataLabs/yellowbrick#1169]
While running residual plots visualization on insurance claims data, get this error

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-50-fc46cead2c19> in <module>
      2 visualizer = ResidualsPlot(model)
      3 
----> 4 visualizer.fit(X_train, y_train)  # Fit the training data to the visualizer
      5 visualizer.score(X_test, y_test)  # Evaluate the model on the test data
      6 visualizer.show()                 # Finalize and render the figure

~/opt/anaconda3/lib/python3.7/site-packages/yellowbrick/regressor/residuals.py in fit(self, X, y, **kwargs)
    260         # fit the underlying model to the data
    261         super(ResidualsPlot, self).fit(X, y, **kwargs)
--> 262         self.score(X, y, train=True)
    263         return self
    264 

~/opt/anaconda3/lib/python3.7/site-packages/yellowbrick/regressor/residuals.py in score(self, X, y, train, **kwargs)
    296         y_pred = self.predict(X)
    297         residuals = y_pred - y
--> 298         self.draw(y_pred, residuals, train=train)
    299 
    300         return score

~/opt/anaconda3/lib/python3.7/site-packages/yellowbrick/regressor/residuals.py in draw(self, y_pred, residuals, train, **kwargs)
    345         # Add residuals histogram
    346         if self.hist in {True, "frequency"}:
--> 347             self.hax.hist(residuals, bins=50, orientation="horizontal", color=color)
    348         elif self.hist == "density":
    349             self.hax.hist(

~/opt/anaconda3/lib/python3.7/site-packages/matplotlib/__init__.py in inner(ax, data, *args, **kwargs)
   1597     def inner(ax, *args, data=None, **kwargs):
   1598         if data is None:
-> 1599             return func(ax, *map(sanitize_sequence, args), **kwargs)
   1600 
   1601         bound = new_sig.bind(ax, *args, **kwargs)

~/opt/anaconda3/lib/python3.7/site-packages/matplotlib/axes/_axes.py in hist(self, x, bins, range, density, weights, cumulative, bottom, histtype, align, orientation, rwidth, log, color, label, stacked, normed, **kwargs)
   6727                     "color kwarg must have one color per data set. %d data "
   6728                     "sets and %d colors were provided" % (nx, len(color)))
-> 6729                 raise ValueError(error_message)
   6730 
   6731         hist_kwargs = dict()

**To Reproduce**

Skearn - 0.24.1
Yellowbrick - 1.3.post1
Python - 3.7.6

**Dataset**
Insurance Dataset attached

**Code**

claims_data = pd.read_csv('./data/insurance.csv')
claims_data.head(10)

# One hot encoding for region
claims_data = pd.concat((claims_data,pd.get_dummies(claims_data.region, prefix='region')),1)
# One hot encoding for sex
claims_data = pd.concat((claims_data,pd.get_dummies(claims_data.sex, prefix='sex')),1)
# One hot encoding for smoker
claims_data = pd.concat((claims_data,pd.get_dummies(claims_data.smoker, prefix='smoker')),1)
# drop the columns 
claims_data.drop(['region', 'sex','smoker'], axis=1,inplace = True)

X = claims_data[['age', 'bmi', 'children','region_northeast',
       'region_northwest', 'region_southeast', 'region_southwest',
       'sex_female', 'sex_male', 'smoker_no', 'smoker_yes']]

y = claims_data[['charges']]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = \
train_test_split(X, y, test_size=0.2,random_state = 0)
model = LinearRegression()
# Instantiate the linear model and visualizer
visualizer = ResidualsPlot(model)

visualizer.fit(X_train, y_train)  # Fit the training data to the visualizer
visualizer.score(X_test, y_test)  # Evaluate the model on the test data
visualizer.show()                 # Finalize and render the figure

**Comment by ukamath** [comment]
Dataset attached
[insurance.txt](https://github.com/DistrictDataLabs/yellowbrick/files/6230533/insurance.txt)

**Comment by lwgray** [comment]
@ukamath Any progress on this error?
Using your data and python, sklearn, yellowbrick versions.  I was unable to reproduce the error.  See chart below

Is there any other insights you might have that could allow me to further diagnose this issue?

![image](https://user-images.githubusercontent.com/1000117/113316936-1b10c680-92cc-11eb-904e-7ffcdbc74e65.png)
