### ISSUE TITLE
prediction-error plot: getting error at score method

### ISSUE THREAD

**Issue by bgjeroska** [DistrictDataLabs/yellowbrick#1177]
If I set 'bestfit = True' I am getting the following error:

![Screenshot 2021-04-27 at 10 17 28](https://user-images.githubusercontent.com/83243412/116209473-3d1e2d00-a742-11eb-9f89-4b5a578c9519.png)

And if I set 'bestfit = False' it works. Do you maybe know what causes this problem?

![Screenshot 2021-04-27 at 10 23 52](https://user-images.githubusercontent.com/83243412/116209955-b3229400-a742-11eb-9add-0f00e5a5a540.png)

**Comment by lwgray** [comment]
@bgjeroska Thank you for using Yellowbrick.  I attempted to replicate your error but wasn't able to.  Which versions of yellowbrick and python are you using.  What OS are you using?  

I would interested to know the data type for your `Y_test` variable.

**Comment by bgjeroska** [comment]
I am using python 3.8.8 and Yellowbrick 1.3 under Mac OS.

Here is the part with the data that gives me an error.

`X_tr = pd.read_csv('X_train.csv')`
`X_te = pd.read_csv('X_test.csv')`
`Y_tr = pd.read_csv('Y_train.csv')`
`Y_te = pd.read_csv('Y_test.csv')`

`lm1 = LinearRegression()`
`lm1.fit(X_tr, Y_tr)`

`vis_pred = PredictionError(lm1)`

`vis_pred.score(X_te, Y_te.iloc[:,0])  # Evaluate the model on the test data`
`vis_pred.show()`


[X_test.csv](https://github.com/DistrictDataLabs/yellowbrick/files/6397383/X_test.csv)
[X_train.csv](https://github.com/DistrictDataLabs/yellowbrick/files/6397384/X_train.csv)
[Y_test.csv](https://github.com/DistrictDataLabs/yellowbrick/files/6397385/Y_test.csv)
[Y_train.csv](https://github.com/DistrictDataLabs/yellowbrick/files/6397386/Y_train.csv)

**Comment by lwgray** [comment]
@bgjeroska I think I found your problem.  Both y_train and y_test have to be pd.Series.  I used the DataFrame squeeze method to convert them to pd.Series

```python
X_tr = pd.read_csv('X_train.csv')
X_te = pd.read_csv('X_test.csv')
Y_tr = pd.read_csv('Y_train.csv')
Y_te = pd.read_csv('Y_test.csv')

Y_te_squeeze = Y_te.squeeze()
Y_tr_squeeze = Y_tr.squeeze()

lm1 = LinearRegression()
lm1.fit(X_tr, Y_tr_squeeze)

vis_pred = PredictionError(lm1, bestfit=True)

vis_pred.score(X_te, Y_te_squeeze) # Evaluate the model on the test data
vis_pred.show();
```

![image](https://user-images.githubusercontent.com/1000117/116574320-d5dfb480-a8ca-11eb-8e42-82fe301af067.png)

**Comment by bgjeroska** [comment]
It works now. Thank you very much!
