### ISSUE TITLE
please specify the same number of colors as labels!

### ISSUE THREAD

**Issue by turovapolina** [DistrictDataLabs/yellowbrick#1179]
**Describe the bug**
Dear Yellowbrick team,

When I am trying to repeat a code from examples for Stacked Feature Importances (https://www.scikit-yb.org/en/latest/api/model_selection/importances.html?highlight=feature_importance#yellowbrick.model_selection.importances.feature_importances) I receive an error when I fit the model that I should specify the same number of colors as labels. But I am not providing these arguments and I suppose that don't have any variables which can have any confusing names.

**To Reproduce**
```
# Steps to reproduce the behavior (code snippet):
#split dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,stratify = y)

#Import svm model
from sklearn import svm

#Create a svm Classifier
clf = svm.SVC(kernel='linear',probability=True) # Linear Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

from yellowbrick.model_selection import FeatureImportances
viz = FeatureImportances(clf, stack=True, relative=False)#,labels = features_formatted)
viz.fit(X_test, y_test)
viz.show()
```
After running cells:
```
/Users/polina_turova/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py:209: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  warnings.warn('From version 0.24, get_params will raise an '
---------------------------------------------------------------------------
YellowbrickValueError                     Traceback (most recent call last)
<ipython-input-5-d5e7630146dc> in <module>
      1 from yellowbrick.model_selection import FeatureImportances
      2 viz = FeatureImportances(clf, stack=True, relative=False)#,labels = features_formatted)
----> 3 viz.fit(X_test, y_test)
      4 viz.show()

~/opt/anaconda3/lib/python3.8/site-packages/yellowbrick/model_selection/importances.py in fit(self, X, y, **kwargs)
    230 
    231         # Draw the feature importances
--> 232         self.draw()
    233         return self
    234 

~/opt/anaconda3/lib/python3.8/site-packages/yellowbrick/model_selection/importances.py in draw(self, **kwargs)
    249             colors = resolve_colors(len(self.classes_), colormap=self.colormap)
    250             legend_kws = {"bbox_to_anchor": (1.04, 0.5), "loc": "center left"}
--> 251             bar_stack(
    252                 self.feature_importances_,
    253                 ax=self.ax,

~/opt/anaconda3/lib/python3.8/site-packages/yellowbrick/draw.py in bar_stack(data, ax, labels, ticks, colors, colormap, orientation, legend, legend_kws, **kwargs)
    191     if legend:
    192         legend_kws = legend_kws or {}
--> 193         manual_legend(ax, labels=labels, colors=colors, **legend_kws)
    194     return ax

~/opt/anaconda3/lib/python3.8/site-packages/yellowbrick/draw.py in manual_legend(g, labels, colors, **legend_kwargs)
     82     # Ensure that labels and colors are the same length to prevent odd behavior.
     83     if len(colors) != len(labels):
---> 84         raise YellowbrickValueError(
     85             "please specify the same number of colors as labels!"
     86         )

YellowbrickValueError: please specify the same number of colors as labels!
```
![download](https://user-images.githubusercontent.com/61549119/118780655-f204bf00-b894-11eb-9faf-82e3f84d0a0c.png)
**Dataset**
X and y can be uploaded from this repository: https://github.com/turovapolina/unsupervised-LC-MS-data-treatment
X is a numpy array (69 samples and 83 features)
y is a list of strings with 7 classes 

**Expected behavior**
Same picture as in the example (https://www.scikit-yb.org/en/latest/api/model_selection/importances.html?highlight=feature_importance#yellowbrick.model_selection.importances.feature_importances) with values for all features and all classes 

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Python Version [3.8.3]
 - Yellowbrick Version [3.1.0]

**Comment by pdamodaran** [comment]
@turovapolina  - thank you for using Yellowbrick.  Apologies for the late response.

The issue here is that the SVC model you are using does not produce a `coefs_` array that contains feature importances for all of the classes in your dataset and therefore using `stack=True` will not work here as it requires feature importances for all the classes in the dataset.  Refer to the documentation [here](https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html).

Your options are as follows:
1) use the default option without setting stack=True.
2) you can consider another model such as the [LinearSVC](https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html) that provides a `coefs_` array in the shape of `(n_classes, n_features)` and so using `stack=True` will work.

Thank you very much for bringing this issue to our attention.  We realize the error you were getting was not meaningful so we will update the code to provide a more explicit error in situations like this.

Please let us know if you have any additional questions.

**Comment by turovapolina** [comment]
Dear @pdamodaran ,

Thank you very much for your reply!
I assumed that the reason of my error is that SVC is not supported by Yellowbrick, but I wanted to make it certain. But that's ok and thank you for your suggestion to use LinearSVC - it worked perfectly for me!
Just one more small question: in order to find out for which models I can reveal important features for each class (use stack=True option) I should check their documentation and confirm that they provide a coef_ array in the shape of (n_classes, n_features), is it correct? Or there are some other limitations or approaches.

Best regards,
Polina

**Comment by pdamodaran** [comment]
@turovapolina - that's correct!
