### ISSUE TITLE
User Study: Jason and Bala

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#119]
- [ ] @jkeung completes user study 
- [ ] @balavenkatesan completes user study

http://www.scikit-yb.org/en/latest/evaluation.html

**Comment by balavenkatesan** [comment]
Created by user study and pushed it here [https://github.com/balavenkatesan/yellowbrick/blob/master/examples/balavenkatesan/testing.ipynb].

**Comment by rebeccabilbro** [comment]
@balavenkatesan Excellent! Can you open a pull request?
