### ISSUE TITLE
Grid Search Viz

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#12]
Create a package for visualizing grid search results. How to generalize this?

**Comment by rebeccabilbro** [comment]
This one might be tricky, mainly because grid search takes so long. But here is a rough draft:

```python
def visual_gridsearch(model, X, y):
    C_range = np.logspace(-2, 10, 5)
    gamma_range = np.logspace(-5, 5, 5)
    param_grid = dict(gamma=gamma_range, C=C_range)
    grid = GridSearchCV(SVC(), param_grid=param_grid)
    grid.fit(X, y)

    scores = [x[1] for x in grid.grid_scores_]
    scores = np.array(scores).reshape(len(C_range), len(gamma_range))

    plt.figure(figsize=(8, 6))
    plt.subplots_adjust(left=.2, right=0.95, bottom=0.15, top=0.95)
    plt.imshow(scores, interpolation='nearest', cmap=cmap)
    plt.xlabel('gamma')
    plt.ylabel('C')
    plt.colorbar()
    plt.xticks(np.arange(len(gamma_range)), gamma_range, rotation=45)
    plt.yticks(np.arange(len(C_range)), C_range)
    plt.title(
        "The best parameters are {} with a score of {:0.2f}.".format(
            grid.best_params_, grid.best_score_)
    )
    plt.show()
```

**Comment by TomAugspurger** [comment]
Thoughts on something [like this](http://nbviewer.jupyter.org/github/TomAugspurger/postlearn/blob/master/examples/IPywidgets.ipynb#Grid-Search-Results) for grid search? It's pretty much just a wrapper around seaborn's factorplot, pulling the data off the `GridSearch.grid_scores_`. The implementation is [here](https://github.com/TomAugspurger/postlearn/blob/1d96b8874ab6717e749d99ebaec961b8603966a6/postlearn/reporter.py#L98), from a library I started working on but haven't had a chance to develop any further.

**Comment by bbengfort** [comment]
Actually, that's really helpful thanks! We're having a lot of angst around
whether to add seaborn as a dependency or to implement our own FactorPlot
somehow, but the unpack_grid_scores function is going to be really helpful!

**Comment by bbengfort** [comment]
Completed in #261
