### ISSUE TITLE
User Study: Matt and Nick

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#120]
- [ ] @mattandahalfew user study 
- [ ] @nickdoesdata user study

http://www.scikit-yb.org/en/latest/evaluation.html

**Comment by NickDoesData** [comment]
Nick user test complete.

**Comment by rebeccabilbro** [comment]
@NickDoesData Great! Can you submit a pull request with your testing.ipynb file inside `yellowbrick/examples/NickDoesData/`?
