### ISSUE TITLE
Argument to PredictionError is overwritten

### ISSUE THREAD

**Issue by aramesh7** [DistrictDataLabs/yellowbrick#1209]
**Describe the bug**
Argument `is_fitted` is overwritten when Instantiating a `PredictionError` or  `ResidualsPlot`.

**To Reproduce**

```python
from yellowbrick.regressor import PredictionError
from sklearn.linear_models import Lasso

visualizer = PredictionError(Lasso(), "test title", is_fitted=True)
print(visualizer.is_fitted)
```

**Expected behavior**
When `is_fitted` is passed in, I expect it to not be overwritten in the __init__ calls

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python Version 3.8.10
 - Yellowbrick Version :  1.3.post1

**Comment by bbengfort** [comment]
@aramesh7 it does appear that `is_fitted` is defaulting to `auto` but I'm not sure why. We'll have to dig into this a bit more.
