### ISSUE TITLE
Requesting a new release that includes PR #1184

### ISSUE THREAD

**Issue by hosungs** [DistrictDataLabs/yellowbrick#1214]
**Describe the issue**

We (Google Colab) need to bump up numpy to 1.21.5 (to bump up tensorflow to 2.8.0), which doesn't work with the latest yellowbrick release 1.3, so requesting a new release that include #1184.

@DistrictDataLabs/team-oz-maintainers

**Comment by lwgray** [comment]
@hosungs We'll push the next release this weekend or early next week

**Comment by bbengfort** [comment]
@hosungs -- @lwgray released Yellowbrick v1.4 today that contains the release!

**Comment by hosungs** [comment]
Thank you very much for your new release and letting us know! I just started the process of updating our Colab runtime container image to add back yellowbrick, and it'll be available on Colab in a few days. Thanks again!
