### ISSUE TITLE
Feature Visualizer - Jason and Bala

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#122]
- Look through web, blog posts, etc. and find an example of someone using a visualization to understand/augment the model selection and/or evaluation process
 - Show how the visualization is created and sketch out how it would work with our API. 
 - In a fork of the repo, implement and demonstrate with one of our data sets.

**Comment by jkeung** [comment]
Let's try to visualize this DBSCAN clustering from sklearn
http://scikit-learn.org/stable/auto_examples/cluster/plot_dbscan.html#sphx-glr-auto-examples-cluster-plot-dbscan-py

**Comment by jkeung** [comment]
Our user story comes from the example inspired above. A user wants to perform DBSCAN clustering algorithm, but is not sure what to set the parameters to be. The parameters that are used in DBSCAN consist of eps and min_samples. Based on these parameters, the algorithm will automatically obtain the number of clusters. 

A Yellowbrick `ClusterVisualizer` will be created to implement a simple scatterplot with the data points labelled according to their cluster. This would be able to be reused by multiple clustering algorithms such as DBSCAN, KMeans, Agglomerative, Hierarchical, etc. 

An additional DBSCAN specific report would be a report that will provide heat maps of the metrics that can be obtained from DBSCAN clustering (ie. # clusters, homogeneity, completeness, V-measure, etc.) The user will be able to pass in an array of which metrics they would like to be outputted from YellowBrick.

**Comment by bbengfort** [comment]
@jkeung @balavenkatesan bump - what's the status of this issue?

**Comment by balavenkatesan** [comment]
@bbengfort ..  @jkeung was taking the lead on this and I dont know if he has made any progress. I believe he is on vacation and I dont have his date of return. Based on our assignments, I will be working with @ndanielsen for this sprint.
