### ISSUE TITLE
User Study: Josh and Judy

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#123]
- [ ] @joshww43 user study 
- [ ] @jsya user study

http://www.scikit-yb.org/en/latest/evaluation.html

**Comment by joshww43** [comment]
Begin initial scan utilizing base examples just to better understand the package. Hope to retackle the workflow with a new dataset and modelling technique.

**Comment by bbengfort** [comment]
@jsya bump - how're you guys doing on this issue?
