### ISSUE TITLE
Question: How is YB different in SHAP for interpreting Machine Learning Models

### ISSUE THREAD

**Issue by BrandonKMLee** [DistrictDataLabs/yellowbrick#1230]
Sorry for the dumb question, observing the links below, they looked similar, but one claim to use Shapley for generalized weighting of factor significance, whilst YB does not?
Ref: https://www.scikit-yb.org/en/latest/api/model_selection/importances.html
Ref: https://github.com/slundberg/shap

**Comment by bbengfort** [comment]
Yellowbrick attempts to visualize the relative magnitude of the weights of individual features, it does not apply any normalization or computation to those weights - displaying the behavior of the model directly. Shapley attempts to explain the behavior of the model by showing on a per-instance basis what features contributed most to a decision about a classification. If Shapely does use factor significance or generalized weighting, then that would also be a difference to what Yellowbrick does. 

I hope that helps!
