### ISSUE TITLE
Add Dropping Curve Documentation

### ISSUE THREAD

**Issue by lwgray** [DistrictDataLabs/yellowbrick#1235]
Now that we've merged in our new Dropping Curve with https://github.com/DistrictDataLabs/yellowbrick/pull/1206, which does not include any documentation, we'd like to follow up by adding docs with a description of the use cases.

@charlesincharge has already added comments and an article in his original issue https://github.com/DistrictDataLabs/yellowbrick/issues/1204

@DistrictDataLabs/team-oz-maintainers

**Comment by wagner2010** [comment]
I'm working on the conda release and a few other promised deliverables but I'm happy to take this on next if someone else will join me!

**Comment by charlesincharge** [comment]
@wagner2010 I can turn my original feature request into some docs but would definitely benefit from your help looking over it!

**Comment by wagner2010** [comment]
That'd be amazing.  Go for making a pr!  Thanks @charlesincharge

**Comment by charlesincharge** [comment]
@wagner2010 I added a pull request: https://github.com/DistrictDataLabs/yellowbrick/pull/1241 . Can you let me know what you think when you have a moment? Thanks!

**Comment by wagner2010** [comment]
I will; awesome job @charlesincharge !  Thanks

**Comment by bbengfort** [comment]
Closed by #1241
