### ISSUE TITLE
Feature Visualizer - Rebecca and Neal

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#125]
- [x] Look through web, blog posts, etc. and find an example of someone using a visualization to understand/augment the model selection and/or evaluation process
 - [x] Show how the visualization is created and sketch out how it would work with our API. 
 - [x] In a fork of the repo, implement and demonstrate with one of our data sets.

**Comment by rebeccabilbro** [comment]
See #139

**Comment by rebeccabilbro** [comment]
Our user story comes from The Python Data Science Handbook example with the confusion matrix heat map visualization ([see In [31] from here](http://nbviewer.jupyter.org/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/05.02-Introducing-Scikit-Learn.ipynb)). 

In this example, the user has used a Scikit-Learn classifier (sklearn.naive_bayes.GaussianNB) to classify the digits dataset, and has determined a high overall `accuracy_score` for the model. However, the user wants to be able to understand where the model performs poorly (e.g. which digits are most often misclassified). 

A Yellowbrick `ConfusionMatrixVisualizer` would implement a heatmap visualization of a sklearn `confusion_matrix` to enable the user to visualize which points are most misclassed, and how.

**Comment by NealHumphrey** [comment]
Closing in favor of #139
