### ISSUE TITLE
DiscriminationThresholds Graph giving different output every run

### ISSUE THREAD

**Issue by representativeend** [DistrictDataLabs/yellowbrick#1250]
**Describe the bug**
Whenever I run the DiscriminationThresholds function and aim to generate a graph I either 1) get what looks like a reasonable threshold plot. 2) end up with a linear nondescriptive graph or 3) Recieve the error 'invalid value encountered in true_divide'.

Here is the code...so I am not doing anything particualrly odd. I have tried adding (random_state  = 10), but still not getting any reproducibility with each run....

```
model = lgb.LGBMClassifier()

from yellowbrick.classifier import DiscriminationThreshold

# Instantiate the classification model and visualizer
visualizer = DiscriminationThreshold(model)

visualizer.fit(X_train, y_train)        # Fit the data to the visualizer
visualizer.show()           # Finalize and render the figure
```
Run 1:
<img width="411" alt="image" src="https://user-images.githubusercontent.com/68786714/169118157-ce099146-cff0-47a8-b899-53dfbc86b97b.png">

Run 2:
<img width="411" alt="image" src="https://user-images.githubusercontent.com/68786714/169118213-33ee20d7-2489-4d29-aeca-1755a34e6a99.png">

Run 3:
<img width="411" alt="image" src="https://user-images.githubusercontent.com/68786714/169118238-68293d24-e3ef-4fc6-8cdd-d3d3ce962b9e.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Python Version 3.9.5 (default, May 18 2021, 12:31:01) 
[Clang 10.0.0 ]
 - Yellowbrick Version 1.4

**Comment by bbengfort** [comment]
@representativeend thank you for using Yellowbrick, we're glad that you've been finding the threshold plot a useful tool! 

Please note that setting the `random_state` on the visualizer will not influence the random state of the underlying classfier; all `random_state` on the visualizer does is manage the shuffle and split of the cross-validation splits, which are stochastic by default. 

If you add `random_state` to both the model and the visualizer, e.g. in the following code do you get a repeatable result?

```pythyon
model = lgb.LGBMClassifier(random_state=42)

from yellowbrick.classifier import DiscriminationThreshold

# Instantiate the classification model and visualizer
visualizer = DiscriminationThreshold(model, random_state=42)

visualizer.fit(X_train, y_train)        # Fit the data to the visualizer
visualizer.show()           # Finalize and render the figure
```

The other thing you can do is fit the model ahead of time, and pass `is_fitted=True` to the visualizer:

```python
model = lgb.LGBMClassifier().fit(X_train, y_train)

from yellowbrick.classifier import DiscriminationThreshold

# Instantiate the classification model and visualizer
visualizer = DiscriminationThreshold(model, is_fitted=True, cv=None)

visualizer.fit()                 # Fit the data to the visualizer
visualizer.show()           # Finalize and render the figure
```

Note, however, that during the CV process, the `estimator` is cloned and it the behavior of `clone` on fitted models is dependent on scikit-learn. 

In the end, it is useful to note that you're dealing with two stochastic processes here:

1. The training and fitting of multiple classifiers with different thresholds 
2. The shuffle and split data during cross-validation for training purposes

Hope that helps, and let us know if you have any other questions!
