### ISSUE TITLE
Feature Visualizer - Ben

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#126]
- Look through web, blog posts, etc. and find an example of someone using a visualization to understand/augment the model selection and/or evaluation process
 - Show how the visualization is created and sketch out how it would work with our API. 
 - In a fork of the repo, implement and demonstrate with one of our data sets.

**Comment by bbengfort** [comment]
So the blog post here is:

[A Complete Tutorial on Ridge and Lasso Regression in Python](https://www.analyticsvidhya.com/blog/2016/01/complete-tutorial-ridge-lasso-regression-python/). 

I've never really seen folks draw out alphas except in the sklearn docs:

- http://scikit-learn.org/stable/auto_examples/linear_model/plot_ridge_path.html
- http://scikit-learn.org/stable/auto_examples/linear_model/plot_ridge_coeffs.html

**Comment by bbengfort** [comment]
See #103 for my implementation.
