### ISSUE TITLE
'KMeans' object has no attribute 'k'

### ISSUE THREAD

**Issue by nipnipj** [DistrictDataLabs/yellowbrick#1266]
When trying to run example:
```
from yellowbrick.cluster import KElbowVisualizer
from sklearn.cluster import KMeans
model = KElbowVisualizer(KMeans(), k=10)
model.fit(X)
```
The following error appears:
```
AttributeError: 'KMeans' object has no attribute 'k'
```

**Comment by nipnipj** [comment]
It didn't work.
```
Python 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from yellowbrick.cluster import KElbowVisualizer

>>> from sklearn.cluster import KMeans
>>> 
>>> from sklearn.datasets import make_blobs
>>> X, y = make_blobs(n_samples=1000, n_features=12, centers=8, random_state=42)
>>> 
>>> model = KElbowVisualizer(KMeans(), k=10)
>>> model.fit(X)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cuysaurus/.local/lib/python3.8/site-packages/sklearn/base.py", line 279, in __repr__
    repr_ = pp.pformat(self)
  File "/usr/lib/python3.8/pprint.py", line 153, in pformat
    self._format(object, sio, 0, 0, {}, 0)
  File "/usr/lib/python3.8/pprint.py", line 170, in _format
    rep = self._repr(object, context, level)
  File "/usr/lib/python3.8/pprint.py", line 404, in _repr
    repr, readable, recursive = self.format(object, context.copy(),
  File "/home/cuysaurus/.local/lib/python3.8/site-packages/sklearn/utils/_pprint.py", line 189, in format
    return _safe_repr(
  File "/home/cuysaurus/.local/lib/python3.8/site-packages/sklearn/utils/_pprint.py", line 440, in _safe_repr
    params = _changed_params(object)
  File "/home/cuysaurus/.local/lib/python3.8/site-packages/sklearn/utils/_pprint.py", line 93, in _changed_params
    params = estimator.get_params(deep=False)
  File "/home/cuysaurus/.local/lib/python3.8/site-packages/yellowbrick/base.py", line 342, in get_params
    params = super(ModelVisualizer, self).get_params(deep=deep)
  File "/home/cuysaurus/.local/lib/python3.8/site-packages/sklearn/base.py", line 211, in get_params
    value = getattr(self, key)
  File "/home/cuysaurus/.local/lib/python3.8/site-packages/yellowbrick/utils/wrapper.py", line 42, in __getattr__
    return getattr(self._wrapped, attr)
AttributeError: 'KMeans' object has no attribute 'k'
```
Same error as before.

**Comment by bbengfort** [comment]
I will still need more information, please provide the version of scikit-learn, matplotlib, yellowbrick, and the operating system you're using. I just ran the code you showed on my machine and it worked; so we'll need to understand what's different about your setup. 

This issue may also be fixed in the latest version of Yellowbrick that's not released. You can try that version out with:

```
$python -m pip install git+https://github.com/DistrictDataLabs/yellowbrick.git@develop
```

**Comment by nipnipj** [comment]
OS: Linux Mint 20.3 x86_64 
```
>>> print(sklearn.__version__)
1.1.1
>>> print(matplotlib.__version__)
3.5.2
>>> print(yellowbrick.__version__)
1.4
```

**Comment by bbengfort** [comment]
@lwgray I believe this issue will be fixed in the next release; did you have any thoughts about when you wanted to do the release? I know there were still some pending PRs you were working on.

**Comment by lwgray** [comment]
@bbengfort I want to do a release after the sklearn pipeline Tests that @pdamodaran is creating are done.

**Comment by shayandavoodii** [comment]
Hi, Can you please check this:  
https://stackoverflow.com/questions/73246595/attributeerror-kmeans-object-has-no-attribute-k

**Comment by bbengfort** [comment]
@shayandavoodii we released the new version of Yellowbrick yesterday; if you `pip install -U yellowbrick` and run Yellowbrick v1.5 I think the problem should be solved.

**Comment by shayandavoodii** [comment]
> @shayandavoodii we released the new version of Yellowbrick yesterday; if you `pip install -U yellowbrick` and run Yellowbrick v1.5 I think the problem should be solved.

Hi,
Since I just use conda venvs, I tried both: `conda update -c conda-forge yellowbrick` and `conda update -c districtdatalabs yellowbrick`. But still, the new update isn't available.

**Comment by bbengfort** [comment]
@shayandavoodii I just double checked, Anaconda Cloud has the yellowbrick version set at v1.5 - https://anaconda.org/DistrictDataLabs/yellowbrick; what version of Python and conda are you using?

**Comment by bbengfort** [comment]
@DistrictDataLabs/team-oz does anyone use `conda` with Yellowbrick on a day-to-day basis who might be able to help @shayandavoodii?

**Comment by nipnipj** [comment]
This example worked for me now:
```
from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs
from yellowbrick.cluster import KElbowVisualizer

X, y = make_blobs(n_samples=1000, n_features=12, centers=8, random_state=42)

model = KMeans()
visualizer = KElbowVisualizer(model, k=(4,12))

visualizer.fit(X)
visualizer.show()
```

**Comment by shayandavoodii** [comment]
> @shayandavoodii I just double checked, Anaconda Cloud has the yellowbrick version set at v1.5 - https://anaconda.org/DistrictDataLabs/yellowbrick; what version of Python and conda are you using?

Hi,
Yes, It's now possible to update `yellowbrick` to `1.5` using `conda update -c conda-forge yellowbrick`. I'm using Python `v3.10.5` and Conda `v4.13.0`. 

<details>
<summary>Using this code</summary>

```python
import numpy as np
from sklearn.cluster import KMeans
from yellowbrick.cluster import KElbowVisualizer

data = np.array([[146162.56679954],[137227.54181954],[126450.29169228],[119435.56512675],[114988.18682806],[111546.74599395],[111521.9739634 ],[110335.78734103],[105098.20650161],[ 99178.48409528],[ 93982.20860075],[ 91453.21097512],[ 94160.32926255],[102299.29173218],[114540.38664748],[122133.18759654],[121756.94400854],[118709.47518003],[119216.20443483],[122172.5736574 ],[122433.8120907 ],[120599.22092939],[118789.73304299],[119107.28063106],[123920.58809778],[128772.96569855],[131502.10371984],[129525.67885428],[123411.68604418],[120263.05106831],[114844.47942828],[108214.07115472],[101822.69619871],[ 94871.33385049],[ 91251.9375137 ],[ 90058.80745747],[ 93606.20700239],[101044.76675943],[109125.2713446 ],[112272.386321  ],[104429.87179175],[ 90827.50408907],[ 80805.43033707],[ 76165.48417937],[ 75002.04576279],[ 75428.52404817],[ 77444.72355588],[ 80389.43621805],[ 83401.15424418],[ 87638.20462011]])


visualizer = KElbowVisualizer(KMeans(), k=11, metric='silhouette', timings= True)
visualizer.fit(data)
```

</details>
The result is:

![image](https://user-images.githubusercontent.com/52105833/186087795-c05e6f3f-f4d1-403a-b029-8575ca59bd00.png)

But the point is I didn't write `visualizer.show()` in my code. So why is that displaying the plot? It is important to note that this happened in JupyterNotebook. But in the Python REPL, it doesn't render the plot unless I add `visualizer.show()`.

**Comment by bbengfort** [comment]
@nipnipj @shayandavoodii glad to hear the v1.5 update fixed things!

@shayandavoodii Jupyter notebooks will automatically render figures that were created in the cell above; that's why both the estimator description figure and the partial K-Elbow figure are visible. Some advice on how to prevent this can be found [in this StackOverflow post](https://stackoverflow.com/questions/18717877/prevent-plot-from-showing-in-jupyter-notebook). Note that without the call to `show` the Yellowbrick figure doesn't have a title, axes names, legend etc. If you want to render these without calling `show` you can call `finalize` instead.

**Comment by shayandavoodii** [comment]
> @nipnipj @shayandavoodii glad to hear the v1.5 update fixed things!
> 
> @shayandavoodii Jupyter notebooks will automatically render figures that were created in the cell above; that's why both the estimator description figure and the partial K-Elbow figure are visible. Some advice on how to prevent this can be found [in this StackOverflow post](https://stackoverflow.com/questions/18717877/prevent-plot-from-showing-in-jupyter-notebook). Note that without the call to `show` the Yellowbrick figure doesn't have a title, axes names, legend etc. If you want to render these without calling `show` you can call `finalize` instead.

Thanks. Yes, I was aware of them. Actually, I don't need the plot. Thanks.
