### ISSUE TITLE
Feature Visualizer - Matt & Nick

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#127]
@mattandahalfew @nickdoesdata

- Look through web, blog posts, etc. and find an example of someone using a visualization to understand/augment the model selection and/or evaluation process
 - Show how the visualization is created and sketch out how it would work with our API. 
 - In a fork of the repo, implement and demonstrate with one of our data sets.

**Comment by bbengfort** [comment]
@mattandahalfew @NickDoesData bump - this issue is resolved, right? can we close it?

**Comment by mattandahalfew** [comment]
I've already completed this issue, but will defer to Nick to close it
