### ISSUE TITLE
More params to the plot functions

### ISSUE THREAD

**Issue by Daniel-Trung-Nguyen** [DistrictDataLabs/yellowbrick#1278]
Hi,
I am trying to customize this metrics report plot, but found it hard to customize the Prediction error plot.
Perhaps, a function to plot both train and test data on a 1:1 graph would be nice.
Also, it should be good if we can change to titles or update the legends as well.
Thanks,
Daniel

![image](https://user-images.githubusercontent.com/22897462/185618187-b1ce1b20-78de-4926-b118-bef9a0cd4700.png)

**Comment by lwgray** [comment]
Hi @Daniel-Trung-Nguyen thank you so much for using yellowbrick.

We use matplotlib for plotting so every element should be customizable including Titles and Legends.  

In Matplotlib, you can use the object oriented interface to alter the elements.  The Figure object is the top level container for all the other elements that make up the graphic image. These “other” elements are called Artists.

I am not sure what you mean by 1:1  graph to plot train and test.

I hope I've answered your question, if not maybe one of my colleagues can assist.

@bbengfort @pdamodaran

**Comment by Daniel-Trung-Nguyen** [comment]
Thanks for the reply @lwgray!
I didn't realize that you can call model.ax and use matplotlib axis functions.
I did, however, tweak the source code a little bit to get what I want as below.
1:1 I meant the identity line in the modeled vs. predicted plot.
![drone_model_regression_metrics](https://user-images.githubusercontent.com/22897462/186039304-af64e7d2-df17-492b-bb73-d99d32f585b6.png)

**Comment by Daniel-Trung-Nguyen** [comment]
Thanks for the reply @lwgray!
I didn't realize that you can call model.ax and use matplotlib axis functions.
I did, however, tweak the source code a little bit to get what I want
![drone_model_regression_metrics](https://user-images.githubusercontent.com/22897462/186039304-af64e7d2-df17-492b-bb73-d99d32f585b6.png)
