### ISSUE TITLE
On the generation of RadViz plot

### ISSUE THREAD

**Issue by ivan-marroquin** [DistrictDataLabs/yellowbrick#1287]
I have Python 3.90 and yellowbrick 1.5

When I try to generate a RadViz plot, I get the following error message:

/home/ivan/python_3.9.0/lib/python3.9/site-packages/yellowbrick/features/radviz.py:134: RuntimeWarning: invalid value encountered in divide
  return (X - a[np.newaxis, :]) / ((b - a)[np.newaxis, :])

So, what should I look in the input data that raises this message?

Thanks for your help,
Ivan

**Comment by rebeccabilbro** [comment]
Hello again @ivan-marroquin - is it possible that you have NaN values in your data? That is one possible trigger for this kind of error. Best of luck and thanks again for using Yellowbrick!
