### ISSUE TITLE
[SilhouetteVisualizer] Constructor argument is_fitted is ignored during initialization

### ISSUE THREAD

**Issue by stergion** [DistrictDataLabs/yellowbrick#1290]
**Describe the bug**
Constructor argument `is_fitted` is ignored during initialization.

**To Reproduce**

https://github.com/DistrictDataLabs/yellowbrick/blob/40e0482a6eede02ebbc9ccffcb58cff1953a4ce1/yellowbrick/cluster/silhouette.py#L115-L127

**Expected behavior**
```python
        # Initialize the visualizer bases
        super(SilhouetteVisualizer, self).__init__(estimator, ax=ax, is_fitted=is_fitted, **kwargs)
```

**Comment by bbengfort** [comment]
Thank you so much for opening a PR for this @stergion! Just waiting for the tests to pass and we can merge and close this issue.
