### ISSUE TITLE
Adjusting markersize in `prediction_error`

### ISSUE THREAD

**Issue by LSYS** [DistrictDataLabs/yellowbrick#1298]
Thank you for the fantastic library to visualize diagnostics. How do I adjust markersize in `prediction_error()`?

I am using this as reference
```python
from sklearn.linear_model import Lasso
from sklearn.model_selection import train_test_split

from yellowbrick.datasets import load_concrete
from yellowbrick.regressor import prediction_error

# Load a regression dataset
X, y = load_concrete()

# Create the train and test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Instantiate the linear model and visualizer
model = Lasso()
visualizer = prediction_error(model, X_train, y_train, X_test, y_test)
```
but my sample is larger and so the resulting plot just looks like a cloud. 
![image](https://user-images.githubusercontent.com/10510571/220511398-27d1ffa2-b4c5-48c9-a2d0-4a6c6e05638b.png)

Smaller markers would help with visualization. Is that adjustment possible?

I've tried passing the "s" size kwarg
```python
visualizer = prediction_error(model, X_train, y_train, X_test, y_test, scatter_kwargs={"s": 50})
```
but that did not work.

**Comment by rebeccabilbro** [comment]
Hello @LSYS and thank you for using Yellowbrick! 

This is an excellent question. Full response below, but the tl;dr is that the behavior you're requesting isn't currently possible, though if you are willing to work on this and open a PR, it probably wouldn't be too hard to add support for changing marker size in `PredictionError`.

Ok, the details:

For most YB plots that plot points or scatterplots, the marker size is left to the default of whatever Matplotlib sets the size/shape to. The one exception is [`ValidationCurve`](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/model_selection/validation_curve.py), which allows the user to pass in a `markers` param that gets used [inside the `draw` method](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/model_selection/validation_curve.py#L271-L273) to influence the markers. This is a fairly recent change implemented [by @lwgray ](https://github.com/DistrictDataLabs/yellowbrick/pull/1258), who may have some additional thoughts here. It should be possible to make similar changes to the `PredictionError` constructor to take in a user-provided param that gets invoked inside the [`draw`](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/regressor/prediction_error.py#L203-L205) method.

If you're interested in moving forward with contributing, check out the [contributor docs](https://www.scikit-yb.org/en/latest/contributing/getting_started.html) and let us know; I'd be happy to help coach you through and review your PR.

**Comment by LSYS** [comment]
@rebeccabilbro Thanks so much for the fast and detailed response. When I have time I'll look in a bit more detail at the API design of `yellowbrick` to see if I can contribute. Perhaps learning how `yellowbrick` interfaces with `matplotlib` would also be helpful for my own work. 

Thanks again! Closing this issue (for now).
