### ISSUE TITLE
Feature Visualizer - Nathan and Preema

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#130]
@pdamodaran @ndanielsen

- Look through web, blog posts, etc. and find an example of someone using a visualization to understand/augment the model selection and/or evaluation process
 - Show how the visualization is created and sketch out how it would work with our API. 
 - In a fork of the repo, implement and demonstrate with one of our data sets.

**Comment by pdamodaran** [comment]
The visualizer is under /examples/pdamodaran/feature_visualizer.ipynb
