### ISSUE TITLE
No figure output of the show method and produce a lot of findfont: Generic family 'sans-serif' not found warnings

### ISSUE THREAD

**Issue by bingyao** [DistrictDataLabs/yellowbrick#1302]
**Describe the bug**
I was just following the offical docs (https://www.scikit-yb.org/en/latest/quickstart.html#walkthrough) in jupyter lab environment.

**To Reproduce**

In the first example, data loading was fine,

```python
import pandas as pd
from yellowbrick.datasets import load_bikeshare
from yellowbrick.features import Rank2D

X, y = load_bikeshare()
```

but when I execute `visualizer.fit_transform(X)` in a cell, it immediately produce a new matrix dataframe and following a figure.

```python
visualizer = Rank2D(algorithm="pearson")
visualizer.fit_transform(X)
```

What's more, there are lot of warning messages:

```
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial, Liberation Sans, Bitstream Vera Sans, sans-serif
```

Then when I execute in a new cell trying to ploting the figure again:

```python
visualizer.show()
```

the output is only showing a string form of a Axes object, instead of rendering a figure:

```python
<Axes: title={'center': 'Pearson Ranking of 12 Features'}>
```

My question are:
1. I am using a Linux server **where I have no sudo privilege**. So in this case, how can I properly fix the `findfont` warnings?
2. How can I **suppress** the figure output of `visualizer.fit_transform` method and give the figure rendering control back to the `visualizer.show` method?

Thanks in advance :)

**Basic working environments (also shown in the second screenshot):**
 - OS: Linux
 - Python Version 3.9
 - Yellowbrick Version 1.5

```
$ jupyter --version
Selected Jupyter core packages...
IPython          : 8.12.0
ipykernel        : 6.19.2
ipywidgets       : 8.0.4
jupyter_client   : 7.4.9
jupyter_core     : 5.3.0
jupyter_server   : 1.23.4
jupyterlab       : 3.5.3
nbclient         : 0.5.13
nbconvert        : 6.4.4
nbformat         : 5.7.0
notebook         : 6.5.3
qtconsole        : 5.4.0
traitlets        : 5.7.1
```

**Additional context (screenshots)**

First:

![20230406195212](https://user-images.githubusercontent.com/2830900/230376357-28483a3e-4362-4442-962f-f02ece60801d.png)

-----

Second:

![20230406195933](https://user-images.githubusercontent.com/2830900/230376377-3b0ee27e-551e-4c17-a638-3a21b1b53bcb.png)

**Comment by bingyao** [comment]
It seems that many methods will produce the `findfont` warning messages:

```
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial, Liberation Sans, Bitstream Vera Sans, sans-serif
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial, Liberation Sans, Bitstream Vera Sans, sans-serif
...
```

and I am not sure why the instantiation of a `ResidualsPlot` visualizer also produce and rendering an empty figure (showing in the screenshot):

```python
visualizer = ResidualsPlot(LinearRegression())
```

![image](https://user-images.githubusercontent.com/2830900/230379735-f57f0800-c543-4bb1-9bda-eeb42d706945.png)

**Comment by pdamodaran** [comment]
Hi @bingyao - thank you for using yellowbrick!  It appears that the issue you are experiencing has to do with `matplotlib` rather than yellowbrick and is typically experienced by users who are on a Linux OS.  Here is a stackoverflow link that outlines potential solutions for you to try out: https://stackoverflow.com/questions/42097053/matplotlib-cannot-find-basic-fonts
