### ISSUE TITLE
Conda install fails

### ISSUE THREAD

**Issue by mlplace** [DistrictDataLabs/yellowbrick#1316]
It appears that districtdatalabs  is unreachable when appempting to install via conda

conda install -c districtdatalabs yellowbrick 

requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://conda.anaconda.org/districtdatalabs/linux-64/current_repodata.json

conda config --show channels
channels:
  - districtdatalabs
  - defaults
  - conda-forge
  - bioconda

**Comment by lwgray** [comment]
Here are two options to resolve the issue:

**Install Yellowbrick from the conda-forge channel:**

Yellowbrick is available on the conda-forge channel, which is a community-driven repository of Conda packages.

`conda install -c conda-forge yellowbrick`


**Alternatively, install Yellowbrick using pip:**

If you prefer or if the Conda installation doesn't work, you can install Yellowbrick using pip.

`pip install yellowbrick`

**NOTE:**  Make sure that pip installs the package into the correct Conda environment by activating the environment before running the command.
