### ISSUE TITLE
DiscriminationThreshold() for catboost

### ISSUE THREAD

**Issue by FeFortti** [DistrictDataLabs/yellowbrick#1317]
```python
visualizer = DiscriminationThreshold(estimator, is_fitted=True, exclude="queue_rate", random_state=42)
visualizer.fit(X_val, y_val)
visualizer.show()
```

When I use the above code with estimators such as random forest, xgboost and lightgbm, it works perfectly.

However, when I try to use the same code for the catboost estimator, the following error appears:

```python
YellowbrickTypeError: Cannot detect the model name for non estimator: '<class 'catboost.core.CatBoostClassifier'>'
```

**Comment by bbengfort** [comment]
@FeFortti I'm glad to hear that Yellowbrick is working for you so far! 

Yellowbrick core specifically targets scikit-learn models; however, we do have a contrib module that wraps third-party estimators like the `CatBoostClassifier`:

https://www.scikit-yb.org/en/latest/api/contrib/wrapper.html

As you can see from the "Tested Libraries" section, the `CatBoostClassifier` should work with the classifier visualizer. 

Hope that helps!

**Comment by FeFortti** [comment]
Hi, @bbengfort 

Thanks for the explanation! I tried, but unfortunately, I was unable to set the parameters needed to use the wrapper.

But that's okay, I understand that I would have to be a more advanced programmer to achieve this.

Anyway, thank you very much for all your attention!

**Comment by bbengfort** [comment]
@FeFortti I'm sorry to hear that it didn't work for you; but thanks for trying it out!
