### ISSUE TITLE
Feature Visualizer - Morgan & Tuuli

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#132]
@morganmendis @tuulihill 

- Look through web, blog posts, etc. and find an example of someone using a visualization to understand/augment the model selection and/or evaluation process
 - Show how the visualization is created and sketch out how it would work with our API.

**Comment by bbengfort** [comment]
@morganmendis and @tuulihill  -- am closing this so you guys can focus on the user study. If I did this in error let me know and I'll reopen the issue.
