### ISSUE TITLE
Updating the Contributing Documentation

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#140]
As we move towards getting a larger group of core contributors and really expanding the open source rapid development of the Project, I've noticed that we need to update the contributing documentation to reflect several things:

- [x] protect master and develop branches with tests, coverage, and reviewers as per the suggestions by @ndanielsen and @NealHumphrey 
- [x] update documentation to reflect the PR review process. 
- [x] create a CONTRIBUTING.md that is similar in style to [sklearn/CONTRIBUTING.md](https://github.com/scikit-learn/scikit-learn/blob/master/CONTRIBUTING.md) 
- [x] create a "Contributors Page" that is separate from the about page, with more detailed instructions about contributions. Again, see [Scikit-Learn Contributing](http://scikit-learn.org/stable/developers/index.html) for inspiration. 
- [x] add information about issues and milestones 
- [x] add information about roadmaps and communication (maybe create a yellowbrick twitter account)?
- [x] review the contributing process to make sure we have the best support for contributors.

**Comment by bbengfort** [comment]
@rebeccabilbro would you mind reading through the [CONTRIBUTING.md](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/CONTRIBUTING.md) and [Contributing](http://www.scikit-yb.org/en/develop/contributing.html) documentation when you get a break, and just give some thoughts about what needs to be done here relative to the tasks above?

**Comment by rebeccabilbro** [comment]
Will do!

**Comment by rebeccabilbro** [comment]
Created yb twitter account, per above list.

**Comment by rebeccabilbro** [comment]
Ok, I think we're in good shape with these - the main thing I noticed upon review is that the PR process is described as though to someone who has push access to develop (i.e. instructing them to `squash-merge` after code review. Most contributors from the general public will not have push access and we will have to merge in their PRs. I can make another subhead to split out instructions for core contributors and those for other contributors - sound good?

**Comment by bbengfort** [comment]
Once the review and checks have completed, GitHub will allow the pull
requester to squash merge.
-- 
Sent from Gmail Mobile

**Comment by rebeccabilbro** [comment]
Ok, sounds good - marking complete and closing this issue.
