### ISSUE TITLE
ClassificationReport fails with multi-class classifiers

### ISSUE THREAD

**Issue by NealHumphrey** [DistrictDataLabs/yellowbrick#141]
When the ClassificationReport is given a multi-class classifier, the `draw()` method produces an `IndexError` on row 160:

```
C:\Users\humph\Documents\Github\yellowbrick\yellowbrick\classifier.py in draw(self, y, y_pred)
    158         for column in range(len(self.matrix)+1):
    159             for row in range(len(self.classes_)):
--> 160                 self.ax.text(column,row,self.matrix[row][column],va='center',ha='center')
    161 
    162         fig = plt.imshow(self.matrix, interpolation='nearest', cmap=self.cmap, vmin=0, vmax=1)

IndexError: list index out of range
```

It appears that at fault is row 158, which uses `range(len(self.matrix)+1)` instead of `3` (3 is the number of scores for columns of self.matrix, i.e. precision, recall, f1). Changing this to `range(len(self.matrix[0]))` bypasses the IndexError, but still produces an incorrect report - i.e. one that has too many columns, though the data labels and shading are only included in the first 3 columns. The column logic must also be happening elsewhere (maybe in `.imshow`?). 

See Neal's Jupyter Notebook example (pull request coming shortly).

**Comment by bbengfort** [comment]
I experienced a similar issue; here are my notes (thanks for opening the bug report!) 

Attempting to get a classification report for a multi-class classifier:

```
logit_balance = ClassificationReport(logit, classes=set(labels_test))
logit_balance.score(docs_test, labels_test)
logit_balance.poof()
``` 

In the same way as before led to the following exception:

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-27-7b911cc79c37> in <module>()
      1 logit_balance = ClassificationReport(logit, classes=set(labels_test))
----> 2 logit_balance.score(docs_test, labels_test)
      3 logit_balance.poof()

/Users/benjamin/Repos/tmp/yellowbrick/yellowbrick/classifier.py in score(self, X, y, **kwargs)
    133         self.scores = map(lambda s: dict(zip(self.classes_, s)), self.scores[0:3])
    134         self.scores = dict(zip(keys, self.scores))
--> 135         return self.draw(y, y_pred)
    136 
    137     def draw(self, y, y_pred):

/Users/benjamin/Repos/tmp/yellowbrick/yellowbrick/classifier.py in draw(self, y, y_pred)
    158         for column in range(len(self.matrix)+1):
    159             for row in range(len(self.classes_)):
--> 160                 self.ax.text(column,row,self.matrix[row][column],va='center',ha='center')
    161 
    162         fig = plt.imshow(self.matrix, interpolation='nearest', cmap=self.cmap, vmin=0, vmax=1)

IndexError: list index out of range
```

And it displayed the following:

![nocr](https://cloud.githubusercontent.com/assets/745966/23617387/fc4dda22-025a-11e7-911d-8d4e34e743fc.png)


**NOTE**: Same behavior when I tried to fit and score the classifier myself.

**Comment by NealHumphrey** [comment]
Note, that's the same stack dump and mangled visualization that I received.

**Comment by bbengfort** [comment]
@NealHumphrey did you fix this, or am I thinking of something else?

**Comment by NealHumphrey** [comment]
It's partially fixed - it no longer produces errors/stack dump, but the
layout of the grid is a little misshapen with more than 2 classes. I'd
close this and open a different ticket called 'convert ClassificationReport
to mesh grid'

Neal
