### ISSUE TITLE
DispersionPlot

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#147]
Implement a `DispersionPlot` similar to that in [NLTK](http://www.nltk.org/_modules/nltk/draw/dispersion.html) that generates a lexical dispersion plot for a corpus. A lexical dispersion plot will plot occurrences of words in a text, creating a kind of mini-map that can allow a user to compare highlighting across documents.

**Comment by lwgray** [comment]
I will be taking a crack at this...
