### ISSUE TITLE
WordCorrelationPlot

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#148]
Implement a `WordCorrelationPlot` that enables users to visualize the correlations between a word and other words in the corpus, similar to what is available in [ggplot2](http://stackoverflow.com/questions/19549280/plot-highly-correlated-words-against-a-specific-word-of-interest).

**Comment by rebeccabilbro** [comment]
[See also](https://trinkerrstuff.wordpress.com/2014/03/14/qdap-1-3-1-release-demoing-dispersion-plots-sentiment-analysis-easy-hash-lookups-boolean-searches-and-more/)

**Comment by bbengfort** [comment]
@rebeccabilbro sounds like something ICX might be interested in?
