### ISSUE TITLE
Model name detection

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#15]
Separate model name detection function to extract from pipelines.

**Comment by bbengfort** [comment]
we need a utility function to detect the model name for a Scikit-Learn model, this could be as easy as:

```python
def get_model_name(model):
    return model.__class__.__name__ 
```

Except when it is in a pipeline ... 

```python
model = Pipeline([
    (transformer, MyTransformer()), 
    (classifier, MyClassifier()), 
])
```

The above method will return "Pipeline" and instead we want "MyClassifier". 

So basically we need a  function (probably something short and memorable) that can inspect a variety of Scikit-Learn objects, looking for an estimator and returning the correct name. _Successful completion of this task will include tests_.

**Comment by rebeccabilbro** [comment]
@jkeung and @pvomelveny
