### ISSUE TITLE
Refactor classifier.py into module

### ISSUE THREAD

**Issue by NealHumphrey** [DistrictDataLabs/yellowbrick#151]
As classifier has grown, should refactor it into a folder with individual .py files for the classes. Should also look into hoisting functionality to create parent classes as necessary.

**Comment by NealHumphrey** [comment]
Be sure to include adapting the `classes_` property in the ClassificationReport to use the same method as ConfusionMatrix - move it into a property and make sure that classes_ gets assigned whether or not fit is called, as discussed here https://github.com/DistrictDataLabs/yellowbrick/pull/144#issuecomment-284432951

**Comment by NealHumphrey** [comment]
Be sure to edit the `__init__` package to appropriately adapt the import syntax to make sure all the refactored classes can be imported properly, as discussed in #143 . Specifically, @bbengfort noted that he is working on a similar refactor of the regressor module, and proposed approach is (as an example): 
```
from .base import * 
from ..base import Visualizer
```
relative syntax for imports, then also use
```
__all__ = ['ResidualsPlot', 'PredictionError'] 
```

**Comment by bbengfort** [comment]
Also a note (as I'm refactoring the regressor module) -- don't forget to update the documentation autodoc functionality.

**Comment by bbengfort** [comment]
Also make sure you refactor the tests.

**Comment by NealHumphrey** [comment]
Some implementation notes for myself:

- Create method on root class for class_counts. Use this to resolve the bug in the sliced ConfusionMatrix as well as to refactor ClassBalance report to not need a fitted model and not use the precison_recall_fscore_support method (all that is needed is y or y_pred and classes_). 
-Write a bunch of passing tests before starting refactor.

**Comment by NealHumphrey** [comment]
@bbengfort and @rebeccabilbro just FYI, I won't be able to get to this until next sprint (prob around 3/23) but still plan to tackle it. Going to address @bbengfort's comments on the light/dark text function first, should have that ready before Wed meeting.

**Comment by rebeccabilbro** [comment]
@NealHumphrey - this is one of the ones that needs to get done for the 0.4.0 release (i.e., in the next two weeks). If you are planning to check this card out, please let us know by assigning it to yourself; otherwise @bbengfort or I can do it.

**Comment by NealHumphrey** [comment]
Can do!
