### ISSUE TITLE
Create utility function for determining light vs. dark text when given a specific palette color. 

### ISSUE THREAD

**Issue by NealHumphrey** [DistrictDataLabs/yellowbrick#154]
This might go in .util, or .style. Should be callable from any class, so that proper text default choice can be used. 

Proposed approach:
```
def textColor(baseColor, textColors=("black","white")):
    # baseColor: the color of the background, in any valid color specification format
    # textColors: a tuple of (dark, light) text format. 
    if baseColor is dark:
        return textColors[0]
    elif baseColor is light:
        return textcolors[1]
```
This lets the user pass in specific light and dark colors to get back if they don't want white vs. black, but allows them to use it in the text function call directly as it actually returns the color (instead of just returning a boolean or something that must be interpreted). 

This should especially be used in the Heatmap classifier visualizers, e.g. ClassificationReport and ConfusionMatrix

**Comment by bbengfort** [comment]
See #94

**Comment by NealHumphrey** [comment]
Completed with PR #172
