### ISSUE TITLE
Associated Projects

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#156]
Add yellowbrick to associated projects in Scikit-Learn and Scipy

**Comment by rebeccabilbro** [comment]
Related: reach out to Burton DeWilde about [Textacy](http://textacy.readthedocs.io/en/latest/). He has an [open issue](https://github.com/chartbeat-labs/textacy/issues/28) that relates to our TextVisualizer class.

**Comment by rebeccabilbro** [comment]
Submitted PRs for [Sklearn](https://github.com/scikit-learn/scikit-learn/pull/8733) and [SciPy](https://github.com/scipy/scipy.org/pull/206) & also reached out to Burton via GH.
