### ISSUE TITLE
Convert size attribute of the base visualizer to an @property

### ISSUE THREAD

**Issue by NealHumphrey** [DistrictDataLabs/yellowbrick#161]
Currently the `self.size` is set if the user passes it as a keyword, but it's not used anywhere. 

In preparation for allowing resizing, and to allow Visualizers to use logic based on the plot size, create an @property for the size. Property should return the actual size in pixels as set by Matplotlib, or the user provided size if available. 

Relevant SO (but for plt method):
http://stackoverflow.com/questions/29702424/how-to-get-matplotlib-figure-size

**Comment by gary-mayfield** [comment]
Hi, I was looking at contributing and this seemed like a good place to start.

Am I ok to have a go at this?

**Comment by ndanielsen** [comment]
@gary-mayfield thanks for wanting to contribute! please go ahead and take a crack at this.

Please make a pull request with your work-in-progress when you're able so that we can potentially give some feedback or offer suggestions!

Thanks again!

**Comment by bbengfort** [comment]
Size is now a property
