### ISSUE TITLE
Prepare to deploy full alpha test

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#167]
**Goal: 100 user tests by April 19**

Communicate to people via their Github usernames about how to participate in the alpha test, what to expect, etc.  Also need to think about how to manage the large number of participants (deploy in batches? all at once but then send reminders to people?).

**Comment by morganmendis** [comment]
- [ ] Create an email to thanks potential testers and explain how to conduct user tests. (~30 new users, some of the respondents have already completed the user testing)
- [ ] Identify a list  of data science mediums that we can post in to request user testing. (Assess how we can ( Ideally the mediums should attract roughly 70 respondents so we can reach the 100 users goal)
- [ ] Create generic post for various data science mediums to gather more potential users willing to perform the user testing.
- [ ] Agree on plan to send email to users and what type of follow-up if any should we proceed with. (Such as a reminder close the deadline as Rebecca mentioned)
- [ ] Determine plan for analyzing responses and incorporating feedback into tickets. ( Add bug and feature requests as tickets to the board, like we did before on the smaller group of testers?)
