### ISSUE TITLE
Small multiples research/plan for implementation

### ISSUE THREAD

**Issue by ayota** [DistrictDataLabs/yellowbrick#168]
**Objective!** We're trying to come up with a plan for handling small multiples. 🐭 🐌 🐤 

The plan is to look at how things are currently built, and see if there is a way to create small multiples out of score classifiers. 

This has two parts:

💾 **Part 1!** Look at existing visualizers and understand what methods they use and what these methods do. Answer four key questions:
- What does `finalize()` do?
- Map out how the methods work together (e.g., does fit call draw?)
- Map out what each method contributes to the end visualization/does with the data
- Parameters for each method

💪 Tentative division of labor: 
Features: Elaine
Regressor: Lisa
Text: David
Bestfit: Laura (or Elaine if Laura doesn't want to be voluntold)
Classifiers: Neal

🌷 **Part 2!** Come up with some psuedocode/idea for how this small multiples thing might work for score visualizers. We'll go over this at the March 22 sprint and see the feasible path forward.

Plan is to check in on this next Wednesday (3/15) via google hangout.

**Comment by lempira** [comment]
ppt for discussion today
https://drive.google.com/open?id=1MmBpUSoUDew_VcMo-TOKa25CfVcwiiyRNe9PzOgMaz0

**Comment by NealHumphrey** [comment]
also to discuss: https://docs.google.com/spreadsheets/d/1Igh_-YYMCwBuhD0O-XsA0PR5uG39j7ug1TsTFTTTA3g/edit?usp=sharing

**Comment by ayota** [comment]
**Next Steps** 👟 
We came up with two main goals for end of this sprint:
1. Neal with make a first stab at a new MultiPlot class. For now, it will:
- Take one set of data (X,Y needed for fit methods)
- Take one model
- Take a list of *score* visualizers
- Output a column of plots stacked on top of each other

2. David, Lisa, and Elaine will out spreadsheet of methods for score visualizers (and more if time), so we can track what gets called where (plus text visualizers David already looked at.

3. Everyone continue recaps/research into multifacet, R implementations of multiplots, etc. for ideas on next steps/where to go next.

**Comment by NealHumphrey** [comment]
I got a first trial version of the root MultipleVisualizer class working:
![MultiVisualizer Notebook Screenshot](https://cloud.githubusercontent.com/assets/5642566/23981000/def8bfc4-09d9-11e7-8c74-586bab51b429.png)

Any particular small multiples visualizer should be able to inherit from this, as well as a visualizer dashboard. 

I need to do some cleanup still but I pushed the code to the multi-visualizer in my fork of the repo.

**Comment by NealHumphrey** [comment]
I also quickly ran the class flattener tool. Output looks good, but it does not replace `super()` code with the code from the parent method. 

I looked around a bit and there were a few other instances of things like this but none that were super sophisticated. The visual output of this one looks really good, I think it would be worth trying to get it to user super properly and maybe contribute a PR upstream to that repo? What do you all think?

**Comment by ayota** [comment]
@NealHumphrey That sounds good. I can take a stab at it on Sunday afternoon, but afraid I am tied up until then with work/helping my sister with her thesis. I don't want to hold you up, so just do as much as you want and I will come in and help where I can. Definitely going to refactor my top features visualizer to leverage the multiplot at least for next week.

**Comment by NealHumphrey** [comment]
@ndanielsen this is the multivisualizer base class I was telling you about; you can pull this branch from my fork of the repository to see the code itself: https://github.com/NealHumphrey/yellowbrick/tree/multi-visualizer

**Comment by NealHumphrey** [comment]
@ayota any progress? Let me know if you need help!

**Comment by NealHumphrey** [comment]
@ayota FYI I worked on implementing a quick example of extending the MultVisualizer using scatter plots. I ran into an issue with the underlying scatter plot so the visualizer doesn't create the type of graph I want, but it's a place to start for looking at how to do your top features visualizer. Here's the branch:
https://github.com/NealHumphrey/yellowbrick/tree/multi-visualizer-with-scatter

**Comment by ndanielsen** [comment]
Just chatted with Elaine and she is planning on continuing working on this in the next two weeks.

**Comment by bbengfort** [comment]
Fixed in #176
