### ISSUE TITLE
Fix Travis tests

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#17]
broke when trying to install matplotlib/scipy/numpy/sklearn etc.

**Comment by bbengfort** [comment]
@xerebz -- hey thanks for looking at the Travis-CI SciPy thing; it's definitely not easy. My last attempt to get SciPy installed was to add this to the .travis.yml: 

```
virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get install -qq python-numpy python-scipy python-sympy
```

As per this post: 

- [http://stackoverflow.com/questions/17224389/scipy-importerror-on-travis-ci](http://stackoverflow.com/questions/17224389/scipy-importerror-on-travis-ci)

Unfortunately it is still not working. I was thinking about trying this:

- [https://github.com/travis-ci/travis-ci/issues/2890](https://github.com/travis-ci/travis-ci/issues/2890)

Looks like you got a passing build, though - any ideas?

**Comment by bbengfort** [comment]
Basically the problem here is that we can't build SciPy or NumPy using pip on Travis.

**Comment by xerebz** [comment]
We can, though. If you apt-get build-dep python-scipy first.

**Comment by xerebz** [comment]
If you are ok with running on 3.4 instead of 3.5, you dont have to rebuild
scipy with pip. Are you at pycon? We can meet up to talk about it.

**Comment by xerebz** [comment]
https://github.com/DistrictDataLabs/yellowbrick/pull/20
