### ISSUE TITLE
ScatterVisualizer can slice classes

### ISSUE THREAD

**Issue by NealHumphrey** [DistrictDataLabs/yellowbrick#175]
The new ScatterVisualizer in #169 accepts the argument of 'classes'. As a user, I would expect this argument to allow me to plot only a subset of the classes in the data by passing a shorter/altered list of classes. Trying to do this causes an index error. In addition, any difference between the user provided class list and the actual classes in y produces the same index error. 

Bug: should better handle user errors in `classes` to alert them if they've asked for a non-existent class. 

Feature:  Should be able to slice the data, only plotting rows that correspond to the classes I've selected. 

To recreate, add an extra cell to examples/ndanielsen/ScatterVizExample with these lines:
```
single_class_sv = ScatterViz(classes=["Iris-setosa"], features=features)
single_class_sv.fit(X,y)
single_class_sv.poof()
```

**Comment by bbengfort** [comment]
@NealHumphrey -- yeh I have this problem with RadViz and ParallelCoordinates as well.

**Comment by rebeccabilbro** [comment]
Going to archive this one for now since the conversation has gone a bit stale; happy to reopen if someone has bandwidth and interest!
