### ISSUE TITLE
Add Guidance to "Contributing" on code documentation

### ISSUE THREAD

**Issue by ndanielsen** [DistrictDataLabs/yellowbrick#177]
Please include a dummy or starter code example with perfectly documented code that a contributor can copy/ paste and get started that will work nicely.  Also an example of real module that meets the perfect code documentation style.

Perhaps add an empty with the 'perfect' starter example code into examples/

Add this to:
http://www.scikit-yb.org/en/latest/about.html#contributing

**Comment by bbengfort** [comment]
And while we're at it - also add documentation about clicking on "squash and merge" and the pull request process.

**Comment by bbengfort** [comment]
I really like the Scikit-Learn contributor documents:

http://scikit-learn.org/stable/developers/contributing.html

I've done a start at getting our documentation closer to this, but could use y'alls help as well.

**Comment by ndanielsen** [comment]
I'll take a look at this soonish, also recommend that we include a link to this document that you shared before:

http://scikit-learn.org/stable/developers/contributing.html#rolling-your-own-estimator

**Comment by bbengfort** [comment]
@ndanielsen it's already included!
