### ISSUE TITLE
Single feature analysis tools (augmenting Rank1D)

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#18]
Radviz, parallel coordinates, and Rank2D are already implemented. We should expand the feature visualization toolset to include single feature analysis tools:
- [ ] boxplots
- [ ] histograms
- [ ] violinplots

Create a `SingleFeatureVisualizer` class whose `poof` method takes as input the name(s) or position(s) of one of the features. Display the appropriate visualization allowing multiple `poof` calls with different features. Make sure to integrate this with Rank1D.

Open questions: do we need to store the data? Or can we create all visualization and then display on demand, or is there some middle ground? 

Note: similar to parallel coordinates and radviz, these need to be native implementations, emulating other libs (seaborn, pandas) as necessary.

**Comment by rebeccabilbro** [comment]
Also, add in violinplots because they are awesome: https://stanford.edu/~mwaskom/software/seaborn/generated/seaborn.violinplot.html

**Comment by rebeccabilbro** [comment]
Note: for any contributors interested in taking these on, we can break these into three separate issues!

**Comment by ChrisPappalardo** [comment]
Hello.  I'm at Pycon 2018 dev sprints today and will take a stab at this issue.

**Comment by lschumm** [comment]
pycon 2019 here. taking a look at this...

**Comment by rebeccabilbro** [comment]
Covered by [`Rank1D`](https://www.scikit-yb.org/en/develop/api/features/rankd.html#rank-1d) as well as follow-on issues #69 #83  #435
