### ISSUE TITLE
Link Github with Slack for notifications

### ISSUE THREAD

**Issue by balavenkatesan** [DistrictDataLabs/yellowbrick#181]
Configure GitHub app for Slack, to get Slack notifications for the following types of events:

* Commit events
* Pull requests
* Issue events
* Deployment statuses
https://get.slack.help/hc/en-us/articles/232289568-Use-GitHub-with-Slack

**Comment by bbengfort** [comment]
@balavenkatesan done - you should have received an invitation to the yb-github channel. 

@ojedatony1616 -- Slack mentioned we were approaching our integration limit, but doesn't look like we have to upgrade our plan yet.
