### ISSUE TITLE
ROCAUC needs X/Y axis labels

### ISSUE THREAD

**Issue by morganmendis** [DistrictDataLabs/yellowbrick#189]
Add  x / y axis labels to ROCAUC visualization

Identified by neal@nhumphrey.com in their response to the user study.

**Comment by cjmorale** [comment]
@bbengfort Made a pull request to resolve this bug.

**Comment by bbengfort** [comment]
@cjmorale feel free to merge and close this issue.

**Comment by cjmorale** [comment]
@bbengfort You might want to close this issue now that we have it resolved.
