### ISSUE TITLE
Module error - Anaconda

### ISSUE THREAD

**Issue by thedatalass** [DistrictDataLabs/yellowbrick#206]
I'm working in Anaconda and even after I did a 'pip install yellowbrick', I am getting an ImportError 'No module named yellowbrick' message.

![image](https://cloud.githubusercontent.com/assets/11978048/25437707/409af890-2a65-11e7-8eb1-31774bb11782.png)

**Comment by ndanielsen** [comment]
@thedatalass have you install the anaconda version of pip?

`conda install pip`

**Comment by ndanielsen** [comment]
I received this error when install yellowbrick in a conda venv:

Collecting yellowbrick
  Using cached yellowbrick-0.3.3-py2.py3-none-any.whl
Collecting matplotlib>=1.5.1 (from yellowbrick)
  Using cached matplotlib-2.0.0-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting cycler>=0.10.0 (from yellowbrick)
  Using cached cycler-0.10.0-py2.py3-none-any.whl
Collecting numpy>=1.11.0 (from yellowbrick)
  Using cached numpy-1.12.1-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting scipy>=0.17.1 (from yellowbrick)
  Using cached scipy-0.19.0-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting scikit-learn>=0.17.1 (from yellowbrick)
  Using cached scikit-learn-0.18.1.tar.gz
Collecting python-dateutil (from matplotlib>=1.5.1->yellowbrick)
  Using cached python_dateutil-2.6.0-py2.py3-none-any.whl
Collecting pytz (from matplotlib>=1.5.1->yellowbrick)
  Using cached pytz-2017.2-py2.py3-none-any.whl
Collecting six>=1.10 (from matplotlib>=1.5.1->yellowbrick)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting pyparsing!=2.0.0,!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 (from matplotlib>=1.5.1->yellowbrick)
  Using cached pyparsing-2.2.0-py2.py3-none-any.whl
Building wheels for collected packages: scikit-learn
  Running setup.py bdist_wheel for scikit-learn ... error
  Complete output from command /Users/ndanielsen/miniconda3/envs/bunnies/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/ll/c15t_4hj6yb9cvy1hgqm8hp4fdh4q9/T/pip-build-93ki3_e1/scikit-learn/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/ll/c15t_4hj6yb9cvy1hgqm8hp4fdh4q9/T/tmpz7sgn8e5pip-wheel- --python-tag cp36:
  Partial import of sklearn during the build process.
  Traceback (most recent call last):
    File "/private/var/folders/ll/c15t_4hj6yb9cvy1hgqm8hp4fdh4q9/T/pip-build-93ki3_e1/scikit-learn/setup.py", line 169, in get_numpy_status
      import numpy
  ModuleNotFoundError: No module named 'numpy'
  Traceback (most recent call last):
    File "/private/var/folders/ll/c15t_4hj6yb9cvy1hgqm8hp4fdh4q9/T/pip-build-93ki3_e1/scikit-learn/setup.py", line 149, in get_scipy_status
      import scipy
  ModuleNotFoundError: No module named 'scipy'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/ll/c15t_4hj6yb9cvy1hgqm8hp4fdh4q9/T/pip-build-93ki3_e1/scikit-learn/setup.py", line 270, in <module>
      setup_package()
    File "/private/var/folders/ll/c15t_4hj6yb9cvy1hgqm8hp4fdh4q9/T/pip-build-93ki3_e1/scikit-learn/setup.py", line 250, in setup_package
      .format(numpy_req_str, instructions))
  ImportError: Numerical Python (NumPy) is not installed.
  scikit-learn requires NumPy >= 1.6.1.
  Installation instructions are available on the scikit-learn website: http://scikit-learn.org/stable/install.html

**Comment by bbengfort** [comment]
@thedatalass perhaps try: 

    conda install -c districtdatalabs yellowbrick

We created an Anaconda yellowbrick package here: https://anaconda.org/DistrictDataLabs/yellowbrick

@ndanielsen that's odd, I wonder why it didn't gather and install the dependencies for Scikit-Learn? Can you manually install numpy and scipy into your conda venv and see if that fixes it?

**Comment by thedatalass** [comment]
I'm afraid I'm still getting the error message thanks , @thedatalass

**Comment by bbengfort** [comment]
@thedatalass sorry to hear that you're still having trouble. Since this is an `ImportError`, it's a bit tough to diagnose remotely. I've been trying installing yellowbrick in a variety of environments and haven't gotten any package or distribution errors. 

The way forward is to determine where yellowbrick was installed. Please check that the kernel you're using with your Jupyter notebook is connected to the same version of Python that either conda or pip are connected to. For example if you `pip install yellowbrick` and pip is using Python 2.7, then yellowbrick is only available from Python2. You could try `pip3 install yellowbrick` to ensure it's installed in Python3. This is made a bit more complicated when there are multiple Python distributions on your system. [Stackoverflow advice also seems a bit limited](http://stackoverflow.com/questions/38368318/installing-a-pip-package-from-within-a-jupyter-notebook-not-working). 

You can figure out where your packages are installed as follows:

```python
from distutils.sysconfig import get_python_lib
print(get_python_lib())
```

On my computer, if I run python3, I get:

```
/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
```

And if I run python2: 

```
/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
```

Sorry this is so complicated.

**Comment by bbengfort** [comment]
@thedatalass any progress? We're here to help!

**Comment by thedatalass** [comment]
Sorry Mr. Bengfort, I'm afraid I wasn't able to get it installed after
several attempts and won't be able to test.

Thanks,
Laura Kahn

**Comment by rebeccabilbro** [comment]
Hiya @thedatalass! Would you mind supplying a bit more information about your operating system (OS X? Windows? Ubuntu?), the version of Python you're running (```conda -V```), and the error messages you're encountering? I noticed that you're working in a Jupyter notebook. Can you try importing yellowbrick from the command line (terminal) to see what error you get? I'm curious if it's [this same error](https://github.com/DistrictDataLabs/yellowbrick/issues/205). If you could paste in the error you're getting, that would be great. While I'm not sure we'll be able to fix the problem (particularly if it has to do with your computer's OS), but it may help future users who experience similar problems!

**Comment by thedatalass** [comment]
When I type the from distutils.sysconfig import get_python_lib
print(get_python_lib()) into the CMD window, I get the following error message:

'from' is not recognized as an internal or external command, operable program or batch file.

**Comment by thedatalass** [comment]
I'm on a Windows 32-bit OS and have  Python 2.7.6 on a different computer. I got an "Import Error: no module named Yellowbrick" now

**Comment by rebeccabilbro** [comment]
Which version of pip do you have? ```pip --version```

**Comment by thedatalass** [comment]
When I type that command in, I'm getting a 'Name Error: 'pip is not
defined' message

**Comment by bbengfort** [comment]
@thedatalass is Anaconda the only version of Python on your computer? Did you install it with the downloadable installer? It sounds like pip is not on your `%PATH%`

**Comment by benbrock26** [comment]
Is yellowbrick issue resolved yet?  I am having the same issue listed above.

I recently installed yellowbrick on a Anaconda Windows 10-64 bit notebook.

conda install -c districtdatalabs yellowbrick 

"yellowbrick" looks like an awesome tool.  I really want to use this in my future data analysis work.

By the way, I am having the same issue in the linux environment too.

**Comment by benbrock26** [comment]
This is related to the yellowbrick issue.

This is the error that I am receiving:
import yellowbrick as yb
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-10-5766046cd81b> in <module>()
----> 1 import yellowbrick as yb

ModuleNotFoundError: No module named 'yellowbrick'

Below is my configuration

platform:  Windows-10-10.0.17134-SP0
Python 3.6.1 | packaged by conda-forge | (default, May 11 2017, 19:39:41) [MSC v.1900 64 bit (AMD64)]
NumPy 1.12.1
SciPy 0.19.0
Scikit-Learn 0.19.1
pandas 0.20.1
seaborn 0.7.1
matplotlib 2.2.2

**Comment by benbrock26** [comment]
Windows Machine:
conda -V
conda 4.3.23

![image](https://user-images.githubusercontent.com/7131837/40588343-197c8af8-61aa-11e8-8b81-835e0ef7a811.png)

Linux Machine
conda -V
conda 4.5.4

![image](https://user-images.githubusercontent.com/7131837/40588328-e666de8e-61a9-11e8-9182-f7922eb9f69f.png)

**Comment by bbengfort** [comment]
@benbrock26 thanks for pasting the tracebacks in; it looks like in the notebook at least you're in a conda virtualenv called "topic_modeling" - when you install yellowbrick to the virtualenv as follows:

`conda install -n topic_modeling -c districtdatalabs yellowbrick`

Does that resolve the issue?

**Comment by benbrock26** [comment]
By the way, I verified that the yellowbrick package was listed in the list of installed packages on the specific Anaconda environment.   

![image](https://user-images.githubusercontent.com/7131837/40588532-bad45726-61ac-11e8-98dd-05f2ab26014f.png)

**Comment by bbengfort** [comment]
@benbrock26 well that 0 is a little worrisome in the package list; let me try to rebuild the conda package to see if that will fix it; give me a couple of minutes.

**Comment by benbrock26** [comment]
I am using an Anaconda Python 3.6 Windows 10-64 Bit with multiple environments.

To get to the topic_modeling environment on a Windows machine, I type the following:
activate topic_modeling 

I entered the following command that you suggested.
conda install -n topic_modeling -c districtdatalabs yellowbrick

No, it did not resolve the problem.

I really want to get this working.  I would like to use yellowbrick for my data analysis

**Comment by benbrock26** [comment]
Ok, I will wait.  Just let me know when you are ready.

**Comment by bbengfort** [comment]
@benbrock26 ok, I've got new Python 3.6 builds uploaded for linux and windows to anaconda; please try reinstalling - you may have to uninstall yellowbrick first.

**Comment by benbrock26** [comment]
I got the yellowbrick package working on my Anaconda Python 3.6 Linux environment.   (Yeah!!!!)

I am now trying to get the yellowbrick package to work on my Anaconda Python 3.6 Windows 10-64 bit environment. 

I am getting the following HTTPS Connection Error:

![image](https://user-images.githubusercontent.com/7131837/40589870-4f8f91c6-61c3-11e8-85ab-b4f438e2a563.png)

**Comment by benbrock26** [comment]
@bbengfort, Thanks for all of the help!

I reviewed the error above closely.  I was able to manually open the url connection from a firefox browser
- "https://conda.anaconda.org/districtdatalabs/win-64/repodata.json".   

Looking closely at the yellowbrick-07-py36_1.tar.bz2 package information. It does seem ok but I am not sure why I am not able to execute the following command w/o getting errors in the Anaconda Python 3.6 Windows 10-64 bit machine:

command used to install yellowbrick on a Anaconda Python 3.6 Windows 10-64-bit machine
conda install -c districtdatalabs yellowbrick

![yellow-newversioninfo](https://user-images.githubusercontent.com/7131837/40590194-b0fa2480-61c8-11e8-83ba-28aaaa6fb683.GIF)

Most of my work will be done in the Anaconda Python 3.6 Windows 10-64 bit machine environment but I am glad the Anaconda Python 3.6 Linux 64-bit machine is working using the yellowbrick package.

**Comment by benbrock26** [comment]
@bbengfort ,  Thanks for all of the help.

I have verified that yellowbrick works in both Anaconda Python 3.6 Linux and Anaconda Python 3.6 Windows 10-64 bit machine environment.

Go Cav's/Celtic's.

**Comment by rebeccabilbro** [comment]
Thank you so much @benbrock26 for letting us know about this and awesome work @bbengfort for getting it resolved so quickly! 

@thedatalass - would be curious to hear if you have any luck with the Yellowbrick v0.7 conda package!

**Comment by benbrock26** [comment]
@thedatalass , @rebeccabilbro , @bbengfort 

I will keep you abreast of the data mining, data analysis work that I plan to do with Yellowbrick v0.7 conda package.   Does the Yellowbrick v0.7 support Anaconda Python 2.7 Windows 10-64 and Anaconda Python 2.7 Linux environments?  Graphlab Create, Turi, or Dato supports only Python 2.7.   That is, why I would like to continue working with Python 2.7.

I plan to do a lot of work with NLP text analyst datasets.  I want to use Yellowbrick v0.7 to help me analyze these type of datasets.  From the Yellowbrick v0.7 online documentation, I saw that the Yellowbrick tool support text analytics (http://www.scikit-yb.org/en/latest/api/text/index.html).    A lot of companies are now using gensim, TfidfVectorizer, CountVectorizer, Latent Dirichlet Allocation, spaCy, word2vec, and other sciki-learn machine learning libraries.

Do you have any more documentation on NLP and Yellowbrick support?

I will stay in contact.

Yellowbrick is an awesome tool!

**Comment by benbrock26** [comment]
Hi,
  Can I help contribute to Yellowbrick?  I would love to help out.


Have a great day,


Ben

**Comment by pdamodaran** [comment]
@benbrock26 - you most certainly can!  We have several open issues that you can take on and help us resolve.  You can also suggest or come up with enhancements to our current visualizers.  We could also use help with our documentation.  Thank you for your support!

**Comment by benbrock26** [comment]
Does the Yellowbrick v0.7 support Anaconda Python 2.7 Windows 10-64 and Anaconda Python 2.7 Linux environments? Graphlab Create, Turi, or Dato supports only Python 2.7. That is, why I would like to continue working with Python 2.7.

**Comment by benbrock26** [comment]
@bbengfort
Can you update the yellowbrick conda install to properly install yellowbrick via Python 2.7 on both the Windows 10-64 bit and Linux 64 environments?

**Comment by bbengfort** [comment]
@benbrock26 are you still getting the import error? The py27 packages for both Windows and Linux have been uploaded to Anacondas and they contain the full package: 

<img width="985" alt="screenshot 2018-05-29 15 43 28" src="https://user-images.githubusercontent.com/745966/40681413-0c407b7a-6357-11e8-8595-3b041db752c3.png">

**Comment by benbrock26** [comment]
It works now.  I finally had a chance to install it on my Anaconda Python
2.7 Windows 1--64 bit notebook.


On Tue, May 29, 2018 at 3:44 PM, Benjamin Bengfort <notifications@github.com

**Comment by bbengfort** [comment]
Glad to hear it!

**Comment by benbrock26** [comment]
How can I communicate with the District Data Labs team silently?  I want to
join the team.

**Comment by benbrock26** [comment]
How can I communicate with the District Data Labs team silently?  I want
to join the team.

**Comment by rebeccabilbro** [comment]
Hey there @benbrock26 - mind moving this conversation to [our Google forum](https://groups.google.com/forum/#!topic/yellowbrick/7ImcUdmTLQ8)? Don't want it to get lost in a closed issue!

**Comment by ColPlunkett** [comment]
I am getting this same error. I literally have tried every differing form of pip install and upgrade to anaconda and access this module. 

![image](https://user-images.githubusercontent.com/40547979/50046502-0613b900-006a-11e9-8020-d34daa339206.png)

**Comment by ColPlunkett** [comment]
In addition, when I try to update anaconda, it goes through this long process before failing.

**Comment by lwgray** [comment]
Below are a series of questions, to help me better understand your problem.  I am trying to discern whether this is an anaconda or yellowbrick issue.

1.  What command are you using to update anaconda? What errors are you getting?
2.  What command are you using to install yellowbrick? are you using pip or conda?
3.  What OS are you working on?

**Comment by ColPlunkett** [comment]
Thanks for the reply @lwgray, I am using Windows 7. Python version 3.6.4. I've used these commands:
pip install yellowbrick
python -m pip install yellowbrick
pip install -U yellowbrick
conda install -c districtdatalabs yellowbrick

and multiple other combinations I am sure. 

I've used I've been getting these 'Access is denied' when I try to update or install through anaconda. 

![image](https://user-images.githubusercontent.com/40547979/50048025-636a3300-0087-11e9-8b09-89727fcaa619.png)

![image](https://user-images.githubusercontent.com/40547979/50048052-1b97db80-0088-11e9-93b2-dc547ee5182c.png)

**Comment by lwgray** [comment]
@benbrock26 I am thinking through these issues however
As for the conda Permission Error... Try right clicking Powershell executable and select run as administrator then try Anaconda again in this environment

**Comment by lwgray** [comment]
@benbrock26 When you typed in the above commands you listed, do you get errors?

**Comment by lwgray** [comment]
@benbrock26 awesome!!!!  Let us know if you run into any other issues.

**Comment by Chris-Larkin** [comment]
Hi @bbengfort, i'm struggling to install yellowbrick.

I'm running python through the Anaconda distribution, and this is my path:

<img width="705" alt="Screen Shot 2020-08-07 at 11 59 50" src="https://user-images.githubusercontent.com/13668520/89639529-a1901800-d8a5-11ea-9bd4-08f895201c7e.png">

This is the output:

<img width="705" alt="Screen Shot 2020-08-07 at 12 07 48" src="https://user-images.githubusercontent.com/13668520/89640052-a99c8780-d8a6-11ea-8224-33236310cb4e.png">

It's been trying to solve the environment for maybe 20 minutes so far. I tried just installing `yellowbrick`, but that returned an error saying that it cannot be found in any of the channels I was looking in (which included `conda forge`)

Any chance you know what might be wrong?

**Comment by bbengfort** [comment]
@Chris-Larkin sorry, I'm not sure what's going on in that error - though it doesn't look yellowbrick specific. It appears there is a lot of discussion [here](https://github.com/conda/conda/issues/9367) about the "failed with initial frozen solve" error, and [here](https://github.com/conda/conda/issues/9004) about the "failed with repodata from current_repodata.json".

The issue could be a dependency issue, so you could try `conda config --set  allow_conda_downgrades true` or you could create a `conda env` and install yellowbrick into the environment with its specific dependencies. Sorry I couldn't be of more help.

**Comment by Chris-Larkin** [comment]
@bbengfort, it was causing me no end of bother and ultimately forced me to confront some suboptimal set-up decisions i took with this computer a few years ago. I've just finished a total uninstall and reinstall of anaconda (and removing virtual environments entirely), and i've managed to install and run yellowbrick with ease. Great program!

**Comment by bbengfort** [comment]
@Chris-Larkin sorry to hear that you had all that trouble; but glad that you managed to get it working. Thanks for using yellowbrick!
