### ISSUE TITLE
Data Loading

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#219]
See: http://scikit-learn.org/stable/datasets/index.html

And #203 and (other issue we don't remember right now)

**Comment by bbengfort** [comment]
changed this issue to move the data downloader from examples to the primary module. That way we can simply put everything in one place similar to how Scikit-Learn provides examples. This will change how we do #223 as well.

**Comment by RaulPL** [comment]
I am working on this issue
