### ISSUE TITLE
Add distortion to kmeans visualizer

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#221]
Add distortion to kmeans visualizer.

**Comment by rebeccabilbro** [comment]
See Nicole's class [tutorial](https://github.com/georgetown-analytics/machine-learning/blob/master/notebook/Clustering%20Flag%20Data.ipynb):

```
K = range(1,10)
meandistortions = []

for k in K:

    elbow = KMeans(n_clusters=k, n_jobs=-1, random_state=1)
    elbow.fit(X)
    meandistortions.append(sum(np.min(euclidean_distances(X, elbow.cluster_centers_), axis=1)) / X.shape[0])

    
plt.plot(K, meandistortions, 'bx-')
plt.xlabel('k')
plt.ylabel('Average distortion')
plt.title('Selecting k with the Elbow Method')
plt.show()
```

**Comment by bbengfort** [comment]
![kmeans_eblow](https://cloud.githubusercontent.com/assets/745966/26057626/737c7ab2-3948-11e7-9a16-764a5d659d7a.png)

Job done, I think it looks pretty good!
