### ISSUE TITLE
Classification Report has an offset with three classes 

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#224]
Rendered a three class classifier using the game dataset (code below), but there is an offset in the grid, creating a white space to the right. This is not related to the double heatmap legend, but that's also a problem (only one rendered in the PDF of this graph). 

![game_nbayes_classification_report](https://cloud.githubusercontent.com/assets/745966/26103364/06570be0-3a07-11e7-9919-85431f256ad8.png)

Did a quick glance at the code in yb, but not sure what's going on. It could easily be something to do with the fact that I'm trying to specify the axes as I'm rendering multiple images at once. 

Here's the code, it's from [here](https://github.com/DistrictDataLabs/PyCon2017/blob/master/poster/gallery.py#L265):

```python
def classification_report(ax):
    from sklearn.naive_bayes import GaussianNB
    from yellowbrick.classifier import ClassificationReport

    features = [
        "a1", "a2", "a3", "a4", "a5", "a6",
        "b1", "b2", "b3", "b4", "b5", "b6",
        "c1", "c2", "c3", "c4", "c5", "c6",
        "d1", "d2", "d3", "d4", "d5", "d6",
        "e1", "e2", "e3", "e4", "e5", "e6",
        "f1", "f2", "f3", "f4", "f5", "f6",
        "g1", "g2", "g3", "g4", "g5", "g6",
    ]

    classes = ['win', 'loss', 'draw']

    splits = load_data('game', cols=features, target='outcome', tts=True)
    X_train, X_test, y_train, y_test = splits

    labels = LabelEncoder()

    estimator = Pipeline([
        ('encoder', MultiColumnEncoder()),
        ('onehot', OneHotEncoder()),
        ('dense', ToDense()),
        ('nbayes', GaussianNB()),
    ])
    visualizer = ClassificationReport(estimator, ax=ax)
    visualizer.fit(X_train, y_train)
    visualizer.score(X_test, y_test)
    return visualizer
```

@NealHumphrey any thoughts, have you seen this before?

**Comment by bbengfort** [comment]
hopefully moving from `imshow` to `colormesh` helps solve this.

**Comment by NealHumphrey** [comment]
Yeah, this is what I mentioned was what was only a partial fix - previously 3 classes would produce a stack dump with errors, so in the refactor I changed it so that it at least showed this graph but w/ bad formatting. I expect that the `mesh` will fix it (or at least side step it).

**Comment by bbengfort** [comment]
Ok; so see #141 -- where this will be worked on with the colormesh solution. 

Also I moved `plt.colorbar()` up to `draw()` so that multiple calls to poof would only create one color bar.
