### ISSUE TITLE
Matplotlib tutorial

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#225]
Add this link to the docs, or better yet, reach out to the author and see if we can incorporate with attribution: http://pbpython.com/effective-matplotlib.html

**Comment by bbengfort** [comment]
@chris1610 - thank you for writing a great tutorial on matplotlib! We have an open source library called yellowbrick that combines Scikit-Learn and matplotlib for machine learning visualization. We were hoping to include a portion of your tutorial on matplotlib (with attribution of course) in our documentation: [http://www.scikit-yb.org](http://www.scikit-yb.org/en/latest/), linking back to your full post on [pbpython.com](http://pbpython.com/effective-matplotlib.html). Would this be interesting to you? I know it would certainly help our developers and contributors.

**Comment by chris1610** [comment]
Thanks for reaching out to me.

Yes, feel free to incorporate content from the article into your documentation.  I appreciate the attribution and link back to the original article.

Yellowbrick looks really cool - I need to take a look at it in more detail!

**Comment by bbengfort** [comment]
@chris1610 thank you so much! We'll add it to our development tutorials section to help folks who want to write visualizers.

**Comment by bbengfort** [comment]
@chris1610 @rebeccabilbro - here is a draft of the incorporation; there is a minor bit of yellowbrick-specific editing and I didn't bring over all images; but I wanted to check in with you both to see if this was what you had in mind before we went too much farther. 

https://github.com/DistrictDataLabs/yellowbrick/blob/develop/docs/matplotlib.rst

**Comment by rebeccabilbro** [comment]
Thanks @chris1610! 
@bbengfort - looks great; just pushed a few gentle edits to `develop`.

**Comment by chris1610** [comment]
The proposed direction looks good to me. I'm glad it was a helpful resource and am excited to see you build on my content.

**Comment by ndanielsen** [comment]
this is great
