### ISSUE TITLE
ROCAUC should be using predict_proba, not score

### ISSUE THREAD

**Issue by tomsvds** [DistrictDataLabs/yellowbrick#227]
Hi.  I was following your examples here:
http://www.scikit-yb.org/en/latest/examples/methods.html#classifier-evaluation
when I saw the ROCAUC example.  The ROC is a triangle, which means you're getting only a single point from the classifier.  This usually means you're not using scores, you're using hard classification labels.  I looked at the code in ./classifier/rocauc.py and indeed in score() you're calling predict() to get hard class labels.  

I suggest you instead call predict_proba() which will give you an array of scores, one for each example.  You then use the scores to produce a ROC curve (a step function, actually).  scikit-learn does it more or less correctly:
http://scikit-learn.org/stable/auto_examples/model_selection/plot_roc.html#sphx-glr-auto-examples-model-selection-plot-roc-py
This will also improve AUC estimates.

I'd fix the code myself but I just began looking at it and don't know your coding conventions yet.

Regards,
-Tom Fawcett

**Comment by bbengfort** [comment]
Hi Tom - thanks for your feedback! Your advice is good, and we'd love to have you contribute. Note #153 where we have plans to do what you mentioned as well as add per-class labels as in the example you cited. We're at PyCon and thought this might be a good thing to leave for newcomers to Yellowbrick at the sprints. If you're here in Portland, join us at the poster session on Sunday morning and at the Sprints Monday and Tuesday, we'd be happy to talk about coding conventions and anything else you need to make your PR.

**Comment by bbengfort** [comment]
@tomsvds ROCAUC now uses `predict_proba` or `decision_function` depending on what the underlying classifier has available. Documentation hasn't been finished yet, but here is an example:

![roc_curves](https://cloud.githubusercontent.com/assets/745966/26506902/17f34e14-421c-11e7-99b3-b608c0519c08.png)
