### ISSUE TITLE
Python 3.6 support

### ISSUE THREAD

**Issue by eyadsibai** [DistrictDataLabs/yellowbrick#228]
many packages now support python 3.6.

**Comment by bbengfort** [comment]
@eyadsibai Yellowbrick supports Python 3.5 and greater; I just ran all the tests on Python 3.6 and they all pass. Are you having any particular compatibility issue with 3.6?

**Comment by eyadsibai** [comment]
when I try to install it through conda it says it cannot be installed as it doesn't support python 3.6 ...

**Comment by bbengfort** [comment]
@jkeung would you package 3.6 with conda, please?

**Comment by bbengfort** [comment]
@eyadsibai ok, we've built a conda package for 3.6 -- should work now.

**Comment by eyadsibai** [comment]
thx
