### ISSUE TITLE
Develop API (yellowbrick/scikit-learn)

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#23]
Yellowbrick needs a standard API that coordinates with and/or corresponds to the Scikit-learn API so that each visualization tool accepts parameters and produces outputs in a systematic way

**Comment by ansate** [comment]
check that it is an estimator object:
import sklearn as sk
isinstance(svc, sk.base.BaseEstimator)

check what kind of estimator:
svc._estimator_type

ex: 'classifier'
