### ISSUE TITLE
Visual Pipeline Documentation

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#231]
Document the visual pipeline and show how it works.

**Comment by rebeccabilbro** [comment]
Pipeline has been implemented and the tests pass. It works by exposing visual steps and filtering out all of the steps that aren't visualizers. It has a `poof` method that accepts as an argument a directory path, and it goes through each visualization in the pipeline, creating an outpath that joins the directory path with the named steps, plus an extension.  If you don't supply a directory path, it will just call `show` (on GTK/Linux, this simultaneously opens up a bunch of windows; on OS X it opens up the windows one after another; no idea about what happens on other operating systems or inside a Jupyter notebook). 

 - [ ] Investigate different combinations of pipelined transformers and see what happens
 - [ ] See what happens inside a notebook

**Comment by rebeccabilbro** [comment]
Bad things. Bad things happen inside a notebook: https://github.com/DistrictDataLabs/yellowbrick/blob/develop/examples/rebeccabilbro/pipelines.ipynb

**Comment by bbengfort** [comment]
And yet, it makes so much sense ... but I wouldn't have guessed. 

Ok, so the pipeline has to create a new axes object for each visualizer. got it.
