### ISSUE TITLE
Update palettes with humor

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#235]
@ndanielsen correctly identified that our palettes aren't humorous enough. It has been recommended that we add some new state-of-the-art colors described in this [recent publication](https://arstechnica.com/information-technology/2017/05/an-ai-invented-a-bunch-of-new-paint-colors-that-are-hilariously-wrong/).

**Comment by ndanielsen** [comment]
Here's my proposed palette:

b:  Esprisse blue, #167192
g: Parp green, #6e7548
r:  Stanky Bean, #c5a2ab 
c: Dad, #00ccff
m: Kold of Tale, #de78ae
y: Stargoon, #ffcc99
k: Dorkwood, #3d3f42
w: Barkying White, #ffffcc

<img width="117" alt="screen shot 2017-05-24 at 8 32 46 pm" src="https://cloud.githubusercontent.com/assets/2944777/26434880/34af6ebe-40c0-11e7-9573-6bcc5ba69923.png">

For names, it should probably be neural or janelle after the author of the blog post. http://lewisandquark.tumblr.com/

**Comment by bbengfort** [comment]
Looks great! Want me to toss it into palettes.py?

**Comment by ndanielsen** [comment]
I'll toss it in later tonight, it's a quick one to do

**Comment by rebeccabilbro** [comment]
Ah, thanks very much @ndanielsen; not sure we would have been able to resolve this one without you. Marking complete and closing this card.
