### ISSUE TITLE
Understanding Yellowbrick and Publishing

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#239]
In order to better understand and utilize yellowbrick we want to explore it from a code analysis standpoint. Suggestions include:

- https://lgtm.com/projects/g/DistrictDataLabs/yellowbrick/
- http://fossa.io/

We can also discuss yellowbrick scientifically:

- http://joss.theoj.org/

**Comment by bbengfort** [comment]
@rebeccabilbro want to work together to submit a paper to the Journal of Open Source Software (a NumFOCUS project) by writing a `paper.md` in the root of our repository? It's only about a 1000 words: https://joss.readthedocs.io/en/latest/submitting.html

**Comment by bbengfort** [comment]
Replaced Landscape with lgtm badge for code quality analysis.

**Comment by rebeccabilbro** [comment]
I'm in @bbengfort; let's open up a specific issue for the JOSS submission. Maybe we can have one person knock out a first draft and the other assemble the bibliography? Then we can swap. I'm happy to take on either task.
