### ISSUE TITLE
DOC: Update bike sharing dataset link in Quick Start

### ISSUE THREAD

**Issue by JimStearns206** [DistrictDataLabs/yellowbrick#240]
Current link [bike sharing data](https://archive.ics.uci.edu/ml/datasets/bike+sharing+dataset) points to UC Irvine data download site, with data before Benjamin's clean-up.

Correct link to [bike sharing data on DDL S3](https://s3.amazonaws.com/ddl-data-lake/yellowbrick/bikeshare.zip).

**Comment by JimStearns206** [comment]
Actually, the DDL S3 file contains the Irvine data column cnvntns (at least that's how UCI would abbreviate conventions :-)
* DDL Preferred: ['month' 'hour' 'weather']
* UCI : ['mnth' 'hr' 'weathersit']

**Comment by bbengfort** [comment]
Updated the data set on S3 and made a note in the walkthrough of where to get the data from; thanks @JimStearns206 !
