### ISSUE TITLE
DOC: Correct data columns in bikeshare WalkThrough

### ISSUE THREAD

**Issue by JimStearns206** [DistrictDataLabs/yellowbrick#242]
Change:
```
data = pd.read_csv('bikeshare.csv')
X = data[[
    "season", "month", "hour", "holiday", "weekday", "workingday",
    "weather", "temp", "atemp", "hum", "windspeed"
]]
```
to:
```
X = data[[
    "season", "month", "hour", "holiday", "weekday", "workingday",
    "weather", "temp", "feelslike", "humidity", "windspeed"
]]
```
I.e:
* Rename "hum" to "humidity"
* Drop "atemp"
* Add "feelslike"

**Comment by bbengfort** [comment]
Thanks @JimStearns206 -- this is really helpful; I've updated the fields, thank you so much for your detailed look at the quickstart!

**Comment by bbengfort** [comment]
http://www.scikit-yb.org/en/develop/quickstart.html#walkthrough

**Comment by JimStearns206** [comment]
Glad to help, @bbengfort! It's a good tutorial. These minor fixes will allow new users to concentrate on learning of the benefits of yb visualization.

**Comment by ndanielsen** [comment]
@JimStearns206 thanks for your feedback! it's very helpful
