### ISSUE TITLE
Add Datasaurus, a version of Anscombe's Quartet

### ISSUE THREAD

**Issue by evelynmitchell** [DistrictDataLabs/yellowbrick#257]
As an addition to Anscombe's Quartet, but starting from a plot that looks like a dinosaur.

https://www.autodeskresearch.com/publications/samestats 
http://www.thefunctionalart.com/2016/08/download-datasaurus-never-trust-summary.html
data: https://www.autodeskresearch.com/sites/default/files/The%20Datasaurus%20Dozen.zip

**Comment by rebeccabilbro** [comment]
@evelynmitchell such a great idea! Want to take a crack at implementing it in Python for Yellowbrick and submitting a pull request?

**Comment by ndanielsen** [comment]
This is amazing. Fun dataset!

**Comment by lwgray** [comment]
@rebeccabilbro   @bbengfort This is my first shot at it?  
![image](https://user-images.githubusercontent.com/1000117/41636069-4a25b238-741a-11e8-999e-04a98f35a6ed.png)

**Comment by ndanielsen** [comment]
Wow

**Comment by bbengfort** [comment]
Nice!
