### ISSUE TITLE
Document example for `ResidualsPlot` uses `PredictionError`

### ISSUE THREAD

**Issue by ianozsvald** [DistrictDataLabs/yellowbrick#262]
The current example for `ResidualsPlot`:
http://www.scikit-yb.org/en/latest/api/yellowbrick.regressor.html
has a copy/paste error. This page shows two examples. The first is for `PredictionError` and it builds `PredictionError(Lasso())`. 
The second incorrect example imports `ResidualsPlot` and creates `PredictionError(Ridge())`, I'm guessing it is meant to use `ResidualsPlot`.

**Comment by ndanielsen** [comment]
@ianozsvald thanks for creating this issue! I'm flagging @bbengfort to take a look as he created the ResidualsPlot visualizer.

**Comment by bbengfort** [comment]
@ianozsvald nice catch - that's a tricky one to notice!
