### ISSUE TITLE
[Feature suggestion] Add `shared_limits=True` option to PredictionError

### ISSUE THREAD

**Issue by ianozsvald** [DistrictDataLabs/yellowbrick#263]
Depending on the quality of a regressor we can get different output ranges to the input range. The `PredictionErrror` scatter plot may then have a slope that isn't 45 degrees, yet the current plot will look as though there's a 45 degree relationship in the data. Here's an example:
![image](https://user-images.githubusercontent.com/273210/27355665-ca189b6c-5603-11e7-8ba5-b7a91b63f739.png)

An option for `shared_limits=True` might be sensible, maybe even default, so that relationships in the data are more apparent.

If I set the axis to share their limits then I get quite a different plot. Here it looks as though my higher measured values (e.g. >130) are consistently under-predicted, in fact my prediction range doesn't look brilliant at all!
![image](https://user-images.githubusercontent.com/273210/27355982-c82230a6-5604-11e7-9f46-55d8b354c848.png)

```
fig, ax = plt.subplots(figsize=(8,6)); 
model.score(X_test, y_test)
ax.set_xlim((70, 170))
ax.set_ylim((70, 170))
model.poof(ax=ax)
```

**Comment by bbengfort** [comment]
@ianozsvald you're absolutely right, and thank you for this outstanding feature request. We'll add it to the backlog and get to it ASAP; though if you're interested in doing a PR for it, we'd be more than happy to accept it! 

We generally have difficulty setting the range of the axes in many of our figures, precisely for the reasons you describe and it's easy to rely on the auto axes. I propose the following to address your feature request, let me know what you think:

- Add an argument to __init__, `shared_limits=True` 
- Set the axes x and y limits in [`PredictionError.finalize()`](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/regressor/residuals.py#L143)
- If `shared_limits` (default), set both the xlim and ylim to `(min(xlim[0], ylim[0]), max(xlim[1], ylim[1]))`, e.g. the lowest valued limit to the highest valued limit on either axis. 

This should ensure that the 45 degree line is, in fact, 45 degrees.

**Comment by ianozsvald** [comment]
@bbengfort that looks lovely!

**Comment by bbengfort** [comment]
I even went so far as to set the aspect ratio to sqaure:

`shared_limits=False`:

![slfalse](https://user-images.githubusercontent.com/745966/27449344-142c5eca-5756-11e7-8a9f-775adc73ebf2.png)

`shared_limits=True`:

![sltrue](https://user-images.githubusercontent.com/745966/27449348-187114e4-5756-11e7-91d8-58952ad61856.png)

Let me know what you think or if I should remove that. 

TODOS:

- [ ] write tests for shared_limits 
- [ ] create visual tests for PE plots 
- [ ] update the documentation 
- [ ] handle the +/- 1 bounds in draw

**Comment by ianozsvald** [comment]
Squared looks sensible. How about (perhaps) adding a 45 degree greyed out line to give a visual reference for the 1:1 prediction ideal vs the black-dashed fitted line (which above is at approx. 50 degrees or so)?

**Comment by bbengfort** [comment]
Your wish, as they say:

![slfalse](https://user-images.githubusercontent.com/745966/27454200-26f2b8cc-5767-11e7-84c0-624b2d80846a.png)

![sltrue](https://user-images.githubusercontent.com/745966/27454204-2904f634-5767-11e7-92b8-04a0b6ef1072.png)

**Comment by ianozsvald** [comment]
I'll enjoy giving this a go, thanks!

**Comment by bbengfort** [comment]
@ianozsvald this changes are now in version 0.5 - so you should be able to update yellowbrick and take advantage of them.

**Comment by ianozsvald** [comment]
@bbengfort just to note - I've had `master` working with a client for a little while, I've been using this change to help explain a regression model - many thanks! https://github.com/ianozsvald/data_science_delivered/blob/master/ml_explain_regression_prediction.ipynb

**Comment by bbengfort** [comment]
Very cool - looks like there are a couple of potential yellowbrick features/visualizers we could add from that notebook! Please let us know if any stand out that you'd be interested in us pursuing.
