### ISSUE TITLE
Column selection for FeatureVisualizers

### ISSUE THREAD

**Issue by pbs929** [DistrictDataLabs/yellowbrick#265]
Raised in #258

Currently the `features` argument to most FeatureVisualizers is taken as a list of labels to be displayed for each feature in the plot. This is useful when X is a numpy array (in which case it does not carry any labels intrinsically) or for overriding the column names when X is a dataframe. 

In some circumstances it may also be useful to allow the user to specify a subset of features from the data to display. One proposed solution for dataframe inputs is to have the `features` argument select a subset of columns from the dataframe by name.  

One problem with this approach is that it leads to an asymmetry in the treatment of numpy arrays and dataframes. In the dataframe case, passing a features argument will potentially reorder the columns, while in the numpy case the same features argument will leave the order the same but just label the columns. So, the same data and same features argument will give you different results depending on which type the data is. 

An alternative approach would be to add an additional argument for column selection while leaving the current functionality of the `features` argument the same.

**Comment by bbengfort** [comment]
I absolutely think that the `features` argument should allow specification of a subset and this is a great feature to add -- one that is currently getting some tracking with your recent code cleanup as well as the new `FeatureImportances` visualizer which ranks features. 

Currently, our thinking is that there should be three input data types:

- Numpy array 
- DataFrame 
- Structured array 

Both the DataFrame and the Structured array do what you suggest. You're right about the Numpy arrays though. My feeling is that users will probably jump through some hoops to deal with this, but I do like your suggestion of an index. I suggest something like this:

```
features = [None, "a", None, "b", "c", None] 
```

Where any `None` values get filtered out and `len(features) == X.shape[1]`.  This could also be a [`np.maarray`](https://docs.scipy.org/doc/numpy/reference/maskedarray.html) (in fact we would convert it to a masked array for implementation). Or we could do something like:

```
features = [("a", 1), ("b", 3), ("c", 4)] 
```

My concern is that if we add an additional column_index things get a bit too complicated, so I'd like to keep this constrained to the type of the `features` (soon to be `labels`) argument. 

Also, see related issue #313 and #319

**Comment by rebeccabilbro** [comment]
Going to archive this one for now since the conversation has gone a bit stale; happy to reopen if someone has bandwidth and interest!
