### ISSUE TITLE
Recursive Feature Elimination

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#268]
This [recursive feature elimination heatmap](http://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.RFE.html#sklearn.feature_selection.RFE) would be a cool feature selection visualization to implement in yb - possibly we can hoist some of #164 into a base class (see #58) for feature importance visualizers?

**Comment by bbengfort** [comment]
I had this idea that we could do a combo plot of [rfecv features scores](http://scikit-learn.org/stable/auto_examples/feature_selection/plot_rfe_with_cross_validation.html#sphx-glr-auto-examples-feature-selection-plot-rfe-with-cross-validation-py) along with the heatmap. I was putting together some code to do this, however when I got to the heatmap I discovered that was specific to the `digits` dataset, the heatmap was just showing the importance of pixels in a 2D array. 

We can/should still use the ranking attribute to show which features are ranked higher relative to the rest, but I'm not sure how to do that. In the meantime, I'll do the RFECV visualizer to get that in our library.
