### ISSUE TITLE
Bubble Maps

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#271]
I think it would be interesting to add geographic features to data sets and be able to visualize them. Probably this is a package on its own and not a Yellowbrick thing; but it would be cool to demo, and perhaps we could generalize it enough for production. 

The idea is to put a background onto a scatter plot with some sort of map representation. The scatter plot points would be geographic positions and the color and size of the point would represent the data, as in:

![Google Bubble Map](https://www.espatial.com/wp-content/uploads/pin-maps-1.png)

It would be fairly simple to do but we would need a manifest of:

- maps 
- positions of relevant geographic items in the maps (countries, states, counties, etc) 
- the ability to map data to those positions 

I can imagine doing a world map and a US states map initially, documenting thoroughly how we composed the map and the mappings. We could then provide these instructions to other users to add other maps for their models.

**Comment by ndanielsen** [comment]
I've been thinking of how to add a geospatial element to yb as well.

**Comment by bbengfort** [comment]
I think that would be cool and it would set us apart.

**Comment by ndanielsen** [comment]
@bbengfort this is totally doable, recommend we add an optional dependency to do this:

https://github.com/jwass/mplleaflet

**Comment by bbengfort** [comment]
This would be super cool, but not a lot of traction around this feature.
