### ISSUE TITLE
Better placement for info labels

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#276]
It would be nice to find a better way to place infolabels (as with [FreqDistVisualizer](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/text/freqdist.py#L283)), so that the text doesn't collide with the data in the plot. Perhaps a mixin?

**Comment by bbengfort** [comment]
Now that we use `loc="best"` in the legend and have a manual legend drawing utility, I believe this issue has been resolved!
