### ISSUE TITLE
Make conda package for 0.5 release

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#277]
We've released version 0.5 to PyPI! Now to make a corresponding conda package...

**Comment by jkeung** [comment]
I have built the conda package and uploaded!

**Comment by bbengfort** [comment]
Updated documentation; we're good to go!

**Comment by ianozsvald** [comment]
Hello. Can we have a conda Python 3.6 version of YellowBrick 0.5 please? I see the Python 2.7 for 0.5, but Python 3.x only exists for 0.4.2: https://anaconda.org/DistrictDataLabs/yellowbrick/files

**Comment by bbengfort** [comment]
@jkeung would you mind doing this?

**Comment by jkeung** [comment]
Yup I got it!

**Comment by bbengfort** [comment]
thanks!

**Comment by jkeung** [comment]
Done!

**Comment by ianozsvald** [comment]
Brilliant - I've updated locally (thanks) and have re-run my Diagnosing Regression Notebook which shows the slightly updated `PredictionError` plot: https://github.com/ianozsvald/data_science_delivered/blob/master/ml_explain_regression_prediction.ipynb
Thanks!
