### ISSUE TITLE
Replace nose with pytest (test runner)

### ISSUE THREAD

**Issue by ndanielsen** [DistrictDataLabs/yellowbrick#291]
As nose has not been maintained for 2.5 years now, we should swap out nose with pytest for the test runner.

**Comment by ndanielsen** [comment]
@bbengfort we need to update the travis-ci too look something like this:

{
  "language": "python",
  "python": "3.6",
  "before_install": [
    "sudo apt-get build-dep python-scipy",
    "pip install scipy",
    *"pip install pytest pytest_cov coverage mock",*
    "pip install coveralls requests"
  ],
  "install": "pip install -r requirements.txt",
  "script": "make test",
  "after_success": "coveralls",
  "group": "stable",
  "dist": "trusty",
  "os": "linux"
}

**Comment by bbengfort** [comment]
This is done and we have flakes and spec - will create another issue for overhauling unittest.
