### ISSUE TITLE
ClassificationReport documentation refers to colormap. Code refers to cmap

### ISSUE THREAD

**Issue by lstmemery** [DistrictDataLabs/yellowbrick#299]
The documentation for the ClassificationReport says to use the `colormap` keyword. This does nothing, `cmap` does, however.

Minimal example:

```
data = load_data('occupancy') 

# Specify the features of interest and the classes of the target 
features = ["temperature", "relative humidity", "light", "C02", "humidity"]
classes = ['unoccupied', 'occupied']

# Extract the numpy arrays from the data frame 
X = data[features].as_matrix()
y = data.occupancy.as_matrix()

# Create the train and test data 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
bayes = GaussianNB()
visualizer = ClassificationReport(bayes, classes=classes, colormap="Blues")

visualizer.fit(X_train, y_train)  # Fit the training data to the visualizer
visualizer.score(X_test, y_test)  # Evaluate the model on the test data 
g = visualizer.poof()             # Draw/show/poof the data
```
vs.

```
data = load_data('occupancy') 

# Specify the features of interest and the classes of the target 
features = ["temperature", "relative humidity", "light", "C02", "humidity"]
classes = ['unoccupied', 'occupied']

# Extract the numpy arrays from the data frame 
X = data[features].as_matrix()
y = data.occupancy.as_matrix()

# Create the train and test data 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
bayes = GaussianNB()
visualizer = ClassificationReport(bayes, classes=classes, cmap="Blues")

visualizer.fit(X_train, y_train)  # Fit the training data to the visualizer
visualizer.score(X_test, y_test)  # Evaluate the model on the test data 
g = visualizer.poof()             # Draw/show/poof the data
```

I love this project and would be willing to submit a pull request to fix this.

**Comment by bbengfort** [comment]
@lstmemery thanks for letting us know, and we're glad you love the project. Let's standardize on `cmap` -- I think it makes as much sense as `colormap` and is used widely in the `matplotlib` literature. We'd love a PR if you could provide it; would you also mind glancing over other visualizers to help us standardize on `cmap`?

**Comment by lstmemery** [comment]
@bbengfort I can do this tomorrow :)

**Comment by lstmemery** [comment]
@bbengfort I'm following the CONTRIBUTING.md, but I can't assign this issue to myself or open a PR without making changes. How should I proceed?

**Comment by bbengfort** [comment]
@lstmemery I've assigned you the issue - I thought we figured out how to get GitHub to let you do that a while back; we must have then broken it again. As for the PR go ahead and open it as soon as you can but you can do a little investigation first -- this isn't a big feature and I don't expect it to require a lot of review so please feel free to work then do the PR.

**Comment by bbengfort** [comment]
This has been fixed in the recent classification report updates #348 and I've also updated the docs a bit to make the classification report more detailed:

http://www.scikit-yb.org/en/develop/api/classifier/classification_report.html
