### ISSUE TITLE
Style Management

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#3]
Create a scheme similar to Seaborn for creating a unified style and context system that sits on top of mpl.RCParams (so that every plot generated by our tool looks the same).

**Comment by bbengfort** [comment]
This task requires the ability to modify the visual environment in Yellowbrick similar to how Seaborn does it - but we're happy for ideas about how to do this in more innovative and intuitive ways. For lack of any ideas right now, I'll discuss Seaborn's:

- `set_style` - set the color scheme and other color properties 
- `set_context` - set the font and size for 'talk', 'poster', 'paper', 'notebook', etc. 

See: https://stanford.edu/~mwaskom/software/seaborn/tutorial/aesthetics.html for more. 

We also want our own unique visual style that is clean like Seaborn without cloning it. We really like the idea of using Color Brewer as a foundation of our visualizations: https://bl.ocks.org/mbostock/5577023

**Comment by pvomelveny** [comment]
Question:
Do we want Yellowbrick to blanket overwrite mpl defaults on import? It would then compete with Seaborn as well I think. Who ever gets imported last gets control of the style? (Actually it may make some kind of odd hybrid if we don't perfectly match the various Seaborn changes)

**Comment by bbengfort** [comment]
It would be awesome to do an experiment about how the drawing environment
changes by mapping the global parameters (and a potential blog post). I
know I just said this outloud, but for the purposes of documentation:

1. Modify the mpl defaults
2. Visualize using striaght mpl
3. Visualizing using pandas
4. Visualize using seaborn
5. set_context/set_style
6. Visualize using straight mpl
7. Visualize using pandas

And we can watch what is happening/changing.

**Comment by pvomelveny** [comment]
Made a [notebook](https://github.com/pvomelveny/Development_Notebooks/blob/master/Test_RC_Changes_in_Figs.ipynb) with some quick experiments. Seems like most things are using the matplotlib rc settings that Seaborn creatively overwrites upon import.

Let me know if I missed anything obvious. Going to start copying over the Seaborn style functionality into Yellowbrick.
