### ISSUE TITLE
ConfusionMatrix FontSize

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#301]
The confusion matrix label font size is hardcoded to 8pt: https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/classifier/confusion_matrix.py#L228

It appears that this may be a tad too small: https://stackoverflow.com/questions/47450804/yellowbrick-increasing-font-size-on-yellowbrick-generated-charts

We should probably remove this line and make it default to the matplotlib font size.

**Comment by ianozsvald** [comment]
+1! 

I'm changing my matplotlib defaults as on my UHD screen the tiny labels are hard to read, this is fine for the `ClassificationReport` but `ConfusionMatrix` is stubbornly unreadable. I'm planning to include these yb plots in a talk for the PyDataLondon conference this year. Unless there's a compelling reason to hard-code to size 8, I'd suggest using the `mpl` defaults. 

The hardcoding occurs 3 times here: https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/classifier/confusion_matrix.py

**Comment by mattharrison** [comment]
+1 Was just going to file this

**Comment by bbengfort** [comment]
This is currently fixed and will be updated in the upcoming 0.6 release -- which should happen this week.

**Comment by ianozsvald** [comment]
Brill :-)
