### ISSUE TITLE
YellowBrick not compatible with statsmodels estimators (and a trivial wrapper as a light fix)

### ISSUE THREAD

**Issue by ianozsvald** [DistrictDataLabs/yellowbrick#306]
I'm comparing GLMs in `statsmodels` and other models in `sklearn`. I wanted to use a consistent visual output but realised that `yellowbrick` only understands the `sklearn BaseEstimator`. 

I've written a trivial wrapper (i.e. - it works for me, it may not do what you need!) around a `statsmodels GLM` that makes it 'look like' a `BaseEstimator`, in the eyes of `yellowbrick`. As a result I can create a `partial` GLM, push it into this wrapper, then call `yb.ResidualsPlot` and `yb.PredictionError`. 

I present this code more as a placeholder in case someone else has the same need and they'd like to build a stronger solution. 

This is tested using `yellowbrick 0.5`, `statsmodels 0.8`, `sklearn 0.19` in Python 3.6.

```
class StatsModelsWrapper(BaseEstimator):
    """Wrap a statsmodels GLM as a sklearn (fake) BaseEstimator for YellowBrick

    To use it, first create a partial 
    ```
    glm_gaussian_partial = functools.partial(sm.GLM, family=sm.families.Gaussian())
    #gaussian_model = glm_gaussian_partial(y_train, X_train) # for statsmodels usage, calling .summary() etc
    fake_est = StatsModelsWrapper(glm_gaussian_partial)
    visualizer = PredictionError(fake_est)
    #subsequent calls to e.g. fake_est.fit(X, y) will be passed through
    ```
    
    NOTE that this wrapper is trivial, options and extra things like weights are not handled
    """
    def __init__(self, 
                 glm_partial, 
                 stated_estimator_type="regressor",
                 scorer=sklearn.metrics.r2_score):
        # YellowBrick checks the attribute to see if it is a regressor/clusterer/classifier
        self._estimator_type = stated_estimator_type
        # assume user passes in a partial which we can subsequently instantiate
        self.glm_partial = glm_partial
        # score() needs a default scoring function, regression uses r^2 in sklearn
        self.scorer = scorer

    def fit(self, X, y):
        """Pretend to be a sklearn estimator, fit in this case is called on creation"""
        # note that GLM takes endog (y) and then exog (X), this is the reverse of sklearn's methods
        self.glm_model = self.glm_partial(y, X)
        self.glm_results = self.glm_model.fit()
        
    def predict(self, X):
        return self.glm_results.predict(X)
    
    def score(self, X, y):
        return self.scorer(y, self.predict(X))
    

def test_stats_models_wrapper():
    """A trivial test of the StatsModelsWrapper defined above"""
    X = np.array([[1], [2], [3]])
    y = np.array([1.1, 2, 3])
    glm_gaussian_partial = functools.partial(sm.GLM, family=sm.families.Gaussian())
    fake_est = StatsModelsWrapper(glm_gaussian_partial)
    fake_est.fit(X, y)
    fake_est.predict(X)
    fake_est.score(X, y)
    print("All the fake methods ran")
test_stats_models_wrapper()
```

**Comment by ndanielsen** [comment]
@ianozsvald thank you! this is a very helpful wrapper that you've contributed here. at our next maintainers meeting, we'll discuss how we might be able to potentially incorporate this in. Maybe in a `contrib` module to start

**Comment by bbengfort** [comment]
See #341 -- once we get the `contrib` module in place, we're planning on including this as well as possibly Keras visualizers in it; as well as some of our more prototype-y implementations.
