### ISSUE TITLE
Yellowbrick on Kaggle

### ISSUE THREAD

**Issue by alexanderbachmann** [DistrictDataLabs/yellowbrick#307]
How can I import yellowbrick module into Kaggle? It seems that it is not recognizing the module even though I have it installed.

**Comment by gary-mayfield** [comment]
Someone please correct me if I'm wrong. 

As far as I know the kernels on Kaggle run from docker image maintained here [https://github.com/Kaggle/docker-python](url)

They accept pull requests for new packages so you could add "pip install yellowbrick" to Dockerfile and submit request for them to add it.

**Comment by alexanderbachmann** [comment]
Thanks for the help i will do exactly that and see if it works.

**Comment by ndanielsen** [comment]
@alexanderbachmann thanks for doing this. 💯 

If you'd like, share a link to your kernel and I'll be sure to upvote it

**Comment by alexanderbachmann** [comment]
https://www.kaggle.com/janiobachmann/crystall-ball-house-prices-eda-ensembling

This is the link to the uploaded kernel. I going to fix the issue with regards to importing the yellowbrick module into the kaggle project. But basically, what I want to do with yellowbrick which I did in my Jupyter notebook locally is a "residual plot". Currently, I am just using a simple matplotlib scatter plot until I fix the issue.

**Comment by ndanielsen** [comment]
@alexanderbachmann thanks for sharing. That's an indepth and highly detailed kernel! Great visualizations and layout! ✨ 

I can also make the PR to the kaggle docker image if you prefer!

**Comment by alexanderbachmann** [comment]
Thanks! Please do and thanks for the help!

**Comment by ndanielsen** [comment]
Added yellowbrick to the kaggle-docker file that powers their kernels here:
https://github.com/Kaggle/docker-python/pull/168

**Comment by ndanielsen** [comment]
@alexanderbachmann I missed worded my comment above. I made pull-request into that repo. The kaggle team will likely take a look and either accept/ deny the PR. If accepted, they will bring it into their main branch and eventually push it into their servers. 

I couldn't give you a timeline for this but they do seem to be fairly response on incoming pull requests.

**Comment by alexanderbachmann** [comment]
Ok thanks for the help! If they replied to you could you send me a message
in order for me to know if I could use yellowbrick in my Kaggle project?
Have a nice day.

**Comment by ndanielsen** [comment]
@alexanderbachmann confirming that yellowbrick is now on kaggle

**Comment by ndanielsen** [comment]
@alexanderbachmann let us know when your kernel with yellowbrick is live!

**Comment by alexanderbachmann** [comment]
Thanks so basically the only thing I have to do is import Yellowbrick
right? I'll check right now if it works on kaggle. Thanks for the update.

**Comment by alexanderbachmann** [comment]
Its already live on kaggle. You can check it out in this link.
https://www.kaggle.com/janiobachmann/in-depth-analysis-house-prices-ensembling

Another last question, is it possible to change test data in my legend for
validation data? Thanks again for the update.

**Comment by bbengfort** [comment]
@ndanielsen any insight for @alexanderbachmann?
