### ISSUE TITLE
Text Focused Decision Boundry Visualizer

### ISSUE THREAD

**Issue by Emiller00** [DistrictDataLabs/yellowbrick#310]
So I am finding Yellowbrick's t-sne visualizer to be very useful for easily inspecting text corpora. However, while it is useful for deciphering if text data is linearly separable, it can't be used to evaluate classifiers. For this reason, I propose a visualizer that can be applied to this problem. 

Text is unique because it is high dimensional. Many of the techniques used in classifying it involve either dimensionality reduction or applying a model that can work high dimensions (such as [LibLinear](https://www.csie.ntu.edu.tw/~cjlin/papers/guide/guide.pdf).) . Visualizing text data proves to be difficult, as one must find a suitable mapping that can express all of the features of a text corpus in two dimensions. This technique is often t-SNE ([t-distributed Stochastic Neighbor Embedding](https://www.csie.ntu.edu.tw/~cjlin/papers/guide/guide.pdf)). 

t-SNE is good for expressing the features of text, but isn't exact a 1-1 mapping of a higher space to 2 dimensions, because of this, on its own, it can not be used to visualize classifiers or decision boundries. Different runs of t-SNE on the same corpus can produce different visualizations. Furthermore, [It is very sensitive to its hyperparameters](https://www.csie.ntu.edu.tw/~cjlin/papers/guide/guide.pdf). 

For this reasons I propose the following workaround:

- Use PCA to compute a map from the high dimensional text space to the low dimension visual space. Then, plot the probability distribution of the classifier in the low dimensional space. This is possible because [anytime we can compute a probability for a class we can visualize the decision boundry](https://www.csie.ntu.edu.tw/~cjlin/papers/guide/guide.pdf)
  - One of the issues with this is that, while PCA can produce a high dimension to 2d mapping, this mapping is often not the greatest. I personally have found it to collapse most of the data onto one of the two principle components it produces. 
 
  - I suspect LDA (Linear Discriminant Analysis) could also be used as a dimension reducer. But I am not sure, as this requires class information. 

- I have also [Found this repo that seems to be able to perform much of what I propose and more](https://github.com/tmadl/highdimensional-decision-boundary-plot), but it appears to be out of date and not maintained. Adapting it may also be possible.

**Comment by rebeccabilbro** [comment]
Sounds great @Emiller00 - we're looking forward to seeing what you come up with! Have you already opened up a preliminary PR?

**Comment by Emiller00** [comment]
I have not. But I can soon! FWIW, I am open to suggestions for text corpora to use! If not I can always use a standard one.

**Comment by rebeccabilbro** [comment]
There's always the Baleen corpus! You can grab a random ~500 MB sample [here](http://pycon.districtdatalabs.com/corpora/baleen/20160525/sample.zip).

**Comment by rebeccabilbro** [comment]
Going to archive this one for now since the conversation has gone a bit stale; happy to reopen if someone has bandwidth and interest!
