### ISSUE TITLE
Yellowbrick Notebook / Kernel on Kaggle

### ISSUE THREAD

**Issue by ndanielsen** [DistrictDataLabs/yellowbrick#311]
Yellowbrick is now on kaggle: https://github.com/DistrictDataLabs/yellowbrick/issues/307

It would be great if we could have a kernel going through the entire data exploration and model selection process with yellowbrick.

**Comment by mitevpi** [comment]
Any preference on dataset type or model type? I have a couple of ideas I've been meaning to try (publicly) so this may be a good opportunity.

**Comment by bbengfort** [comment]
@ndanielsen any thoughts?

**Comment by ndanielsen** [comment]
@mitevpi I was thinking that one of the knowledge or kudos type challenges would be interesting. The Digit Recognition or ImageNet datasets does look interesting, but I leave it to you to find one that is interesting for you.

**Comment by bbengfort** [comment]
@Kautumn06 closing this issue as it seems complete with your notebook and now we've got the NFL dataset as well!
