### ISSUE TITLE
Fix Travis Tests

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#315]
Our travis tests are starting to kill me - we need to find a way to make this more robust. 

@ndanielsen can we use our next office hours to go over this if you're not too busy with blog writing?

**Comment by ndanielsen** [comment]
I know what the error is, it's related to the changes in the ROC awhile ago. 

It's more of a deep bug to fix in how we select colors.

**Comment by ndanielsen** [comment]
Yeah, I'll find a little time to get the fix actually in a PR over the weekend and next week. We can review at the next office hours.

**Comment by bbengfort** [comment]
Awesome, ok thanks -- and we do have a bunch of work to do with the colors stuff. If you can get started with the PR I'd really appreciate it.

**Comment by bbengfort** [comment]
What I'm going to do in the meantime is mark them as xfail.

**Comment by bbengfort** [comment]
@ndanielsen this is kind of an old, non-specific issue that I don't really remember. Do you think this was fixed in #533 or #522? If you do remember, perhaps we could close this in favor of something more specific? I did take a look, none of the roc auc tests are marked as xfail.

**Comment by bbengfort** [comment]
I believe this was fixed in #522 - closing!
