### ISSUE TITLE
Overhaul unittest and fixtures

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#318]
Remove dependency on `unittest.TestCase` by replacing assertions with `assert` statements. This also involves using `pytest.raises` and `pytest.skip` decorators. 

Use PyTest fixtures for datasets and other fixtures. 

~Add PEP checking to pytest (alongside pyflakes)~

- [x] rename `ThingTests` to `TestThing` 
- [x] assertions 
- [x] pytest.skip 
- [x] dataset fixtures 
- [ ] ~PEP8~

Alongside this we should also do a PY2 removal check, namely anywhere:

```python
try:
    from unittest import mock
except ImportError:
    import mock
```

should be replaced with just `from unittest import mock`

**Comment by NealHumphrey** [comment]
@bbengfort what's the motivation for removing the unittest dependency?

**Comment by bbengfort** [comment]
@NealHumphrey the short answer is that weird things happen when you mix and match pytest and unittest - my primary concern is test discovery. PyTest expects `TestThing` vs `ThingTests` (although I guess that is more of a nose thing than a unittest thing). Plus pragmas and marks (e.g. skip, xfail) behave slightly differently. I think it's better to standardize on one or the other. 

Because our feeling is that people are more comfortable with pytest and because of features like pytest-flakes, pytest-spec, etc. we've chosen to move to pytest. Pytest does play well with unittest so there is no rush on this, but the sooner it's standard the easier it will be to diagnose issues in the tests (of which we have a few).

**Comment by rebeccabilbro** [comment]
Yeah @NealHumphrey, this is sort of a follow on from #291 -- after we discovered last year that [nose wasn't being maintained anymore](https://twitter.com/llanga/status/826144101833732097) and started converting all the tests to pytest.

**Comment by NealHumphrey** [comment]
Adding a TODO:
- [ ] Update the [documentation](http://www.scikit-yb.org/en/latest/contributing.html#testing) for contributors

**Comment by NealHumphrey** [comment]
As noted in my pull request, I had trouble running `pytest` locally including pyflakes and coverage. On Windows, haven't tried it on Mac yet. 

What I tried:
1) Create a new virtual environment (using conda) 
2) activate it `activate yb`
3) pip install pytest (b/c it's not in the requirments.txt, see TODO in previous comment), which installed 3.4.2 plus some dependencies, and `pip install --upgrade pyflakes`  (installed v 1.6.0)
4) in root `yellowbrick` folder (i.e. not in `yellowbrick/tests` and not in `yellowbrick/yellowbrick`), run `python -m pytest`

Output: 
```
usage: pytest.py [options] [file_or_dir] [file_or_dir] [...]
pytest.py: error: unrecognized arguments: --cov=yellowbrick --flakes --spec
  inifile: C:\Users\humph\Documents\Github\yellowbrick\setup.cfg
  rootdir: C:\Users\humph\Documents\Github\yellowbrick
```

If I run without the virtual environment and use `python -m pytest`, it runs all the test but lots of them fail (44). There are various causes, though a lot of them seem to trace back to this:
```
    def _actual_img_path(self, extension='.png'):
        """Determines the correct outpath for drawing a matplotlib image that
            corresponds to the unittest module path.
            """
        module_path, test_func_name = self._setup_imagetest()
>       module_path = os.path.join(*module_path)
E       TypeError: join() missing 1 required positional argument: 'path'
```

**Comment by NealHumphrey** [comment]
@bbengfort see above

**Comment by bbengfort** [comment]
@NealHumphrey, thank you for the detailed notes. This is a very good point; the documentation has been updated with pytest, but is currently in develop and will be moved to latest once we go to 0.6 (very shortly). If you could review the develop documents we can try to adapt them to make it a bit friendlier. 

In [Forking the Repository](http://www.scikit-yb.org/en/develop/contributing.html#forking-the-repository) in the contributors guide, step 3 mentions `pip install -r tests/requirements.txt` and `pip install -r docs/requirements.txt`, this isn't in the testing section though which simply mentions:

> The Makefile uses the pytest runner and testing suite as well as the coverage library, so make sure you have those dependencies installed! The DatasetMixin also requires requests.py to fetch data from our Amazon S3 account.

We could adapt this section to reinforce installing the dependencies with `pip install -r tests/requirments.txt` and also mention using `pytest` directly rather than `make test`. 

I believe the error you are observing will be solved when you install pyspec and coverage using that requirements file. 

A note on the various requirements files: the main `requirements.txt` file is used in `setup.py` to determine dependencies, as such we have only the dependencies required for using yellowbrick as a library in it (nor do we manage our dependencies' subdependencies). The requirements for testing and documentation are actually in that file, just commented out and they're uncommented in the respective docs and test directories.

**Comment by rebeccabilbro** [comment]
@bbengfort potentially we could close this in favor of #456 and #682?

**Comment by bbengfort** [comment]
@rebeccabilbro thanks for grooming the backlog of issues! Although #456 and #682 are closely related to this issue, I think this is an independent task from those and there are several gotchas that this issue records (e.g. TestThing vs ThingTests). The good news is that in the PRs since this issue we've added no new unittest dependencies and have replaced some of the old dependencies with PyTest. I think that this should be (relatively) easily sorted when we do the v1.0 release.

**Comment by rebeccabilbro** [comment]
Gotcha @bbengfort, I’ll add to the v1.0 milestone in that case.

**Comment by ndanielsen** [comment]
Recommend that we remove PEP8 from this as we are going to add Black in another V1.0 issue:
https://github.com/DistrictDataLabs/yellowbrick/issues/456
