### ISSUE TITLE
refactor ClassifierReport class

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#32]
refactor ClassifierReport class to take multiple models as input

**Comment by rebeccabilbro** [comment]
The method can only take one model as currently written. The issue here is that the classification report heatmap needs to anticipate multiple models and reflect relative strengths and weaknesses -- probably the easiest way to do that is to create a single heat scale with a fixed 0 to 1 range.

**Comment by bbengfort** [comment]
@rebeccabilbro bump! Can we rewrite this issue with the new `ClassificationReport` visualizer in mind?

**Comment by rebeccabilbro** [comment]
This is dependent on #45
