### ISSUE TITLE
Improvements for FeatureImportances visualizer 

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#322]
There are a couple of enhancements for the `yellowbrick.features.FeatureImportances` visualizer that should be made to really make it stick out. They are as follows:

*Note to contributors: items in the below checklist don't need to be completed in a single PR; if you see one that catches your eye, feel to pick it off the list!*

- [ ] color negative coefs 
- [ ] top n features to filter number displayed (both pos and neg)
- [ ] implement standard deviation for ensemble models 

### Color negative coefs 

The first item is relatively straightforward, currently, the bar chart is a single color, but it might be nice to show negative `coef_` values as a different color, e.g. blue for positive green for negative as below:

![figure_1](https://user-images.githubusercontent.com/745966/36986141-1b9d5a58-2067-11e8-983e-eadb2acac686.png)

To do this, you'll have to create a color array to pass as the color argument, e.g. 

```python
colors = np.array(['b' if v > 0 else 'g' for v in self.feature_importances_]) 
self.ax.barh(pos, self.feature_importances_, color=colors, align='center')
```
We should also create arguments to provide a way to specify the colors. 

### Top N Features 

For the second item, I'm picturing something similar to [most informative features with scikit-learn](https://stackoverflow.com/questions/11116697/how-to-get-most-informative-features-for-scikit-learn-classifiers) (though not exactly this code). Here, an argument `topn` which defaults to None specifies a filter to only plot the `N` best features. 

This should also be relatively straightforward, but gets complicated in the case of negative values. We have two options, we can rank all values including negative values and plot the N best values either positive or negative, or we can do the N best positive and N best negative coefficients 

### Standard Deviation for Ensembles 

Ensemble models like Random Forest and Gradient Boosting have an underlying `estimators_` attribute that describes each feature's importance in a different way. The global feature importances are the mean, but it would be nice to add an `xerr` bar with the standard deviation as in [plot forest importances](http://scikit-learn.org/stable/auto_examples/ensemble/plot_forest_importances.html). 

This could also be useful for `CV` models that also have an underlying `estimators_` attribute. 

The idea with this one is to compute the standard deviations for each feature using `estimators_` and np.std, and storing the value in a `confidences_` attribute during fit. Note that it will also have to be sorted using the `sort_index` -- the confidences are drawn during `ax.barh` with `xerr=self.confidences_`. 

Right now it looks like the example above is no longer working exactly as expected, so some deeper review is necessary. 

See also #194 where a discussion about tree-specific feature importances is ongoing.

**Comment by kim81682** [comment]
Hello, i'm beginning to work on this.

**Comment by bbengfort** [comment]
@majidaldo I agree that most informative features could be its own visualizer and not necessarily related to the current functionality of `FeatureImportances`; any interest in opening a feature request and speccing out what this would look like?

**Comment by JonoCX** [comment]
Hi, I know that this is an old issue, but I can't find an implementation of the top-n feature discussed here. Would a top-n parameter (or even a separate visualizer) be a useful feature? I use the library regularly, and it's a feature that I recently needed for a paper.

**Comment by bbengfort** [comment]
@JonoCX it would absolutely be a useful feature and we'd certainly welcome a PR if you have an implementation!

**Comment by mgarod** [comment]
Hello yellowbrick! For in the interest of _legitimate_ hacktoberfest PRs I took at stab at the top_n feature for this

Please see PR #1102 for my very quick implementation of this feature. I'm open to suggestions on how to fully flesh this out. I did not try out many combinations of parameters, so there are scenarios where `top_n` may or may not even apply which I have not even considered.
