### ISSUE TITLE
Radviz colors - Support Colormap and colors arguments

### ISSUE THREAD

**Issue by ndanielsen** [DistrictDataLabs/yellowbrick#325]
Currently Radviz does not support adding a custom color palette. 

Here's the segment of code to change / improve :
https://github.com/DistrictDataLabs/yellowbrick/blob/c5b2346c03ba5b8aaadf6a4037b1939e9f3063a2/yellowbrick/features/radviz.py#L176-L183

**Comment by Aylr** [comment]
@ndanielsen Is there a visualizer where colormaps are implemented particularly well?

**Comment by ndanielsen** [comment]
@Aylr thanks for asking, I think that this issue has been resolved in https://github.com/DistrictDataLabs/yellowbrick/pull/327 but I need to confirm

**Comment by bbengfort** [comment]
@Aylr here is an [example](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/text/tsne.py#L306) but it's not great - does that help?

**Comment by bbengfort** [comment]
@ndanielsen yes this was fixed in #327; thank you for bringing up the issue and checking on it!
