### ISSUE TITLE
Fix typos in the documentation. 

### ISSUE THREAD

**Issue by ndanielsen** [DistrictDataLabs/yellowbrick#328]
This task will create one or more PRs into the main code branch to fix these. 

There are a few places in the documentation that could use a little polish - they are missing imports or there is a simple typo.

Group: 
@Kautumn06
@ndanielsen (technical support)

**Comment by wagner2010** [comment]
One place that I found that is missing an import statement is with Rank 1-D http://www.scikit-yb.org/en/latest/api/features/rankd.html#

- [ ] Add import statement for rank 1-D

copying the code as is produces a NameError:
NameError                                 Traceback (most recent call last)
<ipython-input-70-40231c1a8401> in <module>()
      1 # Instantiate the 1D visualizer with the Sharpiro ranking algorithm
----> 2 visualizer = Rank1D(features=features, algorithm='shapiro')
      3 
      4 visualizer.fit(X, y)                # Fit the data to the visualizer
      5 visualizer.transform(X)             # Transform the data

NameError: name 'Rank1D' is not defined

**Comment by bbengfort** [comment]
@Kautumn06 I know you worked on this and have several related PRS; can we close this issue?

**Comment by Kautumn06** [comment]
@bbengfort Yes, this issue can be closed. While we are still working on updating the documentation, the typos and missing import statements originally addressed here have been fixed and merged in.

**Comment by bbengfort** [comment]
Thanks!
