### ISSUE TITLE
Cannot import Rank 1-D

### ISSUE THREAD

**Issue by wagner2010** [DistrictDataLabs/yellowbrick#329]
Import error
<img width="1102" alt="screen shot 2018-03-10 at 3 54 07 pm" src="https://user-images.githubusercontent.com/24282993/37246647-51c0268e-247b-11e8-8aaa-8ce3784ef9bc.png">

**Comment by ndanielsen** [comment]
@wagner2010 thanks for much for flagging this issue! I'll take a look and get a fix in place for this one

**Comment by ndanielsen** [comment]
@wagner2010 just ran it and you can import the Rank2D like this.

>>> from yellowbrick.features import Rank2D
>>> from yellowbrick.features import Rank1D

I also added tests in https://github.com/DistrictDataLabs/yellowbrick/pull/332 to confirm that they are accessible

**Comment by wagner2010** [comment]
Hey Nathan, Yes 2-D works but 1-D I still can't get it to work.
<img width="532" alt="screen shot 2018-03-16 at 9 56 36 pm" src="https://user-images.githubusercontent.com/24282993/37550514-ffad4aae-2964-11e8-877c-11c806f9fc51.png">

**Comment by ndanielsen** [comment]
@wagner2010 okay, I'll take another look at this! thanks for your patience

**Comment by bbengfort** [comment]
@wagner2010 what version of Yellowbrick are you running? You can figure that out with:

```python 
import yellowbrick as yb 
print(yb.__version__) 
```

**Comment by wagner2010** [comment]
Sorry for the delay.  It's working now.  I have upgraded to 0.6 now obviously.  Thanks.
