### ISSUE TITLE
RadViz does not support Pandas DataFrames

### ISSUE THREAD

**Issue by Kautumn06** [DistrictDataLabs/yellowbrick#331]
I tried to use a Pandas DataFrame with RadViz and received the following error:

`ValueError: Unable to coerce to DataFrame, shape must be (20560, 5): given (1, 5)`

Here is the code I used:

```
# Load the classification data set
data = load_data('occupancy')

# Specify the features of interest and the classes of the target
features = ["temperature", "relative humidity", "light", "C02", "humidity"]
classes = ['unoccupied', 'occupied']

X = data[features]
y = data.occupancy

# Import the visualizer
from yellowbrick.features import RadViz

# Instantiate the visualizer
visualizer = RadViz(classes=classes, features=features)

visualizer.fit(X, y)      # Fit the data to the visualizer
visualizer.transform(X)   # Transform the data
visualizer.poof()         # Draw/show/poof the data
```

**Comment by ndanielsen** [comment]
@Kautumn06 thanks for creating this issue!

**Comment by ndanielsen** [comment]
@Kautumn06 I added some tests to the RadViz and it seems to support pandas dataframes in the tests that I wrote / adapted from your example. Can you take another look at this?

https://github.com/DistrictDataLabs/yellowbrick/pull/338/files

**Comment by ndanielsen** [comment]
closing this issue as it now has test coverage to confirm it works
