### ISSUE TITLE
Create a localization for Turkish language docs

### ISSUE THREAD

**Issue by Zeynepelabiad** [DistrictDataLabs/yellowbrick#337]
I would like to translate some of the yellowbrick documentation into Turkish. Can you please create a localization for Turkish-language docs.

**Comment by bbengfort** [comment]
I'm glad you're willing to do this! I'm currently looking into how to do it for Chinese, once I've got that setup, I'll also set it up for Turkish.

**Comment by bbengfort** [comment]
Repository has been set up: https://github.com/DistrictDataLabs/yellowbrick-docs-tr 

@Zeynepelabiad you should have write access to that repository. 

Docs can be found here: http://www.scikit-yb.org/tr/latest/ 

(Note the tr language code). 

Feel free to get started on the translation!
