### ISSUE TITLE
Code review checklist

### ISSUE THREAD

**Issue by ndanielsen** [DistrictDataLabs/yellowbrick#345]
Creating a list that eventually will turn into some type of documentation for commonly identified items that might need to be checked for in a code review

Code Conventions
- Check ambiguous comparisons with numpy arrays, switching them to if y is not None etc, aka explicit testing for 'truthy' / 'falsy' values that might be obscured with numpy and other data containers
- added random_state to the visualizer to engage image comparison tests
- user np.unique() instead of set()
- self.classes should be self.classes_ (same for self.score_)

Testing
- Ensure that there is an image comparison test for visualizers
- A random_state to the visualizer to engage image comparison tests
- Ensure there are tests for a variety of inputs formats included pandas dataframes, numpy arrays
- Ensure that fit returns self

Doc String
- Visualizer doc string is under the class
- Contains narrative about visualizer and parameters with correct formatting

**Comment by bbengfort** [comment]
Documentation 

- Is documented under `docs/api/[yb-module]` 
- Has an image generation script with same name in `docs/api/[yb-module]`
- Is indexed under `docs/api/[yb-module]/index.rst`
- Is induxed under `docs/api/index.rst`
- Is listed on main listing page under `docs/index.rst` 
- Is included in README.md
- Is included in DESCRIPTION.txt 

(Maybe we should find a way to make this easier, programmatically)

**Comment by bbengfort** [comment]
Code Conventions:

- has a quick method 
- subclasses the correct visualizer 

Testing:

- uses pytest instead of unittest assertions 
- uses yb test fixtures
