### ISSUE TITLE
Script to autogenerate images in docs

### ISSUE THREAD

**Issue by ndanielsen** [DistrictDataLabs/yellowbrick#353]
Currently in our `docs` folder, we have code that generates png files to be used in the generated docs. It would be helpful to have a script to generate images and save them in the appropriate folder location. 

related to: https://github.com/DistrictDataLabs/yellowbrick/issues/38

**Comment by rebeccabilbro** [comment]
Closing in favor of #687 &mdash; which is very close to done! 😄
