### ISSUE TITLE
Scripts to Regenerate Tutorial and Quickstart Documentation Images

### ISSUE THREAD

**Issue by ndanielsen** [DistrictDataLabs/yellowbrick#354]
In the documentation, the tutorial and quickstart need a script that can autogenerate the images similar to how they are done in the `doc/api/` section. The code to generate the images is located in the rst files and can be simple extracted and moved into a py file.

These scripts can live right alongside their .rst compatriots.

**Comment by ralle123** [comment]
do you want to add something like sphinx-gallery to the config.py?

**Comment by lwgray** [comment]
@ralle123 we don’t know anything about Sphinx gallery but would be interested to learn more

**Comment by ndanielsen** [comment]
Adding this issue streamlining the project Readme:

https://github.com/DistrictDataLabs/yellowbrick/issues/689
