### ISSUE TITLE
Update all the docstrings

### ISSUE THREAD

**Issue by lauralorenz** [DistrictDataLabs/yellowbrick#36]
Now that we are in sphinx land we should update all the docstrings to conform to sphinx markup and also check for accuracy.
- [ ] Good way to mark items as interface? Relevant?
- [x] Good way to autodoc params from a docstring, not the docstring itself or the method name, for cases when I want to DRYly autodoc-inject params from an interface?

**Comment by rebeccabilbro** [comment]
:/ oops, I haven't been doing this, but I can go back and clean up my new docstrings as well as the old ones. 
@lauralorenz @bbengfort We're sticking with sphinx, right?

**Comment by lauralorenz** [comment]
I'm still pro sphinx for api ref purposes since [mkdocs explicitly will not support it](https://github.com/mkdocs/mkdocs/issues/641). I think in our conversations we settled on one of the alternative sphinx docstring formats instead of RST... I can't find proof of what we selected in the issues anywhere in here. Our choices are the native RST format, our the [napoleon plugin-supported](http://www.sphinx-doc.org/en/stable/ext/napoleon.html) Numpy or Google formats ([see the differences here](http://www.sphinx-doc.org/en/stable/ext/napoleon.html#google-vs-numpy).

**Comment by bbengfort** [comment]
@lauralorenz -- perfect, thanks for digging this up! 

I was at a bit of a loss for what style to use as you can see from: [pcoords.py#L47](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/features/pcoords.py#L47)

I believe what I'm doing is native RST right? However, I do much prefer the NumPy format as I find it much more readable. More important though is the documentation; will napoleon serve us well in the docstring parsing particularly for the documentation context?

**Comment by lauralorenz** [comment]
@bbengfort yes yours is RST. 

I don't totally understand the second question, so I'm going to try and rephrase it and tell me if I'm right. 

To me there are 2 types of documentation of interest we're interested in

- the sort of free-form documentation (like tutorial pages ([see pandas](http://pandas.pydata.org/pandas-docs/stable/tutorials.html)), or architecture introduction pages (like [baleen's components page](http://baleen-ingest.readthedocs.io/en/latest/components/)), or galleries, etc) which in Sphinx you would write in RST with `.rst` files in your `docs/` folder. 
- and API documentation which, instead of writing and maintaining separate from the code itself, you include as docstrings directly in line with your classes/functions/what have you.

For the latter, the Sphinx plugin that now ships with Sphinx standard, called [`sphinx-autodoc`](http://www.sphinx-doc.org/en/stable/ext/autodoc.html), can pull them out, format them nicely, link them to source code snippets, etc (for example in yellowbrick we get [this beautiful stuff](http://yellowbrick.readthedocs.io/en/latest/api/yellowbrick.html#yellowbrick.yb_palettes.color_palette) and automagically get [a syntax highlighted HTML rendered source code link as well](http://yellowbrick.readthedocs.io/en/latest/_modules/yellowbrick/yb_palettes.html#color_palette) just by [defining the docstring of the target API reference right](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/yb_palettes.py#L92)). By default those are must be in normal RST, which you can see in that last example.

So the fun next wrinkle is that another Sphinx plugin (also now shipped with Sphinx standard), called [`sphinx-napoleon`](http://www.sphinx-doc.org/en/stable/ext/napoleon.html), allows the HTML renderer for `sphinx-autodoc` to understand alternative docstring formats Numpy and Google. It seems like the napoleon plugin doesn't need to be told what docstring type you're using, but they do recommend to stick with just one - not clear whether this is for technical or clarity reasons:

> The choice between [docstring] styles is largely aesthetic, but the two styles should not be mixed. Choose one style for your project and be consistent with it.

Note that all of this napoleon stuff does not affect the first type of documentation I brought up, the free-form stuff; that is always in RST (unless there's some other slick plugins I don't know about).

LMK if that didn't answer your question at all 😅

**Comment by bbengfort** [comment]
@lauralorenz - a very good description. Yes, those are absolutely the two types of documentation we're interested in, and I think that having links to syntax highlighted html is vital to getting outside contributors. 

My question was more about the RST vs Numpy style docstrings; I had heard that napoleon had some difficulties in parsing the docstrings. However, if it's now shipped with Sphinx (and we stick to one style), it seems like you're confident in that docstring parser? 

So I suggest we use the Numpy format docstring, parsed and rendered into the documentation Laura described above.

**Comment by lauralorenz** [comment]
Ah ok ok I get it now. TBH I actually do all RST on my projects, so I don't have direct experience with napoleon and the other docstring formats, but it came up while Rebecca and I were converting stuff as possibly easier to read in-code and lower barrier-to-entry option. I can certainly do a quick test to make sure it works as expected.

Alternatively if we want to go Numpy style it looks like pandas, matplotlib, and seaborn all use a plugin called [`numpydoc`](https://github.com/numpy/numpydoc) instead of napoleon to deal with numpy docstrings. I don't know if napoleon is new/has updated since those projects started or if they still have good reason to stay on `numpydoc`, but we could just get on the bandwagon with them instead if we're concerned since we know their documentation and know it builds fine. For an explicit example [here's a pandas docstring in numpy format](https://github.com/pydata/pandas/blob/37f95cef85834207db0930e863341efb285e38a2/pandas/io/pickle.py#L11-L17) and [here's their built documentation off it](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_pickle.html#pandas.read_pickle) that used the `numpydoc` parser.

Slightly off topic, but while I was researching these other packages, they seem to also like to use another third party plugin for an [ipython directive](http://matplotlib.org/sampledoc/ipython_directive.html) for running code examples new each time documentation is built, which might be interesting at some point.

**Comment by lauralorenz** [comment]
As discussed IRL: I took a look at the numpydoc parser and it works fine and is now a dependency in the branch for this issue 32-update-doc strings. Some previous work Rebecca and I did to update doc strings got blasted by all the 0.3 reactors but cest la vie

**Comment by rebeccabilbro** [comment]
@lauralorenz @bbengfort I'm going to take a crack at this. Which branch should I do that in, 36-update-docstrings or develop?

**Comment by bbengfort** [comment]
I don't have an opinion here; @lauralorenz ?

**Comment by lauralorenz** [comment]
I merged develop in this weekend so I suggest 36-update-doc strings for the numpydocs install and any of the work we did a few months ago that survived the refactor

**Comment by rebeccabilbro** [comment]
Fleshed out docstrings for regression and classification score visualizers and pushed to develop.

**Comment by rebeccabilbro** [comment]
@rebeccabilbro run make on the docs and see what happens. Reminder to spot check the autodocs for Ben's methods, too

**Comment by rebeccabilbro** [comment]
@lauralorenz we've made some updates to the documentation, attempting to use the sphinx-friendly style. I ran a make html this morning and I can't tell if we've done it right -- can you take a look? It doesn't seem to be finding anything in yellowbrick.style or yellowbrick.features, so maybe I need to go in and manually change some of the conf stuff?

**Comment by lauralorenz** [comment]
@rebeccabilbro this all on develop or do you have a branch going?

**Comment by lauralorenz** [comment]
@rebeccabilbro If I assume your updates are on develop, then the configuration needs to be changed here to determine which modules to auto document using the `.. automodule` directive: https://raw.githubusercontent.com/DistrictDataLabs/yellowbrick/develop/docs/api/yellowbrick.rst. 

I noticed this when I was doing numpy test stuff on [36-update-docstrings](https://github.com/DistrictDataLabs/yellowbrick/tree/36-update-docstrings) because some of the packages have been renamed, e.g what was once in `yellowbrick.yb_palettes` is now in `yellowbrick.style.palettes` which I started to half-fix in this commit: https://github.com/DistrictDataLabs/yellowbrick/commit/86b8c62cdeeeb31e4d055cad4199f34f66d75e5d in the branch [36-update-docstrings](https://github.com/DistrictDataLabs/yellowbrick/tree/36-update-docstrings); in that commit/branch I was doing a whole docs refactor to split up the .rst files more in line with how the packages were organized, but that's a style decision.

So yeah, if that makes sense you could take a stab at it, or I could do it but if the latter I'd like to meet up with you to make sure I'm splitting up the API docs intelligently along the lines of the refactor.

**Comment by bbengfort** [comment]
See #89 - we now have a decorator to duplicate doc strings between functions; this should allow us to more easily document with some forethought. 

For example - I thought the visualizers and the single call wrappers could share their docstrings; this isn't possible in the current setup but could be easily modified to take advantage of the decorator.
