### ISSUE TITLE
ClassificationScoreVisualizers should return accuracy

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#361]
See #358 and #213  -- classification score visualizers should return accuracy when `score()` is called. If F1 or accuracy is not in the figure it should also be included in the figure.

**Comment by bbengfort** [comment]
This is a test alert @DistrictDataLabs/team-oz-maintainers

**Comment by rebeccabilbro** [comment]
echo

**Comment by abatula** [comment]
I'm going to start working on this

**Comment by lwgray** [comment]
As it stands, The following is True about the display of each visualizer
1. Classification Report has F1 score
2. Confusion Matrix has None
3. ROCAUC has None
4. Class Balance has None  *** SPECIAL NOTE*** Doesn't require Accuracy to be displayed
5. Class Prediction Error has None
6. Discrimination Threshold has F1 Score
