### ISSUE TITLE
Gatherplot Feature Visualizer

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#362]
Gatherplots could be a useful feature analysis tool for Yellowbrick, as they enable users to more easily visualize patterns in large datasets by stacking overlapping points.

### Proposal

It would be interesting to implement a `GatherPlot` visualizer in the Yellowbrick API to address the problem of overplotting of data points when visualizing large datasets in a scatterplot. Instead of overlapping, data points that map to the same position are stacked together. 

### Background

 - [*Gatherplots: Generalized Scatterplots for Nominal Data*
by Deokgun Park, Sung-Hee Kim, Niklas Elmqvist](https://arxiv.org/abs/1708.08033)
 - http://www.gatherplot.org/ by @intuinno

**Comment by intuinno** [comment]
Hi, Rebecca. 

Thank you for your kind suggestion.   If you are considering API, ATOM might be interesting to you, too. 

https://intuinno.github.io/unit/#/ 

Thanks.

**Comment by rebeccabilbro** [comment]
Going to archive this one for now since the conversation has gone a bit stale; happy to reopen if someone has bandwidth and interest!
