### ISSUE TITLE
CompareClassifiers visualizer

### ISSUE THREAD

**Issue by NealHumphrey** [DistrictDataLabs/yellowbrick#368]
When doing classification, I often want to compare the results of different scenarios to each other. Here a scenario is the full process of the model selection triple (features, model, hyperparameters) - if I make a change in any one of them, is it an improvement over previous scenarios? 

In the [housing risk project](https://github.com/georgetown-analytics/housing-risk) I approached this by making a bar chart of the `classification_report` parameters, shown below, for various models. I propose replicating this in yellowbrick as a starting point for scenario/model comparison visualizers. 
![for_presentation_under_sampling_confusion_comparisons](https://user-images.githubusercontent.com/5642566/37867405-3f81ce70-2f6e-11e8-84d6-badbb03276a4.png)

# Implementation
As (I believe?) the first multi-model visualizer, this will require some new additions to the yellowbrick API. As such it should definitely go into the [proposed contrib section](https://github.com/DistrictDataLabs/yellowbrick/issues/341), and I expect the first version won't necessarily get it quite right. 

The implementation approach is based on some discussions with @bbengfort about how multi-model visualizers might be implemented, and building on the new [VisualizerGrid](https://github.com/DistrictDataLabs/yellowbrick/pull/176#issuecomment-372522465) to implement the subplots. 

Also, the visualizer needs a better name. 

# Enhancements
A future version could implement the 12-fold `cross_val_predict` method as was sketched out in the MultiModelMixin.

**Comment by bbengfort** [comment]
@NealHumphrey - great idea and certainly a good start to the multi-model visualizer API! As per my last note on `contrib`, it doesn't necessarily have to go in `contrib` but we could prototype it in an edge branch. 

In your demo, are in/out the names of the classes?

**Comment by ndanielsen** [comment]
Just wanted to jump in and say this is awesome

**Comment by NealHumphrey** [comment]
@bbengfort yep in/out are class names. You can see my work in progress in the PR I just opened, which has class names that are more clearly classes.

**Comment by bbengfort** [comment]
@NealHumphrey checkout: 

https://github.com/HDI-Project/ATM

We've been talking to one of the folks on that project and we're thinking about adding some classification comparison visualizers that use ATM to the contrib package.

**Comment by rebeccabilbro** [comment]
Going to archive this one for now since the conversation has gone a bit stale; happy to reopen if someone has bandwidth and interest!
