### ISSUE TITLE
Add triangular git workflow helpers to documentation / contribution

### ISSUE THREAD

**Issue by NealHumphrey** [DistrictDataLabs/yellowbrick#369]
On the [contributing page](http://www.scikit-yb.org/en/latest/contributing.html) on the website and in [contributing.md](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/CONTRIBUTING.md) there are beginner-friendly instructions on how to make a fork of a repository. It would be useful to also include information about how to configure more than one remote repository (origin and upstream) so that contributors new to a forking workflow know how to get updates to the repo that occur after they forked the repo. 

### Proposal/Issue
We can use / adapt the writeup here that talks about this. 
http://housinginsights.org/resources/onboarding/triangular-git.html

### Background
I don't know if anyone has had problems with this, but in Housing Insights I often had people confused why their local code was different when they had done `git pull`, but when it only pulls from their fork they won't get the updates that occur on the DDL upstream repo.

**Comment by bbengfort** [comment]
I think this would be very helpful -- I had a question about this yesterday. I would focus on the contributing page in the RST docs; I want `CONTRIBUTING.md` to mostly forward people to the documentation, At least that way work won't get duplicated.

**Comment by bbengfort** [comment]
I believe this has been fairly well documented in the new contributor docs.
