### ISSUE TITLE
Fitted vs. Unfitted API

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#37]
Since we are moving towards thinking about this as a fitted model API (e.g. a version for more experienced Scikit-Learn users who will naturally want to have more control over their model fitting and tuning), we need to refactor the ROCAUC and ResidualsPlot classes so that they are not doing the fitting and predicting, but instead taking the results of fit and predict (as well as the split train/test data for residuals, and the y_pred for roc-auc).

**Comment by bbengfort** [comment]
The solution for this is to give visualizers a score method, which must be passed some y_test, y_pred combo - just like an estimator. That will update the visual model and store the scores internally.
