### ISSUE TITLE
CVScores

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#374]
Implement a visualizer that shows cross-validation scores as a bar chart along with the final score as an annotated horizontal line. 

We want to start moving toward better cross-validation and model selection. Create `yb.model_selection.CVScores` visualizer that extends `ModelVisualizer` and wraps an estimator. Accepts a `cv` and `scoring` params, similar to the ones exposed in [`sklearn.model_selection.cross_val_score`](http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_score.html). 

Output is a bar chart with the score of each split and a horizontal dotted annotation with the average score.

**Comment by bbengfort** [comment]
@pdamodaran See #377 -- currently creating the `model_selection` package; might be renamed cross validation.

**Comment by bbengfort** [comment]
@pdamodaran just a note that the `model_selection` package has been merged into develop.

**Comment by pdamodaran** [comment]
@bbengfort - noted - I have pulled in the new package and will add to it; what are your thoughts on calling the visualizer yb.model_selection.CVScoreVisualizer?

**Comment by pdamodaran** [comment]
ok - I will call it CVScore - it makes sense - it's not as wordy.
