### ISSUE TITLE
Poof() should return ax

### ISSUE THREAD

**Issue by NealHumphrey** [DistrictDataLabs/yellowbrick#375]
Make sure that ll visualizers return the `self.ax` when calling poof(). This is so that users can always get access to the ax, for example when working inside a function in a notebook. In addition it will encourage the behavior pattern of tweaking the plot if desired after poof(). We will be adjusting our documentation to use this form to also encourage this behavior:

```
ax = viz.poof()
```

This why this behavior pattern is useful:
https://stackoverflow.com/questions/47450804/yellowbrick-increasing-font-size-on-yellowbrick-generated-charts

**Comment by fdion** [comment]
As a workaround, once poof is called, you can access ax through:

`ax = viz.ax`

and fig:

`fig = viz.ax.get_figure()`

**Comment by bbengfort** [comment]
@fdion out of curiosity, we have a handle to the current ax via the visualizer, do you think we should also add one to the figure? I have to say, it's very rare that I'm doing anything with the figure, though we do have the ability to modify the size of the figure on the visualizer.

**Comment by fdion** [comment]
@bbengfort good question, Ben. The primary use is to save to file (pdf for latex), but since that's already covered by yellowbrick, and you currently don't have multi ax figures, probably not a high demand item :)

I return the figure in stemgraphic because I have grids of heatmaps or other plots and stuff like that. If you think faceting / multivariate might be a thing soon in Yellow Brick, then I'd say it would be useful to provide it.

Francois

**Comment by bbengfort** [comment]
Turns out we just included a VisualizerGrid that draws each visualizer on different axes; we're also thinking about trying to do a "flip book" style visualization with multiple figures. Guess I'll have to keep this in mind! Thanks!

**Comment by NealHumphrey** [comment]
Just a quick implementation note on the original ticket. To implement this:
Add the line `return self.ax` at the end of the base visualizer's poof() method in `yellowbrick/base.py`, and then  searching through all the visualizers in the code to make sure no one else overrides poof.

**Comment by michael-ziedalski** [comment]
fdion's way of getting `fig` is currently the only way for me to display `Rank2D` correlation plots. Not sure if this qualifies as a new bug, or is covered here somehow.

**Comment by bbengfort** [comment]
@michael-ziedalski - I'm a bit concerned that `poof` isn't working for you - what environment are you in? Are you still at PyData? Stop by the District Data Labs table and I'd be happy to take a look at it with you.
