### ISSUE TITLE
Draft gallery for the docs

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#38]
Add in some initial images for the gallery in the documentation

**Comment by bbengfort** [comment]
Maybe redo the poster as a webpage?

**Comment by rebeccabilbro** [comment]
I.e. redo webpage following the poster?

**Comment by bbengfort** [comment]
I just meant create a page, gallery.rst with some gallery.css that is similar to or inspired by the poster gallery.

**Comment by ralle123** [comment]
do I go ahead and link the images on the index to their pages, the same idea as in the gallery, you click and you go to the page that has that code?

**Comment by lwgray** [comment]
@ralle123 links back would be great and can be addressed in the next PR
