### ISSUE TITLE
Lots of failing tests - is this normal? "74 failed, 527 passed"

### ISSUE THREAD

**Issue by ianozsvald** [DistrictDataLabs/yellowbrick#389]
Having forked and cloned a copy of the current `develop` branch and, I think, setting things up correctly, if I run `pytest` in the root folder I end up with (this is on Linux + Anaconda):

```74 failed, 527 passed, 17 skipped, 8 xfailed, 1 xpassed, 1 warnings in 119.06 seconds```

I'm at a hackathon, I have some colleagues learning YellowBrick for the first time. I have another new environment on a colleague's machine and he gets (this is on Mac + Anaconda):
```47 failed, 553 passed, 18 skipped, 8 xfailed, 1 xpassed, 1 warnings in 140.51 seconds```

Using my own machine with Anaconda I then ditched the previous environment and made a vanilla Python 3.6 environment, used your 3 pip installs (using pip, not conda), and I had a slightly different output:
```
# conda create -n yellowbrick_ahl_hackathon2 python=3.6 # then 3*pip -r requirements...
74 failed, 382 passed, 162 skipped, 8 xfailed, 1 xpassed, 1 warnings in 113.69 seconds
```

Hmmm. Now with another colleague in my group with Mac+Anaconda on the first run he got:
```1 failed, 600 passed, 17 skipped, 4 xfailed, 5 xpassed, 1 warnings in 238.97 seconds ```
and on the second _and_ third run:
``` 1 failed, 455 passed, 162 skipped, 4 xfailed, 5 xpassed, 1 warnings in 132.37 seconds ```

I haven't tried running the tests for YellowBrick before so quite possibly I got something wrong, I figured it was worth checking before I delve deeper.

My machine - Linux, Anaconda, Python 3.6. All 3 requirements files installed as per https://github.com/DistrictDataLabs/yellowbrick/blob/develop/CONTRIBUTING.md

Do we expect all tests on `develop` to pass or is circa 47 or 74 failing the state of things?

**Comment by bbengfort** [comment]
Well, I'd expect all of the tests to pass, unless you're on a Windows machine -- which it sounds like you guys aren't. It is interesting that you're getting a variable number of tests passing so it might have something to do with the image comparison tests. The only environment we're currently certain of with the tests is the Mac+Python/Pip environment. 

Take a quick look in tests/actual_images -- if you see a lot of *-failed-diff.png files in there, then you can see how the tests are failing on the image comparisons. 

Since you're at a hackathon now; do you just want to jump into Slack to discuss it?

**Comment by ianozsvald** [comment]
Ok - which slack? Do I need an invite? ian@ianozsvald.com if so

**Comment by ianozsvald** [comment]
Looking at the output of `pytest` the vast majority of my errors look like:
```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/base.py:146: in assert_images_similar
    plt.savefig(self._actual_img_path())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def _actual_img_path(self, extension='.png'):
        """Determines the correct outpath for drawing a matplotlib image that
            corresponds to the unittest module path.
            """
        module_path, test_func_name = self._setup_imagetest()
>       module_path = os.path.join(*module_path)
E       TypeError: join() missing 1 required positional argument: 'a'

tests/base.py:79: TypeError
```

Any clues?

**Comment by bbengfort** [comment]
Actually, this is familiar, and I worked on fixing it in #386 -- it hasn't been merged yet since I haven't got all the tests working on Windows yet but perhaps we do an intermediate merge to get things moving forward? 

Are you running the tests from the main project directory?

**Comment by bbengfort** [comment]
@ianozsvald I just pushed a change that might fix this problem; would you mind pulling develop and seeing if the tests run correctly?

**Comment by ianozsvald** [comment]
Hey @bbengfort. I'm at PyDataLondon 2018, I used this bug as one of the examples in my "Make your first open source contribution" session yesterday. 

Brilliant success :-) Thank you.

```
============================================================================================ warnings summary =============================================================================================
tests/test_classifier/test_confusion_matrix.py::ConfusionMatrix visualizer tests::Test LabelEncoder as label encoder to define tick labels
  /home/ian/anaconda3/envs/yellowbrick_ahl_hackathon2/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
    if diff:

-- Docs: http://doc.pytest.org/en/latest/warnings.html
======== 465 passed, 162 skipped, 5 xfailed, 4 xpassed, 1 warnings in 131.31 seconds ======
```

Initially there was 1 error - I had to install the missing `nltk` data (easily done).

**Comment by bbengfort** [comment]
Glad to hear it worked out and that resolved things! Good note about nltk data as well - we have skipif nltk is not installed but should probably also xfail if nltk data is missing. I'll look into that!
