### ISSUE TITLE
Windows: Cannot cast array data from dtype('int64') to dtype('int32') 

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#392]
When running tests on AppVeyor (Windows) with x32 architecture, we're getting the following exception: `TypeError: Cannot cast array data from dtype('int64') to dtype('int32') according to the rule 'safe'` on many tests. 

See https://github.com/numpy/numpy/issues/4384 for more information. 

Current solution: I've simply commented out the x32 architectures in the AppVeyor config so we don't run the tests. Obviously this is less than ideal. 

However, because this bug occurs in the matplotlib internals, which then calls numpy internals there isn't a whole lot we can do except potentially wrap offending code in our own try/except block and attempt to handle it if it occurs. 

For now this issue is informational only in case it comes up again -- if the solution is sorted by a future version of numpy/matplotlib we can close this issue and provide tests on Windows x32 architectures again.

**Comment by rebeccabilbro** [comment]
Check to see if this is resolved by [NumPy 1.15](https://github.com/numpy/numpy/blob/master/doc/release/1.15.0-notes.rst)
