### ISSUE TITLE
xfail if nltk data has not been downloaded (move postag to contrib)

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#395]
Right now we have tests for `yellowbrick.text` that have an nltk depedency (the pos tag visualizer I believe, I don't think the others rely on it). We skip the tests if nltk is not installed, but we do not test if nltk data has been downloaded or is available. We should test this or wrap in a try/except and xfail to ensure that this doesn't fail tests for new users. 

Further, we could move nltk dependencies to the contrib directory, where we could more easily manage the test cases.

**Comment by sayali-sonawane** [comment]
Addressed the issue here:
https://github.com/DistrictDataLabs/yellowbrick/pull/428
