### ISSUE TITLE
Add Support for Other ML Libraries 

### ISSUE THREAD

**Issue by ndanielsen** [DistrictDataLabs/yellowbrick#397]
We currently have an experimental wrapper for StatsModels in : https://github.com/DistrictDataLabs/yellowbrick/pull/383

It would be fantastic if we can add visualizer support for Tensorflow, Keras and other classification selection visualizers using [ATM](https://github.com/HDI-Project/ATM).

**Comment by mitevpi** [comment]
I think there's some great low hanging fruit here in the short term, with even more exciting opportunities for the long term.

One thing I want to understand better - could you clarify how you were envisioning the integration of ATM? Are you thinking that the ATM would occur prior to visualization, or were you thinking that visualization is separate from any model tuning?

**Comment by bbengfort** [comment]
@mitevpi I think the initial idea with ATM was to create a multi-model comparison visualizer that could be generated either during tuning to show progress, or after tuning to demonstrate the scope of the autotuning and its findings (so both?). Because this visualization would be ATM-specific, and possibly require some interactivity/liveness we haven't really had the opportunity to do a deep-dive into what this might look like.

**Comment by rebeccabilbro** [comment]
CC: @carlomazzaferro

**Comment by mattharrison** [comment]
Was just trying to create a ResidualsPlot with a TensorFlow regression model today. Since the keras api has a ``fit`` method that is similar to sklearn, this should be really low hanging fruit.

**Comment by bbengfort** [comment]
@mattharrison did you get an exception when you tried to use the ResidualsPlot with the Keras model? I agree that it is low hanging fruit, and we've had good experience in the past with things just working, like XGBoost.

**Comment by rebeccabilbro** [comment]
See also #637!

**Comment by carlomazzaferro** [comment]
Just as a heads up, you can  make keras work with yellowbrick with minimal work, just like this:

```
from sklearn.datasets import make_regression
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from yellowbrick.regressor import ResidualsPlot
from sklearn.model_selection import train_test_split
from keras.wrappers.scikit_learn import  KerasRegressor
from sklearn.base import BaseEstimator, RegressorMixin
import tensorflow as tf


class KerasClf(BaseEstimator, RegressorMixin, KerasRegressor):

    def __init__(self, build_fn, **kwargs):
        super(KerasRegressor, self).__init__(build_fn,  **kwargs)


def keras_model():
    optimizer = tf.train.RMSPropOptimizer(0.001)
    model = Sequential()
    model.add(Dense(64, input_dim=2, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    model.compile(loss='mse', optimizer=optimizer,
                  metrics=['mae'])

    return model


if __name__ == '__main__':
    x, y = make_regression(n_features=2,  n_informative=1)
    X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
    kf = KerasClf(keras_model, epochs=150, batch_size=10, verbose=0)
    r = ResidualsPlot(kf)
    r.fit(X_train, y_train)  
    r.score(X_test, y_test)
    r.poof()

```
Note that you need to import the sklearn wrapper for keras, which unfortunately is not fully compliant with the sklearn api, and does not have the required attribute `_estimator_type`, hence the need to subclass `BaseEstimator` and `ClassifierMixin`

The same pattern holds for a classifier (tested it against the ROCAUC API),

**Comment by ndanielsen** [comment]
Thanks for sharing this!

**Comment by ndanielsen** [comment]
@carlomazzaferro that's an even better idea. I think that we can likely add a reference in the docs to the example notebooks.

**Comment by carlomazzaferro** [comment]
Cool! I'll work on getting some examples going and I'll do a pull request.

**Comment by ResidentMario** [comment]
I independently had the same thought and took a shot at mating `yellowbrick` to `keras` myself. Here's a write-up, which is currently in draft: ["Evaluation Keras neural network performance using Yellowbrick visualizations"](https://medium.com/@aleksey.bilogur/evaluating-keras-neural-network-performance-using-yellowbrick-visualizations-6fcea1b85a89).

I'd be happy to try and figure out if broad compatibility is possible for a PR, if that's still of interest. The tricky bit is that for most of the interesting plot types, like e.g. `ROCAUC`, `yellowbrick` calls (IIRC) `model.clone()`, which would be non-trivial to hack in, but might be possible.

**Comment by lwgray** [comment]
@ResidentMario Thank you for this awesome work.  I encourage you to open a PR.  However we won’t be able to review it for 2-3 weeks as we are on a short hiatus.  Here is a link to our contributor’s guide.    http://www.scikit-yb.org/en/latest/contributing.html

**Comment by ResidentMario** [comment]
FYI, the write-up is now published to the [Towards Data Science](https://towardsdatascience.com/evaluating-keras-neural-network-performance-using-yellowbrick-visualizations-ad65543f3174) mailer on Medium.

**Comment by bbengfort** [comment]
@ResidentMario such a great write up - thank you so much! We would be certainly interested in a contrib model for Keras if you ever want to pursue it!
