### ISSUE TITLE
Ensure that on import, default style loads

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#4]
Make sure that color palette is loaded in __init__.py so that our default styles always exist, but also can be overrode by the user.

**Comment by bbengfort** [comment]
See #3 - Yellowbrick needs its own, default style and color palette; similar to Seaborn. This style needs to be loaded on init, so it cannot be:

1. destructive (e.g. it must look for resources, and if it doesn't exist, don't quit) 
2. intensive (it must be lightweight and simple) 

To that end we also want a number of ways to configure Yellowbrick:

1. From an environment variable, `YELLOWBRICK_STYLE` and `YELLOWBRICK_CONTEXT` 
2. From a Jupyter configuration file
3. From something like [Confire](https://pypi.python.org/pypi/confire) for YAML based configuration.

**Comment by pvomelveny** [comment]
Actually this answers my question I asked in [Issue #3](https://waffle.io/DistrictDataLabs/yellowbrick/cards/573c8888228eadf800799397)

Do we want to mimic Seaborn and try to have our style/palette objects/functions be basically compatible? How Seaborn-y do we want to be?

**Comment by bbengfort** [comment]
I'd certainly like set_style and set_context to work in a similar way
(though they jump through a lot of hoops as far as I can tell) but I'd also
like us to have our own style based on Color Brewer. In terms of
compatibility, was there anything specific you were thinking of?
