### ISSUE TITLE
Text Visualizations

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#40]
Create a new module `text` and a base class `TextVisualizer` for performing text visualization.

**Comment by rebeccabilbro** [comment]
Think about how we visualize an entire corpus versus a specific document. In the base class, perhaps the default is to visualize the full corpus, but if you pass in a specific document, you can see the stats for that document.

**Comment by rebeccabilbro** [comment]
reminder to add this to the documentation, too:

- [ ]  in api/ create yellowbrick.text.rst
- [ ]  in api/ add yellowbrick.text to the modules.rst toc tree
- [ ]  in examples/ add text.rst to demonstrate examples of text visualizers in action

**Comment by rebeccabilbro** [comment]
also tests

**Comment by rebeccabilbro** [comment]
Preliminary `text` module and `TextVisualizer` base class implemented. Will start working on examples for the documentation and tests once we have  worked on #106 and #107.
