### ISSUE TITLE
Tutorial Vizualization image is out of date

### ISSUE THREAD

**Issue by rhender007** [DistrictDataLabs/yellowbrick#401]
[Short Description]

### Proposal/Issue
Tutorial image colors scheme image should be updated
http://www.scikit-yb.org/en/latest/tutorial.html

visual_model_selection(X, y, LinearSVC())
![image](https://user-images.githubusercontent.com/35784314/40004593-ff31166e-5763-11e8-806f-4155b7000adf.png)

visual_model_selection(X, y, NuSVC())
![image](https://user-images.githubusercontent.com/35784314/40004489-d121b76a-5763-11e8-9cf3-5bd39e22429e.png)

[Describe expected vs actual behavior or feature proposal]
Color scheme is from white to gold. New is more of a heat map shades of red

### Code Snippet

[Code to produce bug or example code for visualizer]

### Background

[Optional, add links and background on the feature or problem]

**Comment by lwgray** [comment]
Thank you for joining us for the Yellowbrick Sprint at PyCon Cleveland.   And also, thank you for submitting this issue.  Great Catch! 

Just to let you know....another of the Yellowbrick sprinters has submitted a pull request to resolve this issue #413 

Feel free to reach out to us and we hope you continue to contribute.

**Comment by bbengfort** [comment]
Fixed in bf5bd3f297ee6fdb589e457ecb0f954f085a5bf8

See updates in develop branch of the documentation:  http://www.scikit-yb.org/en/develop/tutorial.html
