### ISSUE TITLE
Doc error: on Visual Model Evaluation "as well color-coded heatmap" should be "as well as"

### ISSUE THREAD

**Issue by chrisfs** [DistrictDataLabs/yellowbrick#405]
In http://www.scikit-yb.org/en/latest/tutorial.html#visual-model-evaluation
the phrase "as well color-coded heatmap" should be "as well as color coded heatmap"

**Comment by lwgray** [comment]
@chrisfs Thank you for joining us for the Yellowbrick Sprint at PyCon Cleveland. And also, thank you for submitting this issue. Great Catch!

I would encourage you to submit a pull request since this is a simple fix.

Feel free to follow-up on this issue and we hope you continue to contribute.

**Comment by chrisfs** [comment]
I think I submitted a pull request. First time doing it, so I hope it worked.

**Comment by lwgray** [comment]
I merged it... Great Job @chrisfs
