### ISSUE TITLE
docs quick start walkthrough is missing r-squared explanation

### ISSUE THREAD

**Issue by leah-kstra** [DistrictDataLabs/yellowbrick#406]
In the quick start walkthrough, at the end of the ResidualsPlot explanation, one sentence starts "Because our coefficient of determination for this model is 0.328..." but there is no explanation of where this value comes from. 

### Proposal/Issue

It'd be helpful to include another section here which explains how to find the r-squared value before moving onto the next section. (For instance, walking the reader through the exercise creating the PredictionError graph at this point in the walkthrough would help, though it might still make the most sense to keep it at the end.)  Additionally, a useful sentence to add would explain to the reader why their r-squared value might not match the value in the walkthrough due to the randomization in the train/test split. 

### Background

http://www.scikit-yb.org/en/latest/quickstart.html#using-yellowbrick

**Comment by mitevpi** [comment]
I think the scoring is happening in the earlier code block, but I agree that it can be clearer where the value is coming from, and why we're calculating it/making decisions based off of it. 

R-squared origin: https://github.com/DistrictDataLabs/yellowbrick/blob/develop/docs/quickstart.rst/L#176

I wouldn't mind trying to revise the section for a little more clarity - if anyone has other suggestions, please let me know.

**Comment by bbengfort** [comment]
@mitevpi this might be as simple as adding a comment to the code block you identified, but feel free to take this one on!
