### ISSUE TITLE
Release Version 0.3

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#41]
See the Version 0.3 release milestone for more details.

**Comment by rebeccabilbro** [comment]
Closing this as @bbengfort completed this card yesterday. Time to scope out the next milestone?

**Comment by bbengfort** [comment]
@rebeccabilbro There may be a minor issue - still need to test to make sure the push to PyPI worked and that we can pip install it with ease. Saw some stuff that raised some red flags for me.

**Comment by bbengfort** [comment]
Oh, also we have to write the release notes:

https://github.com/DistrictDataLabs/yellowbrick/releases

Didn't quite get there yesterday; sorry.

**Comment by rebeccabilbro** [comment]
@bbengfort gotcha.

Issue complete when: 
 - [ ] pip installation issues are resolved 
 - [ ] release notes are written up

Let me know when you want to tag up to work on the release notes and plan the next milestone

**Comment by bbengfort** [comment]
@rebeccabilbro today and tomorrow are tough - I can do early morning Wednesday if you'd like or Thursday or Friday.

**Comment by rebeccabilbro** [comment]
@bbengfort sounds good

**Comment by bbengfort** [comment]
@rebeccabilbro - ok some folks were having trouble with this, so I just fixed the pip issue during my lunch break. However, I'm going to leave the release notes for when we can catch up; just so we're on the same page and can start the conversation. 

Note, that I injected a hotfix release: 0.3.1a2 as a result of this fix. Yellowbrick should be pip installable now.

**Comment by rebeccabilbro** [comment]
Can confirm that 
```bash 
pip install yellowbrick
``` 
works now!

**Comment by bbengfort** [comment]
For python 2 and 3!

Ben
