### ISSUE TITLE
Unable to parse meta.json files from  the mushroom and bikeshare datasets

### ISSUE THREAD

**Issue by RaulPL** [DistrictDataLabs/yellowbrick#416]
Hi,

I downloaded all the data defined in this script https://github.com/DistrictDataLabs/yellowbrick/blob/develop/examples/download.py. Most of them have a meta.json file inside their folder but for two of them (mushroom and bikeshare datasets) I have a JSONDecodeError exception when I try to parse it with the json module of the standard library. 

### Code

This is an example code that can reproduce the error.
 ```python
import json

with open('data/bikeshare/meta.json') as file:
    meta_data = json.load(file)
meta_data
```

**Comment by navarretedaniel** [comment]
I took a look at this parsing issue and think I may have an idea on how one might approach this.

I warn that it likely won't be an elegant solution, but if anything, it might be a start for more advanced Python coders.

**Comment by lwgray** [comment]
@navarretdaniel we’re glad you’re  going to work on this and we’re looking forward to seeing what you put together.

**Comment by bbengfort** [comment]
@navarretedaniel our new datasets mechanism resolves these issues, but thank you so much for your help!

**Comment by bbengfort** [comment]
@RaulPL the datasets have been completely overhauled and the meta.json is now well formed for both of these datasets; thank you for contributing this issue to yellowbrick!
