### ISSUE TITLE
Improving Quick Start Documentation

### ISSUE THREAD

**Issue by muthukannan91** [DistrictDataLabs/yellowbrick#425]
**Quick Start Documentation**
In the walk through part of the documentation, correlation between actual temperature and feels like temperature were analysed. The author mentioned that it was intuitive to prioritize the feature 'feels like' over 'temp'. But for the reader, it is bit hard to understand  the reason behind author's decision on feature selection from the plot.

Expectation:

 Could add some more details on why 'feels like' is better than 'temp' when we train machine learning models.

### Background

https://www.datascience.com/blog/introduction-to-correlation-learn-data-science-tutorials

https://newonlinecourses.science.psu.edu/stat501/node/346/

**Comment by bbengfort** [comment]
Thank you for your suggestion - I'm certainly happy to read a draft of your suggestions for modifying the quickstart to include this detail.

**Comment by mitevpi** [comment]
I think the documentation is on the right track. When the JointPlotVisualizer is introduced, it is introduced as a way for us to make decisions for our data based on these kinds of relationships. My understanding was that the JointPlotVisualizer makes those "intuitions" present.

Current Doc:
> This plot is very interesting; first there appear to be some outliers in the dataset, where feelslike is approximately equal to 0.25. **These instances may need to be manually removed in order to improve the quality of the final model because they could represent data input errors**. **Secondly, we can see that more extreme temperatures create an exaggerated effect in perceived temperature; the colder it is, the colder people are likely to believe it to be, and the warmer it is, the warmer it appears to be.** Moderate temperatures feel like they do. This gives us the intuition that feelslike may be a better feature than temp, and if it is causing problems in our regression analysis, we should probably remove the temp variable in favor of feels like.

It could even be slightly revised for some extra clarity:

> This plot is very interesting because there appear to be some outliers in the dataset. These instances may need to be manually removed in order to improve the quality of the final model because they may represent data input errors and potentially train the model on a skewed dataset, leading to unreliable model predictions. The first instance of outliers occurs in the temp data where the feelslike value is approximately equal to 0.25 - showing a horizontal line of data, likely created by input error.
> 
> We can also see that more extreme temperatures create an exaggerated effect in perceived temperature; the colder it is, the colder people are likely to believe it to be, and the warmer it is, the warmer it appears to be, with moderate temperatures generally having little effect on individual perception of comfort. This gives us a clue that feelslike may be a better feature than temp - providing a smoother dataset, with less risk of outliers or errors.
> 
> We can ultimately confirm the assumption by training our model on either value, and scoring the results. In the meantime, we will use the feelslike value due to the absence of outliers and input error. If the temp value is indeed less reliable, we should remove the temp variable in favor of feelslike.

**Comment by bbengfort** [comment]
@mitevpi the edits look great if you want to create a PR for it; agreed about added more academic resources here, am happy to look at expanding the documentation with that kind of content in the future.

**Comment by mitevpi** [comment]
Thanks for the review @bbengfort ! I'll be cleaning up the grammar/language and doing just that. Looking forward to getting more familiar and involved in the project.
