### ISSUE TITLE
update docs to reflect new YB datasets module

### ISSUE THREAD

**Issue by wagner2010** [DistrictDataLabs/yellowbrick#441]
Update the documentation to leverage new yellowbrick.datasets & create documentation on metadata on example datasets such as number of samples, number of features, target/class.
For example, [sklearn.datasets.load_digits](http://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_digits.html).

Note: reminder to also update 
 - [x] the [corpus loading docs](https://www.scikit-yb.org/en/develop/api/text/corpus.html)
 - [x] contributor guide with use of datasets/fixtures in tests (both random and real)

**Comment by mitevpi** [comment]
I can take a look at this as I'm continuing on my documentation tear. Do we want to point entirely to the yellowbrick.datasets module or do we still want some instances where we acknowledge downloading manually/from third party sources?

https://github.com/DistrictDataLabs/yellowbrick/blob/1e04216661ac623686b0ccde55df448d70d8de12/docs/api/datasets.rst#L10-L21

**Comment by bbengfort** [comment]
@mitevpi that would be great! I think whenever possible we want to use the new `yellowbrick.datasets` module; if you run across a place where we might want to acknowledge a source or manually download, let me know and I'm happy to review it.
