### ISSUE TITLE
Review and categorize issues raised in residentmario's kaggle notebooks

### ISSUE THREAD

**Issue by ndanielsen** [DistrictDataLabs/yellowbrick#443]
We need to go through the following kaggle kernels and review @ResidentMario's comments and suggestions for improvements for our visualizers. 

https://www.kaggle.com/residentmario/ml-visualization-with-yellowbrick-1
https://www.kaggle.com/residentmario/ml-visualization-with-yellowbrick-2
https://www.kaggle.com/residentmario/ml-visualization-with-yellowbrick-3

As a note, we already several of the suggestions for improvements in our issues but likely there are nuances to some of those issues that we can better address in an upcoming release. We should capture them.

**Comment by ndanielsen** [comment]
Also @ResidentMario thank you for taking the time to go through yellowbrick and publishing them up kaggle! Your comments and suggestions for how to improve the library are very helpful to us and they will be definitely given a close look!

If you have any other suggestions / ideas for new visualizers or how to improve existing ones, I'd like to welcome you to let us know! 

We also just released the v0.7 last night and there are several new features and enhancements that you might find interesting!

Thanks again for giving our library a look!

**Comment by ResidentMario** [comment]
I do not know how you found those notebooks, but now that you have I'm flattered that you think they're actionable. :smile:

I will see if I can't go through it and write this up as specific issues.

**Comment by bbengfort** [comment]
@ResidentMario I definitely appreciated the notebooks, and I think we need more like it - like you said we all have our workflows and tend to use cobbled together matplotlib scripts. Yellowbrick is in a phase right now where we're trying to capture some general cases that cover a lot of our own professional workflow, but until we have users like you writing about what they need, we don't really have a basis to prioritize that generalization. I very much liked how you wrote about the visualizations produced and how to interpret them - it's incredibly valuable both to us figuring out what to implement next, but also new users who want to pick up visual steering tools.

**Comment by ResidentMario** [comment]
Unfortunately the original dataset got deleted, and the notebook got rerun as part of the deletion clearance process. So I'm not sure these notebooks are very actionable anymore unfortunately!

**Comment by bbengfort** [comment]
@ResidentMario ok, thank you for letting us know -- that's too bad that the dataset was removed. If you do any other notebooks with YB please let us know! @ndanielsen because this issue is now a year old and because the datasets have been deleted I propose that we close it. Let me know if you'd prefer to leave it open.
