### ISSUE TITLE
Documentation README

### ISSUE THREAD

**Issue by rwhitt2049** [DistrictDataLabs/yellowbrick#450]
### Proposal

Develop a documentation contribution guideline modeled after [pandas](https://github.com/pandas-dev/pandas/blob/master/doc/README.rst)

Documentation is often seen as a safe place for new contributors to start, but Sphinx and reStructured text can be intimidating at first. The goal of the readme would be to creating an inviting document that gives a high level of how to build the docs, where to find rst documentation, how and when to use the `plot::` directive, and give some direction towards some concrete issues to tackle (ie the novice and doc tags in the issue list).

Relates to issues #353 , #354  and PR #446

**Comment by bbengfort** [comment]
Thanks for adding this issue - I think it's especially important after #354

**Comment by bbengfort** [comment]
This is an excellent proposal and I think would be very valuable to our contributors. After #720 we think this should work as follows:

- Create a `docs/README.md` that has limited instructions about how to build docs and install requirements, then points to the documentation for further instructions.
- Create a section in the contributor's guide for documentation that discusses all of the above. 
- Perhaps also do the same for tests?
