### ISSUE TITLE
Add legend option to PCA visualizer 

### ISSUE THREAD

**Issue by mattharrison** [DistrictDataLabs/yellowbrick#458]
The ``PCADecomposition`` allows us to set the color of the different entries. It would be cool to add a legend to describe the coloring.

### Proposal/Issue

The ``DataVisualizer`` class supports creating legends, but it requires that ``y`` is passed into ``.fit``. Admittedly, PCA doesn't require labels, but sometimes you have them. I would love to label the colorings in PCA. Could the constructor accept a ``legend`` parameter that is similar to the ``color`` parameter, but accepts labels?

**Comment by bbengfort** [comment]
I think this is a great idea, and we can absolutely do this the same way that we do in the `DataVisualizer`, with the `y` attribute. Probably this can be done similarly to the manifold visualizers, which allow both heatmap colors for regression and discrete colors for classification and coloring.

**Comment by rebeccabilbro** [comment]
Note, we now have a `manual_legend` utility in `yellowbrick.draw`, which could be useful here. See #564 for more discussion.

**Comment by Naba7** [comment]
Can I be assigned this issue?

**Comment by rebeccabilbro** [comment]
Hello @Naba7 &mdash; as explained in response to your notes on #738, #677, and #476, we do not "assign" issues or reserve issues for contributors. Anyone is welcome to submit a PR for a feature or bugfix they work on. 

However, given that you already have one PR open that still needs to be completed (#755), have started working on #615, and are new to working on Yellowbrick and still getting to know our API, we would *really* appreciate if you would focus on getting those first PRs across the finish line before starting anything new. 

We appreciate your enthusiasm about contributing to Yellowbrick. One of the most important lessons to learn is that open source is a marathon, not a sprint, so we hope you can be patient and enjoy the journey &mdash; we promise Yellowbrick isn't going away!

**Comment by bbengfort** [comment]
Feature has been added in #874
