### ISSUE TITLE
Finish up CVScores visualizer

### ISSUE THREAD

**Issue by pdamodaran** [DistrictDataLabs/yellowbrick#464]
CVScores is a new visualizer under yellowbrick/model_selection. Here are a couple things left to do and small enhancements:

 - [x] Add documentation ([done](http://www.scikit-yb.org/en/develop/api/model_selection/cv.html))
 - [x] Add test cases
 - [x] Add a legend that labels the average cvscore dotted line with the numeric value of `self.cv_scores_mean_`
 - [x] Adjust the ylim so that `CVScores` plots will be more easily comparable across different models.

**Comment by rebeccabilbro** [comment]
Closed with #559
