### ISSUE TITLE
ROCAUC function

### ISSUE THREAD

**Issue by poppingcode** [DistrictDataLabs/yellowbrick#465]
**Describe the issue**
A clear and concise description of what the issue is.
when i use ROCAUC function,can i load a resnet-50 model?
for example : 
    model =resnet。。。。
    viz = ROCAUC(model)

I want it to extend to other models

@DistrictDataLabs/team-oz-maintainers

**Comment by bbengfort** [comment]
@poppingcode if you're referring to a Keras or TensorFlow resnet-50 model, then I'll say that it's possible with a little bit of glue but still untested - although there is an open issue #397 to add contrib support for these types of estimators. 

If you'd like to try to implement a non-scikit-learn model with yellowbrick, the key is to wrap it in an estimator, with approximately the following interface:

```
from sklearn.base import BaseEstimator 

class WrapperEstimator(BaseEstimator):
    
    def fit(self, X, y):
        return self

    def predict(self, X):
        return yhat 

    def score(self, X, y):
        return score 
```

Some models additionally need a `predict_proba` method; I'm not sure if ROC/AUC is one of those. 

You can see an example of this for StatsModels in [yellowbrick.contrib.statsmodels](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/contrib/statsmodels/base.py#L25). 

Does that help answer the question?
