### ISSUE TITLE
Visual Pipeline

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#47]
Create a visual pipeline class that extends the scikit-learn pipeline class to ensure that visualizers get called correctly.

**Comment by rebeccabilbro** [comment]
Needs to know how to handle `draw` and appropriately allocate resources in the pipeline. There are a number of interesting utilities in Scikit-learn and from others (Tom Augspurger), e.g. Identify model from class.  Most we'll get for free by extending the `Pipeline` class but need to make sure none will interfere. `draw` will be important, also `get_estimator` and `get_score`.

**Comment by bbengfort** [comment]
Let's at least get a prototype going before the sprints.
