### ISSUE TITLE
Joint Plot Viz has messed up (overlapping labels on) axes

### ISSUE THREAD

**Issue by mattharrison** [DistrictDataLabs/yellowbrick#474]
**Describe the bug**

If you look at the x and y axis on http://www.scikit-yb.org/en/latest/api/features/scatter.html#joint-plot-visualization you will see that the labels are overlapping.

**To Reproduce**

Create a joint plot as shown in the docs

**Expected behavior**

Labels on axes should be clear.

**Desktop (please complete the following information):**
 - OS: macOS
 - Python Version 3.6.4
 - Yellowbrick Version 0.8

**Comment by bbengfort** [comment]
@mattharrison thanks for letting us know - we'll take a look at it as soon as we can!
