### ISSUE TITLE
Add alpha support for scatter plots

### ISSUE THREAD

**Issue by mattharrison** [DistrictDataLabs/yellowbrick#475]
**Describe the solution you'd like**
When I'm plotting scatter plots (such as PCA), oftentimes there is a bunch of data. By using the ``alpha`` parameter on matplotlib (also available through the pandas plotting interface), it allows you to discern the data and amount of overlapping.

**Is your feature request related to a problem? Please describe.**
In general, I think an ``alpha`` parameter to any scatter plot visualizations (``PCADecomposition``) would be awesome. It would also be inline with what pandas plotting provides.

**Examples**
Seaborn scatter plots come with a slight alpha applied. But you can use ``scatter_kws={'alpha':0.3}`` to set it. In pandas or matplotlib you just pass ``alpha=0.3``.

Jake's book also has alpha turned on when plotting scatter plots. See https://jakevdp.github.io/PythonDataScienceHandbook/05.09-principal-component-analysis.html

**Comment by rebeccabilbro** [comment]
@bbengfort oh that's an interesting alternative to deprecating ScatterVisualizer altogether in v0.8! While making it a mixin and refactoring the other plots to inherit the scatter-draw behavior might take a bit more work, I imagine it might make things a bit easier down the line as we introduce more types of visualizers. I'm game to help if we decide to go this way.

**Comment by ndanielsen** [comment]
@bbengfort I think that the ScatterVisualizer makes the most sense as a base class. I agree that it is initially more work but would likely makes things simpler down the road

**Comment by lwgray** [comment]
@bbengfort Nothing more to add...I agree with @rebeccabilbro and @ndanielsen

**Comment by mattharrison** [comment]
For ``alpha=`` vs ``scatter_kws``, I think it depends on whether you want to tie the implementation to matplotlib. The former is generic, the latter indicates (to me at least) that these are the parameters that will be passed into matplotlib.

**Comment by bbengfort** [comment]
Ok, I'll get started turning the `ScatterVisualizer` into a mixin - thanks for weighing in everyone!

**Comment by rebeccabilbro** [comment]
I was doing a bit of experimentation (see [notebook here](https://github.com/rebeccabilbro/yellowbrick/blob/scatter-bug/examples/rebeccabilbro/scatter_alpha.ipynb)) with `ScatterVisualizer`, and it would certainly be easy enough to add an `alpha` param. But, given that we're thinking of turning `ScatterVisualizer` into a mixin, it might be best to just do it there. 

One thing I discovered though, is that the alpha param doesn't just impact the translucency of the plotted data, it *also* affects the translucency of the color labels in the plot's legend, making it hard to read. 

![image](https://user-images.githubusercontent.com/8760385/43677254-df4ca094-97cc-11e8-8086-28417ddbdab2.png)

Note this also seems to be true for the other YB visualizers that accept an `alpha`:

![image](https://user-images.githubusercontent.com/8760385/43677258-ffb2a5d6-97cc-11e8-9331-1461d97894fd.png)


Maybe something we should be dealing with a bit higher up in the class hierarchy.

**Comment by bbengfort** [comment]
@rebeccabilbro good catch with the legend transparency, that is definitely an important consideration! Here is the add legend function that I've been using in several places; it adds color circles with a label to the legend. Unfortunately, this implementation can't really handle lines, but it should assist with the transparency issue in scatter plots:

```python 
from matplotlib import patches

def add_manual_legend(colors, labels):
    """
    Create a manual scatter plot legend by specifying a list of colors and labels. 
    """
    handles = [
        patches.Patch(color=color, label=label)
        for color, label in zip(colors, labels)
    ]
    self.ax.legend(handles=handles)
```

**Comment by bbengfort** [comment]
#554 adds `alpha` to the `yellowbrick.contrib.ScatterVisualizer`. Need to:

- [ ] open issue for scatter plot mixin 
- [ ] open issue for non alpha legend mechanism
- [ ] open issue for other scatter visualizers that could use alpha params.
