### ISSUE TITLE
Convert ROCAUC and ClassifierReport

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#48]
Transform `ClassifierReport` and `ROCAUC` into `EstimatorScore` class that knows how to handle them

**Comment by rebeccabilbro** [comment]
Preliminary implementation complete.

ClassifierScoreVisualizers:
 - [ClassificationReport](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/classifier.py#L48)
 - [ROCAUC](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/classifier.py#L112)

**Comment by bbengfort** [comment]
Same with #49 - my comments on this code is in #44 (they apply to both the regressors and the classifiers) so I think this issue is done! Nice work!

**Comment by rebeccabilbro** [comment]
Marking as complete, with the understanding that issue #62 will resolve the fig/ax hook question that came up in the design of the `ScoreVisualizer` class.
