### ISSUE TITLE
[feature request] better visualization method

### ISSUE THREAD

**Issue by stsievert** [DistrictDataLabs/yellowbrick#482]
**Describe the solution you'd like**
Code for data transformations and visualization are inter-twined. It'd be nice to be able to change the encodings at will (e.g., change `metric` encoding from color to y-axis).

For example, the backend function to visualize the results from a grid search are hard-coded to take in two dimensions ([source][1]), and codes the color as the metric, and then use `pcolor` to produce a graph. Could this be changed?

More concretely, yellowbrick currently produces (something like) the graph below for grid searches:

<img src="https://user-images.githubusercontent.com/1320475/41515772-7afda184-72a0-11e8-8ca3-e43ca9b7c51a.png" width="431px" />

It codes two model parameters as the `x` and `y` axes, and `metric` as the color. What if instead I wanted to view the y-axis as `metric` and the color as `param2`? I *could* do this by passing different values for `metric` and `y_value`, but it would still be passed to `plt.pcolor`, not what I want.

That is, I would like something like

<img width="431" alt="screen shot 2018-06-17 at 9 36 27 pm" src="https://user-images.githubusercontent.com/1320475/41515773-7b12e8d2-72a0-11e8-8d96-9a543e9eb861.png">

Turns out this relationship is pretty simple: `metric = param1**2 + param2`. That is not immediately obvious from the first graph but is from the second.

Thank you for this library. More introspection into how machine learning works is appreciated, especially because machine learning is only as good as the features it's given. I am filing this issue because I want to see this library improve, and because I listened the Podcast.__init__ episode that features yellowbrick.
 

[1]:https://github.com/DistrictDataLabs/yellowbrick/blob/a89633ee2f936c5cf35a7eb06a501e6e87b8b23b/yellowbrick/gridsearch/base.py#L21

**Comment by stsievert** [comment]
I think I would recommend the library Altair for this feature request: https://altair-viz.github.io/. This is a *declarative* API, not an imperative API like matplotlib. It requires specification of what to see, not how to draw what you want to see. This could result in more flexibility and easier development.

For example, the second plot shown above was generated by three lines:

``` python
import altair as alt
alt.Chart(df).mark_line().encode(
    x='param1', y='metric', color='param2')
```

It would also result in easier testing: altair plots contain the data, which means they can be coded as JSON. Unfortunately, the separation of generating and specifying visualization means there might be a performance hit.

**Comment by stsievert** [comment]
Unfortunately, there's no matplotlib backend for altair. It looks like NumFocus is sponsoring two students to work on the matplotlib backend this summer: https://www.numfocus.org/programs/john-hunter-technology-fellowship and https://www.numfocus.org/blog/2018-john-hunter-matplotlib-summer-fellows

**Comment by rebeccabilbro** [comment]
Going to close this issue for now due to the current limitations re: Altair/Matplotlib, but let us know if you hear anything more about the NumFocus-sponsored development!
