### ISSUE TITLE
Convert prediction error and regression error plots into estimator scores

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#49]
Convert prediction error and regression error plots into `EstimatorScores`

**Comment by rebeccabilbro** [comment]
Preliminary implementation complete.

RegressionScoreVisualizers:
 - [PredictionError](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/regressor.py#L44)
 - [ResidualsPlot](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/regressor.py#L93)

**Comment by bbengfort** [comment]
These also look great! My comments for #

**Comment by rebeccabilbro** [comment]
Marking as complete, with the understanding that issue #62 will resolve the fig/ax hook question that came up in the design of the `ScoreVisualizer` class.
