### ISSUE TITLE
Hobbies corpus unicode decoding error on Windows x64 (AppVeyor)

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#491]
**Describe the bug**

There appears to be a unicode decoding error on Python 3 in Windows when loading the hobbies corpus. This was observed in AppVeyor builds that use the hobbies corpus during testing such as #489 but is probably true for any Windows machine. 

**To Reproduce**

```python
from tests.dataset import DatasetMixin

datasets = DatasetMixin() 
hobbies = datasets.load_data('hobbies')
```

**Expected behavior**

We should either remove the unicode encoding from the corpus dataset (unless we beleive that this is a positive feature for the tests ... though currently the encoding of the data does not matter to visualizer performance) or we should fix the datasets to correctly decode the data from disk. 

**Traceback**

```
tests\dataset.py:197: in load_data
    return DatasetMixin.load_corpus(name, fixtures)
tests\dataset.py:230: in load_corpus
    data.append(f.read())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
self = <encodings.cp1252.IncrementalDecoder object at 0x0000001C91A0D828>
input = b'The Lonely City\xc2\xa0bristles with heart-piercing wisdom. Loneliness, according to Laing, feels \xe2\x80\x9clike b...an read The\xc2\xa0Rumpus\xe2\x80\x99s review of\xc2\xa0The Lonely City\xc2\xa0right\xc2\xa0here.)\n\nRelated Posts:\n'
final = True
    def decode(self, input, final=False):
>       return codecs.charmap_decode(input,self.errors,decoding_table)[0]
E       UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 164: character maps to <undefined>
C:\Python36-x64\lib\encodings\cp1252.py:23: UnicodeDecodeError
```

**Desktop (please complete the following information):**
 - OS: `AppVeyor Winx64`
 - Python Version `PYTHON=C:\Python36-x64, PYTHON_VERSION=3.6.4, PYTHON_ARCH=64`
 - Yellowbrick Version `develop`

**Additional context**

See [AppVeyor Build 0.7.300](https://ci.appveyor.com/project/districtdatalabs/yellowbrick/build/0.7.300/job/wy9k5x9linoc6tf8) - note that tests _passed_ in `
Environment: PYTHON=C:\Python27-x64, PYTHON_VERSION=2.7.14, PYTHON_ARCH=64`

**Comment by ndanielsen** [comment]
I believe that I resolved this issue in : https://github.com/DistrictDataLabs/yellowbrick/pull/501/commits/11dc0ec4e859b05025b5dfa0959dbf53ceb77259

**Comment by bbengfort** [comment]
@ndanielsen the following tests are marked as xfail due to this issue:

- [ ] [tests.test_text.test_tsne L71](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/tests/test_text/test_tsne.py#L71)
- [ ] [tests.test_text.test_dispersion L33](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/tests/test_text/test_dispersion.py#L33)

Do you want me to uncomment these tests to check the fix, or would you rather do it?

**Comment by bbengfort** [comment]
Also, if you don't mind - I'm going to reopen the issue until the tests are uncommented (just so I don't forget to do that).
