### ISSUE TITLE
Update Model Selection Tutorial example to use Yellowbrick datasets/download module

### ISSUE THREAD

**Issue by joelvanveluwen** [DistrictDataLabs/yellowbrick#500]
The model selection tutorial datasets do not currently the Yellowbrick hosted and modified datasets. For consistency, examples should leverage the core sets as per the 'example datasets' documentation http://www.scikit-yb.org/en/latest/api/datasets.html. 

- [ ] Modify docs on model selection tutorial to align with the example datasets documentation

**Comment by ndanielsen** [comment]
related to this documentation issue: https://github.com/DistrictDataLabs/yellowbrick/issues/441

**Comment by ndanielsen** [comment]
This is a duplicate issue of https://github.com/DistrictDataLabs/yellowbrick/issues/424

Not going to close either issue, but @joelvanveluwen please note that I reworked the datasets api in https://github.com/DistrictDataLabs/yellowbrick/pull/501
