### ISSUE TITLE
Some manifold algorithms do not have transform attribute in sklearn.

### ISSUE THREAD

**Issue by zjpoh** [DistrictDataLabs/yellowbrick#504]
**Describe the bug**
Manifold plotting with `manifold=mds` produces correct plot but raises no transform attribute error.

**To Reproduce**

```python
%matplotlib inline
import numpy as np
from yellowbrick.features.manifold import Manifold

y = np.linspace(-1, 1, 100)[:, ]
X = y[:, None] + np.random.random((100, 10))
viz = Manifold(manifold='mds')
viz.fit_transform(X, y)
viz.poof()
```

**Expected behavior**
No transform attribute error.

**Traceback**

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-7f7457a2faab> in <module>()
      6 X = y[:, None] + np.random.random((100, 10))
      7 viz = Manifold(manifold='mds')
----> 8 viz.fit_transform(X, y)
      9 viz.poof()

~/anaconda3/lib/python3.6/site-packages/sklearn/base.py in fit_transform(self, X, y, **fit_params)
    518         else:
    519             # fit method of arity 2 (supervised transformation)
--> 520             return self.fit(X, y, **fit_params).transform(X)
    521 
    522 

~/anaconda3/lib/python3.6/site-packages/yellowbrick/features/manifold.py in transform(self, X)
    328             Returns the 2-dimensional embedding of the instances.
    329         """
--> 330         return self.manifold.transform(X)
    331 
    332     def draw(self, X, y=None):

AttributeError: 'MDS' object has no attribute 'transform'
```

**Desktop (please complete the following information):**
 - OS: macOS
 - Python 3.6
 - Yellowbrick Version 0.8

**Additional context**
Similarly error for `manifold='spectral'` and `manifold='tsne'`.

**Proposed solution**
Remove the [transform](https://github.com/DistrictDataLabs/yellowbrick/blob/3b3eb63c32bfc86145ec9e130e3a79c9ffc2bec0/yellowbrick/features/manifold.py#L316) method from `yellowbrick.features.manifold` unless it is being used somewhere else.

**Comment by bbengfort** [comment]
@zjpoh thanks for the bug report! I think this should be an easy fix; I'm going to leave `transform` in, but will catch `AttributeErrors` in the implementation; then I'll implement a manifold-specific `fit_transform` method rather than relying on the default implementation that's part of `TransformerMixin`. 

Update to follow shortly!
