### ISSUE TITLE
Html Report Generation

### ISSUE THREAD

**Issue by ndanielsen** [DistrictDataLabs/yellowbrick#506]
**Describe the solution you'd like**
While looking around at library with a similar focus, I noticed that `sklearn-evaluation` has a method for generating reports in html.

https://github.com/edublancas/sklearn-evaluation#generating-reports

This could be a valuable and time saving convenience method for our users that could live in `contrib`

**Examples**

Here's the API that `sklearn-evaluation` uses:

```
 
 template = '''
            # Report
            {estimator_type}
            {date}
            {confusion_matrix}
            {roc}
            {precision_recall}
            '''

ce.generate_report(template, path='report.html')
```

It generates a report like this: http://htmlpreview.github.com/?https://github.com/edublancas/sklearn-model-evaluation/blob/master/examples/report.html

**Comment by bbengfort** [comment]
Interesting, I've never heard of the mistune templating language, but I do think HTML/Markdown reports are a very good idea for the contrib module. 

@edublancas - we would love it if you had thoughts/feedback on Yellowbrick or if you wanted to contribute here.

**Comment by edublancas** [comment]
Hi there,

@bbengfort mistune is just a python library to convert markdown to html

I recently started working on sklearn-evaluation again, I am still brainstorming ideas on which is the best API for generating reports. I re-factored the old code (which was kind of messy) with a new workflow, there is not much documentation yet but I'll briefly explain the logic:

Reports are now generated here: https://github.com/edublancas/sklearn-evaluation/blob/d8606da83c9191d18e3603b595d249c84a5b459d/src/sklearn_evaluation/evaluator.py#L157

Which use this module under the hood: https://github.com/edublancas/sklearn-evaluation/tree/master/src/sklearn_evaluation/report

I have a `ClassifierEvaluator` that abstracts plot creation, so once you initialize it you can do things like `evaluator.confusion_matrix()`, these plotting methods return matplotlib axes objects, which can be further customized at the user's needs.

From the user's side, they only have to provide either a markdown or html template (one provided by default), something like this:

```markdown
# header

confusion matrix is below:

{evaluator.confusion_matrix()}
```

As you can see, the call looks exactly the same `evaluator.confusion_matrix()`. I am now using jinja as templating language, which gives the user a powerful framework for templating.

Let me know what you think about this approach, I'd love feedback on this as I'm still thinking about ways to improve this.

Given my time constraints, I don't think I'd be able to directly contribute to yellowbrick but collaboration with you guys would be great! I think both libraries can co-exist and borrow good things from each other.

**Comment by rebeccabilbro** [comment]
Going to archive this one for now since the conversation has gone a bit stale; happy to reopen if someone has bandwidth and interest!
