### ISSUE TITLE
Feature Correlation to Dependent Variable Visualizer

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#508]
**Describe the solution you'd like**

This issue extends #334 with details about bullet point 3: "plot feature/target correlations". 

As seen in [Model comparison using a noisy dataset -1](https://medium.com/@harsha.g1/model-comparison-using-a-noisy-dataset-1-db20f62c5126), it is useful to compare the pairwise correlation between the features and the dependent variable or target as a bar chart; similar to Rank1D and Rank2D, except that this is for the target only. 

![1_tfldsf_iujqgandsy6b39a](https://user-images.githubusercontent.com/745966/42943280-49a0c4c4-8b30-11e8-9331-d8e1d9f4d6c7.png)

Once the target package has been created, create a visualizer, `yellowbrick.target.FeatureCorrelation` that creates this bar chart by fitting `X` and `y`. Write documentation that links this visualizer to the `JointPlot` visualizer. 

Include the following correlations:

- Pearson 
- [Mutual Information](http://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.mutual_info_classif.html#sklearn.feature_selection.mutual_info_classif)

**Comment by zjpoh** [comment]
@bbengfort If nobody is working on this, I would like to give it a try.

**Comment by bbengfort** [comment]
@zjpoh go for it, thanks for taking this one!
