### ISSUE TITLE
Convert radviz into FeatureVisualizer

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#51]
Convert radviz into `FeatureVisualizer`. Allow the user to specify which dimensions to visualize, either in `init` or `draw`.

**Comment by rebeccabilbro** [comment]
Note that radviz for classifiers and regressors might be different -- might need to do some different things in the way we color them. For classifiers, as many colors as there are classes. Perhaps a gradient for regressors  - red-to-blue gradient where grey is the mean, dark red is 2 standards from positive, dark blue is 2 standards from negative.

**Comment by bbengfort** [comment]
As with parallel coordinates, I'll go ahead and bring the implementation into the yellowbrick code base so that we can optimize it!

**Comment by bbengfort** [comment]
This was a fun one - I had to dive into Numpy a lot more than I expected (the Pandas implementation relied heavily on DataFrame and Series stuff)! 

Same as ParallelCoordinates - this is an initial visualizer, and there is _a lot_ of room for improvement; but this is also where we iterate!

**Comment by bbengfort** [comment]
Also it doesn't seem fair to close this issue without putting an example in! 

![yb_radviz](https://cloud.githubusercontent.com/assets/745966/19199687/2f2a8c3a-8c93-11e6-8b30-ce8db8eea888.png)
