### ISSUE TITLE
Remove old datasets code and rewire with new datasets.load_* api

### ISSUE THREAD

**Issue by ndanielsen** [DistrictDataLabs/yellowbrick#512]
As a follow up to reworking the datasets API, we need to go through and remove redundant old code in these locations:

- [x] `yellowbrick/download.py`

- [ ] `tests/dataset.py`

Part of this will be a requirement to rewire tests and examples as needed. Likely also there might be slight transformations of data in code that will have to happen

@DistrictDataLabs/team-oz-maintainers

**Comment by ndanielsen** [comment]
related issues:
https://github.com/DistrictDataLabs/yellowbrick/issues/500
https://github.com/DistrictDataLabs/yellowbrick/issues/424

**Comment by bbengfort** [comment]
I've got a chance to work on this, so I'll take this on.

**Comment by bbengfort** [comment]
Complete with #535 and covered in other issues described by #683
