### ISSUE TITLE
PredictionError Plot for Multiple target Regressor

### ISSUE THREAD

**Issue by zjpoh** [DistrictDataLabs/yellowbrick#524]
Some regressors can fit to multiple targets (see #510 for the list).

Should we enable `PredictionError` to create different colors scatter plot for different targets?

For example,
![multi-target](https://user-images.githubusercontent.com/8103276/43181975-7573658a-8f94-11e8-82c9-d3239f264fef.png)

**Comment by bbengfort** [comment]
This is a very interesting idea, and I can see how it would be very useful. This visualization would occur when `y` and `y_pred` (returned from predict) had `ndim == 2`, right? 

I think the main question is whether or not this is an adaptation of the current `PredictionError` or if it should be a subclass, `MultiPredictionError`. Answers to the following questions might help us determine that:

- Do we need to draw best fit lines for each target?
- How does the user supply the label/legend for each type? 
- Could this be adapted to work with multiple models?

**Comment by bbengfort** [comment]
@zjpoh I agree with all your answers; let's start with a `MultiPredictionError` subclass of `PredictionError` and see how it looks! Thanks for taking the time to think about this so thoroughly!

**Comment by rebeccabilbro** [comment]
Going to archive this one for now since the conversation has gone a bit stale; happy to reopen if someone has bandwidth and interest!
