### ISSUE TITLE
Add datasets metadata to documentation

### ISSUE THREAD

**Issue by zjpoh** [DistrictDataLabs/yellowbrick#527]
**Describe the issue**
Create documentation on metadata on example datasets such as number of samples, number of features, target/class.
For example, [sklearn.datasets.load_digits](http://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_digits.html).

@DistrictDataLabs/team-oz-maintainers

**Comment by rebeccabilbro** [comment]
Note: have consolidated this task with #441 to ensure we get it done for the v1.0 release!
