### ISSUE TITLE
Incorrect parameter values in K-Elbow Visualizer docstring

### ISSUE THREAD

**Issue by Kautumn06** [DistrictDataLabs/yellowbrick#529]
Initially in the K-Elbow Visualizer's docstring, the possible values for the parameter `metric` are named as `distortion_score`, `silhouette_score`, and `calinski_harabaz_score`. However, using these values returns the following error:

`YellowbrickValueError: '{}' is not a defined metric use one of distortion, silhouette, or calinski_harabaz`

However, the correct names&mdash;`distortion`, `silhouette`, `calinski_harabaz`&mdash;are listed corrected further down under `Parameters`.

![elbow-documentation](https://user-images.githubusercontent.com/19958803/43358572-0f72b404-9262-11e8-8201-7a9ef6cd3fec.png)

**Comment by bbengfort** [comment]
@Kautumn06 ah I see what you mean now; yes you can go ahead and remove the `_score` suffix from those names, which refer to the function names of the metrics.
