### ISSUE TITLE
FeatureImportances stack documentation

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#531]
Thank you so much @zjpoh for enhancing the `FeatureImportance` visualizer with a stack bar chart! There are a couple of minor tasks to complete that I will take care of in the next couple of days:

1. Add documentation about the stack argument and the implications 
2. Add `skipif` pandas not available, or non-pandas testing 
3. When stack gets set to False, issue warning about what happened 
4. Non-classifier multi-output regressors test 

See #492 and #510

**Comment by zjpoh** [comment]
@bbengfort thanks for filling in the gaps of my PR. I will take a look at what you add and hopefully next time I can have a more complete PR. =)

**Comment by bbengfort** [comment]
@zjpoh your PR was absolutely complete in every respect! We try to do things in iterative, small, incremental steps so that we don't overload the PR process or exhaust our contributors. As YB has gotten bigger, there is just a lot of stuff from documentation to checks, CI, dependencies etc. that we have to manage. It's kind of drudge work and just has to be done in order to make the package accessible and intuitive. Please keep submitting PRs and if you'd like to take on some of these other maintenance tasks, we'd be happy to have those types of contributions also! 

RE @DistrictDataLabs/team-oz-maintainers
