### ISSUE TITLE
KElbowVisualizer should take a list of k instead of a tuple

### ISSUE THREAD

**Issue by vallettea** [DistrictDataLabs/yellowbrick#537]
This is just a suggestion that KElbowVisualizer should let the user chose the values of k and not be forced to have a continuous range. 
This is especially useful when you suppose you have a big number of clusters and you want explore the values of k from 10 to 10 or 100 to 100.

Anyway, thanks for your work.

**Comment by bbengfort** [comment]
Hi @vallettea this is an excellent suggestion! I think we would want to support both the range and discrete options; what do you think about the following: 

```python 
k : integer, tuple, or iterable 
        The k values to compute silhouette scores for. If a single integer
        is specified, then will compute the range (2,k). If a tuple of length 
        2 is specified, then k will be in np.arange(k[0], k[1]). Otherwise, 
        specify an iterable of integers to use as values for k. 
```

Test cases:

- [ ] specify `k=8 == np.arange(2, 8)`
- [ ] specfify `k = (4, 12) == np.arange(4, 12)` 
- [ ] specify `k = np.arange(10, 100, 10) == np.arange(10, 100, 10)` 
- [ ] specify `k = [10,20,30,40,50,60,70,80,90] == np.arange(10, 100, 10)`

**Comment by rebeccabilbro** [comment]
Great idea @vallettea! Want to take a crack at a updating `KElbowVisualizer` so that users can specify either a `k` range, `k` list, or `k` ceiling? Feel free to open up a PR whenever you're ready!

**Comment by drwaterman** [comment]
@bbengfort In your list of test cases, is the first one a typo? Existing functionality is:
`k=8 == np.arange(2, 8+1) == [2, 3, 4, 5, 6, 7, 8]`

**Comment by bbengfort** [comment]
@drwaterman yes, that's a typo - please maintain existing functionality; thanks for looking out!

**Comment by rebeccabilbro** [comment]
@drwaterman @lwgray - can we close this one now that #587 is merged in or are there still things on the todo list?
