### ISSUE TITLE
TSNE size & title bug

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#539]
**Describe the bug**
Looks like our `TSNEVisualizer` might have a bug that causes an error on instantiation if either the `size` or `title` parameters are used.

**To Reproduce**

```python
from yellowbrick.text import TSNEVisualizer
from sklearn.feature_extraction.text import TfidfVectorizer

corpus = load_data('hobbies')
tfidf = TfidfVectorizer()
docs = tfidf.fit_transform(corpus.data)
labels = corpus.target

tsne = TSNEVisualizer(size=(1080, 720))
```

or 

```
tsne = TSNEVisualizer(title="My Special TSNE Visualizer")
```

**Dataset**
This bug was triggered using the YB hobbies corpus.

**Expected behavior**
Users should be able to influence the size of the visualizer on instantiation using the `size` parameter and a tuple with `(width, height)` in pixels, and the title of the visualizer using the `title` parameter and a string.

**Traceback**

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-59-120fbfcec07c> in <module>()
----> 1 tsne = TSNEVisualizer(size=(1080, 720))
      2 tsne.fit(labels)
      3 tsne.poof()

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yellowbrick/text/tsne.py in __init__(self, ax, decompose, decompose_by, labels, classes, colors, colormap, random_state, **kwargs)
    180 
    181         # TSNE Parameters
--> 182         self.transformer_ = self.make_transformer(decompose, decompose_by, kwargs)
    183 
    184     def make_transformer(self, decompose='svd', decompose_by=50, tsne_kwargs={}):

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yellowbrick/text/tsne.py in make_transformer(self, decompose, decompose_by, tsne_kwargs)
    234         # Add the TSNE manifold
    235         steps.append(('tsne', TSNE(
--> 236             n_components=2, random_state=self.random_state, **tsne_kwargs)))
    237 
    238         # return the pipeline

TypeError: __init__() got an unexpected keyword argument 'size'

```
or for `title`:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-64-92c88e0bdd33> in <module>()
----> 1 tsne = TSNEVisualizer(title="My Special TSNE Visualizer")
      2 tsne.fit(labels)
      3 tsne.poof()

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yellowbrick/text/tsne.py in __init__(self, ax, decompose, decompose_by, labels, classes, colors, colormap, random_state, **kwargs)
    180 
    181         # TSNE Parameters
--> 182         self.transformer_ = self.make_transformer(decompose, decompose_by, kwargs)
    183 
    184     def make_transformer(self, decompose='svd', decompose_by=50, tsne_kwargs={}):

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yellowbrick/text/tsne.py in make_transformer(self, decompose, decompose_by, tsne_kwargs)
    234         # Add the TSNE manifold
    235         steps.append(('tsne', TSNE(
--> 236             n_components=2, random_state=self.random_state, **tsne_kwargs)))
    237 
    238         # return the pipeline

TypeError: __init__() got an unexpected keyword argument 'title'
```

**Desktop (please complete the following information):**
 - macOS
 - Python Version 3.6
 - Yellowbrick Version 0.8

**Comment by bbengfort** [comment]
Both size and title are handled in the base `Visualizer` class - my first thought about solving this issue is to see if there is a missing `super()` call in any of the subclasses.

**Comment by rebeccabilbro** [comment]
I think I've [figured this out](https://github.com/rebeccabilbro/yellowbrick/blob/tsne-title-size-bug/examples/rebeccabilbro/tsne_title_size_bug.ipynb). The issue is that we pass the `**kwargs` (including any title and size) into the internal sklearn `TSNE` transformer, which doesn't understand those params. I can fix it by popping them in `__init__`. I'll follow up with a PR that fixes the bug and adds some test coverage.

**Comment by bbengfort** [comment]
@rebeccabilbro am going to close this by #542

**Comment by danielhoadley** [comment]
I'm still hitting the exact same problem using version 0.8

**Comment by rebeccabilbro** [comment]
Hello @danielhoadley and thanks for checking out Scikit-Yellowbrick! You're right that the change isn't in v0.8 yet, but we've [made the fix](https://github.com/DistrictDataLabs/yellowbrick/pull/542), and it will be reflected in v0.9, which we should be releasing in just a few weeks!

**Comment by danielhoadley** [comment]
Thanks, @rebeccabilbro! It’s a great library!
