### ISSUE TITLE
Bad link in README

### ISSUE THREAD

**Issue by odeckmyn** [DistrictDataLabs/yellowbrick#54]
in readme there is a broken link that should lead to “quick start guide”, in “Using YellowBrick” section.

Best,

**Comment by bbengfort** [comment]
@odeckmyn thanks for letting us know; we'll check it out!

**Comment by anna-liao** [comment]
yup me too, this one: https://github.com/DistrictDataLabs/yellowbrick/blob/develop/docs/setup.md

**Comment by rebeccabilbro** [comment]
@bbengfort @odeckmyn @anna-liao - should be corrected when [this commit](https://github.com/DistrictDataLabs/yellowbrick/commit/011d1b7346f40e8e9507b85e8f1852a9e9a20659) is merged into master this week!

**Comment by bbengfort** [comment]
@rebeccabilbro closing thanks to your fix in 011d1b7!
