### ISSUE TITLE
Add ClassBalance class

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#55]
Add ClassBalance class, inherits from [ClassificationScoreVisualizer class](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/classifier.py#L35). The purpose is to help the user in visualizing any potential class imbalance issues.

**Comment by rebeccabilbro** [comment]
Suggest using [precision_recall_f1_support method](http://scikit-learn.org/stable/modules/generated/sklearn.metrics.precision_recall_fscore_support.html#sklearn.metrics.precision_recall_fscore_support) from sklearn metrics to get the 4th item in the tuple, which is the support score.

**Comment by rebeccabilbro** [comment]
Preliminary implementation complete: https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/classifier.py#L179. 

Coloring method will need to be refactored.

**Comment by bbengfort** [comment]
I'd like to [use the yellowbrick.style.palettes](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/classifier.py#L206) module as well! I suggest we move that to a new issue, and make sure we keep this class up to date per #44 -- but other than that, if this implementation works, then let's close this issue! Also - you have issues for the tests; so I think you've achieved this card!

**Comment by rebeccabilbro** [comment]
Marking as complete, with the understanding that issues #62 will resolve the fig/ax hook question that came up in the design of the `ScoreVisualizer` class and that #67 will resolve the initial tests requirement.
