### ISSUE TITLE
Add FAQ section to docs

### ISSUE THREAD

**Issue by peterespinosa** [DistrictDataLabs/yellowbrick#552]
**Describe the solution you'd like**
It would be great to add an FAQ section to the docs with answers to commonly asked questions (e.g., how to set the title; change the size; change the colormap).

**Is your feature request related to a problem? Please describe.**
I saw in [this issue](https://github.com/DistrictDataLabs/yellowbrick/issues/551) a suggestion for an FAQ; it sounds like it would be helpful for new users to have an FAQ section in the docs.

**Comment by lwgray** [comment]
Hi @peterespinosa this is a such great suggestion.  The 3 you have listed are definitely questions we've fielded in the past.  Any addition that could make using YB easier is always welcomed.  Was this something you wanted to contribute?

**Comment by rebeccabilbro** [comment]
Closed with #562
