### ISSUE TITLE
Add alpha support for other scatter visualizers

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#558]
**Describe the solution you'd like**
In follow up to @peterespinosa's [recent PR](https://github.com/DistrictDataLabs/yellowbrick/pull/554), we should add an `alpha` (translucency) param to the scatter visualizers that don't currently have one.

**Is your feature request related to a problem? Please describe.**
The following visualizers need an `alpha` parameter:

- PCADecomposition 
- PredictionError 
- ResidualsPlot (implements a default alpha) 
- text.TSNE (implements a default alpha) 

see discussion in #475

**Comment by bbengfort** [comment]
NOTE: When this parameter is added; please also use `manual_legend` to correctly draw the legend without opacity. See #564 and #557
