### ISSUE TITLE
Add 'Yellowbrick for Teachers' slidedeck to docs

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#560]
**Describe the solution you'd like**
Add a sample slide deck to the docs for machine learning teachers to use in teaching model selection & visual diagnostics

**Is your feature request related to a problem? Please describe.**
I've been asked a few times by other teachers of machine learning if I had any slides or teaching materials they could use in their classes. I have some slides that I could put together and publish, or else this might be a good candidate for [Jupyter Notebook slides](https://medium.com/@mjspeck/presenting-code-using-jupyter-notebook-slides-a8a3c3b59d67)

**Examples**
<img width="801" alt="screen shot 2018-08-10 at 2 36 48 pm" src="https://user-images.githubusercontent.com/8760385/43975216-dd9a8d14-9caa-11e8-9f7d-2466cd58df44.png">

<img width="802" alt="screen shot 2018-08-10 at 2 37 31 pm" src="https://user-images.githubusercontent.com/8760385/43975245-f456554c-9caa-11e8-91ef-1b8d1263c05b.png">

**Comment by lwgray** [comment]
@rebeccabilbro This is  such a great idea and I think the community will truly appreciate it.

**Comment by rebeccabilbro** [comment]
Awesome, thanks @lwgray!!

**Comment by rebeccabilbro** [comment]
Closed with #561
