### ISSUE TITLE
Finish the palettes listing

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#57]
This is a great project for anyone who wants a way to quickly and easily contribute to Yellowbrick! Basically what we need is a repair and extension of the palettes we've added in [yellowbrick.colors.palettes](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/colors/palettes.py) to make sure everything looks great. This is a high impact task that should be relatively easy! 
- [x] Check over the colors in the [palettes notebook](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/examples/palettes.ipynb) and make sure that the start of the color palette (for unordered  color maps, e.g. not Paired or Sequential) has the following rough sequence: blue, green, red, maroon, yellow, cyan and if they're longer than 6 long, then black (anything else can follow). 
- [x] Go to the [colorbrewer page](https://bl.ocks.org/mbostock/5577023) and make sure that all the palettes there are represented. 
- [x] Create a sequential colormap list with `mplcol.ListedColormap` as follows: add a new variable called `_COLOR_MAPS` with named lists of the color maps, then create a new top level variable `COLOR_MAPS` that converts the raw lists into a `ListedColorMap` (e.g. is a dictionary of names to `ListedColorMap` objects. Alternatively simply create a function `color_sequence` that behaves like `color_palette` but returns a `ListedColorMap`. 

Happy to discuss this and any questions.

**Comment by hboyan** [comment]
I'm happy to jump in on this one - looking at it today.

**Comment by hboyan** [comment]
Is this ready to be worked on? Let me know and I'll jump in, I'm up for this one.

**Comment by bbengfort** [comment]
@hboyan That would be great if you could! We're still working on planning the 0.3.1 release, but I think this should be a part of it.

**Comment by hboyan** [comment]
Alright, will start on it now!

**Comment by rebeccabilbro** [comment]
Awesome @hboyan! This card is on deck for our forthcoming milestone (the 0.3.2 release) - are you good to go? Let us know if you have any questions!

**Comment by hboyan** [comment]
Yep @rebeccabilbro , working on it! Got all the colorbrew palettes cleaned, just integrating them into the yellowbrick code now. Will let you know if I encounter problems!

**Comment by rebeccabilbro** [comment]
@hboyan excellent! We sent you a Github invite to join the Team Oz Collaborators. Once you accept the invitation, we can assign the card to you to formally credit you with taking this one on. It's read-access, so you'll still need to do a pull request. Look forward to seeing the palettes!! :)

**Comment by rebeccabilbro** [comment]
Hey @hboyan - just wanted to check in to see if there was anything you wanted to push for the palettes? We're wrapping up this milestone this week and need to close this one out in order to move forward. Thanks!

**Comment by hboyan** [comment]
Hi @rebeccabilbro - Thanks for checking in! Yes, I have all the palettes coded, just trying to get them to work with the preview script. Will get it ready and push what I have today!

**Comment by hboyan** [comment]
Hi again @rebeccabilbro - Apologies, had a firestorm from work at the end of the week/over the weekend. I'm not done with this yet - should I keep going, and if so, what's the drop dead on the push?

**Comment by rebeccabilbro** [comment]
Hi @hboyan and thanks for reaching out again! The main issue with this card is that we need it closed so we can finish and close #73, which is part of our upcoming release. We sent you a Github invite to join the Team Oz Collaborators - can you accept it so we can formally assign the card to you?  

We would need to get your pull request for this card by Wednesday 9th - can you swing that?

**Comment by hboyan** [comment]
Thanks @rebeccabilbro I think I found the invite. Let me know if that didn't work. Yes, Wed should be fine. Will get back to you shortly. Thank you!

**Comment by bbengfort** [comment]
See #64 Colorblind Palettes
