### ISSUE TITLE
Intercluster Distance Map (MDS)

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#571]
**Describe the solution you'd like**
Create a cluster visualization that displays the distance between cluster centers and cluster relative sizes by using [multidimensional scaling (MDS)](http://scikit-learn.org/stable/modules/generated/sklearn.manifold.MDS.html). The visualization would be:

1. A scatter plot whose points would be described by the MDS embedding of the cluster centers 
2. Each point would be sized according to the number of instances belonging tot he cluster. 
3. Each point would be labeled with its cluster index 

**Is your feature request related to a problem? Please describe.**
Between this and #570, Yellowbrick could provide a reasonable approximation of PyLDAViz in an interactive notebook with ipywidgets. 

**Examples**

<img width="590" alt="screenshot 2018-08-21 06 55 38" src="https://user-images.githubusercontent.com/745966/44397681-39f12e80-a50f-11e8-88b8-53a76bbaa1ab.png">

**Comment by bbengfort** [comment]
Here is a quick code snippet of how we might implement this in Python:

```python
import numpy as np 
import matplotlib.pyplot as plt 

from sklearn.manifold import MDS 
from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs


def prop_to_size(prop, mi=0, ma=5, power=0.5):
    """
    Scale a property to be used as a size 
    """
    prop = np.asarray(prop)
    return mi + (ma - mi)*((prop - prop.min()) / (prop.max() - prop.min()))**power


def intercluster_distance(model):
    ## Get centers 
    ## TODO: is this how sklearn stores centers in all models? 
    C = model.cluster_centers_

    ## Compute the sizes of the clusters 
    size = prop_to_size(np.bincount(model.predict(X)), 500, 1500)

    ## Use MDS to plot centers 
    Cm = MDS().fit_transform(C)
    
    ## Create the figure and axes 
    _, ax = plt.subplots(figsize=(9,6))

    ## Draw the scatter plot 
    ax.scatter(Cm[:,0], Cm[:,1], s=size, alpha=0.25, edgecolor='k')

    ## Add cluster labels to the middle of each point 
    for i, pt in enumerate(Cm):
        ax.annotate(str(i), (pt[0], pt[1]), va="center", ha="center")
        
    return ax 


## Make 12 blobs dataset 
X, y = make_blobs(centers=12, n_samples=1000, n_features=12, shuffle=True)

## Fit KMeans model on dataset 
model = KMeans(9).fit(X)
intercluster_distance(model)
```

And the result:

![icdm](https://user-images.githubusercontent.com/745966/44399330-3660a600-a515-11e8-84fb-dcd585f91147.png)

**Comment by rebeccabilbro** [comment]
Intriguing idea! For those interested, it looks like by default, pyLDAvis [computes topic coordinates](https://github.com/bmabey/pyLDAvis/blob/master/pyLDAvis/_prepare.py#L181) using a [Principal Coordinate Analysis (PCoA)](https://github.com/bmabey/pyLDAvis/blob/master/pyLDAvis/_prepare.py#L106) based on an [internal implementation](https://github.com/bmabey/pyLDAvis/blob/master/pyLDAvis/_prepare.py#L68) of [Jensen-Shannon Divergence](https://en.wikipedia.org/wiki/Jensen%E2%80%93Shannon_divergence). [Vanilla PCoA](https://github.com/bmabey/pyLDAvis/blob/master/pyLDAvis/_prepare.py#L73), [Metric Multidimensional Scaling](https://github.com/bmabey/pyLDAvis/blob/master/pyLDAvis/_prepare.py#L123), and [TSNE](https://github.com/bmabey/pyLDAvis/blob/master/pyLDAvis/_prepare.py#L142) are also implemented.

**Comment by bbengfort** [comment]
@rebeccabilbro thank you for that list; it would be awesome if we could add all of those embeddings to our visualizer. MDS and TSNE are easy since they're in sklearn; I'll see if I can figure the other ones out too!

**Comment by meggles314** [comment]
I cannot import InterclusterDistance:

  from yellowbrick.cluster import InterclusterDistance
ImportError: cannot import name 'InterclusterDistance'

AttributeError: module 'yellowbrick.cluster' has no attribute 'InterclusterDistance'

**Comment by meggles314** [comment]
Thank you so much!!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
