### ISSUE TITLE
Interactive Visualizer demos with Binder

### ISSUE THREAD

**Issue by jlinGG** [DistrictDataLabs/yellowbrick#585]
Using Ipywidgets, we can create interactive Yellowbrick visualizations.  I would like to allow other users to see these interactive demos using Binder.   Currently our README has a Binder button that launches a Docker with our examples.ipynb notebook viewable.  This allows users can interact with it without having to clone YB and run the notebooks locally.  Additional research is needed to determine how Binder can show the demos.

Images of an interactive visualization.  It includes a dropdown menu that allows users to toggle between different classification visualizations:
<img width="885" alt="screen shot 2018-08-22 at 5 06 36 pm" src="https://user-images.githubusercontent.com/24831129/44490962-cdb91c80-a62d-11e8-83e3-0961e2002e19.png">

<img width="923" alt="screen shot 2018-08-22 at 5 06 55 pm" src="https://user-images.githubusercontent.com/24831129/44490968-cf82e000-a62d-11e8-99f7-3f4e86db4b41.png">

**Comment by bbengfort** [comment]
Archiving unless someone would like to revisit this.
