### ISSUE TITLE
Move _determine_target_color_type from the Manifold visualizer to the utils package

### ISSUE THREAD

**Issue by pdamodaran** [DistrictDataLabs/yellowbrick#588]
The Manifold visualizer currently has a function called _determine_target_color_type that can be used by other visualizers as it determines the type of the other target variable.  It would be great to move this to the utils package.

**Comment by bbengfort** [comment]
Or to the `yellowbrick.target` package!

**Comment by pdamodaran** [comment]
@bbengfort which one do you think is better?  I can take care of this.

**Comment by bbengfort** [comment]
How about a compromise, in `yellowbrick.target.utils`? @rebeccabilbro thoughts?

**Comment by rebeccabilbro** [comment]
Putting it in `yellowbrick.target.utils` would be great!!

**Comment by rebeccabilbro** [comment]
See also #73

**Comment by bbengfort** [comment]
Fixed by #676
