### ISSUE TITLE
Improve Parallel Coordinates

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#59]
See #50 for a more detailed discussion. 

There are several things that need to be done to improve the parallel coordinates visualizer:
- [x] Benchmarking, it is currently SLOW
- [x] Add a `draw_instance` method so that instances can be added to the figure at any time
- [x] Add `DataFrame` support so that the visualizer can accept either an `ndarray` or a `DataFrame` as input.
- [x] Create a subclass `NormalizedParallelCoordinates` that normalizes the data to the space 0 to 1 before drawing the coordinates. 
- [x] Add subsampling of instances to reduce clutter and improve performance 
- [x] Add fast vs. slow drawing methods for performance
- [x] Add alpha so that you can see instances through the other lines 
- [ ] <strike>Create an optimization technique that reorders the columns such that the overlap of two instances by the same class is minimized</strike>

There are probably several more things and there are comments in the Parallel Coordinates codebase as well.

**Comment by thekylesaurus** [comment]
At PyCon 2018 sprints.  I'm going to take a pass at some of these items.

**Comment by thekylesaurus** [comment]
@bbengfort - should we also include an item to make the "sample" capability select random rows, as opposed to ordered rows.  For data sets with sorted targets, you don't end up with a true representative sample.

**Comment by bbengfort** [comment]
@thekylesaurus I think that would be a great idea - [I think we were planning on making sample a uniform random sample](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/features/pcoords.py#L244) but the number of choices for how to conduct sampling led us to simply use `head`. If there is a sklearn-method that does sampling we could use that as a guide for how to treat the `sample` parameter, otherwise perhaps we could simply add a `shuffle=True` argument which would make `head` a uniform random sample? What do you think?

**Comment by thekylesaurus** [comment]
@bbengfort - shuffle=True would definitely get the job done; but I'll check sklearn to see if there is a different convention that we should inherit.
