### ISSUE TITLE
JointPlot Poof Method Doesn't Show Plot

### ISSUE THREAD

**Issue by archaeocharlie** [DistrictDataLabs/yellowbrick#594]
**Describe the bug**
No plot shows after running the example code for a JointPlot. The current `poof` method in jointplot.py seems to lack a `plt.show()` call. Perhaps add to method:
```
if outpath is not 
     plt.savefig(outpath, **kwargs)
else:
     plt.show()
```
**To Reproduce**

```python
# Load the data
df = load_data("concrete")
feature = "cement"
target = "strength"

# Get the X and y data from the DataFrame
X = df[feature]
y = df[target]

from yellowbrick.features import JointPlotVisualizer

visualizer = JointPlotVisualizer(feature=feature, target=target)

visualizer.fit(X, y)
visualizer.poof()
```

**Dataset**
Concrete dataset through tutorial

**Expected behavior**
Expected plot to show

**Traceback**
No error thrown
```
If applicable, add the traceback from the exception.
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 16
 - Python Version 3.6 miniconda
 - Yellowbrick Version current

**Additional context**

**Comment by Kautumn06** [comment]
Thank you @archaeocharlie for opening up an issue! 

To help me find out what's going on, before trying the code, did you have any problems downloading our example datasets? 

For instance, if this is the code from our documentation that you trying to run, the information and script for downloading the files would be up in the far left-hand corner in the "Example Datasets" page (right underneath "Visualizers and API").
![jointplot](https://user-images.githubusercontent.com/19958803/44855785-d61ae400-ac39-11e8-8892-96f8511b9c7f.png)

If you could let me know if you had run into any issues when running the code to download the sample files, that would be very helpful. Thanks so much!
