### ISSUE TITLE
Splitting Data

### ISSUE THREAD

**Issue by Olamyy** [DistrictDataLabs/yellowbrick#597]
**Describe the issue**
I noticed there's really no example in the docs where the data is splitted before any of the `yellowbrick` classes are called. 
While I think this is a bit trivial, it will generally lead to questionable result in the classification report since the model would be scored on the same data it was trained with.
A good example of such code is this:

```
import matplotlib.pyplot as plt

from sklearn.pipeline import Pipeline
from yellowbrick.classifier import ClassificationReport

def visual_model_selection(X, y, estimator):
    """
    Test various estimators.
    """
    y = LabelEncoder().fit_transform(y.values.ravel())
    model = Pipeline([
         ('label_encoding', EncodeCategorical(X.keys())),
         ('one_hot_encoder', OneHotEncoder()),
         ('estimator', estimator)
    ])

    # Create a new figure to draw the classification report on
    _, ax = plt.subplots()
    visualizer = ClassificationReport(
        model, ax=ax, classes=['edible', 'poisonous']
    )
    visualizer.fit(X, y)
    visualizer.score(X, y)
    visualizer.poof()
```

From my understanding, the function above is scoring the estimator with the same set of data it was trained with, which well, can lead to wrong evaluation measures.
I really am not sure if this is a bug or there's an explanation somewhere I'm overlooking but I'd really love to get this cleared.

**Comment by wagner2010** [comment]
Hi @Olamyy , thank you for checking out and using Yellowbrick in Nigeria!  We hope you're enjoying it and thank you for submitting an issue.  If you'd care to join our cause and help improve Yellowbrick, [here](http://www.scikit-yb.org/en/latest/contributing.html) is a link with information on how you can become a contributor.  

When getting started with Yellowbrick, we like to point users to our [Quick Start Guide](http://www.scikit-yb.org/en/latest/quickstart.html).  If you read that carefully and do the [Walkthrough](http://www.scikit-yb.org/en/latest/quickstart.html#walkthrough) you will have examples of completing the train test split for Cross Validation (CV) that you're discussing in your issue.  We encourage users to start there.  The purpose of the Quick Start Guide and the Walkthrough is to cover the steps for users to utilize Yellowbrick in their various projects.

Additionally, we have a set of visualizers in our docs that have code right in the documentation that show you how to do train test split for CV.  These visualizers include: 

- [classificationreport](http://www.scikit-yb.org/en/latest/api/classifier/classification_report.htm)
- [confusion matrix](http://www.scikit-yb.org/en/latest/api/classifier/confusion_matrix.html) 
- [rocauc](http://www.scikit-yb.org/en/latest/api/classifier/rocauc.html) 
- [class prediction error](http://www.scikit-yb.org/en/latest/api/classifier/class_prediction_error.html)
- [residuals](http://www.scikit-yb.org/en/latest/api/regressor/residuals.html) 
- [prediction error plot](http://www.scikit-yb.org/en/latest/api/regressor/peplot.html)

Additionally, we have other visualizers that do the train test splits for CV on the user's behalf including:
 

- [validation curve](http://www.scikit-yb.org/en/latest/api/model_selection/validation_curve.html)
- [learning curve](http://www.scikit-yb.org/en/latest/api/model_selection/learning_curve.html)
- [discrimination threshold](http://www.scikit-yb.org/en/latest/api/classifier/threshold.html)

We thank you again for using Yellowbrick and submitting this issue.  We hope these resources are helpful to you in using Yellowbrick and we welcome your future participation.
