### ISSUE TITLE
Complete Docs and final tasks for Updated DispersionPlot

### ISSUE THREAD

**Issue by lwgray** [DistrictDataLabs/yellowbrick#598]
`DispersionPlot` has undergone a few changes.  Mainly adding color-coded markers that depict label association.  However, there are a few incomplete tasks.

Firstly a feature should be added.
- [ ] the ability to use a Pandas Dataframe as input

Secondly, the documentation must now reflect these changes.
- [x] add documentation and examples of the plots to the docs
- [x] add images to gallery

@DistrictDataLabs/team-oz-maintainers

**Comment by rebeccabilbro** [comment]
Hey there @lwgray &mdash; I'm going to go ahead and close this since most of the checkboxes have now been checked off and there hasn't been much action on the last one. To anyone with interest/bandwidth in fleshing out the Pandas df use case, feel free to reopen!
