### ISSUE TITLE
Feature Analysis: Rank 2D

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#6]
Seaborn has an example of this, but let's create a function that will immediately give the rank 2d in advance of the SPLOM.

**Comment by rebeccabilbro** [comment]
In Seaborn, they have the [diagonal correlation matrix visualization](https://stanford.edu/~mwaskom/software/seaborn/examples/many_pairwise_correlations.html)

**Comment by xerebz** [comment]
dibs

**Comment by xerebz** [comment]
What is the rank 2d in this context, and what does it have to do with the diagonal correlation matrix?

**Comment by bbengfort** [comment]
Rank 2D is basically the same thing as the diagonal correlation matrix, but you can rank by anything, not just Pearson. Feel free to take this on using the API, but I might implement a rough version for some demo stuff I'm doing today.

**Comment by bbengfort** [comment]
http://jpktd.blogspot.ca/2012/06/non-linear-dependence-measures-distance.html

**Comment by bbengfort** [comment]
A basic implementation of this is up with `pcolormesh` and Pearson and Covariance ranking but it needs to be improved more.
