### ISSUE TITLE
Better Documentation for Precision-Recall Curves

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#602]
Improvements for the `PrecisionRecallCurve` documentation and docstring are required. 

- [x] expand docstring for both visualizer and quick method 
- [x] add notes to docstring for visualizer and quick method (e.g. the one vs rest classifier and types) 
- [x] note also that parameters are learned on `score` not just on `fit`
- [x] add definitions of precision, recall, average precision, and area under the curve to documentation 
- [x] give clear guidance on interpreting the visualizations and modifying them 
- [x] discuss why these visualizations are used to compare models.

**Comment by ZhiliangWu** [comment]
Hi @bbengfort, I am a bit confused with the documentation [here](https://www.scikit-yb.org/en/latest/api/classifier/rocauc.html#multi-class-rocauc-curves)

> Yellowbrick addresses this by binarizing the output (per-class) or to use one-vs-rest (micro score) or one-vs-all (macro score) strategies of classification.

Where the strategy of one-vs-rest and one-vs-all would refer to the same strategy as train a binary classifier for each class as in Murphy's book (Machine learning, a probabilistic perspective)
![image](https://user-images.githubusercontent.com/18686697/116464327-22e06e00-a86c-11eb-92c4-d21bb7ec190c.png)
It would be great if you could elaborate a bit why you refer them to micro-score and macro-score here.
