### ISSUE TITLE
Refactor all Visualizers to move fig/ax hooks to base class

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#62]
Move fig/ax hooks to `__init__` in base `Visualizer` class.

**Comment by bbengfort** [comment]
Have the dunder init of the base visualizer accept key word arguments `fig=None` and `ax=None` and set `self.fig=fig` and `self.ax=None` 

Create a function `gca` that returns `self.ax` but first checks if it is None and if so sets it to `plt.gca()`

In all other visualizer subclasses, make sure they call super and pass the axes up.

Let's chat on hangouts if you have questions.

**Comment by bbengfort** [comment]
Let's save this refactor for the next version and not worry about it for this weekend! I'll try to clarify my comments from above.

**Comment by rebeccabilbro** [comment]
@rebeccabilbro https://docs.python.org/3/library/functions.html#super

**Comment by rebeccabilbro** [comment]
See commit [5f7ab81](https://github.com/DistrictDataLabs/yellowbrick/commit/5f7ab81bb5ebf920652e589a7e6b66ad643d49de)
