### ISSUE TITLE
Migrate ScoreVisualizers to separate module?

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#65]
Consider moving `ScoreVisualizer` to a separate module with regressors.py, classifiers.py and its own base, following the model for `FeatureVisualizer`. See also #43

**Comment by bbengfort** [comment]
Closing in favor of the refactoring we did on the classifier and regressor packages -- though I'm not 100% sure where `ScoreVisualizer` ended up, so I'm moving this to 0.4.1 just to do a check on it.

**Comment by bbengfort** [comment]
See #90

**Comment by bbengfort** [comment]
With the refactor of the `ModelVisualizer` and `ScoreVisualizer` I think that we're in a good place with the current hierarchy.
