### ISSUE TITLE
Poofing viz warps the ax

### ISSUE THREAD

**Issue by mattharrison** [DistrictDataLabs/yellowbrick#665]
**Describe the bug**
I want to draw 3 plots next to each other. If I call ``.poof`` on them the last one is pushed off.
**To Reproduce**

Run the following code. Then uncomment the ``.poof`` calls and the ROC curve disappears.

```python
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from yellowbrick.classifier import ClassBalance, ClassificationReport, ConfusionMatrix, PrecisionRecallCurve, ROCAUC

pos = 10 + np.random.randn(100)
neg = 7.5 + np.random.randn(100)

fig = plt.figure(figsize=(20,6))
ax1 = fig.add_subplot(131)
ax1.hist(pos, alpha=.8, label='Pos')
ax1.hist(neg, alpha=.8, label='Neg')
ax1.legend()

ax2 = fig.add_subplot(132)
roc_data = np.append(pos, neg)
roc_X = pd.DataFrame(roc_data)
roc_y = [1 for p in pos] + [0 for n in neg]
pr_clf = LogisticRegression(solver='lbfgs')
pr_clf.fit(roc_X, roc_y)
print('score', pr_clf.score(roc_X, roc_y))
pr_viz = PrecisionRecallCurve(pr_clf, ax=ax2)
pr_viz.fit(roc_X, roc_y)
pr_viz.score(roc_X, roc_y)
#pr_viz.poof()  # Poofing here changes the size

ax3 = fig.add_subplot(133)
roc_viz = ROCAUC(pr_clf, ax=ax3)
roc_viz.score(roc_X, roc_y)
#roc_viz.poof()
```

**Dataset**
Included in example

**Expected behavior**
I expect in the above code to have 3 plots in a row.

**Desktop (please complete the following information):**
 - OS: mac
 - Python Version 3.7
 - Yellowbrick Version 0.9

**Comment by wagner2010** [comment]
Hi @mattharrison Thank you, not only for submitting this issue, but for adopting our appreciated format of bug description, code reproduction, dataset in question, expected behavior and computer information.  @lwgray and I are teaming up to work on this and we will get back to you with what we find.  In the meantime, you are always welcome to submit a PR solution or even a partial solution.  @lwgray sees similarities in the the following issues: [579](https://github.com/DistrictDataLabs/yellowbrick/issues/579), and [380](https://github.com/DistrictDataLabs/yellowbrick/issues/380) so you might want to check those out in the meantime.  We look forward getting back to you when we can.  Also, please take a look at replacing poof() with finalize() and see if that helps.  Stay well and thanks again!

**Comment by lwgray** [comment]
@mattharrison Did changing poof() to finalize() resolve your issue?

**Comment by bbengfort** [comment]
@mattharrison just wanted to bump this question - did @wagner2010's answer assist? More specifically, could you try the following:

```python
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from yellowbrick.classifier import ClassBalance, ClassificationReport, ConfusionMatrix, PrecisionRecallCurve, ROCAUC

pos = 10 + np.random.randn(100)
neg = 7.5 + np.random.randn(100)

fig = plt.figure(figsize=(20,6))
ax1 = fig.add_subplot(131)
ax1.hist(pos, alpha=.8, label='Pos')
ax1.hist(neg, alpha=.8, label='Neg')
ax1.legend()

ax2 = fig.add_subplot(132)
roc_data = np.append(pos, neg)
roc_X = pd.DataFrame(roc_data)
roc_y = [1 for p in pos] + [0 for n in neg]
pr_clf = LogisticRegression(solver='lbfgs')
pr_clf.fit(roc_X, roc_y)
print('score', pr_clf.score(roc_X, roc_y))
pr_viz = PrecisionRecallCurve(pr_clf, ax=ax2)
pr_viz.fit(roc_X, roc_y)
pr_viz.score(roc_X, roc_y)
pr_viz.finalize()  # Poofing here changes the size

ax3 = fig.add_subplot(133)
roc_viz = ROCAUC(pr_clf, ax=ax3)
roc_viz.score(roc_X, roc_y)
roc_viz.finalize()
```

If `finalize()`  is still changing the figure, perhaps add a `plt.tight_layout()` at the end?

**Comment by mattharrison** [comment]
Sorry for the delay in responding. It looks like `.finalize` works. Should I prefer that over `.poof`?

**Comment by bbengfort** [comment]
@mattharrison glad that `finalize` worked for you. In this case, `finalize` is better than `poof` -- `poof` calls `finalize` and then either `show` or `savefig` which concludes the figure, so in a multi-axes plot like you have, you don't want to call `poof`. This is also the strategy we use when we draw multi-axes plots.
