### ISSUE TITLE
Allow Resize of figure

### ISSUE THREAD

**Issue by aaqibshehzad** [DistrictDataLabs/yellowbrick#675]
**Describe the solution you'd like**
I understand the yellowbrick team has set the default figure sizes to ensure scientific accuracy when appraising the visualizations. However, It would be great if an optional parameter was added to allow users the option to scale up the image. It is very difficult when visualizing datasets with high number of features or even to allow for better readability of image when presenting it to a larger audience.

**Is your feature request related to a problem? Please describe.**
N/A

**Examples**
Attach an image with an example of the proposed visualization (e.g. from wikipedia or a wireframe example you've drawn). If there are any references we should include in the documentation, please also include them.
![image](https://user-images.githubusercontent.com/31852293/50347103-de5d9e80-050a-11e9-9c46-34d254393ccc.png)

Example: The above image would benefit greatly from an increased figure size.

**Comment by lwgray** [comment]
Hi @aaqibshehzad  Thanks for submitting a feature request.  We really appreciate the input from the yellowbrick community.  Our response time might be slow due to the Holiday Season.  However, I will confer with the rest of the team and see what kind of answer we can provide.

Happy Holidays

**Comment by lwgray** [comment]
@aaqibshehzad the solution to your problem might be answered in our FAQs
http://www.scikit-yb.org/en/latest/faq.html#how-can-i-change-the-size-of-a-yellowbrick-plot

If you have any further question please don't hesitate to ask

Happy Holidays
