### ISSUE TITLE
Progress bar (tqdm) for  Elbow Curve visualization during clustering

### ISSUE THREAD

**Issue by rohit-ganapathy** [DistrictDataLabs/yellowbrick#685]
I needed to visualize the elbow curve for a data set I was applying clustering on and not getting an idea of how much time it would take to run all iterations 1 to n  for visualizer = KElbowVisualizer(model, k=1,n) was quite frustrating. Felt like it would be a good feature add.

**Comment by bbengfort** [comment]
@rohit-ganapathy let us know if you'd like to include a demo or example of this in a PR, but in the meantime, I'm going to archive your question in case anyone else is interested! Thanks again for the suggestion!
