### ISSUE TITLE
RTD webhook needs to be updated

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#698]
Hello!

Your project, Yellowbrick, is currently using GitHub Services to trigger builds on Read the Docs. 

Effective January 31, 2019, GitHub will no longer process requests using the Services feature, and so Read the Docs will not receive notifications on updates to your repository.To continue building your Read the Docs project on changes to your repository, you will need to add a new webhook on your GitHub repository. You can either connect your GitHub account and configure a GitHub webhook integration, or you can add a generic webhook integration.

You can find more information on our webhook intergrations in our documentation, at: https://docs.readthedocs.io/en/latest/webhooks.html#webhook-github-services

Keep documenting,
Read the Docs

**Comment by bbengfort** [comment]
Added webhook to Github.

**Comment by rebeccabilbro** [comment]
Thanks @bbengfort - I had totally forgotten about this!
