### ISSUE TITLE
Feature Selection Visualization

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#7]
How do we adapt radviz, parallel coords, splom, etc. so that our tool is better/more capable than seaborn or pandas. 

One idea is to perform automatic feature analysis and show which features are most visually relevant to the models. In that case we would pull the relevant code from the libraries and adapt it to our use.

**Comment by rebeccabilbro** [comment]
This issue is related to #18 but is more about optimization and will likely involve some statistical analysis/sampling under the hood to enable yellowbrick to guess features that are most relevant to modeling.  May require some reading/research.

**Comment by rebeccabilbro** [comment]
See issue #43
