### ISSUE TITLE
Color Coordination

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#70]
There are a few places where we've hard coded colors (or colormaps) that we should convert to using our style utility so that all of our graphs are coordinated! 

Step one on this issue will be to identify all the places where this occurs. Step two will be to make sure that we can use our current palettes. Step 3 will be to ensure that users can put in their own custom colors.

**Comment by bbengfort** [comment]
@bbengfort - nominate places where this occurs.

**Comment by rebeccabilbro** [comment]
In classifier.py, see [ClassificationReport](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/classifier.py#L97)

**Comment by rebeccabilbro** [comment]
In regressor.py, see [PredictionError](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/regressor.py#L87)

**Comment by rebeccabilbro** [comment]
In regressor.py, see [ResidualsPlot](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/regressor.py#L211)

**Comment by rebeccabilbro** [comment]
Modify the [best fit line](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/bestfit.py) color. It's currently black and looks a bit too harsh with the other colors. Dark grey?

**Comment by bbengfort** [comment]
@rebeccabilbro I've set the best fit line color to `YB_KEY` which in turn is the dark grey color `#111111`
