### ISSUE TITLE
Update fit to fit_transform in JointPlot plot in walkthrough docs

### ISSUE THREAD

**Issue by dnabanita7** [DistrictDataLabs/yellowbrick#703]
OS:Linux18.04LTS
Python=3.6.8 Anaconda Inc.
YellowBrick=0.9

from yellowbrick.features import JointPlotVisualizer

visualizer = JointPlotVisualizer(feature='temp', target='feelslike')
visualizer.fit(X['temp'], X['feelslike'])
visualizer.poof()

It compiles properly but no plots appear as it appeared in Rank2D.Shall I use as_matrix ?

**Comment by lwgray** [comment]
@Naba7 let me see if I can help you resolve this.

1. Are you getting an error when you run this?  If so, could you post it here. An image would help also.
2. Are you working in jupyter notebooks?
