### ISSUE TITLE
Configure ReadTheDocs custom domain with SSL certificate to support HTTPS

### ISSUE THREAD

**Issue by jamesmyatt** [DistrictDataLabs/yellowbrick#704]
The HTTPS version of the website gives a 403 error: https://www.scikit-yb.org/

**Comment by lwgray** [comment]
Hi @jamesmyatt Thanks for bringing this to our attention

We host our docs at readthedocs.org and it looks like there is some configuration we have to do to get HTTPS set up, which we’ll try to take care of as soon as we can.

Until then, you could continue using HTTP version.

Thank you so very much for using Yellowbrick!

**Comment by bbengfort** [comment]
Ok, it looks like [https://www.scikit-yb.org/en/latest/](https://www.scikit-yb.org/en/latest/) is now available and the redirects are currently propagating.
