### ISSUE TITLE
Clean up notebook examples

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#71]
The Jupyter notebook [examples](https://github.com/DistrictDataLabs/yellowbrick/tree/master/examples) need to be cleaned up, particularly the pipeline one. Resolve by breaking out the regressors and classifiers into separate example notebooks.

**Comment by bbengfort** [comment]
I'm working on this in coordination with the Visual Pipeline. I can separate the notebooks if you'd like - but for now (for testing) I'm leaving them both in. We can split them easily once the code is in place.

**Comment by bbengfort** [comment]
@rebeccabilbro ok - I've got the following in the notebook:

- Anscombe
- Rank2D with covariance and Pearson
- Radviz
- Parallel Coords
- Residuals Plot
- Prediction Error Plot
- Classifier Report
- ROC/AUC
- ClassBalance

https://github.com/DistrictDataLabs/yellowbrick/blob/develop/examples/examples.ipynb

Take a look, we can get code snippets and pretty pictures into your slides!
