### ISSUE TITLE
the data folder is not in yellowbrick repo

### ISSUE THREAD

**Issue by Naba7** [DistrictDataLabs/yellowbrick#717]
OS:Linux18.04LTS
Python:3.6.8 Anaconda Inc.
yellowbrick=0.9

import os
import pandas as pd
names = [
    'class',
    'cap-shape',
    'cap-surface',
    'cap-color'
]
mushrooms = os.path.join('data','agaricus-lepiota.txt')
dataset   = pd.read_csv(mushrooms)
dataset.columns = names
dataset.head()

In docs there is a code,joining the path of csv file agaricus-lepiota.txt from data folder.But repo of yellowbrick has no data folder.Rather https://github.com/rebeccabilbro/rebeccabilbro.github.io has a folder data where the dataset of agaricus-lepiota.txt is stored.So,the forked repos of yellowbrick don't get the dataset and the above code shows error.I used **git grep agaricus** under the forked yellowbrick directory and the result is 

chad7@superuser:~/yellowbrick$ git grep agaricus
docs/tutorial.rst:.. _dataset: https://github.com/rebeccabilbro/rebeccabilbro.github.io/blob/master/data/agaricus-lepiota.txt
docs/tutorial.rst:Our file, "agaricus-lepiota.txt," contains information for 3 nominally
docs/tutorial.rst:    mushrooms = os.path.join('data','agaricus-lepiota.txt')
chad7@superuser:~/yellowbrick$ 

So,I think we should change our docs asking to copy the agaricus-lepiota.txt from data folder in https://github.com/rebeccabilbro/rebeccabilbro.github.io/blob/master/data/agaricus-lepiota.txt.
Or create a data folder in yellowbrick repo whichever is convenient.

**Comment by rebeccabilbro** [comment]
Hi again @Naba7 - the mushroom dataset is part of the new datasets module, which is merged into develop and will be in the v1.0 release. You can read more about the new datasets module [here](https://www.scikit-yb.org/en/develop/api/datasets.html) and [here](https://github.com/DistrictDataLabs/yellowbrick/pull/535). We already have several follow-up issues open for modifying the documentation to reflect the new datasets module (see [this epic](https://github.com/DistrictDataLabs/yellowbrick/issues/683)); feel free to add to those threads if you note anything additional related to datasets in the docs.
