### ISSUE TITLE
ParallelCoordinates have different index

### ISSUE THREAD

**Issue by Naba7** [DistrictDataLabs/yellowbrick#723]
**Describe the bug**

The graph showing Output of ParallelCoordinates is incorrect.
As,the code in the docs outputs a different graph.

**To Reproduce**
```python
import os

from yellowbrick.download import download_all

## The path to the test data sets
FIXTURES  = os.path.join(os.getcwd(), "data")

## Dataset loading mechanisms
datasets = {
    "bikeshare": os.path.join(FIXTURES, "bikeshare", "bikeshare.csv"),
    "concrete": os.path.join(FIXTURES, "concrete", "concrete.csv"),
    "credit": os.path.join(FIXTURES, "credit", "credit.csv"),
    "energy": os.path.join(FIXTURES, "energy", "energy.csv"),
    "game": os.path.join(FIXTURES, "game", "game.csv"),
    "mushroom": os.path.join(FIXTURES, "mushroom", "mushroom.csv"),
    "occupancy": os.path.join(FIXTURES, "occupancy", "occupancy.csv"),
    "spam": os.path.join(FIXTURES, "spam", "spam.csv"),
}

import pandas as pd

def load_data(name, download=True):
    """
    Loads and wrangles the passed in dataset by name.
    If download is specified, this method will download any missing files.
    """

    # Get the path from the datasets
    path = datasets[name]

    # Check if the data exists, otherwise download or raise
    if not os.path.exists(path):
        if download:
            download_all()
        else:
            raise ValueError((
                "'{}' dataset has not been downloaded, "
                "use the download.py module to fetch datasets"
            ).format(name))


    # Return the data frame
    return pd.read_csv(path)

# Load the classification data set
data = load_data("occupancy")

# Specify the features of interest and the classes of the target
features = [
    "temperature", "relative humidity", "light", "C02", "humidity"
]
classes = ["unoccupied", "occupied"]

# Extract the instances and target
X = data[features]
y = data.occupancy


from yellowbrick.features import ParallelCoordinates

# Instantiate the visualizer
visualizer = ParallelCoordinates(
    classes=classes, features=features, sample=0.5, shuffle=True
)

# Fit and transform the data to the visualizer
visualizer.fit_transform(X, y)

# Finalize the title and axes then display the visualization
visualizer.poof(outpath='rank1d_graph.pdf')
```

**Dataset**
occupancy dataset 
Its in yellowbrick/yellowbrick/datasets/fixtures

**Expected behavior**
As expected, in the above visualization, the domain of the light feature should be from  [0, 1600], far larger than the range of temperature in [50, 96].

**Graph shown is attached below**
[rank1d_graph.pdf](https://github.com/DistrictDataLabs/yellowbrick/files/2827967/rank1d_graph.pdf)
[rank1d_graph.pdf](https://github.com/DistrictDataLabs/yellowbrick/files/2827969/rank1d_graph.pdf)

**Desktop (please complete the following information):**
 - OS: Linux18.04
[rank1d_graph.pdf](https://github.com/DistrictDataLabs/yellowbrick/files/2827972/rank1d_graph.pdf)
 - Python Version 3.6
 - Yellowbrick Version  0.9

**Comment by lwgray** [comment]
hi @Naba7 Thanks for the submission.  I am looking into this for you.

**Comment by lwgray** [comment]
Hi @Naba7  Thanks for catching this.  I found the problem however It isn't a bug but a misprint in the documentation.  To generate the image that is in the documentation...the sample param needs to be set to 0.05

```
visualizer = ParallelCoordinates(
    classes=classes, features=features, sample=0.05, shuffle=True
)
```

**Comment by Naba7** [comment]
Okay! Thank you it works .. may I do the PR for this?

**Comment by lwgray** [comment]
@Naba7

We have to do this PR in-house because we are changing the way we construct plots in documentation [446](https://github.com/DistrictDataLabs/yellowbrick/pull/446)

**Comment by Naba7** [comment]
Ok!
