### ISSUE TITLE
Address why Images produced by plot directives differ from previous script generated images

### ISSUE THREAD

**Issue by lwgray** [DistrictDataLabs/yellowbrick#739]
Concerns #687 and #737 
This issue is to capture instances when images that are produced by plot directives are different than the images produced by our former inline scripts .

In comparison to the old script derived Images:
1.  Classification Report - Image doesn't expand across entire width of screen
2.  Class_prediction_Error - The width of the plotted area has shrunk
3.  DispersionPlot - Font is smaller
4.  ConfusionMatrix - Labels cut-off
5.  PosTagVisualizer - Labels cut-off

@DistrictDataLabs/team-oz-maintainers

**Comment by lwgray** [comment]
PosTagVisualizer - Cut-off labels
![image](https://user-images.githubusercontent.com/1000117/53345663-6b461f00-38e3-11e9-8ade-0d55ff7ddb8a.png)

**Comment by lwgray** [comment]
ConfusionMatrix - Labels-Cutoff Before and After Plot Directive
![image](https://user-images.githubusercontent.com/1000117/53345810-c11ac700-38e3-11e9-885e-df5cde136109.png)

**Comment by lwgray** [comment]
Classification Report - Before Plot Directive
![image](https://user-images.githubusercontent.com/1000117/53346197-8c5b3f80-38e4-11e9-8f02-624503e1d02d.png)

Classification Report - After Plot Directive - Image Smaller - The width of the plotted area has shrunk
![image](https://user-images.githubusercontent.com/1000117/53346217-941ae400-38e4-11e9-8b41-197e23e7551b.png)

**Comment by lwgray** [comment]
ClassPredictionError - Before Plot Directive
![image](https://user-images.githubusercontent.com/1000117/53346708-8ade4700-38e5-11e9-9226-daa2b73a29e4.png)

ClassPredictionError - After Plot Directive - The width of the plotted area has shrunk
![image](https://user-images.githubusercontent.com/1000117/53346780-bc571280-38e5-11e9-9867-abfb910c7c64.png)

**Comment by lwgray** [comment]
DispersionPlot Before Plot Directive
![image](https://user-images.githubusercontent.com/1000117/53347027-43a48600-38e6-11e9-8029-0ea8ff3b4eeb.png)

DispersionPlot AFter Plot Directive - Smaller Font
![image](https://user-images.githubusercontent.com/1000117/53347111-6a62bc80-38e6-11e9-982c-c9c07e9a1928.png)

**Comment by pdamodaran** [comment]
Original CVScores Regressor Image:

![cv_scores_regressor](https://user-images.githubusercontent.com/7106134/53684898-6b7a5c00-3ce1-11e9-9f19-0cfbfeee1412.png)

**Comment by pdamodaran** [comment]
New CVScores Regressor Image:

![cross_validation-2](https://user-images.githubusercontent.com/7106134/53685361-82bc4800-3ce7-11e9-9e25-c5c1ed97aaa2.png)
