### ISSUE TITLE
Add elbow detection using the "kneedle" method to Elbow Visualizer

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#764]
It would be nice if we could (optionally) annotate the "best" k in the elbow method by detecting the "knee" of the curve using the "kneedle" method described in: https://github.com/arvkevi/kneed. This feature could be added either by adding `kneed` as an _optional_ dependency or by reimplementing part of the kneedle code in Yellowbrick.

**Comment by saurabhdaalia** [comment]
Hi @bbengfort,
Can I work on this issue? 
Just a clarification, when you say optionally, does that mean giving the user option to get annotated "best k" by passing a parameter to `KElbowVisualizer` ?
