### ISSUE TITLE
Improvements to PosTagVisualizer

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#771]
In #768 we rebooted the part-of-speech tag visualizer to make it more practical for NLP machine learning tasks. Here are a few ideas for follow-up features that could be added:

- [x] optional ordering of the plot by tag count (similar to a frequency distribution). _Note: this should NOT be the default behavior since it could prevent users from being able to compare across plots or across corpora_
- [x] optional stacked barchart for each category/class if `y` is supplied
- [ ] option for NER tags with entity recognition (or maybe this should be another visualizer with a shared base class?)
- [x] optional parsing of raw text (only if nltk or spacy is installed)

**Comment by ajaysub110** [comment]
Hello,
Just a query. For the stacked barchart, do you want the number of elements in each class, for each part of speech?
Thanks
Ajay

**Comment by lwgray** [comment]
Hi @ajaysub110 Thanks for reaching out.  We're a bit busy at the moment & will get back to you soon.

**Comment by dubesar** [comment]
Hello,
Can I know what does parsing the raw text here means? 
Does this is the same as processing the raw text? Like using tokenizer for processing the raw text?

**Comment by rebeccabilbro** [comment]
Hi @dubesar and thanks for checking out Yellowbrick! 

The `PosTagVisualizer` currently expects corpora whose documents have already been transformed from their raw state into a (document) list of (paragraphs) lists of (sentence) lists of (token, tag) tuples; for example:

```python
tagged_stanzas = [                                               # document-level
    [                                                            # paragraph-level
        [                                                        # sentence-level
            ('Whose', 'JJ'),('woods', 'NNS'),('these', 'DT'),    # token-tag-level
            ('are', 'VBP'),('I', 'PRP'),('think', 'VBP'),('I', 'PRP'),
            ('know', 'VBP'),('.', '.')
            ],
        [
            ('His', 'PRP$'),('house', 'NN'),('is', 'VBZ'),('in', 'IN'),
            ('the', 'DT'),('village', 'NN'),('though', 'IN'),(';', ':'),
            ('He', 'PRP'),('will', 'MD'),('not', 'RB'),('see', 'VB'),
            ('me', 'PRP'),('stopping', 'VBG'), ('here', 'RB'),('To', 'TO'),
            ('watch', 'VB'),('his', 'PRP$'),('woods', 'NNS'),('fill', 'VB'),
            ('up', 'RP'),('with', 'IN'),('snow', 'NNS'),('.', '.')
            ]
        ],
    [
        [
            ('My', 'PRP$'),('little', 'JJ'),('horse', 'NN'),('must', 'MD'),
            ('think', 'VB'),('it', 'PRP'),('queer', 'JJR'),('To', 'TO'),
            ('stop', 'VB'),('without', 'IN'),('a', 'DT'),('farmhouse', 'NN'),
            ('near', 'IN'),('Between', 'NNP'),('the', 'DT'),('woods', 'NNS'),
            ('and', 'CC'),('frozen', 'JJ'),('lake', 'VB'),('The', 'DT'),
            ('darkest', 'JJS'),('evening', 'NN'),('of', 'IN'),('the', 'DT'),
            ('year', 'NN'),('.', '.')
            ]
        ],
    [
        [
            ('He', 'PRP'),('gives', 'VBZ'),('his', 'PRP$'),('harness', 'NN'),
            ('bells', 'VBZ'),('a', 'DT'),('shake', 'NN'),('To', 'TO'),
            ('ask', 'VB'),('if', 'IN'),('there', 'EX'),('is', 'VBZ'),
            ('some', 'DT'),('mistake', 'NN'),('.', '.')
            ],
        [
            ('The', 'DT'),('only', 'JJ'),('other', 'JJ'),('sound', 'NN'),
            ('’', 'NNP'),('s', 'VBZ'),('the', 'DT'),('sweep', 'NN'),
            ('Of', 'IN'),('easy', 'JJ'),('wind', 'NN'),('and', 'CC'),
            ('downy', 'JJ'),('flake', 'NN'),('.', '.')
            ]
        ],
    [
        [
            ('The', 'DT'),('woods', 'NNS'),('are', 'VBP'),('lovely', 'RB'),
            (',', ','),('dark', 'JJ'),('and', 'CC'),('deep', 'JJ'),(',', ','),
            ('But', 'CC'),('I', 'PRP'),('have', 'VBP'),('promises', 'NNS'),
            ('to', 'TO'),('keep', 'VB'),(',', ','),('And', 'CC'),('miles', 'NNS'),
            ('to', 'TO'),('go', 'VB'),('before', 'IN'),('I', 'PRP'),
            ('sleep', 'VBP'),(',', ','),('And', 'CC'),('miles', 'NNS'),
            ('to', 'TO'),('go', 'VB'),('before', 'IN'),('I', 'PRP'),
            ('sleep', 'VBP'),('.', '.')
            ]
    ]
]
```

This kind of parsing can be done in Python using `nltk`, for instance with:

```python
import nltk


def nltk_parse(corpus):
    for doc in corpus:
        yield [
            nltk.pos_tag(nltk.word_tokenize(sent))
            for sent in nltk.sent_tokenize(doc)
        ]
```

or with `spacy`, e.g.:

```python
import spacy


def spacy_parse(corpus):
    nlp = spacy.load("en_core_web_sm")
    for doc in X:
        tagged = nlp(doc)
        yield [
            list((token.text, token.pos_) for token in sent)
            for sent in tagged.sents
        ]
```

Our `PosTagVisualizer` currently works with both Penn-Treebank (e.g. via `nltk`) and Universal Dependencies (e.g. via `spacy`)-tagged corpora, but does *not* perform the document parsing, paragraph segmentation, sentence segmentation, and part-of-speech tagging. This is because we do not want to require `nltk` or `spacy` as dependencies for people to use `yellowbrick` (since they are large dependencies, and are also still under active development). 

However, we could add a check to the `PosTagVisualizer` that checks to see if the user has `spacy` and `nltk` installed on their machine, and if they do, could optionally performed the parsing on behalf of the user. For instance, we could have a new `parse` argument that defaults to `False`, but if the user selects `nltk` (for example), we check to see if `nltk` is installed, and if so, have `fit` call an `nltk_parse` function before calling `draw` on the transformed corpus, and otherwise raise a communicative error message. 

```python
from yellowbrick.text import PosTagVisualizer

viz = PosTagVisualizer(parse="nltk")
viz.fit(raw_corpus)
viz.poof()
```

**Comment by dubesar** [comment]
@rebeccabilbro so in short currently we have to add the code for checking the dependencies and providing optional parsing which already exists in yellow brick via spacy or nltk.

**Comment by rebeccabilbro** [comment]
Hi again @dubesar, my apologies but I'm not sure I understand what you mean by "already exists in yellow brick" &mdash; as I explained in my response, yellowbrick currently *does not*:
 - check `nltk` or `spacy` dependencies
 - perform optional parsing

But those *are* indeed the two functionalities that we're hoping to add for the 4th item in this issue. 

Note that there are still some tricky things we'll have to figure out, for instance:
1. If the user specifies `PosTagVisualizer(parse="nltk")`, which of the `nltk` sentence and word tokenizers should we use? 
2. Which version of the `spacy` data models should we anticipate when we do `nlp = spacy.load("en_core_web_sm")`? The `en_core_web_sm` one is just one of many that users might have downloaded independently!! 

But, that's the general idea... Hope that makes sense!

**Comment by ekwiecinska** [comment]
Hi @rebeccabilbro, if no-one else is working on "optional parsing of raw text (only if nltk or spacy is installed)", I'll work on it this week.

**Comment by bbengfort** [comment]
@ekwiecinska please go ahead! Looking forward to a PR!

**Comment by bbengfort** [comment]
@rebeccabilbro I'm closing this issue in favor of #988 - if you think it's still interesting, perhaps we should create a new issue for named entities per your suggestion of having named entities be a separate visualizer?
