### ISSUE TITLE
Plots overlapping 

### ISSUE THREAD

**Issue by ansin218** [DistrictDataLabs/yellowbrick#789]
I have created a function like this: 

```
def VisualizeLearningCurve(X, y, clf_class, title, **kwargs):
    cv = StratifiedKFold(5, shuffle = False)
    sizes = np.linspace(0.3, 1.0, 10)

    title = 'neg_log_loss ' + title
    viz = LearningCurve(
        clf_class(**kwargs, solver = 'liblinear'), cv = cv, train_sizes = sizes,
        scoring = 'neg_log_loss', title = title
    )
    viz.fit(X, y)
    path = 'results/loss/' + title + '.png'
    viz.poof(outpath = path)
```

I am calling this function from a loop where my dataframe is filtered and is passed on to this function to generate the plots. However, all my plots are overlapping.

Suppose I have the loop running thrice, my first image contains one training and one validation curve. My next image from the second loop contains curves of current dataset and the previous one. Similarly, my third loop generates another image with curves from the first two loops plus the current one. 

I am not able to wrap my head around this problem now. Any help to make sure that each of my image only contains curves from the pertaining dataset that is being fed to the function?

**Comment by lwgray** [comment]
hi @ansin218,  It could be just a matter of creating a new axes object through every loop,  e.g.

```
def VisualizeLearningCurve(X, y, clf_class, title, **kwargs):
    cv = StratifiedKFold(5, shuffle = False)
    sizes = np.linspace(0.3, 1.0, 10)
    _, ax = plt.subplots() # Create a new figure

    title = 'neg_log_loss ' + title
    viz = LearningCurve(
        clf_class(**kwargs, solver = 'liblinear'), cv = cv, train_sizes = sizes,
        scoring = 'neg_log_loss', title = title, ax=ax
    )
    viz.fit(X, y)
    path = 'results/loss/' + title + '.png'
    viz.poof(outpath = path)
```

**Comment by ansin218** [comment]
Oh damn, that was silly of me. Nevertheless, thank you for pointing it out. The solution worked!
