### ISSUE TITLE
Remove `numba` test dependency once v0.43 bug is resolved

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#790]
An [update to `numba`](https://numba.pydata.org/numba-doc/dev/release-notes.html#version-0-43-0) was causing strange [errors](https://github.com/lmcinnes/umap/issues/209)  in the `umap-learn` library. Since our `UMAPVisualizer` depends on `umap-learn`, we observed the errors in a series of persistent Travis CI failures to the `UMAPVisualizer` tests. 

By way of a temporary fix, in #780 I pegged our test requirements to `numba==0.42` and `umap-learn==0.3`. However, once the issue is resolved by a later release of `numba`, we should update the test requirements accordingly.

**Comment by rebeccabilbro** [comment]
[This](https://twitter.com/numba_jit/status/1110883203252961280?refsrc=email&s=11&ref_src=twcamp%5Eshare%7Ctwsrc%5Eios%7Ctwgr%5Eemail)  might be relevant!

**Comment by nickpowersys** [comment]
I was testing conda installations for 3.7 on Linux, and saw that the dependency graph could not be solved without downgrading to 3.6.

When I removed the version requirements from

```
umap-learn==0.3
numba==0.42
```
the solver was able to solve without downgrading. I'm not sure whether this impacts the UMAPVisualizer output, but FYI.

numba has reached 0.44.1 https://pypi.org/project/numba/
umap-learn has reached 0.3.9 https://pypi.org/project/umap-learn/

Travis Miniconda 3.7 is automatically downgrading to 3.6 for this reason.
