### ISSUE TITLE
PCA projections on biplot are not clear for datasets with large number of features

### ISSUE THREAD

**Issue by percygautam** [DistrictDataLabs/yellowbrick#795]
**Problem**
The PCA projections visualized on a biplot are not clear, and various feature's projection can be seen to overlap with each other when working with a dataset with a large number of features. e.g. with credit dataset from yellowbrick.datasets
![bug1](https://user-images.githubusercontent.com/20489158/54920524-719ed980-4f29-11e9-9c8e-a64e1f1dc454.png)

This could be solved by considering only certain features in a particular dimension, to avoid overlapping of vectors. Work is required in selecting criteria for features.

**Comment by lwgray** [comment]
@percygautam thanks for opening this issue.  We are just returning from a hiatus and will address this after catching up on our backlog of PRs and Issues.

**Comment by bbengfort** [comment]
@percygautam if you have any specific suggestions related to this one, we'd be glad to hear it. As it stands we agree with your assessment but need a path forward to keep this issue open for one of our contributors to take on.
