### ISSUE TITLE
Multiplot API

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#8]
Seaborn has a FacetGrid - do we need something similar for generating multiple plots?

**Comment by rebeccabilbro** [comment]
https://stanford.edu/~mwaskom/software/seaborn/generated/seaborn.FacetGrid.html

**Comment by rebeccabilbro** [comment]
https://stanford.edu/~mwaskom/software/seaborn/generated/seaborn.factorplot.html#seaborn.factorplot

**Comment by rebeccabilbro** [comment]
https://stanford.edu/~mwaskom/software/seaborn/generated/seaborn.PairGrid.html#seaborn.PairGrid

**Comment by bbengfort** [comment]
See #176 and #168

**Comment by bbengfort** [comment]
Fixed in #176
