### ISSUE TITLE
ValueError: too many values to unpack (expected 2) using load_occupancy()

### ISSUE THREAD

**Issue by chiahsuy** [DistrictDataLabs/yellowbrick#801]
**Describe the bug**
In feature analysis step, the error occurs around this statement "X, y = load_occupancy()"

"ValueError: too many values to unpack (expected 2)"

However, if only one variable is used on the left hand side of assign operator, the error won't occur. (e.g., "y = load_occupancy()")

**To Reproduce**

```python
# Steps to reproduce the behavior (code snippet):
# Should include imports, dataset loading, and execution
# Add the traceback below
```

**Dataset**
Did you use a specific dataset to produce the bug? Where can we access it?

**Expected behavior**

**Traceback**

```
If applicable, add the traceback from the exception.
```
ValueError                                Traceback (most recent call last)
<ipython-input-3-859602daf482> in <module>
      3 
      4 # Load the classification data set
----> 5 X, y = load_occupancy()
      6 print(X)
      7 

ValueError: too many values to unpack (expected 2)

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - Python Version [e.g. 2.7, 3.6, miniconda]
 - Yellowbrick Version [e.g. 0.7]

Windows
Python 3.7
Yellowbrick most current one (Mar 29, 2019)

**Additional context**

**Comment by haleemason** [comment]
Hi @chiahsuy, this happened to me recently and it was due to the fact that I had loaded in another dataset for X and y in a previous cell of the Jupyter Notebook. If you are running an ml-demo from the recent Skills Session, try going to the Kernel Tab and clicking "Restart kernel and clear output"  to see if that helps.

**Comment by lwgray** [comment]
hi @chiahsuy,  we just returned from a hiatus and working our way through our backlog of issues and PRs.  Please know that we will get to this asap.

**Comment by rebeccabilbro** [comment]
Hi there @chiahsuy &mdash; just checking to see if @haleemason's solution worked for you? If so we can go ahead and close this issue. Thanks for coming to the skills session at UVA and for checking out Yellowbrick!

**Comment by rebeccabilbro** [comment]
Hello again @chiahsuy &mdash; I'm hoping we haven't heard back because @haleemason's solution worked great for you and now you're blazing ahead with your exploration of Yellowbrick! 😄  I'm going to go ahead and close this issue, but if your issues persist feel free to reopen! Thanks again!
