### ISSUE TITLE
Scree Plot for Pricipal Component Analysis

### ISSUE THREAD

**Issue by pswaldia** [DistrictDataLabs/yellowbrick#804]
**Describe the solution you'd like**
I would love to have a plot that shows the amount of variance explained by the prinicipal components. It can help to reduce the dimensionality of the features to the dimensions that explains the variance in the dataset the most.  It will help to find the optimal principal components without extensive searching.

**Examples**

![Screenshot 2019-04-01 at 21 09 36](https://user-images.githubusercontent.com/36327997/55340754-ef7f5980-54c2-11e9-8495-49e21bc3198b.png)

*This plot shows that around 350 features out of total 784 explains about 95% of the variance.*

**Comment by lwgray** [comment]
@pawaldia Awesome suggestion!  We are catching up on issues and PRs since we just returned from a short hiatus.  We will respond properly asap.

**Comment by lschumm** [comment]
```

**Comment by lschumm** [comment]
I've done a mockup of some code to make this style of Scree plot:

```
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.decomposition import PCA

df = pd.read_csv("yellowbrick/examples/data/concrete/concrete.csv")

pca = PCA(n_components=9)
pca.fit(df)

plt.plot(np.arange(1, len(df.columns) + 1), np.cumsum(pca.explained_variance_ratio_))
plt.xlabel('number of components')
plt.ylabel('cumulative explained variance')
plt.xticks(np.arange(1, len(df.coulmns + 1), step=1))
```

![An example Scree plot](https://user-images.githubusercontent.com/15222678/57304707-d4999980-70ad-11e9-89d8-b70c2c836ebe.png)

**Comment by pdamodaran** [comment]
@lschumm - fyi - we have a visualizer to do this - it can be found here:

https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/features/decomposition.py

**Comment by lschumm** [comment]
In that case, we ought to close this issue @pdamodaran

**Comment by pswaldia** [comment]
As directedby @pdamodaran , there's already a scree plot visualizer present in yellowbrick for this purpose. I am closing this issue for now.

**Comment by BrandonKMLee** [comment]
Are there any Elbow-like tool for Determining optimal PCA count?

**Comment by bbengfort** [comment]
@BrandonKMLee I had been working on an explained variance plot for this - the WIP PR is here: https://github.com/DistrictDataLabs/yellowbrick/pull/1037 -- it's been a while since I've taken a look at it, but if you want to help get it across the line or just use the code from that PR, I think that's what you're looking for.
