### ISSUE TITLE
Review and Write Documentation

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#81]
Get the following pages in the documentation written:
- [x] Introduction to Yellowbrick 
- [x] Quickstart Guide 
- [x] Examples Tutorial (from notebook) 
- [x] Yellowbrick API 
- [x] About Page 
- [x] Documentation from docstrings 

See #36 #77 and #38

**Comment by rebeccabilbro** [comment]
Ok, preliminary documentation complete: https://github.com/DistrictDataLabs/yellowbrick/tree/develop/docs.
