### ISSUE TITLE
Create User Testing Notebook

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#82]
We have signups on the Yellowbrick testers form, and we want to engage them. 

Create an Jupyter notebook that starts with a tutorial (mostly Markdown). Show how to use different Visualizers. Then turn it over to the user to get a dataset from UCI and step through the different analysis methods to detect bugs and also create a gallery of visualization. 

At the end solicit feedback via a Google Form and second stage user testing based on their experience. 

The goal is to capture as many bugs or issues as possible (e.g. I'd like to change the color but can't). 

Motivate testers to submit feedback on form rather than as issues so that we can organize them better.

**Comment by bbengfort** [comment]
@rebeccabilbro @ojedatony1616 @lauralorenz : the Google form to collect testing responses is drafted and ready for you to review:

https://docs.google.com/a/bengfort.com/forms/d/11-rPVhbakdT5hPiCZvEXLXOc293Ac6ma36f9BxIxAIc/edit?usp=sharing

**Comment by rebeccabilbro** [comment]
From Ben: 

The "user testing notebook" is called (weirdly) [Getting Started with Yellowbrick](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/examples/Getting%20Started%20with%20Yellowbrick.ipynb) - so we'll need to discuss that. I think I was having trouble with a narrative that was different from the examples notebook - particularly as the user testing requires folks to focus on regression or classification. We should also discuss the Google Form I created for user feedback.

**Comment by rebeccabilbro** [comment]
Ok @bbengfort I've updated both the alpha testing guide and the evaluation form.  I'm going to close out this ticket and create a new card for the backlog  for the *deployment* of the alpha study that we can pull into the next sprint.
