### ISSUE TITLE
Add yellowbrick blurb and link to Matplotlib docs

### ISSUE THREAD

**Issue by tacaswell** [DistrictDataLabs/yellowbrick#828]
Please add your self to: https://matplotlib.org/thirdpartypackages/index.html / https://github.com/matplotlib/matplotlib/blob/master/doc/thirdpartypackages/index.rst

**Comment by bbengfort** [comment]
@tacaswell done: https://github.com/matplotlib/matplotlib/pull/14051; thank you!
