### ISSUE TITLE
'conda envs' url in the documentation is invalid

### ISSUE THREAD

**Issue by joeyzhang823** [DistrictDataLabs/yellowbrick#831]
**Describe the issue**
In the 'Forking the Repository' session of the documents (http://www.scikit-yb.org/en/latest/quickstart.html), 'conda envs' points to an invalid link.

Please consider use this link instead: https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html

@DistrictDataLabs/team-oz-maintainers

**Comment by lwgray** [comment]
fixed by #832
