### ISSUE TITLE
Discrimination Threshold Visualizer

### ISSUE THREAD

**Issue by chrisRedwine** [DistrictDataLabs/yellowbrick#84]
Very cool package - I'm interested in starting to contribute at some point in the coming months. 

As a post-learning task, I often find it helpful for classification problems to plot various scores (precision/recall/F1/etc.) over all possible discrimination thresholds (similar to a ROC plot), to gain an intuition for optimal thresholds to use when the model is deployed. Something like this (rough example):

![image](https://cloud.githubusercontent.com/assets/11069501/19951453/24d3fb9c-a12c-11e6-940b-0e1b7e02c9f0.png)

Where the x-axis is the threshold, and the y-axis is the score. In this example, I might choose 30 as my threshold to maximize F1, let's say.

Of course, this could be generalized and enriched, etc. Thoughts on this as a potential feature?

**Comment by rebeccabilbro** [comment]
@chrisRedwine very interesting suggestion! In thinking through your idea, it seems like this might make a good `MultiModelVisualizer`, a subclass of the not yet implemented  `MultiModelMixin` base class. Would you be interested in starting by contributing a new `ScoreVisualizer` that enables the user to visualize the thresholds for train-test splits? Then once we've received the PR, and updated the API to handle `MultiModelMixin` we can work together to refactor to pull it in.

**Comment by bbengfort** [comment]
@chrisRedwine sorry it's taken so long for us to get back to you - I've just been going through the backlog of issues and noticed your suggestion. This visualizer has actually been in Yellowbrick for a version or two now, but I've updated it to include f1 score as well as some annotations. You can find the docs for it here: 

http://www.scikit-yb.org/en/develop/api/classifier/threshold.html
