### ISSUE TITLE
Make minor changes to documentation (tutorial & contributing) to improve readability and or grammar.  

### ISSUE THREAD

**Issue by brl1906** [DistrictDataLabs/yellowbrick#843]
**Describe the issue**
A clear and concise description of what the issue is.

@DistrictDataLabs/team-oz-maintainers
I am proposing the changes to:
* yellowbrick/docs/tutorial.rst in the 'Model Selection Triple' & 'Feature Extraction' sections. 
* yellowbrick/docs/contributing/getting_started.rst in the 'Forking the Repository' section.
* yellowbrick/docs/contributing/developing_visualizers.rst in the 'Developing Visualizers' section.

The changes would **change 3 sentences in total** and:
1. fix one grammatical error
2. make the writing more concise

To facilitate discussion and better understanding of the proposed changes I have included the below image of them:
<img width="1088" alt="proposed-docs-changes-image" src="https://user-images.githubusercontent.com/16468633/57328437-6d94d880-70df-11e9-8004-b5f973a31cd5.png">

**Comment by lwgray** [comment]
@brl1906 thanks for opening this issue.  However, We are currently working our way through issues pertaining to our v1.0 release and will possibly get to this during our next semester of contributing.  If this is something you would like to work on as well as other issues , you can become a core contributor this upcoming semester.  You can sign up below

https://forms.gle/NT3inRQhaV278kf96
