### ISSUE TITLE
Change ordering in which opening a PR is suggested in the Contributing Guide in Docs

### ISSUE THREAD

**Issue by lwgray** [DistrictDataLabs/yellowbrick#849]
We would like to change the ordering of the steps in the contributing guide.  Currently,  we have the contributors opening a PR immediately, meaning prior to adding any significant code to the PR.  

This has lead us to coaching people on how to solve issues instead of reviewing  a somewhat functional PR.  I suggest reordering of the contributing steps so that the opening of the PR is after doing some coding.  

Below are the locations where this would need to be changed.

https://github.com/DistrictDataLabs/yellowbrick/blob/d13065786b25323558c493222d39b67f6b5243d9/docs/contributing/getting_started.rst

https://github.com/DistrictDataLabs/yellowbrick/blob/2869f65a8c37b34b86a520bd6fdb866f33198596/CONTRIBUTING.md

@DistrictDataLabs/team-oz-maintainers

**Comment by ndanielsen** [comment]
Thanks for opening this issue. 

As mentioned the other night, I recommend in the docs to direct folks to make contributions of new visualizers and related tooling to the `contrib` folder. 

This is a great place to incubate and development these additions to the project until they are ready to be hoisted into the main package.  


@lwgray
