### ISSUE TITLE
How to set xticks to modify ax?

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#85]
Need to figure out how to call set_xticks on the current axes rather than the entire plot. See [`finalize` for ClassBalance and ClassificationReport](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/classifier.py).

**Comment by rebeccabilbro** [comment]
This appears to be fairly straightforward: see [ParallelCoordinates](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/features/pcoords.py#L192):

```python
self.ax.set_xticks(x)
self.ax.set_xticklabels(self.features_)
self.ax.set_xlim(x[0], x[-1])
```

**Comment by bbengfort** [comment]
@rebeccabilbro doing some backlog grooming; is this resolved?

**Comment by rebeccabilbro** [comment]
Yes, resolved with [this commit](https://github.com/DistrictDataLabs/yellowbrick/commit/37f4d560ee6420c1b1610476d801e747a44b5b36). Marking complete and closing this card.
