### ISSUE TITLE
Add Q-Q plot to the yellowbrick.regressor.residuals class

### ISSUE THREAD

**Issue by tirthajyoti** [DistrictDataLabs/yellowbrick#853]
You already have a histogram feature for the `ResidulaPlot` method.
It will be immensely helpful to add a standard normality check method to the parent `yellowbrick.regressor.residuals` class like Q-Q plot.

Your functional interface is gearing up to be similar to statistical languages like **R** where you can throw the fitted model inside a function to generate more insight - mostly a visualization or a statistical score.

[Q-Q plot](https://en.wikipedia.org/wiki/Q%E2%80%93Q_plot) ability will be one of such basic statistical insights that can add value.

**Comment by lwgray** [comment]
@tirthajyoti Thanks for opening this issue.  This is an excellent suggestion.  If this is something you would like to work on then you could signup as a core-contributor during our fall semester and begin working on it then.   https://forms.gle/NT3inRQhaV278kf96

**Comment by tirthajyoti** [comment]
I will see what I can do. Is it OK if I use a [`SciPy` method](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.probplot.html) for this to keep the code compact and fast?

**Comment by lwgray** [comment]
@tirthajyoti We definitely use scipy methods... for instance https://github.com/DistrictDataLabs/yellowbrick/blob/76b2f8854a44dde534609b9545d8215d43c6555b/yellowbrick/features/rankd.py#L21

I hope to see you this Fall
