### ISSUE TITLE
resolve_colors() needs a way to be able to pull colormaps from PALETTES

### ISSUE THREAD

**Issue by mgarod** [DistrictDataLabs/yellowbrick#855]
The func `resolve_colors()` in https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/style/colors.py does not have any way to use colors defined in https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/style/palettes.py

See conversation here for some background https://github.com/DistrictDataLabs/yellowbrick/pull/837#discussion_r283103118

**Comment by thisHermit** [comment]
Hi @mgarod, i was assigned to this issue by @lwgray.
Is this how the issue was supposed to be resolved?

**Comment by lwgray** [comment]
@thisHermit did you open a PR?

**Comment by thisHermit** [comment]
@lwgray, sorry for my mistake, I just fixed it.

**Comment by thisHermit** [comment]
@lwgray, just pulled up an PR.
