### ISSUE TITLE
Best fit line axes

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#86]
In `PredictionError` plot, the axis are extending on either side beyond the plotted horizontal line. We think the problem is the [best fit line](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/bestfit.py) attempts to go from axis to axis, but should go from limit to limit.

**Comment by bbengfort** [comment]
I believe this was fixed in 1001b6f when we made the aspect ratio square and added the 45 degree line to the plot.
