### ISSUE TITLE
Additional support for label encoders

### ISSUE THREAD

**Issue by jaydee829** [DistrictDataLabs/yellowbrick#861]
ConfusionMatrix already supports passing 'label_encoder' as an argument, but many of the other classification visualizers do not. I suggest that the feature to support an encoder be added to these other methods.

In particular, I was trying to use ClassPredictionError but noted it did not support this feature. I think it would be almost a copy/paste of lines 163-170 in confusion_matrix.py into class_prediction_error.py

**Comment by jaydee829** [comment]
Nevermind, ClassPredictionError functions as intended, user error

**Comment by bbengfort** [comment]
@jaydee829 glad you figured it out!
