### ISSUE TITLE
CI Tests fail due to NLTK download first byte timeout

### ISSUE THREAD

**Issue by nickpowersys** [DistrictDataLabs/yellowbrick#868]
**NLTK Downloader**

Here is a sample of an NLTK download in progress:

> [nltk_data]    | Downloading package twitter_samples to
[nltk_data]    |     C:\Users\appveyor\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\twitter_samples.zip.
[nltk_data]    | Downloading package omw to
[nltk_data]    |     C:\Users\appveyor\AppData\Roaming\nltk_data...
[nltk_data]    | Error downloading 'omw' from
[nltk_data]    |     <https://raw.githubusercontent.com/nltk/nltk_data
[nltk_data]    |     /gh-pages/packages/corpora/omw.zip>:   HTTP Error
[nltk_data]    |     503: first byte timeout
Error installing package. Retry? [n/y/e]

There is a related issue:
https://github.com/nltk/nltk/issues/1647

Could cached NLTK downloads provide the necessary NLTK data with sufficient freshness?

@DistrictDataLabs/team-oz-maintainers

**Comment by ndanielsen** [comment]
Thanks for creating this issue. It seems to be resolved for the moment, but we can definitely think how to improve this

**Comment by bbengfort** [comment]
This was a temporary bug that was occurring but appears to have been resolved on the CI side.
