### ISSUE TITLE
matplotlib pip testing package to eliminate Freetype font differences across environments

### ISSUE THREAD

**Issue by nickpowersys** [DistrictDataLabs/yellowbrick#892]
@ndanielsen  TLDR: Based on the validated success of the testing version of matplotlib on conda in eliminating Freetype differences on CI builds, it seems worthwhile to ask the matplotlib team if there is the possibility of a pip version being released for testing as well (at least for Windows). The number of affected tests would go well beyond the 31 xfailing on Appveyor generally and Linux conda here: I took tests from the test_classifier folder where there were tols>0.1 and removed them. From this, 14 tests were failing. This is only a single directory: there could be well over 100 tests where Freetype differences could be eliminated across environments.

- Windows conda: Freetype differences are eliminated on CI builds and locally with mpl testing package
- Windows pip: If matplotlib team could provide testing package, have the potential to eliminate diffs
- Linux conda: Local and Travis testing works on all images

### Background
The majority of xfails on Windows (both regular Python and Miniconda) can be removed following the removal of x/y labels and legends, but there is other text that remains

While the baseline images were updated, the xfails that were in place were not removed, because I first wanted to analyze which images would still fail and what overlap there was with Linux, which is what led to the 31 xfailing images listed below.

The finding that most Windows xfails can be removed is based on the analysis here (the builds were on the "windiffs" branch):
https://github.com/DistrictDataLabs/yellowbrick/pull/823#issue-272241944

### Image comparison differences based on less common text elements
The number of tests that are associated with any particular text element are currently relatively small (3-10). Therefore, having a more scalable approach to remove or otherwise reconcile differences in text across OS platforms and/or Python distributions (PyPI/Anaconda) and that will work with future visualizers is more desirable than dealing with such differences for each kind of text.

A common version of Freetype may provide a way to deal with this, if it can be used easily on CI builds and in local testing environments. There is a conda package for testing matplotlib that aims to get rid of Freetype differences across environments.,

### LOCAL Windows conda and Linux conda environments using the testing version of matplotlib
All 31 tests that have been xfailing with the regular version of `matplotlib` PASSED with the `testing` version.
(The testing version of matplotlib has a specific version of Freetype.)  

### CI Appveyor conda and Travis conda using the testing version of matplotlib
All 31 tests PASS on Appveyor
https://ci.appveyor.com/project/nickpowersys/yellowbrick/builds/25701049

25/31 tests PASS on Travis
https://www.travis-ci.org/nickpowersys/yellowbrick/jobs/553964607

**In order to ensure that Travis testing succeeds, the regular matplotlib package should not be installed and uninstalled before installing the matplotlib testing package.**

The following are instances of such tests that have been identified to date:

### Labels on the right side
- test_cluster/test_elbow.py
  - test_timings (it uses poof instead of finalize)
- test_features/test_rankd.py
  - test_rank2d_covariance
  - test_rank2d_integrated_numpy
  - test_rank2d_integrated_pandas
  - test_rank2d_kendalltau
  - test_rank2d_pearson
  - test_rank2d_spearman

### Only one of multiple subplots has text elements removed
- test_base.py
  - test_draw_visualizer_grid
  - test_draw_with_cols
  - test_draw_with_rows

### Labels for each iso_f1_curve
- test_classifier/test_prcurve.py
  - test_binary_probability_decision
  - test_custom_iso_f1_scores
  - test_multiclass_probability
  - test_quick_method

### Labels on the plots
- test_cluster/test_icdm.py
  - test_affinity_tsne_no_legend
  - test_kmeans_md
  - test_quick_method

### Labels on plots besides the main one
- test_regressor/test_residuals.py
  - test_residuals_plot
  - test_residuals_plot_pandas
  - test_residuals_quick_method
  - test_features/test_jointplot.py

### Non-text-based differences as well
- test_features/test_jointplot.py
  - test_columns_double_index_discrete_y_hist
  - test_columns_double_int_index_numpy_no_y_hist
  - test_columns_double_str_index_pandas_no_y_hist
  - test_columns_none_x_hist
  - test_columns_none_x_y_hist
  - test_columns_single_int_index_numpy_hist
  - test_columns_single_str_index_pandas_hist

### Text on the plot
- test_features/test_radviz.py
  - test_integrated_radviz_with_pandas
  - test_text/test_freqdist.py
  - test_integrated_freqdist

### Text within confusion matrix
- test_classifier/test_confusion_matrix.py
  - test_pandas_integration
  - test_quick_method

**Comment by ndanielsen** [comment]
@nickpowersys thanks for your work and analysis on this. At the moment, the maintainers are trying to prioritize the 1.0 release items as we haven't had a release in a while. 

You are more than welcome to join us on the 1.0 efforts. =)

Obviously any efforts in this arena will be highly valued and are definitely important but for any feedback / commentary will be slightly on the back burner until 1.0 is shipped! I know you understand!

**Comment by bbengfort** [comment]
@nickpowersys this is certainly an ambitious approach to fixing the differences between Windows/Miniconda and our tests. Unfortunately, I think this might be a bit too big of a lift for us in the near term. I believe issues #911 #916 and #918, as well as all the other contributions you've made to date, will go a long way to ensuring we have robust tests and coverage across multiple operating systems and have a better ROI for the amount of work required.
