### ISSUE TITLE
ImportError: DLL load failed: %1 不是有效的 Win32 应用程序。

### ISSUE THREAD

**Issue by pangwh** [DistrictDataLabs/yellowbrick#897]
我python版本是3.7.3,使用pip install yellowbrick安装好了之后，在程序里面yellowbrick用鼠标可以点进去，说明导入成功了，yellowbrick使用版本是0.9.1   运行的时候报ImportError: DLL load failed: %1 不是有效的 Win32 应用程序。   搞不懂为什么   我是win1064位的系统，下载的python也是64位的

**EDIT from Maintainer:**
English translation supplied by Google Translate:

My python version is 3.7.3. After installing it with pip install yellowbrick, the yellowbrick can be clicked in the program, indicating that the import is successful. The version of yellowbrick is 0.9.1 when running. ImportError: DLL load failed: % 1 is not a valid Win32 application. I don't understand why I am a win1064 bit system, and the downloaded python is also 64-bit.

**Comment by bbengfort** [comment]
Hello @pangwh -- sorry to hear that you're having trouble with your Python installation. I've never encountered this exception before, Yellowbrick is pure Python and therefore has no C dependencies that need to be compiled to a specific architecture. Unless you installed Yellowbrick with `conda`, I'm not sure what in Yellowbrick could be raising this exception. Could you specify the exact code you're running when the exception is raised and supply the exception traceback please? 

Yellowbrick does depend on numpy, scipy, matplotlib, and scikit-learn; all of which do have C dependencies. Are you getting the same exception when you try to use these packages? The only thing I found on the matter was [this stackoverflow post](https://stackoverflow.com/questions/19019720/importerror-dll-load-failed-1-is-not-a-valid-win32-application-but-the-dlls). 

使用谷歌翻譯翻譯成中文（繁體）：

你好@pangwh  - 很遺憾聽到你的Python安裝有問題。 我以前從未遇到過此異常，Yellowbrick是純Python，因此沒有需要編譯到特定體系結構的C依賴項。 除非你用`conda`安裝了Yellowbrick，否則我不確定Yellowbrick會引發這個異常。 您是否可以指定在引發異常時運行的確切代碼並提供異常回溯？

Yellowbrick確實依賴於numpy，scipy，matplotlib和scikit-learn; 所有這些都有C依賴項。 當您嘗試使用這些包時，是否會遇到相同的異常？ 我在這件事上唯一發現的是 [這個stackoverflow帖子](https://stackoverflow.com/questions/19019720/importerror-dll-load-failed-1-is-not-a-valid-win32-application-but-the-dlls)。

**Comment by xiaoshushu0606** [comment]
hello @pangwh, 请问您说“在程序里面yellowbrick用鼠标可以点进去“是指什么程序？最后运行报错的是什么python呢（是用IDE还是用anaconda运行的）？可以提供完整的报错和异常回溯吗

**Comment by pangwh** [comment]
> 
> 
> hello @pangwh, 请问您说“在程序里面yellowbrick用鼠标可以点进去“是指什么程序？最后运行报错的是什么python呢（是用IDE还是用anaconda运行的）？可以提供完整的报错和异常回溯吗
> 
> **EDIT from Maintainer:**
> _English translation supplied by Google Translate_
> 
> Hello @pangwh, I would like to ask you to say "yellowbrick in the program can be clicked with the mouse" What is the program? Finally, what python is running the error (is it running with IDE or anaconda)? Can I provide complete error and exception backtracking?
问题已经解决了，是其它包的安装版本不对，导致不能用yellowbrick，多谢帮助

**Comment by xiaoshushu0606** [comment]
> > hello @pangwh, 请问您说“在程序里面yellowbrick用鼠标可以点进去“是指什么程序？最后运行报错的是什么python呢（是用IDE还是用anaconda运行的）？可以提供完整的报错和异常回溯吗
> > **EDIT from Maintainer:**
> > _English translation supplied by Google Translate_
> > Hello @pangwh, I would like to ask you to say "yellowbrick in the program can be clicked with the mouse" What is the program? Finally, what python is running the error (is it running with IDE or anaconda)? Can I provide complete error and exception backtracking?
> 
> 问题已经解决了，是其它包的安装版本不对，导致不能用yellowbrick，多谢帮助
> 
> **EDIT from Maintainer:**
> _English translation supplied by Google Translate_
> 
> The problem has been solved, the installation version of other packages is wrong, so you can't use yellowbrick, thank you for your help.

很开心你已经解决了问题。后续使用yellowbrick如果遇到其他问题也欢迎提问。
