### ISSUE TITLE
Best Fit Lines

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#9]
Our visualization uses best fit lines, and we need a mechanism to automatically add these to the scatter plots.

**Comment by rebeccabilbro** [comment]
Seaborn has linear regression model plotting: https://stanford.edu/~mwaskom/software/seaborn/tutorial/regression.html

**Comment by rebeccabilbro** [comment]
Other line-of-best-fit methods with matplotlib:
 - http://matthiaseisen.com/pp/patterns/p0170/
 - http://stackoverflow.com/questions/22239691/code-for-line-of-best-fit-of-a-scatter-plot-in-python
 - http://stackoverflow.com/questions/19068862/how-to-overplot-a-line-on-a-scatter-plot-in-python

**Comment by dot2dotseurat** [comment]
I will give this one a shot. -Meghan

**Comment by rebeccabilbro** [comment]
Thanks to @naturallogofx for the preliminary implementation of the linear best fit lines! Next steps are to put all of them into the API format and develop similar implementations for quadratic and exponential curves (issue #30). I'm thinking we should create a bestfit.py with a BestFit base object and then have LinearBestFit, QuadraticBestFit, ExponentialBestFit classes.
