### ISSUE TITLE
ConfusionMatrix label encoding when passing fitted model

### ISSUE THREAD

**Issue by scholl-c** [DistrictDataLabs/yellowbrick#900]
**Describe the bug**
ConfusionMatrix with a pre-trained model does show up as expected, when putting sparse feature matrix into the .score()-method. But when passing a dict with the mapping in label_encoder it throws an  error message: "ValueError: At least one label specified must be in y_true". 

**To Reproduce**

```python
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from yellowbrick.classifier import ConfusionMatrix
from sklearn.ensemble import RandomForestClassifier
import pandas as pd

data = pd.DataFrame({'text': ["big house", "cat eats mouse", "car drives fast", "deep water", "blue sky last", "hello world", "big tree"], 'cat':[1,1,2,1,2,2,1]})

X = data["text"]
y = data["cat"]
classes = [1,2]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

feature_pipe = Pipeline([
    ('feature', CountVectorizer(analyzer="char"))
])

model_pipe = Pipeline([
    ('model', RandomForestClassifier(n_estimators=10, random_state=6))
])

features = feature_pipe.fit_transform(X_train, y_train)
features_test = feature_pipe.transform(X_test)

fitted_model = model_pipe.fit(features, y_train)

# not working
viz = ConfusionMatrix(fitted_model, classes=[1,2], label_encoder={1:"first class", 2:"second class"})

# working
#viz = ConfusionMatrix(fitted_model)

viz.score(features_test, y_test)
viz.poof()
```

**Expected behavior**
Show confusion matrix with labels "first class" and "second class"

**Traceback**

```
<ipython-input-9-d34ba74314c8> in <module>
     33 #viz = ConfusionMatrix(fitted_model)
     34 
---> 35 viz.score(features_test, y_test)
     36 viz.poof()

/usr/lib/python3.7/site-packages/yellowbrick/classifier/confusion_matrix.py in score(self, X, y)
    172         # Compute the confusion matrix and class counts
    173         self.confusion_matrix_ = confusion_matrix_metric(
--> 174             y, y_pred, labels=self.classes_, sample_weight=self.sample_weight
    175         )
    176         self.class_counts_ = self.class_counts(y)

/usr/lib/python3.7/site-packages/sklearn/metrics/classification.py in confusion_matrix(y_true, y_pred, labels, sample_weight)
    260         labels = np.asarray(labels)
    261         if np.all([l not in y_true for l in labels]):
--> 262             raise ValueError("At least one label specified must be in y_true")
    263 
    264     if sample_weight is None:

ValueError: At least one label specified must be in y_true
```

**Desktop (please complete the following information):**
 - OS: Manjaro (but having the issue also on Windows10)
 - Python Version 3.7.3
 - Yellowbrick Version 0.9.1

**Comment by lwgray** [comment]
hi @scholl-c Thanks for opening this issue.  I think you would simply need to change the name of the classes (see in code below)

    viz = ConfusionMatrix(fitted_model, classes=["first class", "second class"], label_encoder={1:"first class", 2:"second class"})

![image](https://user-images.githubusercontent.com/1000117/60466882-ed907800-9c22-11e9-9eeb-9e387aea3eff.png)

**Comment by rebeccabilbro** [comment]
@scholl-c Hope this helped resolve your issue! If you're still having trouble with the encoding, feel free to let us know via the [listserv](https://groups.google.com/forum/#!forum/yellowbrick) &mdash; you can also check out the [stackoverflow post](https://stackoverflow.com/questions/54646168/error-creating-confusion-matrix-although-label-encoding-done-on-target-variable) related to this question.
