### ISSUE TITLE
User cannot set color for FrequencyVisualizer

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#906]
**Describe the bug**
The `FrequencyVisualizer` [takes a `color` parameter](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/text/freqdist.py#L129), but it doesn't actually know what to do with it!

**To Reproduce**

```python
from yellowbrick.text import FreqDistVisualizer
from yellowbrick.datasets import load_hobbies
from sklearn.feature_extraction.text import CountVectorizer

# Load the text data
corpus = load_hobbies()
y = LabelEncoder().fit_transform(corpus.target)

vectorizer = CountVectorizer(stop_words='english')
docs       = vectorizer.fit_transform(corpus.data)
features   = vectorizer.get_feature_names()

visualizer = FreqDistVisualizer(
    features=features, orient='v', size=(600, 300), colors=["yellow"]
)
visualizer.fit(docs)
visualizer.poof()
```

**Dataset**
Just used the hobbies corpus from Yellowbrick.

**Expected behavior**
Yellow bars!

**Actual behavior**
![image](https://user-images.githubusercontent.com/8760385/60550513-3c5b1200-9cf6-11e9-8257-913f41c76f05.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Python Version: 3.7
 - Yellowbrick Version: develop

**Comment by lwgray** [comment]
@rebeccabilbro Thank you so much for submitting this bug!  :smile_cat:   We are undergoing a major push toward our next development milestone (version 1.0) woohoo!   As soon as we have finished up we will revisit this bug and get it fixed.  Have a Happy 4th of July
