### ISSUE TITLE
Verify that test fixtures for synthetic datasets are pytest fixtures

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#910]
While #907 resolves #682, we would also like to have a consistent way of testing Yellowbrick visualizers using synthetic datasets (e.g. synthetic clustering data, supervised learning datasets with a certain number of features/noise/etc). _Note: currently several tests do this in ad hoc fashion (e.g. in [`test_pca`](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/tests/test_features/test_pca.py#L38-L51)), so may require some refactoring._

This may be a good opportunity to resolve the rest of the outstanding `Dataset.to_numpy` and `Dataset.to_pandas` updates.

**Comment by bbengfort** [comment]
This has been resolved during the Visualizer audit.
