### ISSUE TITLE
Matplotlib 3.1.1 impacts some visual tests

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#912]
Matplotlib 3.1.1 (released on July 1, 2019) broke some of our tests, particularly the Rank2D tests with very big RMSE (~40) and very different diff images. For now in in #907 I have regenerated the baseline images for Rank2D so that our tests will pass on Travis and Appveyor, but I have not changed the `tests/requirements.txt` (except to note this strange behavior). Running the tests with `matplotlib==3.1.0` will result in image comparison failures for Rank2D. We should investigate what the behavior is for other matplotlib versions and determine what has changed in 3.1.1 that changed the Rank2D images (but not, say, the Confusion Matrix or Classification Heatmap) so drastically.

**Comment by nickpowersys** [comment]
I looked at plots on Windows conda under 3.1.0 and 3.0.3 - both are different from 3.1.1. baseline in the same way (~40).

The difference is most likely due to do to a recent fix for the conversions between types for stacked bar charts (bar and barh). It had a 3.1 milestone:
https://github.com/matplotlib/matplotlib/issues/10788#issuecomment-373177134

**Comment by nickpowersys** [comment]
The heights of rows are no longer consistent within 3.1.1, as compared to 3.1.0 and 3.0.3. Exactly where this would need to be corrected, if it is a bug in matplotlib, or a needed change in yb, is not clear to me as yet.

This is across the 6 Rank2D visualiers, but here is the rank2d_integrated_numpy visualizer:

**Integrated NumPy 3.0.3**
![rank2d_integrated_numpy_303](https://user-images.githubusercontent.com/4530874/60759074-8db01d80-9fe4-11e9-8e39-3b2bd966fa7d.png)

**Integrated NumPy 3.1.0**
![rank2d_integrated_numpy_310](https://user-images.githubusercontent.com/4530874/60759077-94d72b80-9fe4-11e9-8705-2ca961f8462a.png)

**Integrated NumPy 3.1.1**
![rank2d_integrated_numpy_311](https://user-images.githubusercontent.com/4530874/60759081-a4567480-9fe4-11e9-95d8-dc82fdf5df26.png)

**Comment by nickpowersys** [comment]
Even when reverting to the yb commit https://github.com/DistrictDataLabs/yellowbrick/commit/1bb171cafb468ea6867668099c1b4a0f23db2b79 from prior to the release of 3.1.1, but using 3.1.1, the heights of the rows are inconsistent.

**Comment by nickpowersys** [comment]
I would recommend that matplotlib!=3.1.1 be added to requirements.txt and tests/requirements.txt to avoid users and contributors installing with 3.1.1. I can file a PR for this, include the previous Rank2D images in it, and create a matplotlib issue, pointing to this yb issue for illustration. Does this sound reasonable?

**Comment by rebeccabilbro** [comment]
>I would recommend that matplotlib!=3.1.1 be added to requirements.txt and tests/requirements.txt to avoid users and contributors installing with 3.1.1. I can file a PR for this, include the previous Rank2D images in it, and create a matplotlib issue, pointing to this yb issue for illustration. Does this sound reasonable?

Thanks for all this great research you've been doing into this issue @nickpowersys! If you wouldn't mind holding off on the PR for just a bit longer as the maintainers are still powering through [some of those contagious issues](https://github.com/DistrictDataLabs/yellowbrick/pull/894#issuecomment-507370010). In the meantime though, If you could do a bit more digging into this, that would be great! A few open questions seem to be:

1. Does the same behavior occur between Matplotlib 3.1.0 and 3.1.1 using a different dataset? E.g. credit or bikeshare? Perhaps there is some data type checking we should be doing from inside the visualizer to ensure the proper dimensions?
2. Specifically what changed in Matplotlib between 3.1.0 and 3.1.1 that is causing this discrepancy in the Rank2D plots? Maybe @tacaswell or @jklymak can help point us in the right direction? 
3. Why is the behavior manifesting in Rank2D but not in any of the other visualizers?

**Comment by jklymak** [comment]
This was a bug and should be fixed 3.1.2.  Sorry about that.  https://github.com/matplotlib/matplotlib/pull/14677

**Comment by rebeccabilbro** [comment]
Thanks for the speedy response @jklymak; btw the mpl team are total badasses &mdash; thank you, thank you, thank you for all you do! And thanks @nickpowersys for offering to do the PR, but I'll go ahead and open one now since I already have a branch on my local with the repairs to the images 😉. Stay tuned!
