### ISSUE TITLE
Question about fitting of data in examples/regression.ipynb

### ISSUE THREAD

**Issue by bhishanpdl** [DistrictDataLabs/yellowbrick#915]
There is a very good example of regression using `yellowbrick` in examples/regression.ipynb file. When looking at the Ridge regression, the residual plot looks like heteroscedastic. I suggest data transforming or using any other data modeling rather than simple linear regression. Or at least explain the assumptions of linear regression before blinding fitting linear regression to the data.

**Comment by lwgray** [comment]
hi @bhishanpdl Thank you so much for using Yellowbrick and for pointing this out.  We will definitely take a look at it.  I will be passing this on to a core contributor.  Did you want to provide other info?  Like, suggestions for data transformation or another data modeling technique or what assumptions should be explained, etc....

**Comment by rebeccabilbro** [comment]
Hi again @bhishanpdl &mdash; since the conversation here has gone a bit stale, I'm going to archive this issue. If you'd like to revisit this in the future with a more specific proposal for an update to our docs, we'd love to have you contribute!
