### ISSUE TITLE
Migrate Windows Miniconda builds to Travis to speed up PR turnaround

### ISSUE THREAD

**Issue by nickpowersys** [DistrictDataLabs/yellowbrick#919]
I am suggesting trying migrating Miniconda builds to Travis. I have determined how to resolve the issue on Windows CI that resulted in #894, but Travis would offer better overall build times for each successful Travis+Appveyor build than continuing with Miniconda on Appveyor.

#### Why Appveyor total build times are longer than on Travis

- Jobs sequential
- Also seems to be additional time needed between jobs in each build

Sample times from recent commits are below.

Having the ability to use either Appveyor or Travis for Windows in general should remain to remain resilient to issues on either CI service, but the discrepancy in total build times between them can be adjusted.

#### Impact of migrating Miniconda greater per job than regular Python

- Each Miniconda job taking longer by up to 2min, 45s.

#### Impact on successful build times

- Potential 12-21 minute reduction in successful build times, depending on whether both 3.6 and 3.7 considered
- Sample Appveyor time now: 25 minutes with Miniconda 3.6 (~35 with Miniconda 3.6 and 3.7)
- Expected Appveyor times after migration: 13-14 minutes without Miniconda
- Expected Travis time after migration: 9:30-10:30 (unknown precisely)

#### Potential small uptick in failed build times, but improvement likely overall

Given a reduction in successful Appveyor build times of about 12 minutes, and a possible (but not known) increase in failing Travis build time of 1-2 minutes, there would need to be about 6-12 times as many failing builds as successful builds in order to avoid at least testing this migration.

#### Appveyor

| Job | Time elapsed | Result |      
|-----|--------------|--------|          
| Python 3.6 | 6:44  |  PASS  |
| Python 3.7 | 6:49  |  PASS  | 
| Miniconda 3.6 | 9:26 | PASS |
| **Setup and all jobs** | **25:04** | **PASS** |

Note that the sum of the job times was just under 23 minutes, but the total time was about 2 minutes longer.

https://ci.appveyor.com/project/districtdatalabs/yellowbrick/builds/25707894

#### Travis
 | Job | Time elapsed | Result |
|-----|---------------|-------|
| Python 3.6 | 7:29    |   PASS   |
| Python 3.7 |  7:29   | PASS |
| Miniconda 3.6 |  8:41   | PASS |
| Miniconda 3.7 |  9:30    | PASS |
| **All jobs** | **9:30** | **PASS** |

https://travis-ci.com/DistrictDataLabs/yellowbrick/builds/117746928   

#### Appveyor

| Job | Time elapsed | Result |
|-----|---------------|-------|
| Python 3.6 | 6:50  |    FAIL   |
| **Total time** |  **6:50** | **FAIL** |

In the case of this failed build, the total time equals the time for this single job. Based on this and the total time for the successful build, there seems to be additional time between jobs in a build that are not included in the Appveyor job times, but impact the overall time.

https://ci.appveyor.com/project/districtdatalabs/yellowbrick/builds/25793515

#### Travis

 | Job | Time elapsed | Result |
|-----|---------------|-------|
| Python 3.6 | 7:33    |    FAIL   |
| Python 3.7 |  7:34   | FAIL |
| Miniconda 3.6 |  9:13   | FAIL |
| Miniconda 3.7 |  9:17    | FAIL |
| **Total time** | **9:17** | **FAIL** |

https://travis-ci.com/DistrictDataLabs/yellowbrick/builds/118174237

@DistrictDataLabs/team-oz-maintainers

I would be glad to work on a PR so the impact can be validated and realized.

**Comment by bbengfort** [comment]
@nickpowersys we've moved off of Travis to GitHub Actions, and it seems like our miniconda builds are more stable as a result. Going to go ahead and close this issue; thank you so much for helping contribute to Yellowbrick!
