### ISSUE TITLE
Get Yellowbrick Domain

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#93]
We need a dedicated page for yellowbrick - grab a domain name!

**Comment by rebeccabilbro** [comment]
I'm thinking either scikit-yb.org or skyellowbrick.com.

**Comment by bbengfort** [comment]
I just purchased a 2 year registration for scikit-yb.org; it cost $30.96 and I registered it under my own domain register (not under a DDL account or with DDL funds). 

We can also purchase skyellowbrick.com if you'd like - but I think the shorter the better. 

I'll point our documentation to that site, and once done - I'll close this task. We can create a GitHub pages site for it or do something else later on. 

!!

**Comment by bbengfort** [comment]
Ok - http://www.scikit-yb.org/ now points to our read the docs documentation!
