### ISSUE TITLE
Issue with customizing ROC-AUC plot (Yellowbrick) using x and y limits

### ISSUE THREAD

**Issue by franzalex1980** [DistrictDataLabs/yellowbrick#932]
Dear Contributors,

I have been trying to set these limits using ax.set_xlim([-0.05, 1.05])
ax.set_ylim([-0.05, 1.05]) for the graph below, to have a good view of the lines.

![Classification_Exp_1_ClassPredictionError_Github](https://user-images.githubusercontent.com/47783454/61699624-86567700-ad3b-11e9-8582-5532c8729532.png)

Please how do I overcome this problem? 

Thanks in advance!

Alex

**Comment by franzalex1980** [comment]
I have gotten the solution already :)

I did more customizing on the labels and axis from matplotlib and also minding the positions of the codes, very important!

**Comment by lwgray** [comment]
Hi @franzalex1980 I am glad you found a solution.  Do you mind posting what you did so that we have an archive just in case someone else has a similar issue?  Thanks!
