### ISSUE TITLE
Remove `y` in fit(X, y) in Rank Features visualizers?

### ISSUE THREAD

**Issue by pavopax** [DistrictDataLabs/yellowbrick#934]
**Describe the issue**

It seems that `y` is not used to rank features, and so should be removed to clarify the fitting process in Rank1d and Rank2d

Specifically, it is the call to fit() like here:

```python
visualizer = Rank1D(features=features, algorithm='shapiro')
visualizer.fit(X, y) 
```

... in documentation like here:

https://www.scikit-yb.org/en/latest/api/features/rankd.html

According to my understanding of these functions, it seems that `y` is not used in the fitting procedure, so should be removed, so that docs are more explicit about what is happening.

Or, is there a use for `y` in the fit() calls?

**Comment by lwgray** [comment]
Hi @pavopax 

Firstly, Thank you for using Yellowbrick

You have brought up a interesting question.  One important reason why the target variable is present has to do with Visual Pipelines.  This is when you want to string together the creation of several Visualizers.  In the instances where you are placing the RankD visualizer in a pipeline,  although RankD isn’t using ‘y’, you may want to pass on the target variable to the next visualizer.  See example below!

![D3078355-C9E1-4404-B964-8ABBEFF974F0](https://user-images.githubusercontent.com/1000117/61899866-60230980-aeea-11e9-8394-c0a4fa233cb4.png)

**Comment by pavopax** [comment]
Thanks! Great to learn about these pipelines, will use them.

And now the reason for including `y` makes sense, and I see it in a note here:

> Optionally, a vector y, which represents the target variable (in supervised learning), can also be supplied as input. [Source](https://www.scikit-yb.org/en/latest/quickstart.html)

Still, I wonder if others may be confused by including `y` like in RankD above... 

One solution could be to have something like this in the unsupervised examples:

```python
visualizer = Rank1D(features=features, algorithm='shapiro')
visualizer.fit(X)   # or visualizer.fit(X,y) if included in a supervised pipeline
```

Just a thought! Maybe there are better ways to document this...

**Comment by Patil2099** [comment]
@pavopax  Can I work on this?

**Comment by pavopax** [comment]
For sure, I was not planning to!

But maybe confirm with a core developer. 

Cheers!
-- 
pavopax.github.io

**Comment by rebeccabilbro** [comment]
Hi @Patil2099, Yellowbrick maintainer here &mdash; thanks for checking out Yellowbrick and for your interest in contributing! Can you let us know what you have in mind in terms of working on this, just so we're on the same page?

**Comment by bbengfort** [comment]
@pavopax Thanks for your question - we're always looking to improve our documentation and I think that we're currently working on some changes related to #47 that might help address this.
