### ISSUE TITLE
Text color/background color handling

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#94]
Come up with a way to ensure that there is good contrast between text color and background color when the text is going to be on top of a background color. 

This came up in particular because of the classification report heatmap, but will come up with other visualizers too.

**Comment by NealHumphrey** [comment]
Looks like we should only keep one of these two tickets open. Just b/c it has slightly more detail I propose keeping #154 and closing this one (and next time will search harder for existing tickets before opening new ones). Ok by you @bbengfort?

**Comment by bbengfort** [comment]
@NealHumphrey sounds good to me.
