### ISSUE TITLE
Some plot directive visualizers not rendering in Read the Docs

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#949]
Currently on Read the Docs (develop branch), a few of our visualizers that use the plot directive (#687) are not rendering the plots:

- [Classification Report](http://www.scikit-yb.org/en/develop/api/classifier/classification_report.html)
- [Silhouette Scores](http://www.scikit-yb.org/en/develop/api/cluster/silhouette.html)
- [ScatterPlot](http://www.scikit-yb.org/en/develop/api/contrib/scatter.html)
- [JointPlot](http://www.scikit-yb.org/en/develop/api/features/jointplot.html)

**Comment by pdamodaran** [comment]
This is fixed as of the v1.0 release.
