### ISSUE TITLE
Version 1.0 release

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#956]
Steps for 1.0 version bump:
 
 - [x] Branch release-1.0
 - [x] Do version bump
 - [x] Update tests and run tests
 - [x] Create change log/release notes
 - [x] Review documentation build
 - [x] Merge into `master`
 - [x] Push release to PyPI ([instructions](https://bbengfort.github.io/programmer/2016/01/20/packaging-with-pypi.html))
 - [x] Create 1.0 tag
 - [x] Copy change log to release notes
 - [x] Push documentation to Read the Docs
 - [x] Merge release into `develop`
 - [x] Delete release
 - [ ] Make issue for updating Zonodo reference
 - [x] Make issue for releasing Conda package
 - [x] Announce on Twitter & Reddit!

**Comment by Kautumn06** [comment]
.. -*- mode: rst -*-

Changelog
=========

Version 1.0
-----------
* Tag: v1.0_
* Deployed: Not yet deployed
* Contributors: Benjamin Bengfort, Rebecca Bilbro, Nathan Danielsen, Kristen McIntyre, Larry Gray, Prema Roman, Carl Dawson, Daniel Navarrete, Francois Dion, Halee Mason, Jeff Hale, Jiayi Zhang, Jimmy Shah, John Healy, Justin Ormont, Kevin Arvai, Michael Garod, Mike Curry, Nabanita Dash, Naresh Bachwani, Nicholas A. Brown, Piyush Gautam, Pradeep Singh, Rohit Ganapathy, Ry Whittington, Sangarshanan, Sourav Singh, Thomas J Fan, Zijie (ZJ) Poh, Zonghan, Xie

.. warning:: **Python 2 Deprecation**: Please note that this release deprecates Yellowbrick's support for Python 2.7. After careful consideration and following the lead of our primary dependencies (NumPy, scikit-learn, and Matplolib), we have chosen to move forward with the community and support Python 3.4 and later.

Major Changes:
    - New ``JointPlot`` visualizer that is specifically designed for machine learning. The new visualizer can compare a feature to a target, features to features, and even feature to feature to target using color. The visualizer gives correlation information at a glance and is designed to work on ML datasets.
    - New ``PosTagVisualizer`` is specifically designed for diagnostics around natural language processing and grammar-based feature extraction for machine learning. This new visualizer shows counts of different parts-of-speech throughout a tagged corpus.
    - New datasets module that provide greater support for interacting with Yellowbrick example datasets including support for Pandas, npz, and text corpora.
    - Management repository for Yellowbrick example data, ``yellowbrick-datasets``.
    - Add support for matplotlib 3.0.1 or greater.
    - ``UMAPVisualizer`` as an alternative manifold to TSNE for corpus visualization that is fast enough to not require preprocessing PCA or SVD decomposition and preserves higher order similarities and distances.
    - Added ``..plot::`` directives to the documentation to automatically build the images along with the docs and keep them as up to date as possible. The directives also include the source code making it much simpler to recreate examples.
    - Added ``target_color_type`` functionality to determine continuous or discrete color representations based on the type of the target variable.
    - Added alpha param for both test and train residual points in ``ResidualsPlot``.
    - Added ``frameon`` param to ``Manifold``.
    - Added frequency sort feature to ``PosTagVisualizer``.
    - Added elbow detection using the "kneedle" method to the ``KElbowVisualizer``.
    - Added governance document outlining new Yellowbrick structure.
    - Added ``CooksDistance`` regression visualizer.
    - Updated ``DataVisualizer`` to handle target type identification.
    - Extended ``DataVisualizer`` and updated its subclasses. 
    - Added ``ProjectionVisualizer`` base class.
    - Restructured ``yellowbrick.target``, ``yellowbrick.features``, and ``yellowbrick.model_selection`` API.
    - Restructured regressor and classifier API.

Minor Changes:
    - Updated ``Rank2D`` to include Kendall-Tau metric.
    - Added user specification of ISO F1 values to ``PrecisionRecallCurve`` and updated the quick method to accept train and test splits.
    - Added code review checklist and conventions to the documentation and expanded the contributing docs to include other tricks and tips.
    - Added polish to missing value visualizers code, tests, and documentation.
    - Improved ``RankD`` tests for better coverage.
    - Added quick method test for ``DispersionPlot`` visualizer.
    - BugFix: fixed resolve colors bug in TSNE and UMAP text visualizers and added regression tests to prevent future errors.
    - BugFix: Added support for Yellowbrick palettes to return ``colormap``.
    - BugFix: fixed ``PrecisionRecallCurve`` visual display problem with multi-class labels.
    - BugFix: fixed the ``RFECV`` step display bug.
    - BugFix: fixed error in distortion score calculation.
    - Extended ``FeatureImportances`` documentation and tests for stacked importances and added a warning when stack should be true.
    - Improved the documentation readability and structure.
    - Refreshed the ``README.md`` and added testing and documentation READMEs.
    - Updated the gallery to generate thumbnail-quality images.
    - Updated the example notebooks and created a quickstart notebook.
    - Fixed broken links in the documentation.
    - Enhanced the ``SilhouetteVisualizer`` with ``legend`` and ``color`` parameter, while also move labels to the y-axis.
    - Extended ``FeatureImportances`` docs/tests for stacked importances.
    - Documented the ``yellowbrick.download`` script.
    - Added JOSS citation for "Yellowbrick: Visualizing the Scikit-Learn Model Selection Process".
    - Added new pull request (PR) template.
    - Added ``alpha`` param to PCA Decomposition Visualizer.
    - Updated documentation with affiliations.
    - Added a ``windows_tol`` for the visual unittest suite.
    - Added stacked barchart to ``PosTagVisualizer``.
    - Let users set colors for ``FreqDistVisualizer`` and other ``ax_bar`` visualizers.
    - Updated ``Manifold`` to extend ``ProjectionVisualizer``.
    - Check if an estimator is already fitted before calling ``fit`` method.
    - Ensure ``poof`` returns ``ax``.

Compatibility Notes:
    - This version provides support for matplotlib 3.0.1 or greater and drops support for matplotlib versions less than 2.0.
    - This version drops support for Python 2

.. _v1.0: https://github.com/DistrictDataLabs/yellowbrick/releases/tag/v1.0

**Comment by bbengfort** [comment]
🎉
