### ISSUE TITLE
Make quick methods primetime

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#960]
After the visualizer audit we believe that the quick methods are ready to be made prime time. 

Quick methods must:

1. Have a function signature identical to the Visualizer constructor with additional data for fit/score
2. Call `finalize()` and not `poof()`/`show()`
3. Return the fitted visualizer instance
4. Some visualizers must also insure that they call transform/fit_transform/score 

For each visualizer found in the list below we must:

- [x] refactor the quick method to the new API 
- [x] document the quick method 
- [x] ensure there is an associated test or tests for the quick method

See #600 for more details on this issue

- [ ] class_prediction_error
- [ ] classification_report
- [ ] confusion_matrix
- [ ] precision_recall_curve
- [x] roc_auc
- [ ] discrimination_threshold
- [ ] alphas
- [ ] cooks_distance
- [ ] prediction_error
- [ ] residuals_plot
- [ ] kelbow_visualizer
- [ ] intercluster_distance
- [x] silhouette_visualizer
- [ ] balanced_binning_reference
- [ ] class_balance
- [ ] feature_correlation
- [x] cv_scores
- [ ] learning_curve
- [ ] validation_curve
- [ ] explained_variance_visualizer
- [ ] feature_importances
- [ ] rank1d
- [ ] rank2d
- [x] rfecv
- [ ] joint_plot
- [ ] mainfold_embedding
- [x] pca_decomposition
- [x] parallel_coordinates
- [x] radviz
- [ ] dispersion
- [ ] freqdist
- [x] postag
- [x] tsne
- [ ] umap
- [ ] gridsearch_color_plot

**Comment by pdamodaran** [comment]
The following is a link to the assignments:

https://docs.google.com/spreadsheets/d/1DX8RuRCVMiJrFd1YWguor57iaAmj5503BLJDX8KGjn8/edit?usp=sharing

**Comment by bbengfort** [comment]
This was completed in v1.1
