### ISSUE TITLE
No module error - Anaconda

### ISSUE THREAD

**Issue by nicolasFracica** [DistrictDataLabs/yellowbrick#966]
Hello, I have been trying to import yellowbrick in a Jupyter Notebook but I keep getting the no module error, I have installed Yellowbrick via Anaconda with no issues and the library is listed in the environment modules.

![Screenshot from 2019-09-08 23-35-58](https://user-images.githubusercontent.com/48388706/64503624-6ea66400-d291-11e9-8910-d8e495cb787b.png)

output from conda list:

![Screenshot from 2019-09-08 23-34-34](https://user-images.githubusercontent.com/48388706/64503579-47e82d80-d291-11e9-94a2-8c2ae144ae3c.png)

I am using Python 3.7.4 and my OS is Ubuntu 18.04
Thanks in advance for any possible solution!

@DistrictDataLabs/team-oz-maintainers

**Comment by lwgray** [comment]
Hi @nicolasFracica  Thank you for trying to use Yellowbrick(yb).  Can you verify that you are not in a  notebook in a different conda environment than the one you installed yb in?

**Comment by nicolasFracica** [comment]
Hi @lwgray that was exactly the issue, the notebook was running on the default kernel, I changed it to the environment that has YB installed and now it works. Thanks you very much!
