### ISSUE TITLE
Quick Start Rank2D example missing feature names

### ISSUE THREAD

**Issue by NapsterInBlue** [DistrictDataLabs/yellowbrick#968]
Hey all,

Brand-spankin'-new to this library and have spent the morning poring through the excellent docs (found YB when looking for a simple way to do residual plots and will likely be hooked from here!)

Was following along with the Quick Start and noticed that the tick labels for the first ``Rank2D`` plot

![image](https://user-images.githubusercontent.com/3505365/64621307-765e2980-d3b3-11e9-9543-acb1139573bb.png)

didn't match up with the ones I got when I ran the same code

![image](https://user-images.githubusercontent.com/3505365/64622036-aeb23780-d3b4-11e9-9256-7aed09fdb2d8.png)

Figured this was a simple "remake the static reference image" issue and went rooting around in the `docs/` folder. A bit of git blame [[1]](https://github.com/DistrictDataLabs/yellowbrick/issues/354) rabbit-holing [[2]](https://github.com/DistrictDataLabs/yellowbrick/pull/446) later [[3]](https://github.com/DistrictDataLabs/yellowbrick/pull/719), and I know marginally more about the ``.. plot::`` directive than when I woke up this morning. So I try running [the hidden code that actually builds the image](https://github.com/DistrictDataLabs/yellowbrick/blame/develop/docs/quickstart.rst#L154-L167) and get the same result

![image](https://user-images.githubusercontent.com/3505365/64621221-4c0c6c00-d3b3-11e9-8c04-312ca448bb99.png)

Sky's hardly falling with this one, but I've been scratching my head over it awhile now and figured it bared asking.

I'm running Python `3.7.3`, Matplotlib `3.0.3`, and YB `1.0.post1`, FWIW

Cheers!

**Comment by wagner2010** [comment]
Thank you @NapsterinBlue for your message.  Love the handle name btw!  We’re going to check it out and get back to you soon!  Welcome to Yellowbrick! Thanks, Yellowbrick Team

**Comment by wagner2010** [comment]
Hi @NapsterInBlue I’m working on your issue now however would you mind, as a best practice, to update your Matplotlib to the latest version (3.1.1) and rerun your code.  It will help YB run best.  Thanks and stay tuned.

**Comment by wagner2010** [comment]
Excellent.  Honestly, if you're getting the names of the features in the plot that is optimal for comparison and I don't see an issue at all with it.  I will confer with the team (we might have to update some docs on our side), but I would say press on and enjoy!  Happy plotting.  We love your enthusiasm and look forward to future contributions!  Don't forget to star our repo here if you don't already!
