### ISSUE TITLE
Deploy Alpha Test

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#97]
Deploy the alpha test by sending out the Getting Started with Yellowbrick notebook instructions to everyone who signed up.

**Comment by rebeccabilbro** [comment]
Reminder @bbengfort  that we had people sign up with their GitHub usernames. Is the easiest way to proceed to tag each of them in this issue? Other ideas?

**Comment by rebeccabilbro** [comment]
Here's the (untagged but deduped) username list:
- jkeung
- Vevahelms
- mdlynch37
- rajashreebaradur 
- Japneetsingh
- lmcinnes
- pbs929
- Msamuel
- chrisbirster
- zaynaib
- Joshpk105
- pbwitt
- paix129
- expectopatronum
- jhboyle
- nd1
- aysent
- EmilyPugliese
- chrisbirster
- coryamanda
- onyame
- emilyliu36
- fdion
- mdlynch37
- jc-healy
- laughingcurve
- neilmartis
- tuulihill
- StampedPassp0rt
- solankidhanesh
- shari-k
- NealHumphrey
- va20171
- nebiyeloul
- marymallampalli
- kayrenhin
- luvogels
- skp53

**Comment by bbengfort** [comment]
@rebeccabilbro @tuulihill bump this issue for the research team!
