### ISSUE TITLE
**kwargs, ^ SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by johnl8888** [DistrictDataLabs/yellowbrick#974]
**Describe the bug**

File "/usr/local/lib/python2.7/site-packages/yellowbrick/classifier/base.py", line 118
    **kwargs,
SyntaxError: invalid syntax

**To Reproduce**

```python
# Steps to reproduce the behavior (code snippet):
# Should include imports, dataset loading, and execution
# Add the traceback below
```
python 2.7
import yellowbrick

Document recommends to use python 3, but also indicates python 2.7 should work.

**Dataset**
Did you use a specific dataset to produce the bug? Where can we access it?

**Expected behavior**

**Traceback**

```
If applicable, add the traceback from the exception.
```

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - Python Version [e.g. 2.7, 3.6, miniconda]
 - Yellowbrick Version [e.g. 0.7]

**Additional context**

**Comment by pdamodaran** [comment]
Hi @johnl8888 - thank you for using Yellowbrick!  Just so you know, as of the v1.0 release, the library no longer supports Python2.7.  Yellowbrick now supports Python 3.4 or later.  Try it out with one of these versions and let us know if you still see the issue.

**Comment by pdamodaran** [comment]
Hi @johnl8888 - since we haven't heard from you we are assuming your issue has been resolved so we will go ahead and close this issue.  Please create a new issue if you are still experiencing problems.  Thanks for using Yellowbrick!
