### ISSUE TITLE
Measure YB user interests based on readthedocs traffic patterns

### ISSUE THREAD

**Issue by nickpowersys** [DistrictDataLabs/yellowbrick#978]
**Measuring interest**

There are various ways to measure how YB is being used and evaluate which kinds of new functionality would appear to be most useful to particular groups of users. Questions posed on stackoverflow or elsewhere are one way. Issues that are filed can also give some indication of where there is definite interest.

User interest in various documentation sections and pages within the sections as measured by Google Analytics can provide insight across available features with documentation. Over time, general patterns and trends should be useful. It would also be useful to understand from where traffic is originating (raw Google searches, for example, as compared to blog posts, social media or other links).

https://docs.readthedocs.io/en/stable/guides/google-analytics.html

**Comment by bbengfort** [comment]
Hi @nickpowersys -- we do have Google Analytics enabled on the documentation; is there some analysis of the traffic patterns you would like to conduct? If so, how would you like us to get you access to the data?

![Analytics All Web Site Data Audience Overview 20190101-20191011](https://user-images.githubusercontent.com/745966/66706206-f4d52080-ecfd-11e9-8261-c1ddf232ba96.png)

**Comment by nickpowersys** [comment]
Hi @bbengfort,

Knowing the count of users' first-time page views by url would be helpful. Either the output of a related report or a Google Analytics account login permission would be fine.

Thanks!
Nick

**Comment by bbengfort** [comment]
Sure thing - here is the pageviews by URL data, I believe you're looking for the "entrances" metric.

[ybdocs_pageviews.csv.gz](https://github.com/DistrictDataLabs/yellowbrick/files/3724640/ybdocs_pageviews.csv.gz)

**Comment by bbengfort** [comment]
@nickpowersys going to close the issue now that data has been provided -- but I'm very interested in hearing what you come up with! Let me know if you'd like to discuss further in Slack.
