### ISSUE TITLE
Development sprints prep

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#98]
Figure out what we need to do in preparation for the development sprints starting February 22.

**Comment by rebeccabilbro** [comment]
This should include reaching out to the following people/orgs to encourage applications:

- [ ] DDL Faculty
- [ ] Kostas
- [ ] Tuuli
- [ ] Jason 
- [ ] Emily
- [ ] Ellen
- [ ] Manil 
- [ ] Ari 
- [ ] Charlie
- [ ] DVDC
- [ ] DSDC
- [ ] DEDC

**Comment by rebeccabilbro** [comment]
In addition, type up some kind of roadmap/syllabus. One of the assignments will be for people to look around on the internet for examples of people using visual diagnostics, with a particular eye towards understanding how people are interpreting those visualizations and how they are using them to guide the modeling process. Then we can follow up with whoever wrote the original post to let them know that we'd like to pull their example into yellowbrick.

**Comment by rebeccabilbro** [comment]
Draft welcome email to send to YB lab participants.

**Comment by bbengfort** [comment]
@rebeccabilbro bump - want to chat sometime today about this issue? I'm finishing up TSNE now and will work on the slides after.

**Comment by bbengfort** [comment]
Food ordered, room reserved, attendee list sent to Matt. I think we're good to go to close this issue up.
