### ISSUE TITLE
 meta.json file is missing from the hobbies dataset on AWS

### ISSUE THREAD

**Issue by micahstubbs** [DistrictDataLabs/yellowbrick#980]
**Describe the bug**
 `meta.json` file is missing from the hobbies dataset on AWS

```
  "hobbies": {
    "url": "https://s3.amazonaws.com/ddl-data-lake/yellowbrick/v1.0/hobbies.zip",
    "signature": "6114e32f46baddf049a18fb05bad3efa98f4e6a0fe87066c94071541cb1e906f"
  },
```

from https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/datasets/manifest.json#L6

**To Reproduce**
follow this tutorial: https://www.scikit-yb.org/en/latest/api/text/tsne.html

```python
from sklearn.feature_extraction.text import TfidfVectorizer

from yellowbrick.text import TSNEVisualizer
from yellowbrick.datasets import load_hobbies

# Load the data and create document vectors
corpus = load_hobbies(data_home='../../data')
tfidf = TfidfVectorizer()

X = tfidf.fit_transform(corpus.data)
y = corpus.target

# Create the visualizer and draw the vectors
tsne = TSNEVisualizer()
tsne.fit(X, y)
tsne.show()
```

**Dataset**
Did you use a specific dataset to produce the bug? Where can we access it?
```
  "hobbies": {
    "url": "https://s3.amazonaws.com/ddl-data-lake/yellowbrick/v1.0/hobbies.zip",
    "signature": "6114e32f46baddf049a18fb05bad3efa98f4e6a0fe87066c94071541cb1e906f"
  },
```

**Traceback**

```python
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-10-47bde9d3407a> in <module>
      1 # Load the data and create document vectors
----> 2 corpus = load_hobbies()
      3 tfidf = TfidfVectorizer()
      4 
      5 X = tfidf.fit_transform(corpus.data)

~/anaconda3/envs/d2s/lib/python3.6/site-packages/yellowbrick/datasets/download.py in load_hobbies(path, extract)
    232     # name of the dataset
    233     name = 'hobbies'
--> 234     data = _load_file_data(name, path, extract)
    235     return data
    236 

~/anaconda3/envs/d2s/lib/python3.6/site-packages/yellowbrick/datasets/download.py in _load_file_data(name, path, extract)
    155     signature = DATASETS[name]['signature']
    156     download_data(url, path=path, signature=signature, extract=extract)
--> 157     with open(os.path.join(path, name, 'meta.json')) as meta_file:
    158         feature_names = json.load(meta_file)
    159     with open(os.path.join(path, name, 'README.md')) as readme_file:

FileNotFoundError: [Errno 2] No such file or directory: 'data/hobbies/meta.json'
```

**Expected behavior**
The hobbies dataset is loaded.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Python Version: python 3.6
 - Yellowbrick Version: 0.7

![Screen Shot 2019-10-15 at 12 42 46 AM](https://user-images.githubusercontent.com/2119400/66810885-fb71bc80-eee4-11e9-86d4-d2f82891f6c0.png)

**Comment by micahstubbs** [comment]
looks somewhat related to #972

**Comment by bbengfort** [comment]
@micahstubbs you mentioned that you're using Yellowbrick v0.7 -- would it be possible for you to upgrade to v1.0.1, e.g. `pip install -U yellowbrick`? This will likely be the simplest mechanism to resolve the error. Once you upgrade, you can clean up your previously downloaded datasets as follows:

```
python -m yellowbrick.download --cleanup
```

This will ensure that you get the latest hobbies corpus with the required data. 

If you've pinned the Yellowbrick version for some reason, please feel free to download the [latest version of the hobbies corpus](https://s3.amazonaws.com/ddl-data-lake/yellowbrick/v1.0/hobbies.zip) and load the data manually.

**Comment by micahstubbs** [comment]
hi @bbengfort, thanks for the steps.  I followed them, but I still do not see `meta.json`. 

```bash
pip install -U yellowbrick
python -m yellowbrick.download --cleanup
```

No `meta.json`

```
(d2s) ➜  hobbies la
total 8
-rw-r--r--    1 m  staff   1.1K Oct 24 20:00 README.md
drwxr-xr-x   74 m  staff   2.3K Oct 24 20:00 books
drwxr-xr-x  102 m  staff   3.2K Oct 24 20:00 cinema
drwxr-xr-x   32 m  staff   1.0K Oct 24 20:00 cooking
drwxr-xr-x  130 m  staff   4.1K Oct 24 20:00 gaming
drwxr-xr-x  120 m  staff   3.8K Oct 24 20:00 sports
(d2s) ➜  hobbies pwd
/Users/m/anaconda3/envs/d2s/lib/python3.6/site-packages/yellowbrick/datasets/fixtures/hobbies
```

**Comment by micahstubbs** [comment]
I'll go run my notebook again - maybe Yellowbrick v `1.0.1` doesn't expect `meta.json` anymore?

**Comment by micahstubbs** [comment]
indeed that does seem to be the case.  the example code now runs just fine without `meta.json`.  huzzah!

![Screen Shot 2019-10-24 at 8 04 28 PM](https://user-images.githubusercontent.com/2119400/67540236-86974300-f699-11e9-9bd0-4013f18659c1.png)

**Comment by micahstubbs** [comment]
thanks again for the advice and the explanation!
