### ISSUE TITLE
Unable to run RFECV on XGBRegressor

### ISSUE THREAD

**Issue by shivendra90** [DistrictDataLabs/yellowbrick#983]
I'm trying to run a reverse feature elimination process on a training set that contains 63 features and 27380 observations. Since I've just recently discovered`yellowbrick` and its powerful methods and utilities, I tried running a RFECV on a XGBregressor with a `max_depth=5` that I've specified explicitly. But it's been almost 1.5 hours and the console is stuck on the fitting process. Can anyone help me out speeding things up or is the method unable to process large number of features?

Update: Tried running RFECV on `LinearRegression` but to no avail; process still stuck on fitting phase. Looks like RFECV is unable to run on large datasets.

@DistrictDataLabs/team-oz-maintainers

**Comment by bbengfort** [comment]
Hi @shivendra90 - I can understand how running RFECV can take a very long time to complete, it is going to end up fitting and training 3 models (for three fold cross validation) 62 times (e.g. until you've removed all but one feature). If it takes each model 1 minute to train then you're looking at 3.1 hours to finish training. 

There are two parameters with RFECV that you can change to speed things up: 

- `cv`: Determines the cross-validation splitting strategy. Possible inputs for cv are: None, to use the default 3-fold cross-validation, integer, to specify the number of folds. An object to be used as a cross-validation generator. An iterable yielding train/test splits. So if you set the `cv` to only a single train test split, then you'll only generate 62 models. 
- `step`: If greater than or equal to 1, then step corresponds to the (integer) number of features to remove at each iteration. If within (0.0, 1.0), then step corresponds to the percentage (rounded down) of features to remove at each iteration. If you set this to 6, you'll only end up fitting around 10 models. 

Other possible issues:

- The models will be copied and if you use an instance-based model (e.g. nearest neighbors), memory constraints on your machine might slow things down. 
- Time the fitting of a single model - ensure that you know the number of RFECV models and ensure you understand what the base training time will be. If it goes longer than something else is going on. 
- Check to ensure the Python process with YB is using 100% CPU. It could be that XBGBoost is parallelized in some way and the parallelization has failed with no feedback to the main process. Check any `njobs` parameters in your models.

It would be great if we could parallelize RFECV with joblib - so if you're interested in this, we'd be happy to 
take a look at a PR!

**Comment by shivendra90** [comment]
I'll see what can be done. The RFE provided by `sklearn.feature_selection` did the job in under 30 minutes with the same parameters. I'll check how `sklearn` does it.

**Comment by bbengfort** [comment]
Yellowbrick uses [`sklearn.feature_selection.RFE`](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/model_selection/rfecv.py#L183) under the hood but does so in the same way that [`sklearn.feature_selection.RFECV`](https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.RFECV.html) works: using cross validated searches to eliminate `step` features at a time.  That means that if `RFE` takes under 30 minutes, then RFECV will be a multiple of that time for each cross-validated RFE run times the number of features being eliminated.

**Comment by jfrjunio** [comment]
HELP, this simple code yeilds a "KeyError: 'weight'" weird error.
//------------
from sklearn.feature_selection import RFECV
from xgboost.sklearn import XGBRegressor
import sklearn.metrics
from sklearn.metrics import mean_absolute_error

estimator = XGBRegressor()    #estimator.fit(x,y) works smoothly
selector = RFECV(estimator, step=1, min_features_to_select=1, cv=10, scoring='neg_mean_absolute_error')
selector = selector.fit(x, y.values.flatten())
//--------
I get the same for either RFE or RFECV:
~/miniconda2/envs/py3/lib/python3.6/site-packages/xgboost/sklearn.py in coef_(self)
    714                                  .format(self.booster))
    715         b = self.get_booster()
--> 716         coef = np.array(json.loads(b.get_dump(dump_format='json')[0])['weight'])
    717         # Logic for multiclass classification
    718         n_classes = getattr(self, 'n_classes_', None)

KeyError: 'weight'

**Comment by bbengfort** [comment]
Hi @jfrjunio - thanks for your message and for using YB. As far as I can tell from your error message, this error is occurring in xgboost as it tries to access the `coef_` property; and even though YB requires access to the `coef_` this is done in sklearn, so I don't think this error has to do with Yellowbrick. Have you tried using the sklearn RFECV estimator? Although it doesn't return a visualization, it is a bit new than YB's implementation and might have a fix for XGBoost specifically.

**Comment by Gooogr** [comment]
Hello @jfrjunio. I faced the same problem, downgrade to xbgoost==0.90 helped me. It seems, that the newer version doesn't support ```coef_``` property of sklearn.
 So,
```
! pip uninstall xgboost -y
! pip install --upgrade xgboost==0.90
```
