### ISSUE TITLE
Installs tests package

### ISSUE THREAD

**Issue by Fronkan** [DistrictDataLabs/yellowbrick#996]
**Describe the bug**
Installing yellowbrick also installs a package "tests" into the enviornment.

**To Reproduce**
```shell
PS> virtualenv env
PS> .\env\Scripts\activate
PS> python -c "import tests; print(tests.__path__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'tests'
PS> pip install yellowbrick
PS> python -c "import tests; print(tests.__path__)"
_NamespacePath(['<PATH_FROM_C:>\\env\\lib\\site-packages\\tests'])
```
I dug into the files and found the scikit-yb developer copyright notice in the source files in the fields.

**Expected behavior**
I would guess it is not the expected nor intendent behavior to install the tests package. Also looking at the setup.py it seems like it should be excluded, so i do not understand why this isn't the case. Mainly,  this is a issue as it causes python to import the yb tests package instead of my local tests package when running pytest.

**Desktop (please complete the following information):**
 - OS: Windows
 - Python Version 3.7.4
 - Yellowbrick Version 1.0.1

**Comment by bbengfort** [comment]
@Fronkan thank you for your note -- this stumped me for a bit but was finally able to figure it out. We'll get it sorted in the v1.1 release!

**Comment by Fronkan** [comment]
No problem, glad you could figure it out. I was suprised the original setup-file did not work and I must say the solution wasn't obvious. Hopefully I remember the solution if I encounter a similar problem.
